### PR TITLE
8315602: Open source swing security manager test

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8315602](https://bugs.openjdk.org/browse/JDK-8315602)
- This PR has two commits
- Commit 1 is a clean back port of original commit
- Commit 2 is the fix for test case error `ClassNotFoundException: allow`

Testing
- Local: Passed
- Pipeline: All checks have passed
- Testing Machine: SAP nightlies passed on `2024-02-11`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315602](https://bugs.openjdk.org/browse/JDK-8315602) needs maintainer approval

### Issue
 * [JDK-8315602](https://bugs.openjdk.org/browse/JDK-8315602): Open source swing security manager test (**Bug** - P4 - Approved)

### Reviewers
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2520/head:pull/2520` \
`$ git checkout pull/2520`

Update a local copy of the PR: \
`$ git checkout pull/2520` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2520/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2520`

View PR using the GUI difftool: \
`$ git pr show -t 2520`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2520.diff">https://git.openjdk.org/jdk11u-dev/pull/2520.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2520#issuecomment-1935040675)

### CODE REVIEW

**Review by reinrich — APPROVED** [review]
Looks good to me.
Cheers, Richard.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.24-oracle. Un-Clean backport. Test case only, no risk. SAP nightlies passed on 2024-02-11”

**Pull request closed without merging**
