### PR TITLE
8270947: AArch64: C1: use zero_words to initialize all objects

### PR DESCRIPTION
**Pull request by navyxliu**
We would like to backport [JDK-8270947](https://bugs.openjdk.org/browse/JDK-8270947) to jdk11u. It's not only less code to maintain, but also better generated code. C1 can leverage DC ZVA in large allocations on aarch64. The secondary consideration is that openjdk11u aligns with oraclejdk11u. 

This isn't a clean backport. Small cosmetic changes are made in `MacroAssembler::zero_words(Register ptr, Register cnt)` chunk. 

There are also 3 trailing bugfixes. We will post them together as stacked PRs

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8270947](https://bugs.openjdk.org/browse/JDK-8270947): AArch64: C1: use zero_words to initialize all objects

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1502/head:pull/1502` \
`$ git checkout pull/1502`

Update a local copy of the PR: \
`$ git checkout pull/1502` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1502/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1502`

View PR using the GUI difftool: \
`$ git pr show -t 1502`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1502.diff">https://git.openjdk.org/jdk11u-dev/pull/1502.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi
I think this has four follow ups:
What about 8280234 and 8271956?

**Review by phohensee — APPROVED** [review]
Passed tier1. Lgtm.

Pre-submit failure looks to be an infrastructure issue.

**Comment by navyxliu** [comment]
> Hi I think this has four follow ups: What about 8280234 and 8271956?
Hi, 
thank you for the reminder.  I didn't notice them at the beginning. 

Those two fixed compilation issues for other variants. 
1. [8271956](https://bugs.openjdk.org/browse/JDK-8271956) is for variant client. 
2. [8280234](https://bugs.openjdk.org/browse/JDK-8280234) is for variant core. 

For item-1, I can reproduce it in jdk11u. The backport is trivial. I will append it to the Stack PRs. 

for item-2, I can't reproduce it! it's because current jdk11u can't build variant 'core'.
Here is the error message. 

```
=== Output from failing command(s) repeated here ===
/usr/bin/printf "* For target hotspot_variant-core_libjvm_objs_globals.o:\n"
* For target hotspot_variant-core_libjvm_objs_globals.o:
(/usr/bin/grep -v -e "^Note: including file:" <  /home/ubuntu/Devel/jdk11u-dev/build/linux-aarch64-normal-core-release/make-support/failure-logs/hotspot_variant-core_libjvm_objs_globals.o.log || true) | /usr/bin/head -n 15
In file included from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/memory/allocation.hpp:28,
                 from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/oops/array.hpp:28,
                 from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/memory/universe.hpp:28,
                 from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/code/oopRecorder.hpp:28,
                 from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/asm/codeBuffer.hpp:28,
                 from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/asm/assembler.hpp:28,
                 from /home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/precompiled/precompiled.hpp:31:
/home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/runtime/globals.hpp:2765:75: error: 'pd_InlineSmallCode' was not declared in this scope; did you mean 'InlineSmallCode'?
 2765 | #define MATERIALIZE_PD_PRODUCT_FLAG(type, name, doc)          type name = pd_##name;
      |                                                                           ^~~
/home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/runtime/globals.hpp:1702:3: note: in expansion of macro 'MATERIALIZE_PD_PRODUCT_FLAG'
 1702 |   product_pd(intx, InlineSmallCode,                                         \
      |   ^~~~~~~~~~
/home/ubuntu/Devel/jdk11u-dev/src/hotspot/share/runtime/globals.hpp:2703:3: note: in expansion of macro 'RUNTIME_FLAGS'
 2703 |   RUNTIME_FLAGS(                                                            \
if test `/usr/bin/wc -l < /home/ubuntu/Devel/jdk11u-dev/build/linux-aarch64-normal-core-release/make-support/failure-logs/hotspot_variant-core_libjvm_objs_globals.o.log` -gt 15; then /usr/bin/echo "   ... (rest of output omitted)" ; fi
   ... (rest of output omitted)
/usr/bin/printf "\n* All command lines available in /home/ubuntu/Devel/jdk11u-dev/build/linux-aarch64-normal-core-release/make-support/failure-logs.\n"

* All command lines available in /home/ubuntu/Devel/jdk11u-dev/build/linux-aarch64-normal-core-release/make-support/failure-logs.
/usr/bin/printf "=== End of repeated output ===\n"
=== End of repeated output ===
```

I would like to sideline 8280234 for time being. if variant core matters to jdk11u, I will seek to fix build core first. 

what do you think?

**Comment by navyxliu** [comment]
I filed an issue about the build failure of variant=core. 
https://bugs.openjdk.org/browse/JDK-8296502

**Comment by phohensee** [comment]
There may be an existing JBS issue patch that fixes the problem.

**Comment by navyxliu** [comment]
> There may be an existing JBS issue patch that fixes the problem.

Yes, I think JDK-8235673 can fix this build issue, but it isn't trivial.

**Comment by phohensee** [comment]
I took a look at JDK-8235673 and agree. Better to do the minimum fix you propose in JDK-8296502.

**Pull request closed without merging**
