### PR TITLE
8343474: [updates] Customize README.md to specifics of update project

### PR DESCRIPTION
**Pull request by vieiro**
Backport of [JDK-8343474](https://bugs.openjdk.org/browse/JDK-8343474).

All links checked.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8343474](https://bugs.openjdk.org/browse/JDK-8343474) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8343474](https://bugs.openjdk.org/browse/JDK-8343474): [updates] Customize README.md to specifics of update project (**Bug** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2978/head:pull/2978` \
`$ git checkout pull/2978`

Update a local copy of the PR: \
`$ git checkout pull/2978` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2978/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2978`

View PR using the GUI difftool: \
`$ git pr show -t 2978`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2978.diff">https://git.openjdk.org/jdk11u-dev/pull/2978.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2978#issuecomment-2539424757)
</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by vieiro** [comment]
/approval request Let's improve guidance for new contributors.

**Pull request closed without merging**
