### PR TITLE
8265773: incorrect jdeps message "jdk8internals" to describe a removed JDK internal API

### PR DESCRIPTION
**Pull request by AlexanderScherbatiy**
This is a direct backport of the fix `JDK-8265773: incorrect jdeps message "jdk8internals" to describe a removed JDK internal API` to jdk11u-dev.
The patch applies cleanly.

The fix has been built with the latest jdk11u-dev sources on Ubuntu 18.04 and manually tested with reactor-core-3.4.5.jar  lib.

The jdeps output without the fix is `jdk8internals`:
```
build/linux-x86_64-normal-server-release/jdk/bin/jdeps -s reactor-core-3.4.5.jar 
reactor-core-3.4.5.jar -> jdk8internals
reactor-core-3.4.5.jar -> java.base
reactor-core-3.4.5.jar -> java.logging
reactor-core-3.4.5.jar -> not found
```

and with the fix is `JDK removed internal API`
```
build/linux-x86_64-normal-server-release/jdk/bin/jdeps -s reactor-core-3.4.5.jar 
reactor-core-3.4.5.jar -> JDK removed internal API
reactor-core-3.4.5.jar -> java.base
reactor-core-3.4.5.jar -> java.logging
reactor-core-3.4.5.jar -> not found
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8265773](https://bugs.openjdk.java.net/browse/JDK-8265773): incorrect jdeps message "jdk8internals" to describe a removed JDK internal API

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/32/head:pull/32` \
`$ git checkout pull/32`

Update a local copy of the PR: \
`$ git checkout pull/32` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/32/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 32`

View PR using the GUI difftool: \
`$ git pr show -t 32`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/32.diff">https://git.openjdk.java.net/jdk11u-dev/pull/32.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
This is a clean backport. It only needs maintainer approval in the bug. Please add "Fix Request" comment and appropriate label.

**Comment by AlexanderScherbatiy** [comment]
> This is a clean backport. It only needs maintainer approval in the bug. Please add "Fix Request" comment and appropriate label.

What does `jdk11u-fix-yes` label mean for the backport?
Does it mean that the clean backport will be automatically backported to jdk11u-dev repository or it needs to be backported manually? 

According to [JDK11u](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u) Wiki page:
```
The maintainers will either approve by setting jdk11u-fix-yes or reject 
by setting jdk11u-fix-no...
If and only if the fix gets approved, it may be pushed
to the jdk11u-dev repository.
```
Is it still correct information and the backport needs to be manually pushed to jdk11u-dev mercurial repository?

**Comment by jerboaa** [comment]
> > This is a clean backport. It only needs maintainer approval in the bug. Please add "Fix Request" comment and appropriate label.
> 
> What does `jdk11u-fix-yes` label mean for the backport?
> Does it mean that the clean backport will be automatically backported to jdk11u-dev repository or it needs to be backported manually?
> 
> According to [JDK11u](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u) Wiki page:
> 
> ```
> The maintainers will either approve by setting jdk11u-fix-yes or reject 
> by setting jdk11u-fix-no...
> If and only if the fix gets approved, it may be pushed
> to the jdk11u-dev repository.
> ```

The wiki is correct. The confusion seems to be about pushing changes. Since jdk11u-dev is in Git now you have to push there. The way to do this is by using the /integrate pull request command if and only iff your bug was granted `jdk11u-fix-yes`.

> Is it still correct information and the backport needs to be manually pushed to jdk11u-dev mercurial repository?

No. Mercurial is read-only now.

**Pull request closed without merging**
