### PR TITLE
8247676: vcruntime140_1.dll is not needed on 32-bit Windows

### PR DESCRIPTION
**Pull request by gdams**
depends on https://github.com/openjdk/jdk11u-dev/pull/1247. CC @GoeLin who requested this backport be raised in parallel.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8247676](https://bugs.openjdk.org/browse/JDK-8247676): vcruntime140_1.dll is not needed on 32-bit Windows

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1275/head:pull/1275` \
`$ git checkout pull/1275`

Update a local copy of the PR: \
`$ git checkout pull/1275` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1275/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1275`

View PR using the GUI difftool: \
`$ git pr show -t 1275`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1275.diff">https://git.openjdk.org/jdk11u-dev/pull/1275.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi George, 
will this be clean if you backport it on top of 1247?
Are you aware of the possibility to have dependent pull requests? You can make a pull request on top of the branch of 1247.  This is the common way if you backport a change and a follow up fix.
Also, please only add jdk11u-fix-request if you have the change reviewed!
Further, you need to get the tests green here in the PR, or at least check them that the failure is unrelated. If you do so, note it down in a comment.
I will again remove the jdk11u-fix-request tags.
Have you ever read the instructions about making changes in 11/17?  https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+a+fix

Also, somewhere you state that the risk of the backport is low because the change applies clean.
That is not the kind of risk I consider when approving a backport.
The question is: might the change introduce an error that crashes the VM? Will it change the behaviour of the VM? Will it somehow require users to adapt something? E.g. the need to install a different vcruntime would be a risk. If users don't do so they will break their system when updating.

**Comment by gdams** [comment]
@GoeLin as per @RealCLanger's comment here (https://github.com/openjdk/jdk11u-dev/pull/1265#pullrequestreview-1048891543). The GHA failure is unrelated and a known intermittent issue.

**Pull request closed without merging**
