### PR TITLE
8224829: AsyncSSLSocketClose.java has timing issue

### PR DESCRIPTION
**Pull request by RealCLanger**
Backport of 8224829: AsyncSSLSocketClose.java has timing issue.
To make this one fit better (and maybe future backports), I also included the new recordLock functionality from JDK-8221882.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8224829](https://bugs.openjdk.java.net/browse/JDK-8224829): AsyncSSLSocketClose.java has timing issue

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to a75d36e9401d666e14cc33a0271f61e029ccac0e

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/446/head:pull/446` \
`$ git checkout pull/446`

Update a local copy of the PR: \
`$ git checkout pull/446` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/446/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 446`

View PR using the GUI difftool: \
`$ git pr show -t 446`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/446.diff">https://git.openjdk.java.net/jdk11u-dev/pull/446.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Right, we need the `recordLock` for this change. Unfortunately, JDK-8221882 is too large for a backport and the part you have taken from it is not small, either. So, we need to be careful when doing more backports in this area. Your version looks good to me.

**Comment by RealCLanger** [comment]
> Right, we need the `recordLock` for this change. Unfortunately, JDK-8221882 is too large for a backport and the part you have taken from it is not small, either. So, we need to be careful when doing more backports in this area. Your version looks good to me.

Thanks for the review! Yes, the alternative would be to refactor the head change to use `synchronized` instead of recordLock but I think for possible future backports in that area I guess it's not a bad idea to use the new style locking. I went through the code quite thoroughly, to make sure I have catched every occurence of synchronization on the Record object and every usage of recordLock. I've spotted no regressions during testing.

**Comment by GoeLin** [comment]
Why is the Linux x86 integration test failing?

**Comment by RealCLanger** [comment]
> Why is the Linux x86 integration test failing?

Hm, hotspot test compiler/types/correctness/OffTest.java... I'm pretty sure that this is an intermittent one. I can't think of how that could relate here. In any case, I'll merge in master to let GHA run once again.

**Comment by RealCLanger** [comment]
> > Why is the Linux x86 integration test failing?
> 
> Hm, hotspot test compiler/types/correctness/OffTest.java... I'm pretty sure that this is an intermittent one. I can't think of how that could relate here. In any case, I'll merge in master to let GHA run once again.

Now it looks better, although MacOS release build was skipped, probably for some infrastructure reasons.

**Pull request closed without merging**
