### PR TITLE
8268771: javadoc -notimestamp option does not work on index.html

### PR DESCRIPTION
**Pull request by varpa89**
In jdk 14 there was a change which allows conditionally generate timestamp in index.html of javadoc.
It would be nice to have this feature in jdk 11 for supporting reproducible builds

https://github.com/openjdk/jdk14u/commit/2ace3e69e6de678d77719376dad961bdcb0d550e#diff-ac839a98e6e91aa8aba6e1b9efdfc018616306f478fc95bae067dfc44d3667d4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8268771](https://bugs.openjdk.java.net/browse/JDK-8268771): javadoc -notimestamp option does not work on index.html

### Reviewers
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/33/head:pull/33` \
`$ git checkout pull/33`

Update a local copy of the PR: \
`$ git checkout pull/33` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/33/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 33`

View PR using the GUI difftool: \
`$ git pr show -t 33`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/33.diff">https://git.openjdk.java.net/jdk11u-dev/pull/33.diff</a>

</details>

### CODE REVIEW

**Comment by michael-o** [comment]
Maven PMC here, we are getting annoying reports about this. Please address.

**Review by RealCLanger — APPROVED** [review]
Looks good to me and makes sense to backport to 11u. I've requested approval in the JBS item.

**Review by RealCLanger — APPROVED** [review]

**Comment by RealCLanger** [comment]
> @varpa89
> Your change (at version [4fb2643](https://github.com/openjdk/jdk11u-dev/commit/4fb2643730bd54bb837faf25e65d66ab8e8689bf)) is now ready to be sponsored by a Committer.

Need to wait with sponsoring until JBS bug gets approved for 11u.

**Comment by michael-o** [comment]
Thank you folks!

**Pull request closed without merging**
