### PR TITLE
8326591: New test JmodExcludedFiles.java fails on Windows when --with-external-symbols-in-bundles=public is used

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This PR contains a backport of [43c6f0b5880899b797fab2f851bd35be1c342439](https://github.com/openjdk/jdk/commit/43c6f0b5880899b797fab2f851bd35be1c342439). 

Patch is not clean. Test won't build in 11 because it can't find ```import jdk.internal.util.OperatingSystem```.

This class was introduced in 21 as part of [JDK-8303485](https://bugs.openjdk.org/browse/JDK-8303485).

I've worked around that by removing the dependency to that utility function and checking the operating system with ```test/lib/jdk/test/lib/Platform.java```.

Testing: 
- [x] Modified test case passes 

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8326591](https://bugs.openjdk.org/browse/JDK-8326591) needs maintainer approval

### Issue
 * [JDK-8326591](https://bugs.openjdk.org/browse/JDK-8326591): New test JmodExcludedFiles.java fails on Windows when --with-external-symbols-in-bundles=public is used (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2679/head:pull/2679` \
`$ git checkout pull/2679`

Update a local copy of the PR: \
`$ git checkout pull/2679` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2679/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2679`

View PR using the GUI difftool: \
`$ git pr show -t 2679`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2679.diff">https://git.openjdk.org/jdk11u-dev/pull/2679.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2679#issuecomment-2072510142)

### CODE REVIEW

**Comment by amosshi** [comment]
Testing Machine: SAP nightlies passed on 2024-05-02

- Automated jtreg test: jtreg_jdk_tier1
- `jdk/modules/etc/JmodExcludedFiles.java`: SUCCESSFUL GitHub 📊⏲ - [221 msec]

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by TheRealMDoerr** [comment]
This one is ready for integration.

**Pull request closed without merging**
