### PR TITLE
8267666: Add option to jcmd GC.heap_dump to use existing file

### PR DESCRIPTION
**Pull request by RealCLanger**
Backport of the heap dump enhancement. CSR includes update releases.

Patch did not apply cleanly, I had to resolve/modify
src/hotspot/share/services/diagnosticCommand.cpp
src/hotspot/share/services/diagnosticCommand.hpp
src/hotspot/share/services/heapDumper.cpp
src/hotspot/share/services/heapDumper.hpp

Following files do not exist in 11u:
src/hotspot/share/services/heapDumperCompression.cpp
src/hotspot/share/services/heapDumperCompression.hpp
Changes had been made in heapDumper.cpp/heapDumper.hpp

I have built it on linuxx86_64 and verified that the modified test succeeds. Will also run it through SAP's test suite before merging.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267666](https://bugs.openjdk.java.net/browse/JDK-8267666): Add option to jcmd GC.heap_dump to use existing file

### Reviewers
 * [Ralf Schmelter](https://openjdk.java.net/census#rschmelter) (@schmelter-sap - no project role)
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/131/head:pull/131` \
`$ git checkout pull/131`

Update a local copy of the PR: \
`$ git checkout pull/131` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/131/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 131`

View PR using the GUI difftool: \
`$ git pr show -t 131`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/131.diff">https://git.openjdk.java.net/jdk11u-dev/pull/131.diff</a>

</details>

### CODE REVIEW

**Review by schmelter-sap — APPROVED** [review]
Looks good to me.

**Review by GoeLin — APPROVED** [review]
LGTM

**Review by tstuefe — APPROVED** [review]
+1

**Comment by AntonKozlov** [comment]
Don't we need https://bugs.openjdk.java.net/browse/JDK-8263066 to be backported as well? Just want to be sure, since I see `DumpWriter::seek_to_offset` in the source code, and it is used.

**Comment by schmelter-sap** [comment]
To be able to use the -overwrite flag for domain sockets or pipes this would be needed, but overwriting an existing file would work. 

I had not backported my change to 11, because the diff between 15 and 11 was large and it wasn't a bugfix, so not strictly needed. But if there is interest, it should be possible.

**Comment by RealCLanger** [comment]
> To be able to use the -overwrite flag for domain sockets or pipes this would be needed, but overwriting an existing file would work.
> 
> I had not backported my change to 11, because the diff between 15 and 11 was large and it wasn't a bugfix, so not strictly needed. But if there is interest, it should be possible.

Hm, together with this change actually https://bugs.openjdk.java.net/browse/JDK-8234510 seems more worthwhile to do. Maybe you want to look into bringing it to JDK11 now, @schmelter-sap? In any case, this backport seems to be good as is and does not need JDK-8234510 as a prerequisite, though its use is limited for the moment.

**Comment by schmelter-sap** [comment]
> Hm, together with this change actually https://bugs.openjdk.java.net/browse/JDK-8234510 seems more worthwhile to do. Maybe you want to look into bringing it to JDK11 now, @schmelter-sap? In any case, this backport seems to be good as is and does not need JDK-8234510 as a prerequisite, though its use is limited for the moment.

Yes, it would make sense to downport it now, since we now have an actual use for it.

**Comment by buddyliao** [comment]
> > Hm, together with this change actually https://bugs.openjdk.java.net/browse/JDK-8234510 seems more worthwhile to do. Maybe you want to look into bringing it to JDK11 now, @schmelter-sap? In any case, this backport seems to be good as is and does not need JDK-8234510 as a prerequisite, though its use is limited for the moment.
> 
> Yes, it would make sense to downport it now, since we now have an actual use for it.

I had backport your patch(JDK-8234510 ) here https://github.com/openjdk/jdk11u-dev/pull/134
Would you help me to review it? Thank you.

**Pull request closed without merging**
