### PR TITLE
8280007: Enable Neoverse N1 optimizations for Arm Neoverse V1 & N2

### PR DESCRIPTION
**Pull request by mmyxym**
Backport of JDK-8280007. The change should be enabled in JDK11 better performance on Neoverse V1/N1/N2. It is quite safe for existing in upstream and 17u for years.

Additional testing: aarch64 server ARM Neoverse N2 release/fastdebug tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8280007](https://bugs.openjdk.org/browse/JDK-8280007) needs maintainer approval

### Issue
 * [JDK-8280007](https://bugs.openjdk.org/browse/JDK-8280007): Enable Neoverse N1 optimizations for Arm Neoverse V1 &amp; N2 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2425/head:pull/2425` \
`$ git checkout pull/2425`

Update a local copy of the PR: \
`$ git checkout pull/2425` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2425/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2425`

View PR using the GUI difftool: \
`$ git pr show -t 2425`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2425.diff">https://git.openjdk.org/jdk11u-dev/pull/2425.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2425#issuecomment-1873581571)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi,
you approval request is not complete.
Please list reason, risk, testing and whether
the backport was clean. See also 
https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix "Example Fix Request comment"

Also, please enable GHA actions and restart the tests. 

Removing the label in the meantime.

**Comment by theRealAph** [comment]
Have a look at "Fix Approvals" https://wiki.openjdk.org/display/JDKUpdates/JDK11u and see what you think. I'm not sure if this one qualifies.

**Comment by mmyxym** [comment]
/approval request The reason to backport this patch is that enabling UseSIMDForMemoryOps will improve the performance of JDK11 on aarch64 neoverse servers. The Risk is quite low since the code is in upstream and 17u for years. The backport is actually clean but I had to resolve it because of the copyright modification. I have tested the aarch64 tier1 with fastdebug/release builds on Neoverse N2 and we have turned on this option on JDK11 in Alibaba for years on hundreds of workloads with ARM Neoverse N2.

**Comment by mmyxym** [comment]
> Have a look at "Fix Approvals" https://wiki.openjdk.org/display/JDKUpdates/JDK11u and see what you think. I'm not sure if this one qualifies.

I believe this backport is worth considering. JDK11 is still the most used JDK version and Arm Neoverse servers grow rapidly. And this patch is quite safe.

**Comment by GoeLin** [comment]
Given the fact this runs live at Alibaba it should be tested sufficiently to consider approval for 11, although this is a stable release and the change an optimization.  Disabling it again is simple in case it actually brings problems.

**Comment by theRealAph** [comment]
> > Have a look at "Fix Approvals" https://wiki.openjdk.org/display/JDKUpdates/JDK11u and see what you think. I'm not sure if this one qualifies.
> 
> I believe this backport is worth considering. JDK11 is still the most used JDK version and Arm Neoverse servers grow rapidly. And this patch is quite safe.

Understood, but that only addresses the "is of low risk" part of the requirement, but not the "substantial benefit to OpenJDK 11u users" part. What is the substantial benefit?

**Comment by mmyxym** [comment]
> > > Have a look at "Fix Approvals" https://wiki.openjdk.org/display/JDKUpdates/JDK11u and see what you think. I'm not sure if this one qualifies.
> > 
> > 
> > I believe this backport is worth considering. JDK11 is still the most used JDK version and Arm Neoverse servers grow rapidly. And this patch is quite safe.
> 
> Understood, but that only addresses the "is of low risk" part of the requirement, but not the "substantial benefit to OpenJDK 11u users" part. What is the substantial benefit?

UseSIMDForMemoryOps takes great advantage of ARM Neoverse on array copy ops which is substantial to applications on JDK11 running on ARM Neoverse servers.

**Comment by theRealAph** [comment]
> > > > Have a look at "Fix Approvals" https://wiki.openjdk.org/display/JDKUpdates/JDK11u and see what you think. I'm not sure if this one qualifies.
> > > 
> > > 
> > > I believe this backport is worth considering. JDK11 is still the most used JDK version and Arm Neoverse servers grow rapidly. And this patch is quite safe.
> > 
> > 
> > Understood, but that only addresses the "is of low risk" part of the requirement, but not the "substantial benefit to OpenJDK 11u users" part. What is the substantial benefit?
> 
> UseSIMDForMemoryOps takes great advantage of ARM Neoverse on array copy ops which is substantial to applications on JDK11 running on ARM Neoverse servers.

OK, so let's have a look at the benchmark results. I guess there was a benchmark submitted with the original patch which introduced vectorized memcpy, so it should just be a matter of re-running that on Neoverse V1 & N2. We could try it on V2 while we're at it, so we don't have to go through all this again soon.

**Comment by mmyxym** [comment]
> > > > > Have a look at "Fix Approvals" https://wiki.openjdk.org/display/JDKUpdates/JDK11u and see what you think. I'm not sure if this one qualifies.
> > > > 
> > > > 
> > > > I believe this backport is worth considering. JDK11 is still the most used JDK version and Arm Neoverse servers grow rapidly. And this patch is quite safe.
> > > 
> > > 
> > > Understood, but that only addresses the "is of low risk" part of the requirement, but not the "substantial benefit to OpenJDK 11u users" part. What is the substantial benefit?
> > 
> > 
> > UseSIMDForMemoryOps takes great advantage of ARM Neoverse on array copy ops which is substantial to applications on JDK11 running on ARM Neoverse servers.
> 
> OK, so let's have a look at the benchmark results. I guess there was a benchmark submitted with the original patch which introduced vectorized memcpy, so it should just be a matter of re-running that on Neoverse V1 & N2. We could try it on V2 while we're at it, so we don't have to go through all this again soon.

We have a bunch of array tests. UseSIMDForMemoryOps provides 10-60% improvements on several typical non-short array copy micro benchmarks on JDK11 with Neoverse N2.

**Comment by mmyxym** [comment]
> Please enable the GHA tests for the jdk11u-dev repo and restart the tests. You can restart them by merging head.

Merged and passed the GHA tests.

**Review by theRealAph — APPROVED** [review]
OK. On further contemplation, this falls within the scope of a change intended to keep the JDK working well as the world moves on. It doesn't set any precedents for other performance backports.

**Comment by mmyxym** [comment]
> OK. On further contemplation, this falls within the scope of a change intended to keep the JDK working well as the world moves on. It doesn't set any precedents for other performance backports.

Hi APH, could you please help to sponsor? Thanks.

**Pull request closed without merging**
