### PR TITLE
8313816: Accessing jmethodID might lead to spurious crashes

### PR DESCRIPTION
**Pull request by jbachorik**
This backport is, unfortunately, not a clean one.

The functional changes applied almost cleanly, modulo the change of 'nullptr' to 'NULL' in the source code.

The problematic part is the testing - the test had to be adjusted for JDK 11, I had to pull in two test support files (or could have extracted the support methods but it felt like having the full files would be easier to review considering differences against the original) and I had to change the whitebox function to trigger purging of the previous class version.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816): Accessing jmethodID might lead to spurious crashes (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2321/head:pull/2321` \
`$ git checkout pull/2321`

Update a local copy of the PR: \
`$ git checkout pull/2321` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2321`

View PR using the GUI difftool: \
`$ git pr show -t 2321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2321.diff">https://git.openjdk.org/jdk11u-dev/pull/2321.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2321#issuecomment-1836259847)

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
Looks like a clean backport from the 17u PR, except for replacing nullptr with NULL as you note, and the unused declaration of metaspaceSharedRegionAlignment in WhiteBox.java. The latter doesn't seem have a definition in 11u: if so, please remove it.

**Comment by jbachorik** [comment]
@phohensee There are the additional changes in the testing that were necessary. Although they are not affecting any existing code/tests.

**Comment by jbachorik** [comment]
/approval request Please, approve this backport of a fix improving stability of stack sampling profilers. The changed code is relevant only to retransformed method and the change itself is very simple - just nulling out any dangling pointers.

**Comment by amosshi** [comment]
Hi @jbachorik,

In  today's test result, the test case `test/hotspot/jtreg/serviceability/jvmti/thread/GetStackTrace/GetStackTraceAndRetransformTest/GetStackTraceAndRetransformTest.java` is failing with the following info:

- _Unsupported internal testing APIs have been used._

```
----------System.out:(20/1185)----------
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/metadataOnStackMark.cpp:50
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/priv/jenkins/client-home/workspace/openjdk-11u-dev-linux_x86_64-dbg/jdk/src/hotspot/share/classfile/metadataOnStackMark.cpp:50), pid=65261, tid=65413
#  assert(SafepointSynchronize::is_at_safepoint()) failed: sanity check
#
# JRE version: OpenJDK Runtime Environment (11.0.23) (fastdebug build 11.0.23-internal+0-adhoc..jdk)
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 11.0.23-internal+0-adhoc..jdk, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Core dump will be written. Default location: /priv/jvmtests/output_openjdk11_dev_dbgU_linuxx86_64/jtreg_hotspot_tier2_work/JTwork/scratch/8/core.65261
#
Unsupported internal testing APIs have been used.

# An error report file with more information is saved as:
# /priv/jvmtests/output_openjdk11_dev_dbgU_linuxx86_64/jtreg_hotspot_tier2_work/JTwork/scratch/8/hs_err_pid65261.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
```

Need your help to identify if this failure is caused by current PR or not.

Thanks
Amos
A Happy Developer

**Comment by jbachorik** [comment]
The test failure is tracked as https://bugs.openjdk.org/browse/JDK-8322752

**Pull request closed without merging**
