### PR TITLE
8268773: Improvements related to: Failed to start thread - pthread_create failed (EAGAIN)

### PR DESCRIPTION
**Pull request by basil**
Hi all,

This pull request contains a backport of [JDK-8268773](https://bugs.openjdk.java.net/browse/JDK-8268773) (commit [e35005d5ce383ddd108096a3079b17cb0bcf76f1](https://github.com/openjdk/jdk/commit/e35005d5ce383ddd108096a3079b17cb0bcf76f1)) from the [openjdk/jdk](https://git.openjdk.java.net/jdk) repository.

There was a trivial merge conflict in `thread.hpp`. In addition, I had to drop the change to `Thread::is_JavaThread_protected` in `thread.cpp`, because `Thread::is_JavaThread_protected` does not exist on `jdk11u-dev`.

The commit being backported was authored by @dholmes-ora on July 15, 2021, and was reviewed by @tstuefe and @iklam.

See [JENKINS-65873](https://issues.jenkins.io/browse/JENKINS-65873) for the motivation behind this backport.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8268773](https://bugs.openjdk.java.net/browse/JDK-8268773): Improvements related to: Failed to start thread - pthread_create failed (EAGAIN)

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/1074/head:pull/1074` \
`$ git checkout pull/1074`

Update a local copy of the PR: \
`$ git checkout pull/1074` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/1074/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1074`

View PR using the GUI difftool: \
`$ git pr show -t 1074`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/1074.diff">https://git.openjdk.java.net/jdk11u-dev/pull/1074.diff</a>

</details>

### CODE REVIEW

**Comment by basil** [comment]
I do not have JBS access. Can someone please submit the following comment with the `jdk11u-fix-request` label:

> Backporting https://github.com/openjdk/jdk/commit/e35005d5ce383ddd108096a3079b17cb0bcf76f1 shows a very significant reduction of the number of occurrences of [JENKINS-65873](https://issues.jenkins.io/browse/JENKINS-65873) (0.04% instead of 0.2% over 5000-6000 builds). The patch applies after resolving a trivial merge conflict in `thread.hpp` and dropping the change to `Thread::is_JavaThread_protected` in `thread.cpp` (because `Thread::is_JavaThread_protected` does not exist on `jdk11u-dev`).

**Comment by dholmes-ora** [comment]
JBS issue updated as requested

**Review by TheRealMDoerr — APPROVED** [review]
Ok, the omitted hunk belongs to [JDK-8241403](https://bugs.openjdk.java.net/browse/JDK-8241403) which will probably not get backported to 11u. LGTM.

**Pull request closed without merging**
