### PR TITLE
8301269: Update Commons BCEL to Version 6.7.0

### PR DESCRIPTION
**Pull request by RealLucy**
Fix request [11u] 

One of the required updates of external libs.

I based the bckport to 11u on Goetz's backport to 17u, Low risk.
Except for two copyright format issues (missing comma), I had to resolve just this one file: src/java.xml/share/classes/com/sun/org/apache/bcel/internal/classfile/Utility.java
This file had undergone major restructuring. In the end, the resolve process resulted in a simple copy from 17 to 11. 

SAP nightly testing successful. No findings attributable to this backport.
Review received.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301269](https://bugs.openjdk.org/browse/JDK-8301269): Update Commons BCEL to Version 6.7.0 (**Enhancement** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2082/head:pull/2082` \
`$ git checkout pull/2082`

Update a local copy of the PR: \
`$ git checkout pull/2082` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2082/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2082`

View PR using the GUI difftool: \
`$ git pr show -t 2082`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2082.diff">https://git.openjdk.org/jdk11u-dev/pull/2082.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2082#issuecomment-1680296860)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Ok, the diffs exist because https://github.com/openjdk/jdk17u-dev/commit/d799563ac06d66acea6dbd9cb1fe78b253e8a0e7 was not backported before this one. ([JDK-8256919](https://bugs.openjdk.org/browse/JDK-8256919) is actually also fixed with this PR.) LGTM.

**Comment by RealLucy** [comment]
Thank you for the review, @TheRealMDoerr 
I'll go ahead and request integrate authorization.

**Comment by RealLucy** [comment]
Failing pre-submit tests point to an infrastructure issue. Not related to this PR.

**Pull request closed without merging**
