### PR TITLE
8293563: [macos-aarch64] SA core file tests failing with sun.jvm.hotspot.oops.UnknownOopException

### PR DESCRIPTION
**Pull request by RealCLanger**
The backport of [JDK-8248194](https://bugs.openjdk.org/browse/JDK-8248194) introduced the testing of core files in test/hotspot/jtreg/serviceability/sa/ClhsdbFindPC.java. This can cause issues which we are seeing on MacOS arm64. With this backport, these seem to be gone.

The fix does not exactly fit into the 11u-dev codebase, so I had to make several adpatations.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8293563](https://bugs.openjdk.org/browse/JDK-8293563) needs maintainer approval

### Issue
 * [JDK-8293563](https://bugs.openjdk.org/browse/JDK-8293563): [macos-aarch64] SA core file tests failing with sun.jvm.hotspot.oops.UnknownOopException (**Bug** - P3 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2698/head:pull/2698` \
`$ git checkout pull/2698`

Update a local copy of the PR: \
`$ git checkout pull/2698` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2698/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2698`

View PR using the GUI difftool: \
`$ git pr show -t 2698`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2698.diff">https://git.openjdk.org/jdk11u-dev/pull/2698.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2698#issuecomment-2095394686)

### CODE REVIEW

**Comment by MBaesken** [comment]
When comparing to 17u-dev
https://github.com/openjdk/jdk17u-dev/pull/1903/files
I still see the 8269982 exclusions for macosx-aarch64 in the problem list. Why is that ? E.g.  TestJmapCore.java.

**Comment by RealCLanger** [comment]
> When comparing to 17u-dev https://github.com/openjdk/jdk17u-dev/pull/1903/files I still see the 8269982 exclusions for macosx-aarch64 in the problem list. Why is that ? E.g. TestJmapCore.java.

Good catch. Makes sense to remove this bug id in the three places where it currently appears. All of these tests have been addressed with this change.

**Comment by theRealAph** [comment]
The last time I tried, I couldn't get core files at all without doing a ton of fiddly config, turning off SIP, etc. Did you have to do any of that? Perhaps it's no longer a problem.

**Comment by RealCLanger** [comment]
> The last time I tried, I couldn't get core files at all without doing a ton of fiddly config, turning off SIP, etc. Did you have to do any of that? Perhaps it's no longer a problem.

Hm, when current jdk11u-dev hit our ci, the MacOS arm64 test is failing with exceptions like:

sun.jvm.hotspot.oops.UnknownOopException
	at jdk.hotspot.agent/sun.jvm.hotspot.oops.ObjectHeap.newOop(ObjectHeap.java:266)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.JavaThread.getThreadObj(JavaThread.java:359)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.JavaThread.getCurrentParkBlocker(JavaThread.java:411)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:82)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
	at jdk.hotspot.agent/sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor$24.doit(CommandProcessor.java:1066)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.executeCommand(CommandProcessor.java:1974)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.executeCommand(CommandProcessor.java:1944)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.run(CommandProcessor.java:1824)
	at jdk.hotspot.agent/sun.jvm.hotspot.CLHSDB.run(CLHSDB.java:99)
	at jdk.hotspot.agent/sun.jvm.hotspot.CLHSDB.main(CLHSDB.java:40)
	at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.runCLHSDB(SALauncher.java:224)
	at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.main(SALauncher.java:522)

And with this modification it goes away. That's all I can say... 😉

**Comment by MBaesken** [comment]
> > When comparing to 17u-dev https://github.com/openjdk/jdk17u-dev/pull/1903/files I still see the 8269982 exclusions for macosx-aarch64 in the problem list. Why is that ? E.g. TestJmapCore.java.
> 
> Good catch. Makes sense to remove this bug id in the three places where it currently appears. All of these tests have been addressed with this change.


You removed the bug-number 8269982, but not the references macosx-aarch64, why is that ?
Please compare to https://github.com/openjdk/jdk17u-dev/pull/1903/files  .

**Comment by RealCLanger** [comment]
> You removed the bug-number 8269982, but not the references macosx-aarch64, why is that ? Please compare to https://github.com/openjdk/jdk17u-dev/pull/1903/files .

You could be right, the other bug ids all refer to non macos-aarch64 problems. So let's try and enable the tests for macos-aarch64.

**Comment by MBaesken** [comment]
> So let's try and enable the tests for macos-aarch64.

Change looks okay to me otherwise.
Should we wait for some additional test outcomes after the   macos-aarch64   reenabling ?

**Comment by RealCLanger** [comment]
> > So let's try and enable the tests for macos-aarch64.
> 
> Change looks okay to me otherwise. Should we wait for some additional test outcomes after the macos-aarch64 reenabling ?

Yes, let's wait for GHA and SAP nightlies.

**Comment by RealCLanger** [comment]
Testing looks good.

**Review by MBaesken — APPROVED** [review]

**Pull request closed without merging**
