### PR TITLE
8290920: sspi_bridge.dll not built if BUILD_CRYPTO is false

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 11.0.19-oracle.

The file is named /make/lib/Lib-java.security.jgss.gmk in head, 
but make/lib/Lib-java.security.jgss.gmk in 11.
Modulo this file rename the patch applies clean.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290920](https://bugs.openjdk.org/browse/JDK-8290920): sspi_bridge.dll not built if BUILD_CRYPTO is false

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [9289bbd6](https://git.openjdk.org/jdk11u-dev/pull/1679/files/9289bbd6d8e3926b7e3c58a61073f18a43ee03a3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1679/head:pull/1679` \
`$ git checkout pull/1679`

Update a local copy of the PR: \
`$ git checkout pull/1679` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1679/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1679`

View PR using the GUI difftool: \
`$ git pr show -t 1679`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1679.diff">https://git.openjdk.org/jdk11u-dev/pull/1679.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Pre-submit failure: infra failure, unrelated.

**Review by MBaesken — COMMENTED** [review]
Hi Goetz , this needs isTargetOs  (see line 41). I think to use this you first have to backport 8218431: Improved platform checking in makefiles (see https://github.com/openjdk/jdk17u-dev/commit/208c58c8621247023e39c98a7b81638c62daedec ) .
Maybe not the whole commit but at least  what is in make/common/Utils.gmk .
Speaking of this,  it is already (probably wrongly so far) used in 11u-dev  
launcher/LauncherCommon.gmk:219:  ifeq ($(call isTargetOs, macosx), true)

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
I backported the change that brings isTargetOs, so this should be good on top of that change.
I force pushed to get this clean on top of that change.

**Comment by GoeLin** [comment]
Pre-submit failuer: All errors similar to  "Unable to connect to azure.archive.ubuntu.com:http" Restarting.

**Pull request closed without merging**
