### PR TITLE
8309305: sun/security/ssl/SSLSocketImpl/BlockedAsyncClose.java fails with jtreg test timeout

### PR DESCRIPTION
**Pull request by sendaoYan**
---------
### Progress
- [ ] [JDK-8309305](https://bugs.openjdk.org/browse/JDK-8309305) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309305](https://bugs.openjdk.org/browse/JDK-8309305): sun/security/ssl/SSLSocketImpl/BlockedAsyncClose.java fails with jtreg test timeout (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2537/head:pull/2537` \
`$ git checkout pull/2537`

Update a local copy of the PR: \
`$ git checkout pull/2537` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2537/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2537`

View PR using the GUI difftool: \
`$ git pr show -t 2537`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2537.diff">https://git.openjdk.org/jdk11u-dev/pull/2537.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2537#issuecomment-1956538160)

### CODE REVIEW

**Comment by sendaoYan** [comment]
[JDK-8309305](https://bugs.openjdk.org/browse/JDK-8309305) doesn't affect linux, I need some time to make a windows test environment. 

/approval cancel

**Comment by sendaoYan** [comment]
Shoule I close this PR first. After I finish verify this backport on windows reopen this PR?

**Comment by GoeLin** [comment]
No, there is no need to close it.  But you should not request approval if it is not ready.  Maybe you want to make it a draft PR.

**Comment by sendaoYan** [comment]
> No, there is no need to close it. But you should not request approval if it is not ready. Maybe you want to make it a draft PR.

OK.

**Comment by sendaoYan** [comment]
This testcase run pass on windows for now. And this testcase not in Problem-list.txt. I think it's not need to backport [JDK-8309305](https://bugs.openjdk.org/browse/JDK-8309305)



image

**Pull request closed without merging**
