### PR TITLE
8296343: CPVE thrown on missing content-length in OCSP response

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi!

Here is backport of [JDK-8296343](https://bugs.openjdk.org/browse/JDK-8296343). The patch fixes CertPathValidatorException taking place if OCSP response does not contain ContentLength field.

Original patch is applied cleanly except a conflict in Copyright record in `src/java.base/share/classes/sun/security/provider/certpath/OCSP.java`

Verification (amd64/20.04): newly added `test/jdk/sun/security/provider/certpath/OCSP/OCSPNoContentLength.java` FAILS, to be fixed by backporting of [JDK-8300939](https://bugs.openjdk.org/browse/JDK-8300939) (see https://github.com/openjdk/jdk11u-dev/pull/1921)
Regression (amd64/20.04): `jdk_security`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8296343](https://bugs.openjdk.org/browse/JDK-8296343) needs maintainer approval

### Integration blocker
&nbsp;⚠️ Dependency #1918 must be integrated first

### Issue
 * [JDK-8296343](https://bugs.openjdk.org/browse/JDK-8296343): CPVE thrown on missing content-length in OCSP response (**Bug** - P3)

### Reviewers
 * [Vladimir Kempik](https://openjdk.org/census#vkempik) (@VladimirKempik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1920/head:pull/1920` \
`$ git checkout pull/1920`

Update a local copy of the PR: \
`$ git checkout pull/1920` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1920/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1920`

View PR using the GUI difftool: \
`$ git pr show -t 1920`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1920.diff">https://git.openjdk.org/jdk11u-dev/pull/1920.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1920#issuecomment-1570600582)

### CODE REVIEW

**Comment by apavlyutkin** [comment]
Please don't close this, bot.

**Comment by apavlyutkin** [comment]
no blocker anymore

**Review by VladimirKempik — APPROVED** [review]
lgtm

**Pull request closed without merging**
