### PR TITLE
8306067: Open source AWT Graphics,GridBagLayout related tests

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8306067](https://bugs.openjdk.org/browse/JDK-8306067) and [JDK-8306838](https://bugs.openjdk.org/browse/JDK-8306838)

Testing
- Local: Test passed, on MacOS 14.4.1
  - `DrawNullStringTest.java`: Test results: passed: 1
  - `GetGraphicsTest.java`: Test results: passed: 1
  - `GridBagLayoutButtonsOverlapTest.java`: Test results: passed: 1
  - `GridBagLayoutOutOfBoundsTest.java`: Test results: passed: 1
- Pipeline: **All checks have passed**
- Testing Machine: SAP nightlies `GetGraphicsTest.java` skipped on `2024-04-25`
  - `java/awt/Graphics/GetGraphicsTest.java`: **SKIPPED** [Filter: Keywords - Not matching the given keyword expression: `(((!headful)&(!printer)&(!intermittent))) & !manual & !ignore`] GitHub 📊 - [0 msec]

---------
### Progress
- [x] [JDK-8306838](https://bugs.openjdk.org/browse/JDK-8306838) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8306067](https://bugs.openjdk.org/browse/JDK-8306067) needs maintainer approval

### Issues
 * [JDK-8306067](https://bugs.openjdk.org/browse/JDK-8306067): Open source AWT Graphics,GridBagLayout related tests (**Bug** - P4 - Approved)
 * [JDK-8306838](https://bugs.openjdk.org/browse/JDK-8306838): GetGraphicsTest needs to be headful (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2653/head:pull/2653` \
`$ git checkout pull/2653`

Update a local copy of the PR: \
`$ git checkout pull/2653` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2653/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2653`

View PR using the GUI difftool: \
`$ git pr show -t 2653`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2653.diff">https://git.openjdk.org/jdk11u-dev/pull/2653.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2653#issuecomment-2051015306)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request "Backporting for parity with 11.0.24-oracle. No risk, test fix. Clean backport. SAP nightlies passed on 2024-04-16,17,19,20”

**Comment by GoeLin** [comment]
@amosshi, the SAP nightlies are not passing! Please have a look.

**Comment by amosshi** [comment]
> @amosshi, the SAP nightlies are not passing! Please have a look.

Oops, `GetGraphicsTest.java` failed 

```
java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at GetGraphicsTest.<init>(GetGraphicsTest.java:35)
	at GetGraphicsTest.main(GetGraphicsTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:829)

JavaTest Message: Test threw exception: java.awt.HeadlessException
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.awt.HeadlessException
```

The 2nd commit just added, commit hash  rebased to jdk17u-dev so current PR is clean, waiting for testing machine result for the next days.

**Comment by amosshi** [comment]
/approval request "Backporting for parity with 11.0.24-oracle. Clean backport. No risk, test fix. SAP nightlies SKIPPED on 2024-04-25. Tested passed in local machine MacOS 14.4.1”

**Pull request closed without merging**
