### PR TITLE
8268185: Update GitHub Actions for jtreg 6

### PR DESCRIPTION
**Pull request by gdams**
simple backport of [JDK-8268185](https://bugs.openjdk.java.net/browse/JDK-8268185): Update GitHub Actions for jtreg 6 in preparation for the GitHub action rewrite backport.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8268185](https://bugs.openjdk.org/browse/JDK-8268185): Update GitHub Actions for jtreg 6

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [179d5224](https://git.openjdk.org/jdk11u-dev/pull/1239/files/179d5224c5f1a051e4f3cc1234d608480de70d07)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**) ⚠️ Review applies to [179d5224](https://git.openjdk.org/jdk11u-dev/pull/1239/files/179d5224c5f1a051e4f3cc1234d608480de70d07)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1239/head:pull/1239` \
`$ git checkout pull/1239`

Update a local copy of the PR: \
`$ git checkout pull/1239` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1239/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1239`

View PR using the GUI difftool: \
`$ git pr show -t 1239`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1239.diff">https://git.openjdk.org/jdk11u-dev/pull/1239.diff</a>

</details>

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
Should be clean, no idea why the bot doesn't recognize it.

**Comment by GoeLin** [comment]
Great. Let's see whether the tests are passing.

**Comment by GoeLin** [comment]
The backport is not clean because in 
.github/workflows/submit.yml
The original calls 'sh', but jdk11u-dev calls 'bash'.

Also, the context in make/conf/test-dependencies
differs ( BOOT_JDK_VERSION=11 vs 16).

But the change looks good.

Please only use the /clean command if you 
understood why the change is not clean.
Adaptions to Copyright, ProblemList and maybe
some Whitespace differences allow to 
use the command. 
Any resolves in code require a review, also 
such as the differences here.

I'll mark it reviewed in case the tests 
complete green.

**Comment by gdams** [comment]
@GoeLin all tests pass

**Review by GoeLin — APPROVED** [review]
LGTM

**Comment by GoeLin** [comment]
After pushing the other change, you have to give the bots some minutes to resolve this one.
Sometimes they manage and you can integrate right away, sometimes you need to merge.

**Comment by gdams** [comment]
@GoeLin / @RealCLanger looks like the rebase requires a new review...

**Pull request closed without merging**
