### PR TITLE
8140466: ChaCha20 and Poly1305 TLS Cipher Suites

### PR DESCRIPTION
**Pull request by alexeybakhtin**
This backport adds ChaCha20 cipher suites to 11u implementation for TLSv1.3 and TLSv1.2 protocols.
TLS_CHACHA20_POLY1305_SHA256 is one of the cipher suites SHOULD be implemented according to rfc8446 [1].

The original patch applies almost clean except for the test/jdk/javax/net/ssl/TLSCommon/CipherSuite.java file - the list of cipher suites was reordered by JDK-8210632 [2]

Also, I had to update two jtreg tests with ChaCha cipher suites:
test/jdk/javax/net/ssl/sanity/ciphersuites/CheckCipherSuites.java is updated because of JDK-8217579 [3] backport to 11u missed CHACHA20 cipher suites

test/jdk/javax/net/ssl/sanity/ciphersuites/CipherSuitesInOrder.java is updated because of JDK-8234728 [4] backport to 11u missed CHACHA20 cipher suites

sun/security/ssl and javax/net/ssl tests passed

[1] - https://datatracker.ietf.org/doc/html/rfc8446
[2] - https://bugs.openjdk.java.net/browse/JDK-8210632
[3] - https://bugs.openjdk.java.net/browse/JDK-8217579
[4] - https://bugs.openjdk.java.net/browse/JDK-8234728

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8140466](https://bugs.openjdk.java.net/browse/JDK-8140466): ChaCha20 and Poly1305 TLS Cipher Suites

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/59/head:pull/59` \
`$ git checkout pull/59`

Update a local copy of the PR: \
`$ git checkout pull/59` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/59/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 59`

View PR using the GUI difftool: \
`$ git pr show -t 59`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/59.diff">https://git.openjdk.java.net/jdk11u-dev/pull/59.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Looks good. Thanks for backporting!

**Comment by RealCLanger** [comment]
> @RealCLanger the issue for this pull request, [JDK-8140466](https://bugs.openjdk.java.net/browse/JDK-8140466), already has an approved CSR request: [JDK-8204192](https://bugs.openjdk.java.net/browse/JDK-8204192)

OK, /csr obviously doesn't work with backports. We need to wait until [JDK-8269299](https://bugs.openjdk.java.net/browse/JDK-8269299) is approved.

**Pull request closed without merging**
