### PR TITLE
8249087: Always initialize _body[0..1] in Symbol constructor

### PR DESCRIPTION
**Pull request by jmtd**
This change is closely related to 8247818, which we want to backport as part of getting jdk11u-dev to build with GCC >= 12.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8249087](https://bugs.openjdk.org/browse/JDK-8249087) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8249087](https://bugs.openjdk.org/browse/JDK-8249087): Always initialize _body[0..1] in Symbol constructor (**Enhancement** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2471/head:pull/2471` \
`$ git checkout pull/2471`

Update a local copy of the PR: \
`$ git checkout pull/2471` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2471/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2471`

View PR using the GUI difftool: \
`$ git pr show -t 2471`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2471.diff">https://git.openjdk.org/jdk11u-dev/pull/2471.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2471#issuecomment-1904159745)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Seems OK to me.

**Comment by jerboaa** [comment]
Please check if GHA failures of macos-aarch64 are related.

**Comment by jmtd** [comment]
@jerboaa 
> Please check if GHA failures of macos-aarch64 are related.

Thanks for your review!

I can reproduce them locally on an M1 Mac from this branch, and from the parent ([openjdk:pr/2451](https://github.com/openjdk/jdk11u-dev/tree/pr/2451)) and from its parent commit too (https://github.com/openjdk/jdk11u-dev/commit/bcfabe3ce20f9ba39501030957d6e5a96847d70c , merged to `master`).

Rebasing onto current `master` (https://github.com/openjdk/jdk11u-dev/commit/a60fb5a71d82faae6e6d7e6364d421fb181f2077) resolves the issue for me (for both PRs).

As such, the failures are unrelated. To get GHA green lights, I would need to rebase these two PRs. Would you like that?

**Comment by jerboaa** [comment]
> As such, the failures are unrelated. To get GHA green lights, I would need to rebase these two PRs. Would you like that?

Don't rebase. Merge master into your branch. That should fix it too. Thanks!

**Comment by jerboaa** [comment]
> > As such, the failures are unrelated. To get GHA green lights, I would need to rebase these two PRs. Would you like that?
> 
> Don't rebase. Merge master into your branch. That should fix it too. Thanks!

On second thought this is a dependent PR. OK, merge master into #2451 and rebase this one if you like.

**Comment by jmtd** [comment]
/approval request related backports 8247818 and 8249087 for modern GCC support in 11u ready for another look. Thanks!

**Pull request closed without merging**
