### PR TITLE
8215624: Add parallel heap iteration for jmap –histo

### PR DESCRIPTION
**Pull request by buddyliao**
Unclean backport, since original patch does not apply cleanly to 11u, because jmap command parameter is different between each other, and the code structure has little changed.
 
    8215624: Add parallel heap iteration for jmap -histo
    8253763: ParallelObjectIterator should have virtual destructor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8215624](https://bugs.openjdk.java.net/browse/JDK-8215624): Add parallel heap iteration for jmap –histo
 * [JDK-8253763](https://bugs.openjdk.java.net/browse/JDK-8253763): ParallelObjectIterator should have virtual destructor

### Reviewers
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/127/head:pull/127` \
`$ git checkout pull/127`

Update a local copy of the PR: \
`$ git checkout pull/127` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/127/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 127`

View PR using the GUI difftool: \
`$ git pr show -t 127`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/127.diff">https://git.openjdk.java.net/jdk11u-dev/pull/127.diff</a>

</details>

### CODE REVIEW

**Comment by buddyliao** [comment]
Would anyone help me to review this backport? Thank you!

**Comment by RealCLanger** [comment]
Hi, @buddyliao, we can have a look.

First of all, I see that you have included JDK-8253763 in this commit, which seems to make sense. Can you please add the issue to this PR via the "/issue add" command?

Furthermore, JDK-8251570 seems to be a follow up. Do you plan to backport this as well? If so, you could use a "dependent PR" to also propose a backport for this and we can test it together. Please let me know and I can guide you on how to do it.

**Comment by RealCLanger** [comment]
Another thing: Could you please enable Github Actions for this PR by merging jdk11u-dev master?

**Comment by buddyliao** [comment]
> Hi, @buddyliao, we can have a look.
> 
> First of all, I see that you have included JDK-8253763 in this commit, which seems to make sense. Can you please add the issue to this PR via the "/issue add" command?
> 
> Furthermore, JDK-8251570 seems to be a follow up. Do you plan to backport this as well? If so, you could use a "dependent PR" to also propose a backport for this and we can test it together. Please let me know and I can guide you on how to do it.

Hi RealCLanger , thank you for your kindly review and suggestions. I intent to backport JDK-8251570 after this patch. But I really don't know how to do it by using "dependent PR", since JDK-8251570 is based on this patch. Would you please guide me how to do this ? Thank you!

**Comment by RealCLanger** [comment]
> Hi RealCLanger , thank you for your kindly review and suggestions. I intent to backport JDK-8251570 after this patch. But I really don't know how to do it by using "dependent PR", since JDK-8251570 is based on this patch. Would you please guide me how to do this ? Thank you!

Sure. It is as simple as to do the backport based on this change/branch and create a PR with branch [pr/127](https://github.com/openjdk/jdk11u-dev/tree/pr/127) as target. If you have created the PR for JDK-8251570, please let me know. We can then run it together through our testing.

**Comment by buddyliao** [comment]
> > Hi RealCLanger , thank you for your kindly review and suggestions. I intent to backport JDK-8251570 after this patch. But I really don't know how to do it by using "dependent PR", since JDK-8251570 is based on this patch. Would you please guide me how to do this ? Thank you!
> 
> Sure. It is as simple as to do the backport based on this change/branch and create a PR with branch [pr/127](https://github.com/openjdk/jdk11u-dev/tree/pr/127) as target. If you have created the PR for JDK-8251570, please let me know. We can then run it together through our testing.

Hi RealCLanger, JDK-8251570 has been backported in https://github.com/openjdk/jdk11u-dev/pull/284, would you please help me to review them together, thank you very much.

**Review by schmelter-sap — COMMENTED** [review]
Thanks for the downport. The changes look good to me.

**Review by RealCLanger — APPROVED** [review]

**Pull request closed without merging**
