### PR TITLE
8257679: Improved unix compatibility layer in Windows build (winenv)

### PR DESCRIPTION
**Pull request by gdams**
The main conflict is the lack of the WSL backport ([8215445: Enable building for Windows in WSL](https://github.com/openjdk/jdk/commit/46eb26b692ac7f9431d5b479028ec87e56707557)) Something which doesn't apply particularly cleanly and isn't required to achieve the MSYS2 backport that I'm trying to reach. There are also several Solaris specific edge cases that needed to be rewritten.

This PR will finally allow me to backport [8287724: Fix various issues with msys2](https://github.com/openjdk/jdk17u-dev/commit/2e21c87fac8d60c3c7ed7b2d0afae9abfc110359) cleanly which should be the final piece in the puzzle to enabling MSYS2 builds.

@RealCLanger / @GoeLin I suggest that this is run through the full SAP nightlies before this is merged.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8257679](https://bugs.openjdk.org/browse/JDK-8257679): Improved unix compatibility layer in Windows build (winenv)
 * [JDK-8260272](https://bugs.openjdk.org/browse/JDK-8260272): bash configure --prefix does not work after JDK-8257679

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1278/head:pull/1278` \
`$ git checkout pull/1278`

Update a local copy of the PR: \
`$ git checkout pull/1278` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1278/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1278`

View PR using the GUI difftool: \
`$ git pr show -t 1278`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1278.diff">https://git.openjdk.org/jdk11u-dev/pull/1278.diff</a>

</details>

### CODE REVIEW

**Comment by gdams** [comment]
Getting build failures here.. Going to need some investigation

**Comment by gdams** [comment]
@magicus you wrote the original patch. Do you have any idea why the make is failing with:

```output
Building target 'default (exploded-image)' in configuration 'macos-aarch64'
make[3]: *** No rule to make target `/Users/gadams/jdk11u-dev/build/macos-aarch64/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS.vardeps', needed by `/Users/gadams/jdk11u-dev/build/macos-aarch64/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS_batch'.  Stop.
```

**Comment by magicus** [comment]
Not really, no. There is a lot of changes going on in this PR. I can see no clear reason why vardeps should have become broken. Try clearing the entire build directory and try again.

**Comment by gdams** [comment]
Triggering a set of builds on the Adoptium CI:

- [jdk11u-windows-x64-temurin #154](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/154/)

- [jdk11u-mac-aarch64-temurin #113](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-aarch64-temurin/113/)

- [jdk11u-linux-aarch64-temurin #150](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin/150/)

- [jdk11u-linux-s390x-temurin #136](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-temurin/136/)

- [jdk11u-linux-arm-temurin #140](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-temurin/140/)

- [jdk11u-linux-ppc64le-temurin #138](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-temurin/138/)

- [jdk11u-aix-ppc64-temurin #155](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/155/)

- [jdk11u-windows-x86-32-temurin #148](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-temurin/148/)

- [jdk11u-mac-x64-temurin #149](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-temurin/149/)

- [jdk11u-linux-x64-temurin #170](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-temurin/170/)

**Comment by RealCLanger** [comment]
I went over this PR now. It's rather huge and causes some headache - but on the other hand it modernizes the windows build environment and helps to significantly improve Github Actions testing. So I think we should go for it.

Testing in SAP's environment showed no issues or regressions.

One last question I have: The original change removes make/autoconf/util_windows.m4. Any reason why this is missed out here?

**Comment by gdams** [comment]
> One last question I have: The original change removes make/autoconf/util_windows.m4. Any reason why this is missed out here?

Good spot, removed it now

**Comment by lutkerd** [comment]
This seems to be causing a problem for us at Amazon. I am trying to figure out how but we are loosing a "\" in the middle of a path. It should be `C:\tools\cygwin\tmp\fixpath.3ZobaJ\atfile` and not `C:\toolscygwin\tmp\fixpath.3ZobaJ\atfile`

```
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
error: file not found: C:\toolscygwin\tmp\fixpath.3ZobaJ\atfile
make[3]: *** [ToolsLangtools.gmk:40: /cygdrive/c/wsjdk/corretto11src/installers/windows/zip/corretto-build/buildroot/build/windows-x86_64-normal-server-release/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS_batch] Error 3
make[2]: *** [make/Main.gmk:73: buildtools-langtools] Error 2
```

**Comment by RealCLanger** [comment]
> This seems to be causing a problem for us at Amazon. I am trying to figure out how but we are loosing a "" in the middle of a path. It should be `C:\tools\cygwin\tmp\fixpath.3ZobaJ\atfile` and not `C:\toolscygwin\tmp\fixpath.3ZobaJ\atfile`
> 
> ```
> Compiling 8 files for BUILD_TOOLS_LANGTOOLS
> error: file not found: C:\toolscygwin\tmp\fixpath.3ZobaJ\atfile
> make[3]: *** [ToolsLangtools.gmk:40: /cygdrive/c/wsjdk/corretto11src/installers/windows/zip/corretto-build/buildroot/build/windows-x86_64-normal-server-release/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS_batch] Error 3
> make[2]: *** [make/Main.gmk:73: buildtools-langtools] Error 2
> ```

Thanks for reporting. Would be good if you could find some more details here. Which make targets do you call?

**Comment by lutkerd** [comment]
> Thanks for reporting. Would be good if you could find some more details here. Which make targets do you call?

Just figured our the problem and will have the PR shortly to backport [JDK-8258005](https://bugs.openjdk.org/browse/JDK-8258005)

**Pull request closed without merging**
