### PR TITLE
8268635: Corrupt oop in ClassLoaderData

### PR DESCRIPTION
**Pull request by earthling-amzn**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8268635](https://bugs.openjdk.java.net/browse/JDK-8268635): Corrupt oop in ClassLoaderData

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/114/head:pull/114` \
`$ git checkout pull/114`

Update a local copy of the PR: \
`$ git checkout pull/114` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/114/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 114`

View PR using the GUI difftool: \
`$ git pr show -t 114`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/114.diff">https://git.openjdk.java.net/jdk11u-dev/pull/114.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
@earthling-amzn You should add `jdk11u-fix-request` tag and "Fix Request" comment for 11u maintainers approvals first.

**Comment by earthling-amzn** [comment]
/tag jdk11u-fix-request

Fix Request

**Comment by earthling-amzn** [comment]
@shipilev - Guessing I should do this on the JBS ticket?

**Comment by shipilev** [comment]
> @shipilev - Guessing I should do this on the JBS ticket?

Yes. https://wiki.openjdk.java.net/display/JDKUpdates/How+to+contribute+a+fix

**Comment by RealCLanger** [comment]
I approved it.

/sponsor

**Pull request closed without merging**
