### PR TITLE
8242188: error in jtreg test jdk/jfr/api/consumer/TestRecordedFrame.java on linux-aarch64

### PR DESCRIPTION
**Pull request by caojoshua**
clean backport after https://github.com/openjdk/jdk11u-dev/pull/1326

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8242188](https://bugs.openjdk.org/browse/JDK-8242188): error in jtreg test jdk/jfr/api/consumer/TestRecordedFrame.java on linux-aarch64

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1327/head:pull/1327` \
`$ git checkout pull/1327`

Update a local copy of the PR: \
`$ git checkout pull/1327` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1327/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1327`

View PR using the GUI difftool: \
`$ git pr show -t 1327`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1327.diff">https://git.openjdk.org/jdk11u-dev/pull/1327.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
Needs renaming to "Backport <sha>" as well...

**Comment by phohensee** [comment]
JBS issue tagged.

**Comment by caojoshua** [comment]
pushed merge from master

**Pull request closed without merging**
