### PR TITLE
8221907: make reconfigure breaks when configured with relative paths

### PR DESCRIPTION
**Pull request by gdams**
Backport applies cleanly except for missing some WSL-specific patches. Backport is a prerequisite of https://github.com/openjdk/jdk11u-dev/pull/1277

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8221907](https://bugs.openjdk.org/browse/JDK-8221907): make reconfigure breaks when configured with relative paths

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1301/head:pull/1301` \
`$ git checkout pull/1301`

Update a local copy of the PR: \
`$ git checkout pull/1301` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1301/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1301`

View PR using the GUI difftool: \
`$ git pr show -t 1301`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1301.diff">https://git.openjdk.org/jdk11u-dev/pull/1301.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
> Backport applies cleanly other than [`make/Init.gmk`](https://github.com/openjdk/jdk/commit/0974861dd800fdb44b3888e68b08c570f1985b58#diff-0bff77b1e720a2f054706fa08e621af3034963c0e132a5537b006670fed865a5R282) Which doesn't have `AUTOCONF="$(AUTOCONF)"` in JDK11u. Backport is a prerequisite of #1277

Maybe you want to make this a dependent PR of #1300 and it would then be clean?

**Comment by gdams** [comment]
> Maybe you want to make this a dependent PR of https://github.com/openjdk/jdk11u-dev/pull/1300 and it would then be clean?

@RealCLanger I was planning on doing so - just waiting for the branch to be created

**Review by RealCLanger — APPROVED** [review]
This looks fine and passes SAP nightlies.

**Pull request closed without merging**
