### PR TITLE
8232839: JDI AfterThreadDeathTest.java failed due to "FAILED: Did not get expected IllegalThreadStateException on a StepRequest.enable()"

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8232839](https://bugs.openjdk.org/browse/JDK-8232839)

Unclean backport
- The [original PR](https://github.com/openjdk/jdk/commit/84184f947342fd1adbe4e3f2230ce3de4ae6007e) was removing 2 lines from `test/jdk/ProblemList.txt` file
- While in Java 11 these lines does not exist, so no need to touch this file

Teses
- PR: All checks have passed
- SAP nightlies passed on `2023-12-23,24`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8232839](https://bugs.openjdk.org/browse/JDK-8232839) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8232839](https://bugs.openjdk.org/browse/JDK-8232839): JDI AfterThreadDeathTest.java failed due to "FAILED: Did not get expected IllegalThreadStateException on a StepRequest.enable()" (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2376/head:pull/2376` \
`$ git checkout pull/2376`

Update a local copy of the PR: \
`$ git checkout pull/2376` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2376/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2376`

View PR using the GUI difftool: \
`$ git pr show -t 2376`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2376.diff">https://git.openjdk.org/jdk11u-dev/pull/2376.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2376#issuecomment-1854670678)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean backport. SAP nightlies passed on 2023-12-15”

**Comment by GoeLin** [comment]
Hi @amosshi, the original change removes the line from the ProblemList, your change adds it.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean back port. SAP nightlies passed on 2023-12-19”

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean back port. SAP nightlies passed on 2023-12-19”

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean back port. SAP nightlies passed on 2023-12-23”

**Pull request closed without merging**
