### PR TITLE
8211978: Move  testlibrary/jdk/testlibrary/SimpleSSLContext.java and testkeys to network testlibrary

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8211978](https://bugs.openjdk.org/browse/JDK-8211978)

The following files need manual merge:
- `test/jdk/java/net/HttpURLConnection/SetAuthenticator/HTTPSetAuthenticatorTest.java`
  - `Copyright (c) year` sections cannot be auto merged
  - The curent `year` in [jdk11u-dev](https://github.com/openjdk/jdk11u-dev) is newer, so the change can be considered as **clean**
- `test/jdk/java/net/HttpURLConnection/SetAuthenticator/HTTPTest.java`
  - `Copyright (c) year` sections cannot be auto merged
  - The curent `year` in [jdk11u-dev](https://github.com/openjdk/jdk11u-dev) is newer, so the change can be considered as **clean**
- `test/jdk/java/net/httpclient/AbstractThrowingPushPromises.java` 
  - The base line number is different so cannot be auto merged; 
  - the changes are the same as original commit in [jdk](https://github.com/openjdk/jdk) repo, so the change is **clean**
- `test/jdk/java/net/httpclient/HttpsTunnelTest.java` 
  - The base line number is different so cannot be auto merged; 
  - the changes are the same as original commit in [jdk](https://github.com/openjdk/jdk) repo, so the change is **clean**
- `test/jdk/java/net/httpclient/InvalidSSLContextTest.java` 
  - The base line number is different so cannot be auto merged; 
  - the changes are the same as original commit in [jdk](https://github.com/openjdk/jdk) repo, so the change is **clean**
- `test/jdk/java/net/httpclient/ShortResponseBody.java` 
  - `@library /lib/testlibrary` and `@build jdk.testlibrary.SimpleSSLContext` lines does not exist, just as [jdk](https://github.com/openjdk/jdk) repo, so we san safely ignore them, so the change is **clean**
- `test/jdk/java/net/httpclient/SmokeTest.java` 
  - The base line number is different so cannot be auto merged; 
  - the changes are the same as original commit in [jdk](https://github.com/openjdk/jdk) repo, so the change is **clean**
- `test/jdk/java/net/httpclient/SpecialHeadersTest.java` 
  - The base line number is different so cannot be auto merged; 
  - the changes are the same as original commit in [jdk](https://github.com/openjdk/jdk) repo, so the change is **clean**
- `test/jdk/java/net/httpclient/UnknownBodyLengthTest.java` 
  - The base line number is different so cannot be auto merged; 
  - the changes are the same as original commit in [jdk](https://github.com/openjdk/jdk) repo, so the change is **clean**
- `test/jdk/java/net/httpclient/whitebox/java.net.http/jdk/internal/net/http/FlowTest.java` 
  - `Copyright (c) year` sections cannot be auto merged
  - The curent `year` in [jdk11u-dev](https://github.com/openjdk/jdk11u-dev) is newer, so the change can be considered as **clean**
- `test/jdk/sun/net/www/protocol/http/RedirectOnPost.java` 
  - Delete unused `@library /lib/testlibrary/` line
  - after the changes, the code is the same as current [jdk](https://github.com/openjdk/jdk) repo, so the change can be considered as **clean**

Special change via the 2nd commit https://github.com/openjdk/jdk11u-dev/pull/2330/commits/01d0d52b6dd33dc2df04df00d39dd727c055385d
- `ShortResponseBodyWithRetry.java` has been renamed to `test/jdk/java/net/httpclient/ShortResponseBodyPostWithRetry.java`
  - Manually adopted the same change to the current file `ShortResponseBodyPostWithRetry.java`

This PR **test succeeded in local dev machine** of MacBook Pro Apple M1 Max

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8211978](https://bugs.openjdk.org/browse/JDK-8211978) needs maintainer approval

### Issue
 * [JDK-8211978](https://bugs.openjdk.org/browse/JDK-8211978): Move  testlibrary/jdk/testlibrary/SimpleSSLContext.java and testkeys to network testlibrary (**Sub-task** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2330/head:pull/2330` \
`$ git checkout pull/2330`

Update a local copy of the PR: \
`$ git checkout pull/2330` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2330/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2330`

View PR using the GUI difftool: \
`$ git pr show -t 2330`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2330.diff">https://git.openjdk.org/jdk11u-dev/pull/2330.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2330#issuecomment-1838278489)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean backort. SAP nightlies passed on 2023-12-04.”

**Review by MBaesken — COMMENTED** [review]
I found 70 occurrences of "import jdk.testlibrary.SimpleSSLContext;" in your change that were replaced.

But when doing a grep on current 11u-dev/test  dir I find 80 occurrences, what happens to the other 10, are they replaced in another change or kept for good reason ?

jdk/com/sun/net/httpserver/SelCacheTest.java:34:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test1.java:41:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test12.java:39:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test13.java:40:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test6a.java:39:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test7a.java:39:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test8a.java:39:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test9.java:39:import jdk.testlibrary.SimpleSSLContext;
jdk/com/sun/net/httpserver/Test9a.java:39:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/HttpURLConnection/SetAuthenticator/HTTPTest.java:42:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/URLPermission/URLTest.java:41:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ALPNProxyFailureTest.java:46:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/AbstractNoBody.java:38:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/AbstractThrowingPublishers.java:27:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/AbstractThrowingPushPromises.java:43:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/AbstractThrowingSubscribers.java:27:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/AsFileDownloadTest.java:70:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/BasicRedirectTest.java:56:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/CancelledResponse.java:29:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ConcurrentResponses.java:70:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/CookieHeaderTest.java:46:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/CustomRequestPublisher.java:65:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/CustomResponseSubscriber.java:60:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/DependentActionsTest.java:46:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/DependentPromiseActionsTest.java:43:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/DigestEchoClient.java:54:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/EchoHandler.java:35:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/EncodedCharsInURI.java:45:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/EscapedOctetsInURI.java:61:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ExpectContinue.java:52:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/FlowAdapterPublisherTest.java:46:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/FlowAdapterSubscriberTest.java:51:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ForbiddenHeadTest.java:50:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/HeadTest.java:45:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/HttpClientBuilderTest.java:51:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/HttpEchoHandler.java:35:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/HttpVersionsTest.java:51:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/HttpsTunnelTest.java:26:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ImmutableFlowItems.java:60:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/InvalidInputStreamSubscriptionRequest.java:41:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/InvalidSSLContextTest.java:51:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/InvalidSubscriptionRequest.java:42:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/LightWeightHttpServer.java:53:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/LineBodyHandlerTest.java:55:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ManyRequests.java:66:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ManyRequestsLegacy.java:73:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/MappingResponseSubscriber.java:65:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/MaxStreams.java:63:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/NonAsciiCharsInURI.java:61:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ProxySelectorTest.java:51:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ProxyTest.java:59:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/RedirectMethodChange.java:53:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/RedirectWithCookie.java:58:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/Response204V2Test.java:61:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ResponseBodyBeforeError.java:55:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ResponsePublisher.java:43:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/RetryWithCookie.java:45:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ServerCloseTest.java:38:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/ShortResponseBody.java:47:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/SmokeTest.java:93:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/SpecialHeadersTest.java:49:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/SplitResponse.java:43:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/StreamingBody.java:56:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/TimeoutBasic.java:34:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/UnauthorizedTest.java:49:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/UnknownBodyLengthTest.java:42:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/UserCookieTest.java:79:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/BadHeadersTest.java:41:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/BasicTest.java:50:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/ContinuationFrameTest.java:58:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/ErrorTest.java:49:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/FixedThreadPoolTest.java:43:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/NoBodyTest.java:48:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/http2/ProxyTest2.java:55:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/websocket/WSHandshakeExceptionTest.java:42:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/websocket/WebSocketProxyTest.java:62:import jdk.testlibrary.SimpleSSLContext;
jdk/java/net/httpclient/websocket/HandshakeUrlEncodingTest.java:42:import jdk.testlibrary.SimpleSSLContext;
jdk/javax/net/ssl/HttpsURLConnection/Equals.java:37:import jdk.testlibrary.SimpleSSLContext;
jdk/sun/net/www/protocol/http/RedirectOnPost.java:42:import jdk.testlibrary.SimpleSSLContext;
jdk/sun/security/krb5/auto/HttpsCB.java:97:import jdk.testlibrary.SimpleSSLContext;

**Comment by TheRealMDoerr** [comment]
Your resolution looks very good. I've checked all your edits.
ShortResponseBodyWithRetry.java has been renamed to ShortResponseBodyPostWithRetry.java by https://github.com/openjdk/jdk11u/commit/2b75da651699bdbe44ba42be7259fade9e65dfcc.
I think the ShortResponseBodyWithRetry.java from https://github.com/openjdk/jdk/commit/4fe2edae5948e95f1940a64a3e9d4379e8362d8c should get integrated to the other file.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean back port. SAP nightlies passed on 2023-12-04”

**Comment by TheRealMDoerr** [comment]
I still don't see the ShortResponseBodyWithRetry.java part from https://github.com/openjdk/jdk/commit/4fe2edae5948e95f1940a64a3e9d4379e8362d8c.

**Review by TheRealMDoerr — APPROVED** [review]
Thanks! Looks good, now.

**Pull request closed without merging**
