### PR TITLE
8217850: CompressedClassSpaceSizeInJmapHeap fails after JDK-8217612

### PR DESCRIPTION
**Pull request by toshiogata**
Hi all,

This is a backport of JDK-8217850: CompressedClassSpaceSizeInJmapHeap fails after JDK-8217612

I worked for backporting JDK-8217612, and found that this related patch should be backported at the same time.

The riginal patch is applied cleanly to JDK-8217612 applied code.

Testing: all serviceability agent tests, hotspot_all that includes CompressedClassSpaceSizeInJmapHeap.java and the test which come with JDK-8217612.

Thank you.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8217850](https://bugs.openjdk.org/browse/JDK-8217850): CompressedClassSpaceSizeInJmapHeap fails after JDK-8217612 (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2096/head:pull/2096` \
`$ git checkout pull/2096`

Update a local copy of the PR: \
`$ git checkout pull/2096` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2096/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2096`

View PR using the GUI difftool: \
`$ git pr show -t 2096`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2096.diff">https://git.openjdk.org/jdk11u-dev/pull/2096.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2096#issuecomment-1691339262)

### CODE REVIEW

**Comment by phohensee** [comment]
Please make this PR dependent on https://github.com/openjdk/jdk11u-dev/pull/2096. It should apply cleanly/minimally after that.

**Comment by phohensee** [comment]
Please merge with upstream jdk11u-dev now that https://github.com/openjdk/jdk11u-dev/pull/2093 has been integrated. The result should be clean.

**Comment by toshiogata** [comment]
Thank you for your comment. Merged with upstream jdk11u-dev to verify that this is a clean backport.

**Pull request closed without merging**
