### PR TITLE
8210988: Improved handling of compiler warnings in the build

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 11.0.24-oracle.
make/hotspot/lib/CompileGtest.gmk
‘DISABLED_WARNINGS_microsoft := $(DISABLED_WARNINGS_microsoft) \
        4146, \’
make/hotspot/lib/CompileJvm.gmk
DISABLED_WARNINGS_microsoft := $(DISABLED_WARNINGS_microsoft) 4146, \

The DISABLED_WARNINGS_microsoft change to 4146 as in src\hotspot\cpu\aarch64\register_aarch64.hpp(285)
'uint32_t first = _bitset & -_bitset' remains.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8210988](https://bugs.openjdk.org/browse/JDK-8210988) needs maintainer approval

### Issue
 * [JDK-8210988](https://bugs.openjdk.org/browse/JDK-8210988): Improved handling of compiler warnings in the build (**Bug** - P3 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to [383b9e3d](https://git.openjdk.org/jdk11u-dev/pull/2606/files/383b9e3d58e0cdbdb3c31060626a62903620433c)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2606/head:pull/2606` \
`$ git checkout pull/2606`

Update a local copy of the PR: \
`$ git checkout pull/2606` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2606/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2606`

View PR using the GUI difftool: \
`$ git pr show -t 2606`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2606.diff">https://git.openjdk.org/jdk11u-dev/pull/2606.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2606#issuecomment-2003046601)

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
LGTM

**Comment by GoeLin** [comment]
Hi @luchenlin, @RealLucy,
are you sure the build errors are unrelated?

d:\a\jdk11u-dev\jdk11u-dev\src\hotspot\cpu\aarch64\register_aarch64.hpp(285): error C2220: the following warning is treated as an error
d:\a\jdk11u-dev\jdk11u-dev\src\hotspot\cpu\aarch64\register_aarch64.hpp(285): warning C4146: unary minus operator applied to unsigned type, result still unsigned
make[3]: *** [lib/CompileGtest.gmk:64: /d/a/jdk11u-dev/jdk11u-dev/build/windows-aarch64/hotspot/variant-server/libjvm/gtest/objs/BUILD_GTEST_LIBJVM_pch.obj] Error 1
make[2]: *** [make/Main.gmk:272: hotspot-server-libs] Error 2

Best regards, Goetz.

**Comment by luchenlin** [comment]
> Hi @luchenlin, @RealLucy, are you sure the build errors are unrelated?
> 
> d:\a\jdk11u-dev\jdk11u-dev\src\hotspot\cpu\aarch64\register_aarch64.hpp(285): error C2220: the following warning is treated as an error d:\a\jdk11u-dev\jdk11u-dev\src\hotspot\cpu\aarch64\register_aarch64.hpp(285): warning C4146: unary minus operator applied to unsigned type, result still unsigned make[3]: *** [lib/CompileGtest.gmk:64: /d/a/jdk11u-dev/jdk11u-dev/build/windows-aarch64/hotspot/variant-server/libjvm/gtest/objs/BUILD_GTEST_LIBJVM_pch.obj] Error 1 make[2]: *** [make/Main.gmk:272: hotspot-server-libs] Error 2
> 
> Best regards, Goetz.

Hi @GoeLin,  not sure about this, is this like the related backport? https://bugs.openjdk.org/browse/JDK-8211081

**Comment by gnu-andrew** [comment]
I found a number of issues with this backport, detailed in [JDK-8335801](https://bugs.openjdk.org/browse/JDK-8335801) and fixed in https://github.com/openjdk/jdk11u-dev/pull/2838

I don't see why this was backported at all. There is no strong reason given in the approval request. Oracle parity is not a sufficient reason alone in most cases, and certainly not for build issues. Oracle have to worry about one build environment (their own) when backporting fixes. As a FOSS project, OpenJDK 11 has to be buildable on a myriad of different compilers, operating systems and architectures. Backports that alter the build system should not be undertaken lightly and they certainly need to be done more carefully than this one was.

**Pull request closed without merging**
