### PR TITLE
8227122: [TESTBUG] Create Docker sidecar test cases

### PR DESCRIPTION
**Pull request by vieiro**
This is a backport of [JDK-8227122](https://bugs.openjdk.org/browse/JDK-8227122).

Backport is not clean because we've already applied [JDK-8272398](https://bugs.openjdk.org/browse/JDK-8272398) in jdk11u (in upstream JDK-8272398 was applied _after_ JDK-8227122), so it's necessary to make a small adaptation, that I've separated in a second commit to ease review.  Let me know if you prefer me squashing the commits.

Tested on Fedora 40 with Docker version 27.0.1, build 7fafd33.

```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/containers/docker/TestJcmdWithSideCar.java
                                                         1     1     0     0   
==============================
TEST SUCCESS
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8227122](https://bugs.openjdk.org/browse/JDK-8227122) needs maintainer approval

### Issue
 * [JDK-8227122](https://bugs.openjdk.org/browse/JDK-8227122): [TESTBUG] Create Docker sidecar test cases (**Enhancement** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2815/head:pull/2815` \
`$ git checkout pull/2815`

Update a local copy of the PR: \
`$ git checkout pull/2815` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2815/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2815`

View PR using the GUI difftool: \
`$ git pr show -t 2815`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2815.diff">https://git.openjdk.org/jdk11u-dev/pull/2815.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2815#issuecomment-2191321515)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by vieiro** [comment]
Thanks for the review! Let's now
/approval request JDK-8227122  [TESTBUG] Create Docker sidecar test cases

**Comment by vieiro** [comment]
/approval request JDK-8227122  [TESTBUG] Create Docker sidecar test cases

**Comment by jerboaa** [comment]
@vieiro Please take a minute and look at the generated fix request comment created in https://github.com/openjdk/jdk11u-dev/pull/2815#issuecomment-2192072624. It's not useful (consider that maintainers use the JBS system to look at those requests):

```
[jdk11u-fix-request] Approval Request from Antonio Vieiro
[JDK-8227122](https://bugs.openjdk.org/browse/JDK-8227122) [TESTBUG] Create Docker sidecar test cases
```

So you're request comment repeats the bug synopsis, which is already apparent when looking at it for approval.

Fix request comment guidance is here (Step 6, point `ii`):
https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

Please update the request by issuing `/approval request` again.

**Comment by vieiro** [comment]
/approval request Fix Request 11u,
For parity with Oracle 11.0.24. Low risk. This also paves the way for adding further container related tests to 11u.

**Comment by vieiro** [comment]
/integrate
Thanks for the review and tips!

**Pull request closed without merging**
