### PR TITLE
8287906: Rewrite of GitHub Actions (GHA) sanity tests

### PR DESCRIPTION
**Pull request by gdams**
The final piece of the puzzle here, backports the GitHub actions rewrite. Also backported JDK-8288499 as it is required for this to be complete.

Clean other than the fact that JDK-8295714 was applied before so had to be rewritten and macOS-10.15 is now deprecated so had to switch to 11 (which had happened already in the old workflow layout.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8287906](https://bugs.openjdk.org/browse/JDK-8287906): Rewrite of GitHub Actions (GHA) sanity tests
 * [JDK-8288499](https://bugs.openjdk.org/browse/JDK-8288499): Restore cancel-in-progress in GHA

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1554/head:pull/1554` \
`$ git checkout pull/1554`

Update a local copy of the PR: \
`$ git checkout pull/1554` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1554/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1554`

View PR using the GUI difftool: \
`$ git pr show -t 1554`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1554.diff">https://git.openjdk.org/jdk11u-dev/pull/1554.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
The backport of [JDK-8288499](https://bugs.openjdk.org/browse/JDK-8288499), though trivial, should be done separately. You can make that backport dependent on this one, see

https://blog.logrocket.com/using-stacked-pull-requests-in-github/

**Review by RealCLanger — APPROVED** [review]
This looks good now!

**Comment by RealCLanger** [comment]
> The backport of [JDK-8288499](https://bugs.openjdk.org/browse/JDK-8288499), though trivial, should be done separately. 

Hi, @phohensee, 
yes, usually that's the process. But I think for this type of little regression fixes, it's ok and pragmatic to do that inline. The Skara bots also help to resolve the JBS items correctly. We've been doing that here and there already and I personally endorse this pattern.

**Review by phohensee — APPROVED** [review]
If that's the policy, lgtm. :)

**Pull request closed without merging**
