### PR TITLE
8288763: Pack200 extraction failure with invalid size

### PR DESCRIPTION
**Pull request by backwaterred**
While running some internal testing, a college has discovered a failure related to the Pack200 archive format on the zLinux platform. The problematic code was removed in the current repo by [JDK-8234596](https://bugs.openjdk.org/browse/JDK-8234596), however that change was large, and required a CSR. I feel that it would be too risky and cumbersome to backport those changes to jdk11 (and ultimately jdk8 as well), so I'd like to propose this change as a new change to jdk11 rather than via the usual backport process.

### Testing
These changes have been run against the failing test on zLinux and the Tier 1 tests completed successfully.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288763](https://bugs.openjdk.org/browse/JDK-8288763): Pack200 extraction failure with invalid size

### Reviewers
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1163/head:pull/1163` \
`$ git checkout pull/1163`

Update a local copy of the PR: \
`$ git checkout pull/1163` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1163/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1163`

View PR using the GUI difftool: \
`$ git pr show -t 1163`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1163.diff">https://git.openjdk.org/jdk11u-dev/pull/1163.diff</a>

</details>

### CODE REVIEW

**Review by RealLucy — CHANGES_REQUESTED** [review]
Changes look good to me. 

I would like to see a short comment, explaining why it is necessary to reset the compressed size. Looking at the class declaration, I see all members being preset with some value. Is the same instance (re)used multiple times?

Additional "issue": I'm not a Reviewer for the jdk-updates project. Someone else will need to jump in here, maybe @TheRealMDoerr

**Comment by backwaterred** [comment]
Thanks for your feedback @simonis, @RealCLanger and @RealLucy.

> I would like to see a short comment, explaining why it is necessary to reset the compressed size.

I think this is a good suggestion, and it's on my todo list.

> This is all a little bit confusing. First of all I don't think that this issue is s390 related.

This is likely my mistake. A member of the Linux on s390 team reported the issue to me, and I must have assumed it was related to that platform. Sorry for the confusion; I have removed the s390 tag in JBS.

> Can you please report the following... Then, do the following

Yes. Though I won't have access to this system until next week. I will report back when I have this information.

**Comment by backwaterred** [comment]
It took me a bit longer than anticipated to get to this. Below is the output you requested @simonis.

> - is the libzip.so of your JDK statically or dynamically linked against zlib (i.e. ldd <path-to-jdk>/lib/libzip.so | grep libz)

Looks like it is dynamically linked:
```
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted# ldd ../temurin/lib/libzip.so
...
	libz.so.1 => /lib/s390x-linux-gnu/libz.so.1 (0x000003ffaa900000)
```

> - the version of the system zlib (i.e. /lib/x86_64-linux-gnu/libz.so.1 -> libz.so.1.2.11)

You had the version right on.

```
 ls -al /lib/s390x-linux-gnu/libz.so.1
lrwxrwxrwx 1 root root 14 Mar 26 18:20 /lib/s390x-linux-gnu/libz.so.1 -> libz.so.1.2.11
```

Following the remaining steps shows a different compressed size.

```
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted# zipinfo -l sample04.jar
Archive:  sample04.jar
Zip file size: 11392 bytes, number of entries: 7
-rw----     2.0 fat        0 bX        2 defN 04-Jan-30 13:34 META-INF/
-rw----     2.0 fat       68 bl       68 defN 04-Jan-30 13:34 META-INF/MANIFEST.MF
-rw----     2.0 fat      943 bl      502 defN 04-Jan-30 13:06 com/sun/java/help/impl/CustomKit$CustomDocument.class
-rw----     2.0 fat     3574 bl     1882 defN 04-Jan-30 13:06 com/sun/java/help/impl/CustomKit$ObjectView1.class
-rw----     2.0 fat      191 bl      154 defN 04-Jan-30 13:06 com/sun/java/help/impl/ViewAwareComponent.class
-rw----     2.0 fat     1009 bl      497 defN 04-Jan-30 13:06 com/sun/java/help/impl/JHSecondaryViewer$1.class
-rw----     2.0 fat    14175 bl     7067 defN 04-Jan-30 13:06 com/sun/java/help/impl/JHSecondaryViewer.class
7 files, 19960 bytes uncompressed, 10172 bytes compressed:  49.0%
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted# mkdir scratch
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted# cd scratch/
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted/scratch# cp ../sample04.jar .
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted/scratch# unzip sample04.jar
Archive:  sample04.jar
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF
  inflating: com/sun/java/help/impl/CustomKit$CustomDocument.class
  inflating: com/sun/java/help/impl/CustomKit$ObjectView1.class
  inflating: com/sun/java/help/impl/ViewAwareComponent.class
  inflating: com/sun/java/help/impl/JHSecondaryViewer$1.class
  inflating: com/sun/java/help/impl/JHSecondaryViewer.class
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted/scratch# #../../temurin/bin/jar cfm new_sample.jar META-INF/MANIFEST.MF *
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted/scratch# rm sample04.jar
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted/scratch# ../../temurin/bin/jar cfm new_sample.jar META-INF/MANIFEST.MF *
root@15d4a6cf6145:~/workspace/UnpackDistributedFailureExtracted/scratch# zipinfo -l new_sample.jar
Archive:  new_sample.jar
Zip file size: 13114 bytes, number of entries: 12
-rw----     2.0 fat        0 bX        2 defN 22-Jul-07 13:58 META-INF/
-rw----     2.0 fat       68 bl       71 defN 22-Jul-07 13:58 META-INF/MANIFEST.MF
-rw----     1.0 fat        0 b-        0 stor 22-Jul-07 13:57 com/
-rw----     1.0 fat        0 b-        0 stor 22-Jul-07 13:57 com/sun/
-rw----     1.0 fat        0 b-        0 stor 22-Jul-07 13:57 com/sun/java/
-rw----     1.0 fat        0 b-        0 stor 22-Jul-07 13:57 com/sun/java/help/
-rw----     1.0 fat        0 b-        0 stor 22-Jul-07 13:57 com/sun/java/help/impl/
-rw----     2.0 fat      191 bl      161 defN 04-Jan-30 13:06 com/sun/java/help/impl/ViewAwareComponent.class
-rw----     2.0 fat    14175 bl     7841 defN 04-Jan-30 13:06 com/sun/java/help/impl/JHSecondaryViewer.class
-rw----     2.0 fat     3574 bl     2219 defN 04-Jan-30 13:06 com/sun/java/help/impl/CustomKit$ObjectView1.class
-rw----     2.0 fat      943 bl      548 defN 04-Jan-30 13:06 com/sun/java/help/impl/CustomKit$CustomDocument.class
-rw----     2.0 fat     1009 bl      540 defN 04-Jan-30 13:06 com/sun/java/help/impl/JHSecondaryViewer$1.class
12 files, 19960 bytes uncompressed, 11382 bytes compressed:  43.0%
```
```

**Comment by backwaterred** [comment]
> Thanks for running the additional tests, really appreciated.
> As I said before, I think your changes are fine and I'll approve them.

@simonis Thanks for your review! I appreciate having an extra set of eyes on the changes as well.

> Do you know if the native zlib on your system contains some extra changes or enhancements compared to the upstream version? And by the way, what Linux distro did you observe this issue?

Yes :smirk: this was discovered on an IBM zLinux machine with a hardware accelerated zlib. It's special sauce galore! The OS is Ubuntu 20.04, and has been seen on RHEL 8.6 as well.

**Comment by simonis** [comment]
> > Do you know if the native zlib on your system contains some extra changes or enhancements compared to the upstream version? And by the way, what Linux distro did you observe this issue?
> 
> Yes this was discovered on an IBM zLinux machine with a hardware accelerated zlib. It's special sauce galore! The OS is Ubuntu 20.04, and has been seen on RHEL 8.6 as well.

Thanks for the additional information. You should have said that right from the beginning :)

Interesting to see how the hardware acceleration seems to trade speed for compression ratio (the newly compressed files are all slightly bigger) in the same way the other, purely software based zlib enhancements are doing this (see for example https://github.com/simonis/zlib-bench/blob/master/Results.md).

You should also be aware that this difference in behavior can impact other code, both in the JDK core libraries as well as in user code. [JDK-8253952: Refine ZipOutputStream.putNextEntry() to recalculate ZipEntry's compressed size](https://bugs.openjdk.org/browse/JDK-8253952) has a detailed explanation of why this problem occurs along with a list of some internal classes which have been fixed and some external libraries which are affected.

Ideally, you should downport [JDK-8253952](https://bugs.openjdk.org/browse/JDK-8253952) but unfortunatley that can't be done because it changes the public API specification and has an associated CSR. Maybe it will be acceptable to only downport the code fix part of [JDK-8253952](https://bugs.openjdk.org/browse/JDK-8253952)?

**Comment by RealCLanger** [comment]
> /integrate

Hi @backwaterred, in JDK-Updates projects you must not issue /integrate only when a PR is ready. You also need to get maintainer approval by putting the jdk11u-fix-request label in the JBS issue, along with some comment why you're requesting the backport, its testing etc., and waiting for the approval label. This is also true for net new items that aren't a downport of some existing fix as in your case. So, please add the JBS ceremony. Thx.

**Comment by backwaterred** [comment]
Oh, of course! I was thinking of that as a 'backport thing', but I should have known that it was a wider requirement. Thanks for the head's up. I will add the 'JBS ceremony' :-)

**Comment by backwaterred** [comment]
> Thanks for the additional information. You should have said that right from the beginning :)

Haha. Maybe I should have. My understanding of the zLinux system is growing, so this difference is not one I knew right from the beginning.

> Ideally, you should downport [JDK-8253952](https://bugs.openjdk.org/browse/JDK-8253952) which fixes the root of the problem and not just a single affected caller like your current fix. But unfortunately, that can't be done straight away because it changes the public API specification and has an associated CSR.

I agree with this assessment. If there is a strong preference to go with the other change minus the API changing code I would be open to that as well.

**Comment by RealCLanger** [comment]
> Oh, of course! I was thinking of that as a 'backport thing', but I should have known that it was a wider requirement. Thanks for the head's up. I will add the 'JBS ceremony' :-)

Great. I approved it now and will also sponsor.

/sponsor

**Pull request closed without merging**
