### PR TITLE
8218471: generate-unsafe-access-tests.sh does not correctly invoke build.tools.spp.Spp

### PR DESCRIPTION
**Pull request by zhengxiaolinX**
The `generate-unsafe-access-tests.sh` script doesn't work on JDK11 and the fix is in JDK13. I am working around the changes belonging to [JDK-8207146](https://bugs.openjdk.org/browse/JDK-8207146), please see discussions in [JDK-8292443](https://bugs.openjdk.org/browse/JDK-8292443).

Thanks,
Xiaolin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8218471](https://bugs.openjdk.org/browse/JDK-8218471): generate-unsafe-access-tests.sh does not correctly invoke build.tools.spp.Spp (**Bug** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1852/head:pull/1852` \
`$ git checkout pull/1852`

Update a local copy of the PR: \
`$ git checkout pull/1852` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1852/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1852`

View PR using the GUI difftool: \
`$ git pr show -t 1852`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1852.diff">https://git.openjdk.org/jdk11u-dev/pull/1852.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1852#issuecomment-1524704351)

### CODE REVIEW

**Comment by GoeLin** [comment]
Please enable Pre-submit testing. 
If you merge head the tests are restarted.
Pleas get a review and follow the instructions in the manual!!!
Only label if the change is ready to be integrated.
I remove the labels, add them again once the changes are ready.

**Comment by zhengxiaolinX** [comment]
> Please enable Pre-submit testing. If you merge head the tests are restarted. Pleas get a review and follow the instructions in the manual!!! Only label if the change is ready to be integrated. I remove the labels, add them again once the changes are ready.

Thank you. I see  :-)

**Comment by phohensee** [comment]
Why not backport [JDK-8218461](https://bugs.openjdk.org/browse/JDK-8218461) first?

**Comment by zhengxiaolinX** [comment]
> Why not backport [JDK-8218461](https://bugs.openjdk.org/browse/JDK-8218461) first?

Thank you for the advice, Paul. Though it looks like [JDK-8218461](https://bugs.openjdk.org/browse/JDK-8218461) depends on [JDK-8210031: implementation for JVM Constants API](https://bugs.openjdk.org/browse/JDK-8210031) first, so it seems to me a little unrelated? If you would like to mention [JDK-8218460](https://bugs.openjdk.org/browse/JDK-8218460) instead of JDK-8218461, I guess, then that one has been backported to 11u already in [this commit](https://github.com/openjdk/jdk11u-dev/commit/915ac570b54aa820adf474ab5046e17007601f4e) in this March, containing two JBS issues inside.

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by zhengxiaolinX** [comment]
Thank you a lot for reviewing and helping update the JBS issues! :-) @phohensee

**Comment by zhengxiaolinX** [comment]
I have received the `jdk11u-fix-yes` approval.

/integrate

**Pull request closed without merging**
