### PR TITLE
8214004: Missing space between compiler thread name and task info in hs_err

### PR DESCRIPTION
**Pull request by yukikimmura**
I'd like to backport JDK-8214004. 
The original patch does not applies cleanly because JDK-8163511 was applied first in 11u. 

The change only reflects JDK-8163511 on the following line, and there is no risk.
I tested tier1 with rhel and windows x86_64, and no errors found.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8214004](https://bugs.openjdk.java.net/browse/JDK-8214004): Missing space between compiler thread name and task info in hs_err ⚠️ Issue is not open.

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/831/head:pull/831` \
`$ git checkout pull/831`

Update a local copy of the PR: \
`$ git checkout pull/831` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/831/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 831`

View PR using the GUI difftool: \
`$ git pr show -t 831`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/831.diff">https://git.openjdk.java.net/jdk11u-dev/pull/831.diff</a>

</details>

### CODE REVIEW

**Comment by yukikimmura** [comment]
Could anyone review the fix please?

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by yukikimmura** [comment]
Thank you for your review, phohensee.

/integrate
I would appliciate it if someone could sponsor the fix.

**Pull request closed without merging**
