### PR TITLE
JDK-8302000: [11u] A subtle race condition during jdk11u build

### PR DESCRIPTION
**Pull request by kusrinivasan**
Hi,

**This is to fix issue caused by:**
JDK-8257679: Improved unix compatibility layer in Windows build (winenv)
Please refer to JDK-8302000 for the evaluation of how the above causes the race condition.

The changes below are in an effort to make the existing jdk11u source more robust and closer to the upstream code.

**Initial Spp.java changes:**
JDK-8215445: Enable building for Windows in WSL
https://github.com/openjdk/jdk/compare/88b95f05706..46eb26b692a

_Note: Too large to be back-ported, only changes for Spp.java associated build logic 
changes needs to be back-ported manually._

**Required additional make logic adjustments required for Spp.java changes:**
JDK-8218460: https://github.com/openjdk/jdk/compare/1fcbd0cd0dc..f380787a41e

_Note: patch does not apply cleanly and all the changes have to be applied manually._

**Optional, Spp.java Improvements:**
JDK-8223347: Integration of Vector API (Incubator)
https://github.com/openjdk/jdk/compare/386e7e8b733..0c99b192588

_Note: Clearly the entire commit is totally inapplicable to jdk11u, since it is an Incubator feature,
however small improvement to Spp.java can be back-ported manually, in an effort to bring jdk11u 
sources closer to upstream_

If the above solutions  are not acceptable, then I could add parenthesis to the ExecutWithLog call-sites, however
this will further diverge the jdk11u code base from upstream.

If none of the above solutions are acceptable then I recommend the jdk11u maintainers assign JDK-8302000 to 
the author of JDK-8257679 and have them remove the ExecuteWithLog additions.

I personally have tested the fix using tier1 and tier2 regression testing on both Windows and Linux.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8302000](https://bugs.openjdk.org/browse/JDK-8302000): [11u] A subtle race condition during jdk11u build
 * [JDK-8218460](https://bugs.openjdk.org/browse/JDK-8218460): Test generation scripts do not invoke stream preprocessor correctly ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1774/head:pull/1774` \
`$ git checkout pull/1774`

Update a local copy of the PR: \
`$ git checkout pull/1774` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1774/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1774`

View PR using the GUI difftool: \
`$ git pr show -t 1774`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1774.diff">https://git.openjdk.org/jdk11u-dev/pull/1774.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
Hi @kusrinivasan,
thanks for contributing this fix. I'm wondering whether you could add the patch for JDK-8218460 completely in all its details and we could then also mark this PR as backporting JDK-8218460?

**Comment by kusrinivasan** [comment]
Hi @RealCLanger yes it is possible to apply JDK-8218460, I am assuming once that is added you want me to add all the other changes to Spp.java on top of the back-port of JDK-8218460 ?

**Comment by RealCLanger** [comment]
> Hi @RealCLanger yes it is possible to apply JDK-8218460, I am assuming once that is added you want me to add all the other changes to Spp.java on top of the back-port of JDK-8218460 ?

No, not necessarily. I just want to see JDK-8218460 backported as a whole, if we anyway take the gist of it. Or are there any follow ups that must be taken then? Not sure whether [JDK-8218461](https://bugs.openjdk.org/browse/JDK-8218461) and [JDK-8218471](https://bugs.openjdk.org/browse/JDK-8218471) are nice-to-haves or they get mandatory after your fix.

**Comment by kusrinivasan** [comment]
@RealCLanger if we decide to back-port JDK-8218460, then we definitely need fixes to Spp.java  from JDK-8215445!,
without which the back-port will fail.

Also If we decide to go  the back-port route, does it mean this PR and JBS is closed and file a new back-port issue 
for JDK-8218460 ?

**Comment by kusrinivasan** [comment]
Hi @RealCLanger et. al., 
Perhaps I was not clear with my introduction, let me try to clarify in detail:

1. JDK-8215445 is mandatory, with the following that are absolutely required:
a. make/jdk/src/classes/build/tools/spp/Spp.java
b. make/gensrc/GensrcBuffer.gmk
c. make/gensrc/GensrcCharsetCoder.gmk
d. make/gensrc/GensrcVarHandles.gmk

2. JDK-8218460 is also mandatory once JDK-8215445 is applied, but as I said earlier JDK-8218460 can be applied in its entirety.

3. Fixes for Spp.java from JDK-8223347 is optional.
4.
So please let me know how you want to proceed.

**Comment by RealCLanger** [comment]
> Hi @RealCLanger et. al., Perhaps I was not clear with my introduction, let me try to clarify in detail:
> 
> 1. **JDK-8215445 is mandatory, with the following that are absolutely required**:
>    a. make/jdk/src/classes/build/tools/spp/Spp.java
>    b. make/gensrc/GensrcBuffer.gmk
>    c. make/gensrc/GensrcCharsetCoder.gmk
>    d. make/gensrc/GensrcVarHandles.gmk
> 2. **JDK-8218460 is also mandatory** once JDK-8215445 is applied, but as I said earlier JDK-8218460 can be applied in its entirety.
> 3. Fixes for Spp.java from JDK-8223347 is optional.
> 
> So please let me know how you want to proceed.

That sounds good. So my request for this PR would be to add everything from JDK-8218460 and mark this PR as a backport of it with the `/issue JDK-8218460` command.

**Comment by RealCLanger** [comment]
This looks good to me now. I'll run it through our nightlies and let you know the results tomorrow. Please flag this PR as resolving JDK-8218460. Thanks.

**Comment by kusrinivasan** [comment]
> This looks good to me now. I'll run it through our nightlies and let you know the results tomorrow. Please flag this PR as resolving JDK-8218460. Thanks.

Christoph, one thing to note, the changes in JDK-8218460 don't really affect tier1 and tier2 testing. These are scripts likely developed by JPG (Java Platform Group) SQE to help produce the actual tests from a template, if and when the underlying feature changes. This is the reason why it was done as separate fix in the upstream as it was never caught when JDK-8215445 was introduced.

**Comment by RealCLanger** [comment]
> > This looks good to me now. I'll run it through our nightlies and let you know the results tomorrow. Please flag this PR as resolving JDK-8218460. Thanks.
> 
> Christoph, one thing to note, the changes in JDK-8218460 don't really affect tier1 and tier2 testing. These are scripts likely developed by JPG (Java Platform Group) SQE to help produce the actual tests from a template, if and when the underlying feature changes. This is the reason why it was done as separate fix in the upstream as it was never caught when JDK-8215445 was introduced.

OK, this explains why the wrong path to Spp.java in certain scripts did not cause problems that were spotted immediately.

**Review by RealCLanger — APPROVED** [review]
SAP nightlies passed.

**Pull request closed without merging**
