### PR TITLE
8300742: jstat's CGCT is 5 percent higher than the pause time in -Xlog:gc.

### PR DESCRIPTION
**Pull request by yukikimmura**
Could anyone review the fix please?
I explain the fix below. 
I tested hotspot/gc with rhel and windows x86_64, and no errors found.
I added a test to confirm the fix. There is no risk.

GC time in the gclog is calculated in the GCTraceTime constructor,
and jstat's CGCT is calculated in the TraceCollectorStats constructor.

In my investigation, the cost of the GCTraceTime constructor is larger than that of TraceCollectorStats.
CGCT includes the executing time of GCTraceTime.
Since CGCT is the accmulated time, as the number of CMSGC increases, the difference with the gclog increases.

Only CMSGC, execution order of GCTraceTime and TraceCollectorStats is different from other GCs.

concurrentMarkSweepGeneration.cpp
  TraceCollectorStats
  GCTraceTime

g1CollectedHeap.cpp / vm_operations_g1.cpp / psParallelCompact.cpp / genCollectedHeap.cpp
  GCTraceTime
  TraceCollectorStats

I modified the order of two constructors in concurrentMarkSweepGeneration.cpp.
The following is the result. The difference between two timers bcomes small.
The difference of time a GC should be small, because CGCT is the accmulated time.
The order of two timers should be same for all GCs.
Naturally, the GC time in the gclog will increase slightly which is several micro secs in Xmx512m, 2.5GHz CPU.

Windows 2016 / x64

befor modification
  jstat CGT 6011
  jstat CGCT 8593.0 ms
  gclog invocations 6011
  gclog time 8136.4 ms

  jstat/loggc=1.056  (the difference is 5.6%)

after modification
  jstat CGT 6104
  jstat CGCT 7503.0 ms
  gclog invocations 6104
  gclog time 7603.5 ms

  jstat/loggc=0.987 (the difference is 1.3%)

RHEL 7 / x64

befor modification
  jstat CGT 4576
  jstat CGCT 5010.0ms
  gclog invocations 4576
  gclog time 4871.4 ms

  jstat/loggc=1.028  (the difference is 2.8%)

after modification
  jstat CG 4297
  jstat CGCT 3408.0ms
  gclog invocations 4297
  gclog time 3416.95 ms

  jstat/loggc=0.997  (the difference is 0.3%)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300742](https://bugs.openjdk.org/browse/JDK-8300742): jstat's CGCT is 5 percent higher than the pause time in -Xlog:gc.

### Reviewers
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**) ⚠️ Review applies to [c1f78569](https://git.openjdk.org/jdk11u-dev/pull/1676/files/c1f78569d43238aaf4513906d400c08df841756b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1676/head:pull/1676` \
`$ git checkout pull/1676`

Update a local copy of the PR: \
`$ git checkout pull/1676` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1676/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1676`

View PR using the GUI difftool: \
`$ git pr show -t 1676`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1676.diff">https://git.openjdk.org/jdk11u-dev/pull/1676.diff</a>

</details>

### CODE REVIEW

**Review by reinrich — COMMENTED** [review]
Hi Kimura,

cms changes seem ok.
I'm not sure though if the test is necessary (and worth the CO2). What are the runtimes you are seeing?

Thanks, Richard.

**Comment by yukikimmura** [comment]
Hello Richard, 
Thank you for your review.

The test is to make sure the difference of elapsed time between the two timers. It might be a flaky test.
I think it should not be included in the jtreg test set, once the effect of the fix has been confirmed.
I removed the test from the commit.

Thanks,
Kimura Yukihiro

**Review by reinrich — APPROVED** [review]
Looks good to me.

Thanks, Richard.

**Comment by reinrich** [comment]
Hi @yukikimmura ,
I think you can now add the `jdk11u-fix-request` label to the JBS item https://bugs.openjdk.org/browse/JDK-8300742.

**Comment by yukikimmura** [comment]
Hello Richard,
Thank you for your advice. 
I added the jdk11u-fix-request label to the JBS.

Thanks,
Kimura Yukihiro

**Comment by reinrich** [comment]
You're welcome. This would be a general guide: https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix
Its only partially applicable to your fix though since it isn't a backport.

**Pull request closed without merging**
