### PR TITLE
8202142: jfr/event/io/TestInstrumentation is unstable

### PR DESCRIPTION
**Pull request by dongbohe**
Fix jdk/jfr/event/io/TestInstrumentation.java and remove it from ProblemList.txt.

There are only context and copyright conflicts, which have been resolved manually

Test: jdk/jfr/event/io/TestInstrumentation.java passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8202142](https://bugs.openjdk.java.net/browse/JDK-8202142): jfr/event/io/TestInstrumentation is unstable

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)
 * [Hamlin Li](https://openjdk.java.net/census#mli) (@Hamlin-Li - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/653/head:pull/653` \
`$ git checkout pull/653`

Update a local copy of the PR: \
`$ git checkout pull/653` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/653/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 653`

View PR using the GUI difftool: \
`$ git pr show -t 653`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/653.diff">https://git.openjdk.java.net/jdk11u-dev/pull/653.diff</a>

</details>

### CODE REVIEW

**Comment by dongbohe** [comment]
ping?

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by dongbohe** [comment]
Thank you for your review, Paul.

**Pull request closed without merging**
