### PR TITLE
8247589: Implementation of Alpine Linux/x64 Port

### PR DESCRIPTION
**Pull request by voitylov**
JDK-8247589 is in the main issue in the third batch of a chain of backports for Alpine support to 11u as discussed in the mailing list. For the full set of anticipated changes please refer to the jdk-updates mailing list [1].

Original changeset does not apply cleanly because of:

8244224: Implementation of JEP 381: Remove the Solaris and SPARC Ports,
8215445: Enable building for Windows in WSL
8257913: Add more known library locations to simplify Linux cross-compilation
8244592: Start supporting SOURCE_DATE_EPOCH
8244752: Enable Linux support for multiple huge page sizes -XX:LargePageSizeInBytes

Testing: JCK + JTreg on Windows, Linux, Solaris, Mac without regressions.

[1] https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2022-February/012271.html

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8247589](https://bugs.openjdk.java.net/browse/JDK-8247589): Implementation of Alpine Linux/x64 Port

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to 1dd4c57c677dcdbd11cfb54679ec954a7e3facb7
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/910/head:pull/910` \
`$ git checkout pull/910`

Update a local copy of the PR: \
`$ git checkout pull/910` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/910/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 910`

View PR using the GUI difftool: \
`$ git pr show -t 910`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/910.diff">https://git.openjdk.java.net/jdk11u-dev/pull/910.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
@voitylov Could you please resolve conflicts? Thanks!

**Comment by voitylov** [comment]
@jerboaa merge conflict with 8246494 is now resolved.

**Review by jerboaa — APPROVED** [review]
This looks OK to me.

**Comment by RealCLanger** [comment]
I'll run this patch through SAP's testing tonight. I'm going to approve it when we don't see regressions.

**Comment by voitylov** [comment]
Thanks Christoph!

**Comment by MBaesken** [comment]
Hi, we noticed a small issue in [test/jdk/tools/launcher/Test7029048.java](https://github.com/openjdk/jdk11u-dev/pull/910/files#diff-a2a1433f01e8291062945a7383286214ee41a0e8deecab03bd37bc0bebe3da14) .
test/jdk/tools/launcher/Test7029048.java  now has  private static void printSkipMessage(String description)  twice ,
this leads to the error

test/jdk/tools/launcher/Test7029048.java:215: error: method printSkipMessage(String) is already defined in class Test7029048
    private static void printSkipMessage(String description) {
                        ^

**Comment by voitylov** [comment]
@MBaesken thanks for spotting this. GHA gives "E: Version '9.4.0-1ubuntu1~20.04' for 'gcc-9' was not found" which is unrelated to this change.

**Comment by RealCLanger** [comment]
> @MBaesken thanks for spotting this. GHA gives "E: Version '9.4.0-1ubuntu1~20.04' for 'gcc-9' was not found" which is unrelated to this change.

Yes, about to fix this with https://github.com/openjdk/jdk11u/pull/36 [JDK-8283778](https://bugs.openjdk.java.net/browse/JDK-8283778)

**Review by RealCLanger — APPROVED** [review]

**Comment by voitylov** [comment]
@MBaesken I'd like to play it safe and kindly ask you to rerun the SAP nightly testing, if possible.

**Comment by voitylov** [comment]
@RealCLanger I see my ask to Matthias crossed with your review. Can I assume SAP is happy with the updated version?

**Comment by RealCLanger** [comment]
> @RealCLanger I see my ask to Matthias crossed with your review. Can I assume SAP is happy with the updated version?

Yes, the patch is running in our nightlies for days now - no further issues. 😄

**Pull request closed without merging**
