### PR TITLE
8268916: Tests for AffirmTrust roots

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all, 

This is a backport for [8c1bb2b28066ee32bef22110df06318d938c7d8b](https://github.com/openjdk/jdk/commit/8c1bb2b28066ee32bef22110df06318d938c7d8b).

Original patch does not apply cleanly to 11u because of how the switch statement is structured. Notably, I had to add return statements to the added cases. 

Testing: affected test, tier 1.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8268916](https://bugs.openjdk.org/browse/JDK-8268916) needs maintainer approval

### Issue
 * [JDK-8268916](https://bugs.openjdk.org/browse/JDK-8268916): Tests for AffirmTrust roots (**Enhancement** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [25e5c214](https://git.openjdk.org/jdk11u-dev/pull/2247/files/25e5c2142d7d9a3de524e24b2fd40a11ef999897)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2247/head:pull/2247` \
`$ git checkout pull/2247`

Update a local copy of the PR: \
`$ git checkout pull/2247` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2247/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2247`

View PR using the GUI difftool: \
`$ git pr show -t 2247`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2247.diff">https://git.openjdk.org/jdk11u-dev/pull/2247.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2247#issuecomment-1787311415)

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
Missing a blank line between lines 534 and 535. Otherwise lgtm.

**Comment by jerboaa** [comment]
@SoniaZaldana There are still some whitespace issues. See https://github.com/openjdk/jdk11u-dev/pull/2247/checks?check_run_id=18407757489

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
Looks like you need to remerge.

**Review by jerboaa — APPROVED** [review]
LGTM

**Comment by jerboaa** [comment]
@SoniaZaldana Please request approval for this one. Thanks!

**Pull request closed without merging**
