### PR TITLE
8250902: Implement MD5 Intrinsics on x86

### PR DESCRIPTION
**Pull request by phohensee**
I'd like to backport MD5 intrinsification because it improves security related performance. I understand that it may be a bridge too far for 11u. In that case we (Amazon) intend to backport it to our internal 11u distro followed by Corretto.

Testing: tier1, including the new and existing sha tests.

Ludovic Henry did an 11u backport in 2020 (see [JDK-8251319](https://bugs.openjdk.java.net/browse/JDK-8251319)), but I can't find a review request on the jdk-updates-dev list. My backport is essentially identical to his, and is based on the [backport from jdk15u](https://github.com/openjdk/jdk15u-dev/pull/163). It was not clean.

1. Copyright date conflicts.
2. Context differences.
3. Changing SHAOptionsBase to DigestOptionsBase.
4. Rewriting Assembler::roll() to use emit_int8() because emit_int16() and emit_24() don't exist in 11.

This backport would be immediately followed by a backport of [JDK-8251260](https://bugs.openjdk.java.net/browse/JDK-8251260) to fix two tests. After that, I'd like to backport the aarch64 version in [JDK-8251216](https://bugs.openjdk.java.net/browse/JDK-8251216).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8250902](https://bugs.openjdk.java.net/browse/JDK-8250902): Implement MD5 Intrinsics on x86

### Reviewers
 * [Bernhard Urban-Forster](https://openjdk.java.net/census#burban) (@lewurm - no project role) ⚠️ Review applies to 9fd44b55633b20c7586c10326d105c418a915b38
 * [Ludovic Henry](https://openjdk.java.net/census#luhenry) (@luhenry - no project role) ⚠️ Review applies to 9fd44b55633b20c7586c10326d105c418a915b38
 * [Volker Simonis](https://openjdk.java.net/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/806/head:pull/806` \
`$ git checkout pull/806`

Update a local copy of the PR: \
`$ git checkout pull/806` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/806/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 806`

View PR using the GUI difftool: \
`$ git pr show -t 806`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/806.diff">https://git.openjdk.java.net/jdk11u-dev/pull/806.diff</a>

</details>

### CODE REVIEW

**Comment by lewurm** [comment]
There was a proposal to backport it to 11u, but to the wrong mailing list: http://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2020-August/039412.html

I think it has baked enough on tip now 🙂

**Review by lewurm — APPROVED** [review]
Looks good to me, but I'm not an official reviewer.

**Review by luhenry — APPROVED** [review]

**Comment by phohensee** [comment]
You're the original author, which is as "official" as it gets. Thanks for the review!

**Comment by phohensee** [comment]
Thanks for the review, Bernhard!

**Review by simonis — CHANGES_REQUESTED** [review]
Hi Paul,
thanks for doing this downport.
The changes look good except for one comment in `CheckGraalIntrinsics.java`
Best regards,
Volker

**Comment by phohensee** [comment]
Fixed, see incremental webrev. Thanks for the review!

**Review by simonis — APPROVED** [review]
Thanks, looks good now.

**Comment by phohensee** [comment]
Thanks, Volker. Tagged.

**Comment by phohensee** [comment]
JBS ssue was tagged 10 days ago. May I have a decision please? March 1st is 11.0.15 rampdown and quite close.

**Comment by phohensee** [comment]
Backport rejected.

**Pull request closed without merging**
