### PR TITLE
8278951: containers/cgroup/PlainRead.java fails on Ubuntu 21.10

### PR DESCRIPTION
**Pull request by jmtd**
Part of cgroups v2 backport works. Conflict on copyright line. local testing: v1 system passed; v2 system with no user delegated cpu controller failed, this is fixed by later bug 8250984. I am about to verify v2 with delegated cpu controller locally and will update this when I have the result.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8278951](https://bugs.openjdk.java.net/browse/JDK-8278951): containers/cgroup/PlainRead.java fails on Ubuntu 21.10

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/984/head:pull/984` \
`$ git checkout pull/984`

Update a local copy of the PR: \
`$ git checkout pull/984` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/984/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 984`

View PR using the GUI difftool: \
`$ git pr show -t 984`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/984.diff">https://git.openjdk.java.net/jdk11u-dev/pull/984.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

Aside: JDK-8250984 is already in JDK 11u, so that backport cannot fix anything at this point. Any fixes would need to be done as a 11u-specific bug.

**Comment by jmtd** [comment]
Update on testing: test passes after I manually configure cpu cgroup delegation to user process heirarchy on my host; it was not enabled by default.

**Pull request closed without merging**
