### PR TITLE
8239785: Cgroups: Incorrect detection logic on old systems in hotspot

### PR DESCRIPTION
**Pull request by jmtd**
This is a backport of 8239785 for jdk11u. It depends upon
pr/865: 8253714 (hopefully the bots will figure this out automatically)

It's not clean, but the only conflict was the copyright line in the
comment header for src/hotspot/share/prims/whitebox.hpp.

I tried these tests, and they pass:
```
test/hotspot/jtreg/applications/ctw/modules/java_compiler.java
test/hotspot/jtreg/compiler/c2/Test8004741.java
test/hotspot/jtreg/containers/cgroup/CgroupSubsystemFactory.java
```
Awaiting tier tests via GA.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Integration blocker
&nbsp;⚠️ Dependency #865 must be integrated first

### Issue
 * [JDK-8239785](https://bugs.openjdk.java.net/browse/JDK-8239785): Cgroups: Incorrect detection logic on old systems in hotspot

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/881/head:pull/881` \
`$ git checkout pull/881`

Update a local copy of the PR: \
`$ git checkout pull/881` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/881/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 881`

View PR using the GUI difftool: \
`$ git pr show -t 881`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/881.diff">https://git.openjdk.java.net/jdk11u-dev/pull/881.diff</a>

</details>

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8239785](https://bugs.openjdk.java.net/browse/JDK-8239785): Cgroups: Incorrect detection logic on old systems in hotspot

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/881/head:pull/881` \
`$ git checkout pull/881`

Update a local copy of the PR: \
`$ git checkout pull/881` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/881/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 881`

View PR using the GUI difftool: \
`$ git pr show -t 881`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/881.diff">https://git.openjdk.java.net/jdk11u-dev/pull/881.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
Did you run container tests on a cgroups v1 and cgroups v2 system?

**Comment by jmtd** [comment]
> Did you run container tests on a cgroups v1 and cgroups v2 system?

Just a v2 one so far. I'm looking at setting up a v1 environment now.

**Comment by jerboaa** [comment]
OK, thanks!

**Comment by jmtd** [comment]
I've now run the following on a v1/hybrid setup as well as a pure v2. all pass in both cases:

```
test/hotspot/jtreg/containers/cgroup/CgroupSubsystemFactory.java
test/hotspot/jtreg/applications/ctw/modules/java_compiler.java
test/hotspot/jtreg/compiler/c2/Test8004741.java
```

If there's any other specific tests worth running on v1/hybrid please let me know (or if you think I should do the whole tier1... not sure which of v1 or v2 GitHub Actions is testing. I'll try to check)

**Comment by jmtd** [comment]
`test/hotspot/jtreg/containers/cgroup/PlainRead.java` is failing (for me) on pure v2. Investigating

**Review by jerboaa — CHANGES_REQUESTED** [review]
This looks good to me, just fix the copyright update (the old value `2017` should change to `2020`) which was also done in head and this is good to go.

See: https://hg.openjdk.java.net/jdk/jdk/rev/d527da8f8f9b#l4.6

**Comment by jerboaa** [comment]
> `test/hotspot/jtreg/containers/cgroup/PlainRead.java` is failing (for me) on pure v2. Investigating

That's likely https://bugs.openjdk.java.net/browse/JDK-8278951

**Comment by jmtd** [comment]
> That's likely https://bugs.openjdk.java.net/browse/JDK-8278951

It looks likely (although backporting that does not resolve the failure for me). I've traced the failure right back to pr/840, so I'll leave further investigation there.

**Comment by jmtd** [comment]
Closing since the bug is still marked dependendent on an abandoned PR.

**Pull request closed without merging**
