### PR TITLE
8339637: (tz) Update Timezone Data to 2024b

### PR DESCRIPTION
**Pull request by RadekCap**
Backport of JDK-8339637 from 17u-dev.

Clean backport. Passed tier1 tests. Passed gtests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8339637](https://bugs.openjdk.org/browse/JDK-8339637) needs maintainer approval
- [x] Change requires CSR request [JDK-8342331](https://bugs.openjdk.org/browse/JDK-8342331) to be approved

### Issues
 * [JDK-8339637](https://bugs.openjdk.org/browse/JDK-8339637): (tz) Update Timezone Data to 2024b (**Enhancement** - P3 - Approved)
 * [JDK-8342331](https://bugs.openjdk.org/browse/JDK-8342331): (tz) Update Timezone Data to 2024b (**CSR**)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2971/head:pull/2971` \
`$ git checkout pull/2971`

Update a local copy of the PR: \
`$ git checkout pull/2971` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2971/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2971`

View PR using the GUI difftool: \
`$ git pr show -t 2971`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2971.diff">https://git.openjdk.org/jdk11u-dev/pull/2971.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2971#issuecomment-2501223946)
</details>

### CODE REVIEW

**Comment by RadekCap** [comment]
/approval clean back port of (tz) Update Timezone Data to 2024b

**Comment by RadekCap** [comment]
/approval request clean backport of (tz) Update Timezone Data to 2024b

**Review by gnu-andrew — COMMENTED** [review]
Confirmed clean.

Do the timezone tests (`java/time`, `java/text/Format`, `java/util/TimeZone`, `sun/util/calendar` and `sun/util/resources`) pass?  The first two are not covered by tier 1 testing.

**Comment by RadekCap** [comment]
I run 
`make run-test TEST="jtreg:java/text/Format java/util/TimeZone sun/util/calendar sun/util/resources"`

with these results:

`````
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/java/text/Format                      90    90     0     0   
   jtreg:test/jdk/java/util/TimeZone                    25    25     0     0   
   jtreg:test/jdk/sun/util/calendar                      5     5     0     0   
   jtreg:test/jdk/sun/util/resources                    21    21     0     0   
==============================
TEST SUCCESS

Finished building target 'run-test' in configuration 'linux-x86_64-normal-server-release'

`````

**Review by gnu-andrew — APPROVED** [review]
Thanks. Looks good to me.

**Pull request closed without merging**
