### PR TITLE
8307811: [TEST] compilation of TimeoutInErrorHandlingTest fails after backport of JDK-8303861

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi!

This one fixes compilation of 

runtime/ErrorHandling/ThreadsListHandleInErrorHandlingTest.java

broken by backport of JDK-8303861. The problem is about backported delta refers to ERROR_LOG_TIMEOUT member that was introduced by different changeset and so was not backported and it stayed covered because the test is selected only for debug VM build

Verification/regression (amd64/20.04LTS): 
```
alex@alex-VirtualBox:~/jdk11u-dev$ /opt/jtreg/bin/jtreg -v -jdk:./build/linux-x86_64-normal-server-fastdebug/images/jdk test/hotspot/jtreg/runtime/ErrorHandling
runner starting test: runtime/ErrorHandling/BadNativeStackInErrorHandlingTest.java
runner finished test: runtime/ErrorHandling/BadNativeStackInErrorHandlingTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/CreateCoredumpOnCrash.java
runner finished test: runtime/ErrorHandling/CreateCoredumpOnCrash.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/ErrorFileRedirectTest.java
runner finished test: runtime/ErrorHandling/ErrorFileRedirectTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/ErrorHandler.java
runner finished test: runtime/ErrorHandling/ErrorHandler.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/NestedThreadsListHandleInErrorHandlingTest.java
runner finished test: runtime/ErrorHandling/NestedThreadsListHandleInErrorHandlingTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/ProblematicFrameTest.java
runner finished test: runtime/ErrorHandling/ProblematicFrameTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/SafeFetchInErrorHandlingTest.java
runner finished test: runtime/ErrorHandling/SafeFetchInErrorHandlingTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/SecondaryErrorTest.java
runner finished test: runtime/ErrorHandling/SecondaryErrorTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/ShowRegistersOnAssertTest.java
runner finished test: runtime/ErrorHandling/ShowRegistersOnAssertTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestCrashOnOutOfMemoryError.java
runner finished test: runtime/ErrorHandling/TestCrashOnOutOfMemoryError.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestExitOnOutOfMemoryError.java
runner finished test: runtime/ErrorHandling/TestExitOnOutOfMemoryError.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestHeapDumpOnOutOfMemoryError.java
runner finished test: runtime/ErrorHandling/TestHeapDumpOnOutOfMemoryError.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestHeapDumpOnOutOfMemoryErrorInMetaspace.java
runner finished test: runtime/ErrorHandling/TestHeapDumpOnOutOfMemoryErrorInMetaspace.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestHeapDumpPath.java
runner finished test: runtime/ErrorHandling/TestHeapDumpPath.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestOnError.java
runner finished test: runtime/ErrorHandling/TestOnError.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TestOnOutOfMemoryError.java
runner finished test: runtime/ErrorHandling/TestOnOutOfMemoryError.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/ThreadsListHandleInErrorHandlingTest.java
runner finished test: runtime/ErrorHandling/ThreadsListHandleInErrorHandlingTest.java
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TimeoutInErrorHandlingTest.java#default
runner finished test: runtime/ErrorHandling/TimeoutInErrorHandlingTest.java#default
Passed. Execution successful
runner starting test: runtime/ErrorHandling/TimeoutInErrorHandlingTest.java#with-on-error
runner finished test: runtime/ErrorHandling/TimeoutInErrorHandlingTest.java#with-on-error
Passed. Execution successful
runner starting test: runtime/ErrorHandling/VeryEarlyAssertTest.java
runner finished test: runtime/ErrorHandling/VeryEarlyAssertTest.java
Passed. Execution successful
Test results: passed: 20
Report written to /home/alex/jdk11u-dev/JTreport/html/report.html
Results written to /home/alex/jdk11u-dev/JTwork
alex@alex-VirtualBox:~/jdk11u-dev$
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307811](https://bugs.openjdk.org/browse/JDK-8307811): [TEST] compilation of TimeoutInErrorHandlingTest fails after backport of JDK-8303861

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1882/head:pull/1882` \
`$ git checkout pull/1882`

Update a local copy of the PR: \
`$ git checkout pull/1882` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1882/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1882`

View PR using the GUI difftool: \
`$ git pr show -t 1882`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1882.diff">https://git.openjdk.org/jdk11u-dev/pull/1882.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1882#issuecomment-1542063192)

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
Is the different changeset worth backporting on its own, rather than doing this patch?

**Review by RealCLanger — APPROVED** [review]

**Comment by GoeLin** [comment]
Hi, why are the Pre-submit tests failing?

**Comment by apavlyutkin** [comment]
I'll check it but for sure this does not relate to fixed test because it's disabled for Windows
```
/*
 * @test id=default
 * @bug 8166944
 * @summary Hanging Error Reporting steps may lead to torn error logs
 * @modules java.base/jdk.internal.misc
 * @library /test/lib
 * @requires (vm.debug == true) & (os.family != "windows")
 * @author Thomas Stuefe (SAP)
 */
/*
 * @test id=with-on-error
 * @bug 8303861
 * @summary Error handling step timeouts should never be blocked by OnError etc.
 * @modules java.base/jdk.internal.misc
 * @library /test/lib
 * @requires (vm.debug == true) & (os.family != "windows")
 * @run driver TimeoutInErrorHandlingTest with-on-error
 */
```

**Pull request closed without merging**
