### PR TITLE
8217730: Split up MakeBase.gmk

### PR DESCRIPTION
**Pull request by GoeLin**
This is a change only moving make code from MakeBase to new files.
The code basically remains unchanged.

There are four small differences in current 11 MakeBase to the version this
change was originally applied to. I moved these to Utils, see the extra change 
on top.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8217730](https://bugs.openjdk.org/browse/JDK-8217730): Split up MakeBase.gmk

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [f85a458e](https://git.openjdk.org/jdk11u-dev/pull/1695/files/f85a458e247f16fed17f0b2a53fe45bd4d0b3bcf)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1695/head:pull/1695` \
`$ git checkout pull/1695`

Update a local copy of the PR: \
`$ git checkout pull/1695` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1695/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1695`

View PR using the GUI difftool: \
`$ git pr show -t 1695`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1695.diff">https://git.openjdk.org/jdk11u-dev/pull/1695.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Pre-submit Windows build failures are infrastructure issues.

**Comment by GoeLin** [comment]
Pre-submit failure: source 1.2 -target 1.1 issue. Unrelated.
It's a pity these tests did not run. For this change touching the makefiles, making sure 
the Windows builds work would be nice. But the win x86_64 builds worked in SAPs nightlies,
I thinik this should be sufficient to continue.  Also, the changes do not touch platform
dependent make funcionality.

**Comment by GoeLin** [comment]
Thanks for the review! Also the tests passed after the fix for the jtreg compilation issue.

**Pull request closed without merging**
