### PR TITLE
8314495: Update to use jtreg 7.3.1

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this as announced in https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-March/030818.html

Clean backport from 17 except for test/lib-test/TEST.ROOT.
That file is not in 11. I added it for this change. I think it makes sense to have this in 11 as well.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8314495](https://bugs.openjdk.org/browse/JDK-8314495) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314495](https://bugs.openjdk.org/browse/JDK-8314495): Update to use jtreg 7.3.1 (**Enhancement** - P3 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to [f7d6f693](https://git.openjdk.org/jdk11u-dev/pull/2612/files/f7d6f693b14e4ab627ff060ff6fecf1d569d4ad8)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2612/head:pull/2612` \
`$ git checkout pull/2612`

Update a local copy of the PR: \
`$ git checkout pull/2612` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2612/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2612`

View PR using the GUI difftool: \
`$ git pr show -t 2612`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2612.diff">https://git.openjdk.org/jdk11u-dev/pull/2612.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2612#issuecomment-2007342146)

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
I don't think we should be adding lib-test here. It is a part of much larger [JDK-8211977](https://bugs.openjdk.org/browse/JDK-8211977). Otherwise looks good.

**Review by RealLucy — APPROVED** [review]
Looks good.
My approval is not intended to overrule the request by @shipilev

**Review by shipilev — APPROVED** [review]
Looks good! Let's do this.

**Comment by GoeLin** [comment]
GHA failure: StringRepeat.java: Could not reserve enough space for 2097152KB object heap. Unrelated.

**Pull request closed without merging**
