### PR TITLE
8288377: [REDO] DST not applying properly with zone id offset set with TZ env variable

### PR DESCRIPTION
**Pull request by Deigue**
Backport changes from JDK-8288377

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288377](https://bugs.openjdk.org/browse/JDK-8288377): [REDO] DST not applying properly with zone id offset set with TZ env variable

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1328/head:pull/1328` \
`$ git checkout pull/1328`

Update a local copy of the PR: \
`$ git checkout pull/1328` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1328/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1328`

View PR using the GUI difftool: \
`$ git pr show -t 1328`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1328.diff">https://git.openjdk.org/jdk11u-dev/pull/1328.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
@Deigue: I suggest you backport this fix to jdk19u and jdk17u first before attempting to go back to jdk11u. Please also enable GitHub Actions on your repository to have some validation results.

**Comment by Deigue** [comment]
Yes, I will prep the PR for jdk17 and jdk19 repos. After looking at the error on enabling Github Actions here though, looks like a method from `ProcessTools` used in my jtreg test is using a different method signature in this repo, and might be the case in the other repos (jdk17,jdk19) as well. Not sure if an additional commit will be needed to fix it on the other repos, but I will check there and see. Otherwise, only will be needed to fix it here later on. Did not have the error occurring in the openjdk repo initially, so wasn't expecting errors.

**Comment by Deigue** [comment]
jdk17 PR: https://github.com/openjdk/jdk17u-dev/pull/662
jdk19 PR: : https://github.com/openjdk/jdk19u/pull/16
Also added additional commit to fix the test compile error happening only for the jdk11u-dev repo PR.

**Comment by RealCLanger** [comment]
> jdk17 PR: [openjdk/jdk17u-dev#662](https://github.com/openjdk/jdk17u-dev/pull/662) jdk19 PR: : [openjdk/jdk19u#16](https://github.com/openjdk/jdk19u/pull/16) Also added additional commit to fix the test compile error happening only for the jdk11u-dev repo PR.

OK, next step is to request backport approval by tagging the JBS bugs. I can do it for you, when you give me a Fix request comment statement (e.g. why you want to have it in the update releases, what testing you did, what's the risk etc.)

**Comment by Deigue** [comment]
Backport Request jdk-11u
Requesting this fix to be backported in order to address https://bugs.openjdk.org/browse/JDK-8288377 , which fixes the incorrect timezone displayed in DST period, when a custom TZ code is used. The risk is minimal as the code change is only a small piece of logic in how the offset between GMT and local time is calculated and returned. [(offset fix)](https://github.com/openjdk/jdk11u-dev/pull/1328/files#diff-806fc08210f7476f46a4df89d03c1e3a53ca528812ce0f4a7a2dd58cbaa36dcdR884) In addition, the repeat definition of the function for macOS has been consolidated, while keeping the macOS specific logic when it is needed. Tier 1 testing is passing on macOS and Linux.

Assuming that this backport approval request is step 6 of [how to contribute a fix](https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+a+fix) , I wanted to add that a small tweak was made to the original backport on jdk11u (this PR **only**, jdk-17 and jdk-19 are clean backports) , and thus as per step 5 I will be needing a code review on this PR as it won't be labeled as clean. The only new [change](https://github.com/openjdk/jdk11u-dev/pull/1328/files#diff-1ef896deae588b4f1c6c07a1e87789288ff996a555257e7abb2509bb6a0088e3R45) was modifying the arguments to the `createJavaProcessBuilder` function as its function signature differs within this repo to accept String params instead of a List of Strings.

Please let me know if I need to also comment a request like this on both the other PRs as well, since they are going to be more or less quite similar.

**Review by RealCLanger — APPROVED** [review]
Looks good.

**Comment by RealCLanger** [comment]
> Please let me know if I need to also comment a request like this on both the other PRs as well, since they are going to be more or less quite similar.

I added the fix request labels for all 3 update releases (19, 17 and 11) and posted the fix request comment on your behalf. Please monitor the JBS bug for further activity. I can sponsor the PRs when they are approved.

**Pull request closed without merging**
