### PR TITLE
8260274: Cipher.init(int, key) does not use highest priority provider for random bytes

### PR DESCRIPTION
**Pull request by RealLucy**
This backport is done for 11.0.20-oracle parity. 

The patch applies cleanly except for copyright header mismatches after the predecessor patch JDK-8246383.
Unfortunately, the newly introduced TestDefaultRandom.java uses switch expressions which are not available in jdk11. The test had to be backfitted to compile with jdk11.

Tests (GHA and SAP internal) sucessful after test update.
Separate execution of TestDefaultRandom.java (new test) successful with this patch applied. fails otherwise.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8260274](https://bugs.openjdk.org/browse/JDK-8260274): Cipher.init(int, key) does not use highest priority provider for random bytes (**Bug** - `"4"`)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1902/head:pull/1902` \
`$ git checkout pull/1902`

Update a local copy of the PR: \
`$ git checkout pull/1902` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1902/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1902`

View PR using the GUI difftool: \
`$ git pr show -t 1902`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1902.diff">https://git.openjdk.org/jdk11u-dev/pull/1902.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1902#issuecomment-1562906890)

### CODE REVIEW

**Comment by GoeLin** [comment]
LGTM, code basically identical to head, Test works nicely.

**Review by GoeLin — APPROVED** [review]

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for backporting!

**Comment by RealLucy** [comment]
Thanks for the reviews, Martin & Goetz!
JBS bug flagged with fix-request.

**Pull request closed without merging**
