### PR TITLE
8209946: [TESTBUG] CDS tests should use "@run driver"

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8209946](https://bugs.openjdk.org/browse/JDK-8209946)
Notes
- Comparing to the original commit, the following files has been changed and no need to change in current PR
  - `test/hotspot/jtreg/runtime/SharedArchiveFile/TestInterpreterMethodEntries.java` No need
  - `test/hotspot/jtreg/runtime/appcds/cacheObject/GCStressTest.java` No need
  - `test/hotspot/jtreg/runtime/appcds/customLoader/HelloCustom.java` No need
- The following file the base line content is different, so I manually changed the file based on the original commit
  - `test/hotspot/jtreg/runtime/appcds/cacheObject/RedefineClassTest.java` Base version is different, so manually edit

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8209946](https://bugs.openjdk.org/browse/JDK-8209946) needs maintainer approval

### Issue
 * [JDK-8209946](https://bugs.openjdk.org/browse/JDK-8209946): [TESTBUG] CDS tests should use "@run driver" (**Enhancement** - P3 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2318/head:pull/2318` \
`$ git checkout pull/2318`

Update a local copy of the PR: \
`$ git checkout pull/2318` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2318/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2318`

View PR using the GUI difftool: \
`$ git pr show -t 2318`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2318.diff">https://git.openjdk.org/jdk11u-dev/pull/2318.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2318#issuecomment-1833354240)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean backort. SAP nightlies passed on 2023-12-04.”

**Review by MBaesken — APPROVED** [review]

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean back port. SAP nightlies passed on 2023-12-04.”

**Pull request closed without merging**
