### PR TITLE
8215291: Broken links when generating from project without modules

### PR DESCRIPTION
**Pull request by basil**
Hi all,

This pull request contains a clean backport of [JDK-8215291](https://bugs.openjdk.org/browse/JDK-8215291) (openjdk/jdk@cb553175b7c8248ab89738a7694ea72026027198).

The commit being backported was authored by @hns on December 21, 2018, and was reviewed by @jonathan-gibbons.

See [JENKINS-68761](https://issues.jenkins.io/browse/JENKINS-68761) for the motivation behind this backport.

I tested this by reproducing the search problem described in [JENKINS-68761](https://issues.jenkins.io/browse/JENKINS-68761) on `jdk11u-dev` and verified that I could no longer reproduce the problem after backporting this commit.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8215291](https://bugs.openjdk.org/browse/JDK-8215291): Broken links when generating from project without modules

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1157/head:pull/1157` \
`$ git checkout pull/1157`

Update a local copy of the PR: \
`$ git checkout pull/1157` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1157/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1157`

View PR using the GUI difftool: \
`$ git pr show -t 1157`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1157.diff">https://git.openjdk.org/jdk11u-dev/pull/1157.diff</a>

</details>

### CODE REVIEW

**Comment by basil** [comment]
I do not have JBS access. Can someone please submit the following comment with the `jdk11u-fix-request` label:

> See [JENKINS-68761](https://issues.jenkins.io/browse/JENKINS-68761) for the motivation behind this backport. I tested this by reproducing the search problem described in [JENKINS-68761](https://issues.jenkins.io/browse/JENKINS-68761) on `jdk11u-dev` and verified that I could no longer reproduce the problem after backporting this commit. The commit applied cleanly with no conflicts.

**Comment by basil** [comment]
@TheRealMDoerr You've helped shepherd some of my previous backports to completion, for which I am grateful. Are you interested in shepherding this one to completion? I am not sure what else I need to do from my perspective to drive this forward.

**Comment by TheRealMDoerr** [comment]
Label and comment added. Please wait for the "jdk11u-fix-yes" label before using `/integrate`.

**Comment by basil** [comment]
Thank you!

**Pull request closed without merging**
