### PR TITLE
8278434: timeouts in test  java/time/test/java/time/format/TestZoneTextPrinterParser.java

### PR DESCRIPTION
**Pull request by RealLucy**
This backport is for parity with 11.0.20-oracle.
The patch did not apply cleanly. There were conflicts in the copyright year and in the list of bugs. 

Reviews are welcome!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8278434](https://bugs.openjdk.org/browse/JDK-8278434): timeouts in test  java/time/test/java/time/format/TestZoneTextPrinterParser.java

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1894/head:pull/1894` \
`$ git checkout pull/1894`

Update a local copy of the PR: \
`$ git checkout pull/1894` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1894/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1894`

View PR using the GUI difftool: \
`$ git pr show -t 1894`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1894.diff">https://git.openjdk.org/jdk11u-dev/pull/1894.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1894#issuecomment-1561312285)

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
In TextZonePrinterParser.java, the bug list includes 8277049 and 8177819, which do not appear in 11u or in the 17u backport.

The 17u backport doesn't include the ZoneStrings.java jmh test. @GoeLin (https://github.com/openjdk/jdk17u-dev/pull/1228) might want to fix that up.

**Review by phohensee — APPROVED** [review]
Looks good now.

**Comment by RealLucy** [comment]
@phohensee Thank you for the review, Paul.

**Pull request closed without merging**
