### PR TITLE
8280550: SplittableRandom#nextDouble(double,double) can return result >= bound

### PR DESCRIPTION
**Pull request by GoeLin**
The original fix patches jdk/internal/util/random/RandomSupport.java.
This class is not in 11.

The Random code was completely reworked by
"8248862: Implement Enhanced Pseudo-Random Number Generators"
In the old 11 code there are several methods 'nextDouble' or
'internalNextDouble' all using the same pattern.  They were
replaced by the implementation in the new class
RandomSupport in 17.

I adapted the following methods:
in java/util/Random.java:
  final double internalNextDouble(double origin, double bound)

in java/util/SplittableRandom.java
  final double internalNextDouble(double origin, double bound)
  public double nextDouble(double bound)

in java/util/concurrent/ThreadLocalRandom.java
  final double internalNextDouble(double origin, double bound)
  public double nextDouble(double bound)

I think this are all affected methods, but please double-check.

The change requires follow-up 8280950 which needs to be
adapted to touch the three internalNextDouble()
methods.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280550](https://bugs.openjdk.org/browse/JDK-8280550): SplittableRandom#nextDouble(double,double) can return result >= bound

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1478/head:pull/1478` \
`$ git checkout pull/1478`

Update a local copy of the PR: \
`$ git checkout pull/1478` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1478/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1478`

View PR using the GUI difftool: \
`$ git pr show -t 1478`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1478.diff">https://git.openjdk.org/jdk11u-dev/pull/1478.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
There's similar code in java.desktop/share/classes/sun/awt/geom/Curve.java, but it hasn't been updated in tip, so lgtm.

**Comment by GoeLin** [comment]
Good catch of this further appearance. I agree the fix is not needed there.  But the methods there might not always deliver the previous double either.

**Comment by GoeLin** [comment]
I opened JDK-8296402 for the pattern in Curve.java.

**Pull request closed without merging**
