### PR TITLE
8229867: Re-examine synchronization usages in http and https protocol handlers

### PR DESCRIPTION
**Pull request by PoojaDP-23**
This is a backport request and this fix is a dependency for [8293562](https://github.com/openjdk/jdk/commit/03f25a9c6924430ec4063b801b2b6ca55b9067c9).

This is a fix that upgrades the old HTTP and HTTPS legacy stack to use virtual-thread friendly locking instead of synchronized monitors.

We have removed @java.io.serial in AuthenticationInfo.java since the serial.class file not located.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8229867](https://bugs.openjdk.org/browse/JDK-8229867): Re-examine synchronization usages in http and https protocol handlers

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1710/head:pull/1710` \
`$ git checkout pull/1710`

Update a local copy of the PR: \
`$ git checkout pull/1710` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1710/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1710`

View PR using the GUI difftool: \
`$ git pr show -t 1710`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1710.diff">https://git.openjdk.org/jdk11u-dev/pull/1710.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1710#issuecomment-1439218005)

### CODE REVIEW

**Comment by robilad** [comment]
Hi, please send an e-mail to Dalibor.Topic@oracle.com so that I can mark your account as verified in Skara.

**Comment by PoojaDP-23** [comment]
@robilad - I have sent an email to [Dalibor.Topic@oracle.com](mailto:Dalibor.Topic@oracle.com). Thanks

**Comment by PoojaDP-23** [comment]
@robilad - Earlier Workflows aren't being run on this forked repository because it was not enabled. Now I have enabled the workflow but still tests are not running on my fork. Could you please let me know what action needs to be done by myside? 
Thanks

**Comment by RealCLanger** [comment]
> @robilad - Earlier Workflows aren't being run on this forked repository because it was not enabled. Now I have enabled the workflow but still tests are not running on my fork. Could you please let me know what action needs to be done by myside? Thanks

Hi @PoojaDP-23,
I guess the easiest way to get current GHA checks is to merge your branch with current master of [jdk11u-dev](https://github.com/openjdk/jdk11u-dev) and push it. This will trigger a run with the most current code.

**Comment by PoojaDP-23** [comment]
@RealCLanger - Could you please review the backport PR?

**Comment by RealCLanger** [comment]
> @RealCLanger - Could you please review the backport PR?

I can have a look. But please do a merge with master before and by that, trigger GHA. Thanks.

**Comment by PoojaDP-23** [comment]
@RealCLanger - I have triggered GHA for my branch and master. Is that ok or do I need to merge and trigger GHA. Could you pls confirm on this?

**Comment by PoojaDP-23** [comment]
@RealCLanger - Could you please review the PR? because customer dependent on this fix. Thanks

**Comment by RealCLanger** [comment]
Hi @PoojaDP-23,

when looking at the scope of this backport and its successor, [JDK-8293562](https://github.com/openjdk/jdk/commit/03f25a9c6924430ec4063b801b2b6ca55b9067c9), which I've understood is what you actually want to fix, I'm a bit concerned whether this is appropriate as a backport to JDK11. After all, it completely reworks the locking in the HTTP client and we can't be sure what side effects this might cause in other productive usages. It might even unveil issues that have not been discovered in head.

So, could you go back and give some more explanation what kind of bug you want to fix in 11u? Maybe we can find a less intrusive fix that could also differ from OpenJDK upstream? Maybe JDK-8293562 can be adapted for 11u without this one?

Thanks
Christoph

**Comment by PoojaDP-23** [comment]
Thanks for the update  @RealCLanger  

Yes, we need to backport JDK-8293562 to jdk-11 and backporting the dependency as well. Please let us know about the less intrusive fix, we shall evaluate if this resolves the issue.

Also, could you please help us understand the following ?

1) How this backport will be different from JDK17 as this is already backported to JDK17 and what/why are we expecting side effects in JDK11 ? 

2) Unit test suite execution will be sufficient to confirm the adaptability of these two backports or what exact side effects to be concerned with. 

Please share your response ASAP. It will help us to decide on next steps. thx

**Comment by GoeLin** [comment]
Dear @PoojaDP-23 

Christoph already reasoned why he thinks this is not appropriate for 11: " After all, it completely reworks the locking in the HTTP client and we can't be sure what side effects this might cause in other productive usages. It might even unveil issues that have not been discovered in head."

You did not give a reason why you need these changes yet.   Please reason for this carefully. 

You ask "Please let us know about the less intrusive fix," It is up to you, the Contributor, to draft a less intrusive fix. If you can not do that yourself, you also can not judge the risk of the backport properly because you have not understood the fix.

ASAP is not a vocabulary used typically in open source projects where people work on a voluntary basis.

Please see https://wiki.openjdk.org/display/JDKUpdates/JDK11u for a description of eligible backports.

**Comment by GoeLin** [comment]
Also, you have failing tests.

**Comment by theRealAph** [comment]
No. This patch will never be accepted in JDK 11u.

**Pull request closed without merging**
