### PR TITLE
8238268: Many SA tests are not running on OSX because they do not attempt to use sudo when available

### PR DESCRIPTION
**Pull request by RealCLanger**
This is a backport of [JDK-8238268](https://bugs.openjdk.org/browse/JDK-8238268). We need it, because the backport of [JDK-8215544](https://bugs.openjdk.org/browse/JDK-8215544) has added code that calls `sudo -E` on MacOS without the option `-n`. This call might not return when sudo starts prompting for a password. In our CI it leads to hanging processes when subsequent tests call sudo, even with the -n option. This fix rectifies that behavior. And, after all, it improves test coverage on MacOS, so it's a good backport candidate.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8238268](https://bugs.openjdk.org/browse/JDK-8238268): Many SA tests are not running on OSX because they do not attempt to use sudo when available
 * [JDK-8238196](https://bugs.openjdk.org/browse/JDK-8238196): tests that use SA Attach should not be allowed to run against signed binaries on Mac OS X 10.14.5 and later

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1269/head:pull/1269` \
`$ git checkout pull/1269`

Update a local copy of the PR: \
`$ git checkout pull/1269` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1269/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1269`

View PR using the GUI difftool: \
`$ git pr show -t 1269`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1269.diff">https://git.openjdk.org/jdk11u-dev/pull/1269.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
GHA failure would be fixed with #1268

**Review by GoeLin — COMMENTED** [review]
Hi

you add a very thorough description why you backport this.
This should go to the JBS fix comment. 
Unfortunately it does not help reviewing the change.
I assume you ran SAP testing on this.

Here my comments:

test/hotspot/jtreg/TEST.ROOT
Copyright. ok. 

test/hotspot/jtreg/serviceability/sa/ClhsdbLauncher.java
Why do you remove 
   `processBuilder.redirectError(ProcessBuilder.Redirect.INHERIT);`

The special check for OSX is removed in several tests.
It looks different in 11 and the original change, but as
the code is removed this does not matter.

test/hotspot/jtreg/serviceability/sa/TestUniverse.java
Chunk for new test not in 11 omitted


test/hotspot/jtreg/testlibrary_tests/TestMutuallyExclusivePlatformPredicates.java
Besides replacein shouldSAAttach by isRoot, isSigned OSX is added. 
Is this by purpose?

test/jdk/sun/tools/jhsdb/HeapDumpTestWithActiveProcess.java
Chunk is omitted. Test is not in 11.

test/jtreg-ext/requires/VMProps.java
Copyright.

test/lib/jdk/test/lib/Platform.java
Imports were adapted.
isSignedOSX() is added. What is the original change of this?
Please mention in the JBS FixRequest comment that you 
include code from that change.

test/lib/jdk/test/lib/SA/SATestUtils.java
Imports were adapted.

**Comment by RealCLanger** [comment]
Hi Goetz,

thanks for the review. Yes, I have the patch running in the SAP tests without regressions, as far as I can tell.

> test/hotspot/jtreg/serviceability/sa/ClhsdbLauncher.java Why do you remove `processBuilder.redirectError(ProcessBuilder.Redirect.INHERIT);`

Hm, when I looked at [JDK-8234277](https://bugs.openjdk.org/browse/JDK-8234277), I thought it could be a good idea to do the removal in this change already but maybe you're right and we should keep it consistent. I'm actually not sure about the effects so I'll re-add it.

> test/lib/jdk/test/lib/Platform.java Imports were adapted. isSignedOSX() is added. What is the original change of this? Please mention in the JBS FixRequest comment that you include code from that change.

This originally comes from [JDK-8238196](https://bugs.openjdk.org/browse/JDK-8238196). Since merely all of the code of that bug is part of this PR as well (either as is or augmented), I'll add JDK-8238196 to this backport, too.

**Comment by RealCLanger** [comment]
> Thanks for the clarifications. LGTM.

Thanks for review and approval.

/integrate

**Pull request closed without merging**
