### PR TITLE
8295322: Tests for JDK-8271459 were not backported to 11u

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi!

Here is a portion of tests from [JDK-8271459](https://bugs.openjdk.org/browse/JDK-8271459) adopted to the 11. Original tests were not backported to the 11 because of the fact they use IR test framework that does not exists in the 11.

Verified on amd64/20.04LTS:

7 of 7 new tests PASS on https://github.com/openjdk/jdk11u-dev/commit/844c504bc18fa8a79ceacc6b6f235650f5e643bf
4 of 7 new tests FAIL on the previous https://github.com/openjdk/jdk11u-dev/commit/4940e2e8d85f2eef88c6132923b165253c13aa73

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295322](https://bugs.openjdk.org/browse/JDK-8295322): Tests for JDK-8271459 were not backported to 11u

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Contributors
 * Christian Hagedorn `<chagedorn@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1460/head:pull/1460` \
`$ git checkout pull/1460`

Update a local copy of the PR: \
`$ git checkout pull/1460` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1460/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1460`

View PR using the GUI difftool: \
`$ git pr show -t 1460`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1460.diff">https://git.openjdk.org/jdk11u-dev/pull/1460.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
This looks fine as is, but seems to be a completely new test. Are there tests which could be backported that include the functionality in this new test?

**Comment by apavlyutkin** [comment]
> This looks fine as is, but seems to be a completely new test. Are there tests which could be backported that include the functionality in this new test?

Here you are https://github.com/openjdk/jdk/commit/3953e0774c59c5e936e752aa08b6b6778e232994#diff-23a7c0bc2991c82f3ab4be6a23789dc57829aa5a399c70b9328479d5a9c88850

**Review by phohensee — APPROVED** [review]
Thank you. Lgtm. :)

**Comment by apavlyutkin** [comment]
> Thank you. Lgtm. :)

Thank you for the review

**Pull request closed without merging**
