### PR TITLE
8244078: ProcessTools executeTestJvm and createJavaProcessBuilder have inconsistent handling of test.*.opts

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 11.0.20-oracle.

A row of files are not in 11 or have been moved. 
Some trivial resolves were necessary.
An extra commit fixes the remaining occurances.

test/hotspot/jtreg/compiler/graalunit/common/GraalUnitTestLauncher.java
Context

not in 11: test/hotspot/jtreg/gc/logging/TestMetaSpaceLog.java
not in 11: test/hotspot/jtreg/gc/nvdimm/TestAllocateOldGenAt.java
not in 11: test/hotspot/jtreg/gc/nvdimm/TestAllocateOldGenAtError.java
not in 11: test/hotspot/jtreg/gc/nvdimm/TestAllocateOldGenAtMultiple.java
not in 11: test/hotspot/jtreg/gc/nvdimm/TestHumongousObjectsOnNvdimm.java
not in 11: test/hotspot/jtreg/gc/nvdimm/TestOldObjectsOnNvdimm.java
not in 11: test/hotspot/jtreg/gc/nvdimm/TestYoungObjectsOnDram.java

test/hotspot/jtreg/runtime/7162488/TestUnrecognizedVmOption.java
Later change undoes this, and is already backported (8247741). Skipped.

not in 11: test/hotspot/jtreg/runtime/InvocationTests/invocationC1Tests.java
not in 11: test/hotspot/jtreg/runtime/InvocationTests/invocationGraalTests.java
not in 11: test/hotspot/jtreg/runtime/InvocationTests/invokeinterfaceTests.java
not in 11: test/hotspot/jtreg/runtime/InvocationTests/invokespecialTests.java
not in 11: test/hotspot/jtreg/runtime/InvocationTests/invokevirtualTests.java

not in 11: test/hotspot/jtreg/runtime/cds/SharedArchiveFile.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/DumpClassList.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/GraalWithLimitedMetaspace.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/TestCommon.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/dynamicArchive/DynamicArchiveTestBase.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/dynamicArchive/NoClassToArchive.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/sharedStrings/SharedStringsBasic.java
not in 11: test/hotspot/jtreg/runtime/cds/appcds/sharedStrings/SysDictCrash.java

test/hotspot/jtreg/runtime/handshake/HandshakeTransitionTest.java
Context

test/hotspot/jtreg/serviceability/logging/TestLogRotation.java
Extra empty line.

test/hotspot/jtreg/serviceability/sa/TestJmapCore.java
Context.

not in 11: test/jdk/java/lang/RuntimeTests/shutdown/ShutdownInterruptedMain.java
not in 11: test/jdk/jdk/jfr/api/consumer/streaming/TestCrossProcessStreaming.java
not in 11: test/jdk/jdk/jfr/api/consumer/streaming/TestProcess.java
not in 11: test/jdk/jdk/jfr/event/runtime/TestDumpReason.java
not in 11: test/jdk/jdk/jfr/event/runtime/TestShutdownEvent.java
not in 11: test/jdk/sun/security/ssl/SSLSessionImpl/ResumptionUpdateBoundValues.java

test/lib/jdk/test/lib/process/ProcessTools.java
Context.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8244078](https://bugs.openjdk.org/browse/JDK-8244078): ProcessTools executeTestJvm and createJavaProcessBuilder have inconsistent handling of test.*.opts (**Enhancement** - P4)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2000/head:pull/2000` \
`$ git checkout pull/2000`

Update a local copy of the PR: \
`$ git checkout pull/2000` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2000/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2000`

View PR using the GUI difftool: \
`$ git pr show -t 2000`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2000.diff">https://git.openjdk.org/jdk11u-dev/pull/2000.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2000#issuecomment-1606101851)

### CODE REVIEW

**Comment by GoeLin** [comment]
To make the tests pass, I include a change to ModuleOptionsTest.java that was done in JDK-8243945.
Also, 8237111 renamed a method in Utils.java to prependTestJavaOpts().
I added a new method with this name and the same implementation so that both names
can be used. Else I need to include large parts of 8237111.

See latest commit.

**Review by RealLucy — APPROVED** [review]
LGTM.
In the future, we may want to think twice before we backport enhancements with such widespread reach.

**Comment by GoeLin** [comment]
Thanks for reviewing!

**Pull request closed without merging**
