### PR TITLE
8307134: Add GTS root CAs

### PR DESCRIPTION
**Pull request by jianglizhou**
Backport to JDK 11u for parity with 11.0.21-oracle.

Manually merged:
- Placed new cacert files under make/data/cacerts/.
- Updated `CHECKSUM` in test/jdk/sun/security/lib/cacerts/VerifyCACerts.java.

Tested both test/jdk/security/infra/java/security/cert/CertPathValidator/certification/GoogleCA.java and test/jdk/sun/security/lib/cacerts/VerifyCACerts.java with JDK 11 test binary.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307134](https://bugs.openjdk.org/browse/JDK-8307134): Add GTS root CAs

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1892/head:pull/1892` \
`$ git checkout pull/1892`

Update a local copy of the PR: \
`$ git checkout pull/1892` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1892/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1892`

View PR using the GUI difftool: \
`$ git pr show -t 1892`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1892.diff">https://git.openjdk.org/jdk11u-dev/pull/1892.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1892#issuecomment-1559906064)

### CODE REVIEW

**Comment by jerboaa** [comment]
@jianglizhou Please enable testing on your fork. Thanks.

**Comment by jianglizhou** [comment]
> @jianglizhou Please enable testing on your fork. Thanks.

Done, thanks. 

I'll look into starting the workflow ...

**Review by jerboaa — APPROVED** [review]
Looks fine to me. Almost clean to the 17u-dev version. Only context differences in a test. Thanks!

**Comment by jianglizhou** [comment]
> Looks fine to me. Almost clean to the 17u-dev version. Only context differences in a test. Thanks!

Thanks for the review.

**Comment by jianglizhou** [comment]
> Hi @jianglizhou, please enable GHA tests and restart them by merging head!

Restarted test workflow by merging head. Thanks.

**Comment by GoeLin** [comment]
Thanks!

**Pull request closed without merging**
