### PR TITLE
8268457: XML Transformer outputs Unicode supplementary character incorrectly to HTML

### PR DESCRIPTION
**Pull request by Nagata-Haruhito**
I want to backport JDK-8268457 to JDK11u.
This is almost clean except lastmodified month.

Note, included test is broken, it was fixed with JDK-8274606, 
I intend to follow up with its backport same as jdk17u.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8268457](https://bugs.openjdk.org/browse/JDK-8268457): XML Transformer outputs Unicode supplementary character incorrectly to HTML (**Bug** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1907/head:pull/1907` \
`$ git checkout pull/1907`

Update a local copy of the PR: \
`$ git checkout pull/1907` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1907/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1907`

View PR using the GUI difftool: \
`$ git pr show -t 1907`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1907.diff">https://git.openjdk.org/jdk11u-dev/pull/1907.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1907#issuecomment-1566874496)

### CODE REVIEW

**Comment by Nagata-Haruhito** [comment]
Would you please review this PR?

**Comment by GoeLin** [comment]
Please, first review, then label fix-request.
Also, prepare a dependent PR for the test fix on top of this one.
I will only approve both at a time.

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by Nagata-Haruhito** [comment]
Thank you for your advice.
I create new PR for my PR branch. 
Is it OK for "a dependent PR for the test fix on top of this one" ?

**Comment by Nagata-Haruhito** [comment]
Should I re-label "11u-fix-request" on JBS ? Or can I type `/integrate` now ?

**Comment by Nagata-Haruhito** [comment]
I have confirmed jdk11u-fix-yes label is added on JBS. Thank you very match.

**Comment by gnu-andrew** [comment]
Is there a reason that `SurrogateTest.java` in this change has a different copyright year (2023) to the version in 17u and 18 (2021)?

**Pull request closed without merging**
