### PR TITLE
8287017: Bump update version for OpenJDK: jdk-11.0.17

### PR DESCRIPTION
**Pull request by GoeLin**
The necessary version change.
To be pushed on June 1st after tag jdk-11.0.17+0

This includes adding ea as asked in [JDK-8283911](https://bugs.openjdk.java.net/browse/JDK-8283911)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287017](https://bugs.openjdk.java.net/browse/JDK-8287017): Bump update version for OpenJDK: jdk-11.0.17

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/1100/head:pull/1100` \
`$ git checkout pull/1100`

Update a local copy of the PR: \
`$ git checkout pull/1100` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/1100/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1100`

View PR using the GUI difftool: \
`$ git pr show -t 1100`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/1100.diff">https://git.openjdk.java.net/jdk11u-dev/pull/1100.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Pre-submit failure: SuspendAtExit.java This test fails every once in a while, unrelated.

**Review by TheRealMDoerr — COMMENTED** [review]
I can't judge if "ea" should be set. It's not done in 17u-dev: `make/conf/version-numbers.conf:DEFAULT_PROMOTED_VERSION_PRE=`. Does this make sense? Besides this, LGTM.

**Comment by GoeLin** [comment]
Hi, in 17, there is an extra change to set ea.  See description above.

**Pull request closed without merging**
