### PR TITLE
8222926: Shenandoah build fails with --with-jvm-features=-compiler1

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

As discussed here https://github.com/openjdk/jdk11u-dev/pull/921#issuecomment-1073341167 , I'd like to backport this patch to fix the build failure of jdk11u when c1 is disabled.

The patch doesn't apply cleanly since most of the changes are already in the jdk11u repo.
Actually, only two include statements are added in the backport, so the risk is low.

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8222926](https://bugs.openjdk.java.net/browse/JDK-8222926): Shenandoah build fails with --with-jvm-features=-compiler1

### Reviewers
 * [Vladimir Kempik](https://openjdk.java.net/census#vkempik) (@VladimirKempik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/933/head:pull/933` \
`$ git checkout pull/933`

Update a local copy of the PR: \
`$ git checkout pull/933` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/933/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 933`

View PR using the GUI difftool: \
`$ git pr show -t 933`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/933.diff">https://git.openjdk.java.net/jdk11u-dev/pull/933.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Please undo the copyright change.  A backport should only change the copyright if the original change did so.

Please point out the change that backported all the other content.

**Comment by DamonFool** [comment]
> Please undo the copyright change. A backport should only change the copyright if the original change did so.

I'm fine to revert the copyright change.
The copyright was changed since the patch didn't apply cleanly, so I just made the change by hand.
Thanks.

**Comment by DamonFool** [comment]
> Please point out the change that backported all the other content.

Hi @GoeLin , please see here: https://bugs.openjdk.java.net/browse/JDK-8250784

**Comment by DamonFool** [comment]
> Please undo the copyright change. A backport should only change the copyright if the original change did so.

Updated.
Thanks.

**Review by VladimirKempik — APPROVED** [review]

**Comment by DamonFool** [comment]
Fix request had been approved.
So integrate it.
Thanks @VladimirKempik and @GoeLin .
/integrate

**Pull request closed without merging**
