### PR TITLE
8216318: The usage of Disposer in the java.awt.Robot can be deleted

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Clean backport of JDK-8216318.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8216318](https://bugs.openjdk.java.net/browse/JDK-8216318): The usage of Disposer in the java.awt.Robot can be deleted

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/365/head:pull/365` \
`$ git checkout pull/365`

Update a local copy of the PR: \
`$ git checkout pull/365` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/365/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 365`

View PR using the GUI difftool: \
`$ git pr show -t 365`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/365.diff">https://git.openjdk.java.net/jdk11u-dev/pull/365.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Not recognized as clean because of Copyright year changes.

**Review by GoeLin — APPROVED** [review]
LGTM

**Comment by TheRealMDoerr** [comment]
Thanks for the review!
/integrate

**Pull request closed without merging**
