### PR TITLE
8336292: [11u]  awt_ImagingLib passes arguments to function without a prototype

### PR DESCRIPTION
**Pull request by vieiro**
This is a fix to [JDK-8336292](https://bugs.openjdk.org/browse/JDK-8336292): Building 11u on the latest macos-13 GHA platform (XCode 14, clang 14) fails as we are passing arguments to a function without a prototype in awt_ImagingLib.c. 

The fix adds disables the `deprecated-non-prototype` when building with clang, for the build to pass. 

This is a 11u only issue, as the make infrastructure was reorganized in [JDK-8244044](https://bugs.openjdk.org/browse/JDK-8244044) after OpenJDK 15, and enhanced afterwards. Backporting [JDK-8244044](https://bugs.openjdk.org/browse/JDK-8244044) is an important change that should be avoided unless strictly necessary.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] [JDK-8336292](https://bugs.openjdk.org/browse/JDK-8336292) needs maintainer approval
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Dependency #2844 must be integrated first

### Issue
 * [JDK-8336292](https://bugs.openjdk.org/browse/JDK-8336292): [11u]  awt_ImagingLib passes arguments to function without a prototype (**Enhancement** - P4)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2854/head:pull/2854` \
`$ git checkout pull/2854`

Update a local copy of the PR: \
`$ git checkout pull/2854` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2854/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2854`

View PR using the GUI difftool: \
`$ git pr show -t 2854`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2854.diff">https://git.openjdk.org/jdk11u-dev/pull/2854.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2854#issuecomment-2225032051)

### CODE REVIEW

**Comment by vieiro** [comment]
The GHA macos-13 runner has problems with reverse DNS lookups https://github.com/actions/runner-images/issues/8649, that causes JDI/JDWSP tests to fail.

Modifying [/etc/hosts](https://github.com/openjdk/jdk11u-dev/commit/3ac6cd6165b4779290f23f260ce5aee0bc392c49) to allow the hostname to be resolved fixes the problem.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by vieiro** [comment]
Hi @TheRealMDoerr . Thanks for the review. Would it be possible to rerun macos jobs? (I don't have permissions to do that ). Thanks!.

**Comment by TheRealMDoerr** [comment]
> Hi @TheRealMDoerr . Thanks for the review. Would it be possible to rerun macos jobs? (I don't have permissions to do that ). Thanks!.

I can only rerun jobs in my own PRs. You should find a rerun button next to the failing test.

**Comment by vieiro** [comment]
Thanks, @TheRealMDoerr . I couldn't rerun failed jobs, so I ran the whole workflow. 
Checks are green now.

I think I'll wait for reviews on the remaining integration blockers/PRs before requesting an approval.

**Comment by vieiro** [comment]
Parent pull requests have been closed without review, so there's no point in continuing just with this PR.

**Pull request closed without merging**
