### PR TITLE
8210112: remove jdk.testlibrary.ProcessTools

### PR DESCRIPTION
**Pull request by GoeLin**
I want to backport this ot simplify follow-up test backports.

I had to adapt the change in several means.  This is a list 
of the changes to resolve failed hunks:

Already fixed:
patching file test/jdk/com/sun/jdi/ExclusiveBind.java

Resolved, 8211171 move JarUtils to top-level testlibrary already backported.
patching file test/jdk/java/lang/ClassLoader/getResource/automaticmodules/Driver.java
patching file test/jdk/java/lang/ClassLoader/securityManager/ClassLoaderTest.java
patching file test/jdk/java/lang/instrument/executableJAR/ExecJarWithAgent.java
patching file test/jdk/java/rmi/module/ModuleTest.java

Context
patching file test/jdk/java/lang/System/OsVersionTest.java
patching file test/jdk/java/security/Policy/SignedJar/SignedJarTest.java
patching file test/jdk/java/util/Arrays/TimSortStackSize2.java

Copyright
patching file test/jdk/javax/management/remote/mandatory/connection/DefaultAgentFilterTest.java

Resolved, 8211171 move JarUtils to top-level testlibrary already backported.
patching file test/jdk/jdk/modules/scenarios/automaticmodules/RunWithAutomaticModules.java
patching file test/jdk/sun/security/tools/jarsigner/TsacertOptionTest.java

Copyright
patching file test/jdk/sun/security/tools/jarsigner/Warning.java
patching file test/jdk/sun/security/tools/jarsigner/warnings/BadKeyUsageTest.java

Resolved, 8211171 move JarUtils to top-level testlibrary already backported.
patching file test/jdk/sun/security/tools/jarsigner/warnings/NoTimestampTest.java

File not in 11:  --- probably goes away
test/jdk/sun/tools/jcmd/JcmdBase.java b/test/jdk/sun/tools/jcmd/JcmdBase.java
patching file test/jdk/sun/tools/jcmd/TestJcmdDefaults.java
patching file test/jdk/sun/tools/jcmd/TestJcmdSanity.java

Copyright
patching file test/jdk/sun/tools/jmap/BasicJMapTest.java

Resolved
patching file test/jdk/sun/tools/jstatd/JstatdTest.java

Resolved, 8211171 move JarUtils to top-level testlibrary already backported.
patching file test/jdk/tools/jlink/basic/BasicTest.java
patching file test/jdk/tools/launcher/modules/addexports/manifest/AddExportsAndOpensInManifest.java
patching file test/jdk/tools/launcher/modules/addreads/AddReadsTest.java
patching file test/jdk/tools/launcher/modules/illegalaccess/IllegalAccessTest.java
patching file test/jdk/tools/launcher/modules/patch/basic/PatchTest.java
patching file test/jdk/tools/launcher/modules/patch/basic/PatchTestWarningError.java
patching file test/jdk/tools/launcher/modules/validate/ValidateModulesTest.java

On top of this, I had to adapt a few tests to work after removal of 
the old testlibrary file.

Last, I had to move the `change` of  "8217375: jarsigner breaks old signature with long lines in manifest"
to OutputAnalyzer.java from the old file to the new one.

Now all test are passing.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8210112](https://bugs.openjdk.java.net/browse/JDK-8210112): remove jdk.testlibrary.ProcessTools

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/945/head:pull/945` \
`$ git checkout pull/945`

Update a local copy of the PR: \
`$ git checkout pull/945` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/945/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 945`

View PR using the GUI difftool: \
`$ git pr show -t 945`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/945.diff">https://git.openjdk.java.net/jdk11u-dev/pull/945.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Thanks for the detailed description. However, it's still not easy to review. Can you be more specific regarding "I had to adapt a few tests to work after removal of the old testlibrary file.", please?
(It sometimes helps reviewers to use individual commits when several steps were done. Just as an idea for future backports.)

**Comment by GoeLin** [comment]
Hi,

thanks for looking at this cumbersome change :).

It have basically been these files I had to edit on top of the original change:
test/jdk/sun/security/tools/jarsigner/compatibility/Compatibility.java
test/jdk/sun/security/tools/jarsigner/compatibility/SignTwice.java
test/jdk/sun/security/tools/jarsigner/warnings/LowerCaseManifest.java

Also, I had to edit one of the OutputAnalyzer constructors.
It was only added in a later change in head, but already
backported to 11. It needs to call OutputBuffer.

**Comment by GoeLin** [comment]
Pre-submit failure
* missing dependencie
* assertion in CMS
Both unrealted to this test-only change.  But the assertion is something to look at.

**Pull request closed without merging**
