### PR TITLE
8218136: minor hotspot adjustments for xlclang++ from xlc16 on AIX

### PR DESCRIPTION
**Pull request by backwaterred**
#993 

8218136: minor hotspot adjustments for xlclang++ from xlc16 on AIX

Reviewed-by: dholmes, goetz, ihse

Backport Notes:

- src/hotspot/share/runtime/arguments.cpp: Remove `UNSUPPORTED_OPTION_NULL(AllocateOldGenAt)` modified by backport but not present in original source.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8218136](https://bugs.openjdk.java.net/browse/JDK-8218136): minor hotspot adjustments for xlclang++ from xlc16 on AIX

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/997/head:pull/997` \
`$ git checkout pull/997`

Update a local copy of the PR: \
`$ git checkout pull/997` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/997/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 997`

View PR using the GUI difftool: \
`$ git pr show -t 997`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/997.diff">https://git.openjdk.java.net/jdk11u-dev/pull/997.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi, what's wrong with the Pre-submit tests?

**Comment by backwaterred** [comment]
> what's wrong with the Pre-submit tests? Is it caused by your change or by some other, unrelated problem

To your other point, I was not able to reproduce the failure with gcc 9 or gcc 7 on an x86_64 machine running Ubuntu. I believe they are unrelated to this change.

**Review by TheRealMDoerr — APPROVED** [review]
Looks good. This allows us to build OpenJDK 11.0.16 on AIX with updated harfbuzz!

**Pull request closed without merging**
