### PR TITLE
8259530: Generated docs contain MIT/GPL-licenced works without reproducing the licence

### PR DESCRIPTION
**Pull request by yukikimmura**
I would like to backport
JDK-8259530: Generated docs contain MIT/GPL-licenced works without reproducing the licence.
The original patch does not apply cleanly to 11u. 
Because the original patch has switch expressions which can not be used in 11u,
and it has the Class jdk.javadoc.internal.doclets.formats.html.HtmlOptions which is not defined in 11u. 
There is no risk, because the logic around the changes is the same as jdk17. 
I confirmed the following test and all langtool tests.
test/langtools/jdk/javadoc/doclet/testLegalNotices/TestLegalNotices.java

Could anyone review the fix please?

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8259530](https://bugs.openjdk.org/browse/JDK-8259530): Generated docs contain MIT/GPL-licenced works without reproducing the licence

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1805/head:pull/1805` \
`$ git checkout pull/1805`

Update a local copy of the PR: \
`$ git checkout pull/1805` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1805/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1805`

View PR using the GUI difftool: \
`$ git pr show -t 1805`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1805.diff">https://git.openjdk.org/jdk11u-dev/pull/1805.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
In HtmlConfiguration.java, why not make legalNotices private and add the legalNotices() accessor as in the original commit?

**Comment by yukikimmura** [comment]
Hello Paul,

Thank you for your advice.
In HtmlConfiguration.java, all variables for command line options are defined as public variable. For instance helpfile, stylesheetfile or createindex. 
Should all variables make private, including legalnotices?

Thanks,
Kimura Yukihiro

**Review by phohensee — APPROVED** [review]
You're correct.

**Comment by yukikimmura** [comment]
In the case of 17u, 
variables about javadoc options are defined as PRIVATE variable in HtmlOptions.java and BaseOptions.java
On the other hand, variables about configurations are defined as PUBLIC variable in HtmlConfiguration.java and BaseConfiguration.java

In the case of 11u, 
both variables about options and configurations are defined as public variables
in HtmlConfiguration.java and BaseConfiguration.java
I changed variables about javadoc options to private variables according to the latest JDK.

**Comment by yukikimmura** [comment]
Hello Paul,

Thank you for your advice. I modified the fix.
I would appreciate if you could review it.

Thanks,
Kimura Yukihiro

**Comment by yukikimmura** [comment]
Hello Paul,

Thank you for your advice. I modified the fix.
I would appreciate if you could review it.

Thanks,
Kimura Yukihiro

**Comment by phohensee** [comment]
Hi, Kimura.

I accepted your original fix after you corrected me. :) Your new update changes 101 files, which won't be approved by the Maintainers, so please revert to the original patch.

**Comment by yukikimmura** [comment]
Hello Paul,

I reverted to the original pacth.

Thanks,
Kimura Yukihiro

**Review by phohensee — APPROVED** [review]
Looks good.

The backport has been approved in the JBS issue, so I can sponsor as soon as you add /integrate.

**Comment by RealCLanger** [comment]
Hi @yukikimmura, this backport has broken the bootcycle build with JDK10, due to the lack of Path.of. (See the comments at https://bugs.openjdk.org/browse/JDK-8305385). Can you please fix this. Thanks!

**Comment by yukikimmura** [comment]
Hello Christoph,

Thank you for your comment.
The problem was reproduced in my environment.
I'm investigating it, and below is the fix.

-                Path javaHome = Path.of(System.getProperty("java.home"));
+                Path javaHome = FileSystems.getDefault().getPath(System.getProperty("java.home"));

-                    legalNoticesDir = Path.of(legalNotices);
+                    legalNoticesDir = FileSystems.getDefault().getPath(legalNotices);

Can I reopen the pullrequest, or should I issue a new pullrequest?

**Comment by RealCLanger** [comment]
Hi,

I created JBS issue [JDK-8305528](https://bugs.openjdk.org/browse/JDK-8305528). You can open a PR with the fix against this bug. I can help to test/review it.

Cheers
Christoph

**Comment by pavelrappo** [comment]
What are the reasons that the option type was changed from that of the original commit? In the original commit it was eXtended, in this backport it is standard.

**Comment by pavelrappo** [comment]
> What are the reasons that the option type was changed from that of the original commit? In the original commit it was eXtended, in this backport it is standard.

@yukikimmura, @RealCLanger, @phohensee, if there are no reasons for that change in option type, then I believe it should be reverted.

**Comment by RealCLanger** [comment]
> > What are the reasons that the option type was changed from that of the original commit? In the original commit it was eXtended, in this backport it is standard.
> 
> @yukikimmura, @RealCLanger, @phohensee, if there are no reasons for that change in option type, then I believe it should be reverted.

@pavelrappo I was not involved in the review, I just discovered an issue with the test afterwards. However, I also can't see what exeactly you mean with the option type. Could you please elaborate this a bit more? Thanks

**Comment by pavelrappo** [comment]
> @pavelrappo I was not involved in the review, I just discovered an issue with the test afterwards. However, I also can't see what exeactly you mean with the option type. Could you please elaborate this a bit more? Thanks

In the original commit, the new option is defined like this:

    new XOption(resources, "--legal-notices", 1)

In this backport, the new option is defined like this:

    new Option(resources, "--legal-notices", 1)

**Comment by yukikimmura** [comment]
To the best of my recollection, I didn't intentionally change "XOption" to "Option." I believe it's a bug.

**Comment by pavelrappo** [comment]
> To the best of my recollection, I didn't intentionally change "XOption" to "Option." I believe it's a bug.

While this backport could've used `git range-diff` or some other tool to catch that issue, the original bug could've also provided a better test.

Could you please publish a PR to fix the option type in jdk11u? Thanks.

**Comment by yukikimmura** [comment]
Thank you for your comment and for pointing this out.
Yes, I will make this correction. 
However, due to the long holiday in Japan, the office where I do my development work is closed, 
which will cause a slight delay in starting work.

Thanks,
Kimura Yukihiro

**Pull request closed without merging**
