### PR TITLE
8246387: switch to jtreg 5.1

### PR DESCRIPTION
**Pull request by shipilev**
This is a compound backport that brings the entire 11u to 5.1 b1. There are many dependencies thorough the repository history, so I opted to squash them together. It seems the 11.0.13-oracle backport exists only for this issue, which indicates Oracle maintainers did the same. 

The current list of included patches is:

```
8246387: switch to jtreg 5.1
8238943: switch to jtreg 5.0
8235866: bump jtreg requiredVersion to 4.2b16
8219552: bump jtreg requiredVersion to b14 in test/jdk/sanity/client/
8219417: bump jtreg requiredVersion to b14
8236111: narrow allowSmartActionArgs disabling
```

Tested on Linux x86_64 fastdebug with jtreg5.1-b1 and the following test suites:
 - tier1
 - tier2
 - tier3
 - vmTestbase_nsk_jvmti
 - vmTestbase_vm_metaspace
 - vmTestbase_vm_defmeth
 - vmTestbase_vm_mlvm
 - vmTestbase_vm_compiler
 - vmTestbase_nsk_jvmti
 - vmTestbase_vm_metaspace
 - sanity/client

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8246387](https://bugs.openjdk.java.net/browse/JDK-8246387): switch to jtreg 5.1
 * [JDK-8238943](https://bugs.openjdk.java.net/browse/JDK-8238943): switch to jtreg 5.0
 * [JDK-8235866](https://bugs.openjdk.java.net/browse/JDK-8235866): bump jtreg requiredVersion to 4.2b16
 * [JDK-8219552](https://bugs.openjdk.java.net/browse/JDK-8219552): bump jtreg requiredVersion to b14 in test/jdk/sanity/client/
 * [JDK-8219417](https://bugs.openjdk.java.net/browse/JDK-8219417): bump jtreg requiredVersion to b14
 * [JDK-8236111](https://bugs.openjdk.java.net/browse/JDK-8236111): narrow allowSmartActionArgs disabling

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to 14cde8bee0c452102b7ed34fa00171a62ce78391
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to 14cde8bee0c452102b7ed34fa00171a62ce78391

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/103/head:pull/103` \
`$ git checkout pull/103`

Update a local copy of the PR: \
`$ git checkout pull/103` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/103/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 103`

View PR using the GUI difftool: \
`$ git pr show -t 103`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/103.diff">https://git.openjdk.java.net/jdk11u-dev/pull/103.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
CDSTestUtils.java needs a copyright update to 2020.
All the TEST.properties files have an extra newline at their ends.

**Comment by shipilev** [comment]
> CDSTestUtils.java needs a copyright update to 2020.

Right, fixed.

> All the TEST.properties files have an extra newline at their ends.

I don't follow. TEST.properties are from https://hg.openjdk.java.net/jdk/jdk/rev/1922c31f1dcc verbatim: two lines each.

**Review by RealCLanger — APPROVED** [review]

**Comment by RealCLanger** [comment]
/issue add 8246387, 8238943, 8235866, 8219552, 8219417, 8236111

**Comment by RealCLanger** [comment]
@shipilev, I eyeballed the bugs you mentioned and then tried to mark them as solved in this PR. Obviously I'm not allowed to... can you do it?

**Comment by shipilev** [comment]
/issue add 8246387, 8238943, 8235866, 8219552, 8219417, 8236111

**Comment by shipilev** [comment]
> @shipilev, I eyeballed the bugs you mentioned and then tried to mark them as solved in this PR. Obviously I'm not allowed to... can you do it?

Done. This would create the backport bugs for all of these, right? I thought we are going with a squashed commit to match only this `11.0.13-oracle`. But either way, this would be good to report as proper history too.

**Comment by RealCLanger** [comment]
> > @shipilev, I eyeballed the bugs you mentioned and then tried to mark them as solved in this PR. Obviously I'm not allowed to... can you do it?
> 
> Done. This would create the backport bugs for all of these, right? I thought we are going with a squashed commit to match only this `11.0.13-oracle`. But either way, this would be good to report as proper history too.

Yes, this creates backport bugs for all of them. Although it's a squashed commit, which is good here, I think it's helpful to keep the history. One could argue that e.g. https://bugs.openjdk.java.net/browse/JDK-8219417 isn't necessary since nothing of this change remains after the squash (maybe there are others with the same effect).

Do you want me to run this through SAP's nightlies once? But if you're confident you can integrate it right away. I leave it to you...

**Comment by shipilev** [comment]
> Do you want me to run this through SAP's nightlies once? But if you're confident you can integrate it right away. I leave it to you...

I am in no rush to integrate, and have limited capacity to handle follow-up issues, so the more pre-integration testing, the merrier. Thanks!

**Comment by RealCLanger** [comment]
> > Do you want me to run this through SAP's nightlies once? But if you're confident you can integrate it right away. I leave it to you...
> 
> Yes, please. I am in no rush to integrate, and have limited capacity to handle follow-up issues, so the more pre-integration testing, the merrier. Thanks!

Our testing went well. So 👍 from me.

**Comment by shipilev** [comment]
> Our testing went well. So  from me.

Thank you, I'll arrange the push shortly. I picked up GHA from master in hopes it would provide more coverage, but I think bootstrap JDK downloads have a checksum bug: https://github.com/shipilev/jdk11u-dev/actions/runs/1103985012

**Comment by shipilev** [comment]
GHA run is complete and green now: https://github.com/shipilev/jdk11u-dev/runs/3261042243 -- I'll integrate on Sunday night.

**Pull request closed without merging**
