### PR TITLE
8255239: The timezone of the hs_err_pid log file is corrupted in Japanese locale

### PR DESCRIPTION
**Pull request by yukikimmura**
This is a backport of JDK-8255239: The timezone of the hs_err_pid log file is corrupted in Japanese locale.
Original patch applies cleanly to 11u.

Testing: 
  build on Windows x86_64 and Linux x86_64
  tier1 on Windows x86_64 and Linux x86_64
  a specific test to confirm the fix in Japanese locale

Could you please review this PR?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8255239](https://bugs.openjdk.java.net/browse/JDK-8255239): The timezone of the hs_err_pid log file is corrupted in Japanese locale

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/824/head:pull/824` \
`$ git checkout pull/824`

Update a local copy of the PR: \
`$ git checkout pull/824` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/824/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 824`

View PR using the GUI difftool: \
`$ git pr show -t 824`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/824.diff">https://git.openjdk.java.net/jdk11u-dev/pull/824.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Thanks for addressing this issue! 
If this is actually clean, you did something wrong because skara should mark it as clean. And if so, no review is needed.  Please change the title to "Backport <hash of original commit>". This has the same effect as the commit message in Step 2 Option 3 in  https://wiki.openjdk.java.net/display/JDKUpdates/How+to+contribute+a+fix

**Comment by yukikimmura** [comment]
Thank you for your advice. 
I used Option 3 in Step 2.
This is my first contribution. 
I would appreciate it if you could give me some time to check the flow.

**Comment by GoeLin** [comment]
Hi, sure, take your time.
It needs to be the hash of the existing commit: b46d73bee808af7891b699df30a5a6dec3f5139f
(If there are several existing commits, e.g. for 19 and 17.0.3, you can choose either.)

**Pull request closed without merging**
