### PR TITLE
8272180: Upgrade JSZip from v3.6.0 to v3.7.1 

### PR DESCRIPTION
**Pull request by jmtd**
This is an implementation of the fix described in JDK-8272180, which was backported to 11.0.13-oracle but which does not have a public patch.

I took jszip 3.7.1 from GitHub. The archive I downloaded was from <https://github.com/Stuk/jszip/archive/refs/tags/v3.7.1.tar.gz> and I calculate the sha1 sum to be `c5ba7227f1db44a2bd8e30e0cf7edbaf53ef4387` (note: calculated locally, I haven't yet convinced GitHub to show me a checksum for that archive that I can compare).

`jszip.js` and `jszip.min.js` are straight copies of the corresponding files from the path `dist/` in the jszip archive.

`src/jdk.javadoc/share/legal/jszip.md` is a copy of `jszip-3.7.1/LICENSE.markdown` with the following modifications:
 *  added ## JSZip v3.7.1 markdown header
 *  changed markdown headings to match the levels in the openjdk copy of the license (I.e., switched underline-style level 2 headings to prefix-style level 3 headings)
 *  added backticks to indicate pre-formatted text

Note that this update to `jszip.md` also resolves JDK-8272828 (Add correct licenses to jszip.md) for which there is also no public patch. There is no clear description of what the problem was with the license before, but jszip is dual licensed  MIT and GPL3, and prior to this, the 11u copy of the license only included MIT. I've preserved both licenses in this patch.

Initial testing: in a pet project (https://github.com/jmtd/wadc), I ran javadoc and inspected the output. Javadoc command:

    $JAVA_HOME/bin/javadoc -cp src/main/java --add-modules java.desktop -verbose  -d . org.redmars.wadc

Prior to patch: jszip 3.2.1 is bundled
After patch: jszip 3.7.1 is bundled

I also checked that the functionality jszip supports (client-side searching for keywords) was working. I got the same results before and after patch: immediate keyword suggestion/completion as I typed into the search box. Attempting to follow any of the links resulted in a broken link for me, however, with an additional "undefined/" included in the URI (file:///home/jon/git/doom/wadc.tmp2/undefined/org/redmars/wadc/EngineConfigDialog.html). I don't know the cause of this yet, so I can't attribute it to a problem in jszip (and if there is one, it's there already.)

I await GHA tier1 testing after raising this PR. I'll also check now which other javadoc-related tests are worth trying.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8272180](https://bugs.openjdk.java.net/browse/JDK-8272180): Upgrade JSZip from v3.6.0 to v3.7.1 ⚠️ Issue is not open.
 * [JDK-8272828](https://bugs.openjdk.java.net/browse/JDK-8272828): Add correct licenses to jszip.md ⚠️ Issue is not open.

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/407/head:pull/407` \
`$ git checkout pull/407`

Update a local copy of the PR: \
`$ git checkout pull/407` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/407/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 407`

View PR using the GUI difftool: \
`$ git pr show -t 407`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/407.diff">https://git.openjdk.java.net/jdk11u-dev/pull/407.diff</a>

</details>

### CODE REVIEW

**Comment by jmtd** [comment]
I've rebase this PR on top of master since https://github.com/openjdk/jdk11u-dev/pull/439 was merged.

**Review by GoeLin — APPROVED** [review]
LGTM

After integrating, please add to "8272828 Add correct licenses to jszip.md" 
a link "backport" to the issue created during the integration.  Then that one is marked as backportet, too.

**Comment by jmtd** [comment]
@GoeLin wrote:
> LGTM

Thank you!

I've flagged https://bugs.openjdk.java.net/browse/JDK-8272180 "jdk11u-fix-request" and I would normally await
someone changing that to "yes" before I issued integrate.

> After integrating, please add to "8272828 Add correct licenses to jszip.md"
> a link "backport" to the issue created during the integration. Then that one is marked as backportet, too.

If I understand you correctly, once I issue integrate, the bots will raise a separate JBS bug, and it's that I should add as a Backport link to the original JBS bug?

Since this PR also resolves JDK-8272828 , I have to figure out how that can be indicated too. For jdk8u in this situation I've written an "RFA" mail to the dev list. Would that suffice do you think?

Thanks!

**Comment by RealCLanger** [comment]
> Since this PR also resolves JDK-8272828 , I have to figure out how that can be indicated too. For jdk8u in this situation I've written an "RFA" mail to the dev list. Would that suffice do you think?

@jmtd there's a more elegant way to accomplish that: just comment "/issue JDK-8272828" as per https://wiki.openjdk.java.net/display/SKARA/Pull+Request+Commands#PullRequestCommands-/issue. Then, when you integrate this one, both backports will be resolved.

**Pull request closed without merging**
