### PR TITLE
8322511: [11u] JfrCheckpointThreadClosure::do_thread crashes when fetching thread_id

### PR DESCRIPTION
**Pull request by jia-wei-tang**
Threads which are in the state of `is_attaching_via_jni` may have the NULL object as their `_threadObj` . 
So the JVM will crash when calling `JfrCheckpointThreadClosure::do_thread()`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8322511](https://bugs.openjdk.org/browse/JDK-8322511) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8322511](https://bugs.openjdk.org/browse/JDK-8322511): [11u] JfrCheckpointThreadClosure::do_thread crashes when fetching thread_id (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2413/head:pull/2413` \
`$ git checkout pull/2413`

Update a local copy of the PR: \
`$ git checkout pull/2413` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2413/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2413`

View PR using the GUI difftool: \
`$ git pr show -t 2413`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2413.diff">https://git.openjdk.org/jdk11u-dev/pull/2413.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2413#issuecomment-1906784007)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi,
is this an error in 11 only?
If so, explain why & where this was fixed in higher versions.
Else please close this PR, reopen it against repo jdk. Once it is submitted there, backport it to 21, 17 and 11.
See also https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

**Comment by jia-wei-tang** [comment]
@GoeLin This is an error in 17,11 and 8. 
1. In the newest JDK, commit [JDK-8276125 ](https://github.com/jia-wei-tang/jdk/commit/a885aab696777c99c8c4c5d9a46afc5fe0a4fe47)  has solved half of the problem. It prevents jvm from visiting the null object when getting thread_group_id. And this commit is a bug fix.
2. In 17, commit [JDK-8226511](https://github.com/jia-wei-tang/dragonwell17/commit/8addc1418acf6d0cbba7c56429a12be2e1ebf521) has solved the other part of the problem.  It prevents jvm from visiting the null object when getting thread_id. But this commit is a Sub-task, and I speculate that developers didn't notice that this place would cause a jvm crash at that time.
Thus, in 17, I need to port JDK-8276125. In 11 and 8, I need to combine both commits I mentioned above to fix this error. 
Since the newest JDK don't have this problem, I am wondering where to open this PR.

**Comment by jia-wei-tang** [comment]
@GoeLin I'm sorry to disturb you. I had signed the OCA three weeks ago and contacted the Oracle’s open-source administrators through email, but I don't get any reply. The OCA is still in the state "under review". What should I do?

**Comment by jia-wei-tang** [comment]
@GoeLin Hi, I has not been an author so I cannot use `/backport` to backport  JDK-8276125 from jdk to jdk17u-dev. I asked my colleague to do this for me. I read the description of JDK-8276125, I think the issue ([JDK-8322511](https://bugs.openjdk.org/browse/JDK-8322511))  is different from that even though they are similar. I hope that you could review my code and give me some suggestions if I need to make more changes. Thanks.

**Comment by jia-wei-tang** [comment]
@GoeLin  Hi, I made some changes to fix this bug. Combine this PR and  [BackPort 8276125](https://github.com/openjdk/jdk11u-dev/pull/2501) can fix the JVM crash.

Some details about how JVM visit the null object `_threadObj` as follows.
1. JNI call `AttachCurrentThread` 
2. JVM creates a JavaThread, which is set in the state of `is_attaching_via_jni`
3. `Threads::add` add this new JavaThread into ThreadList
4. The JavaThread continues to initialize and call `allocate_threadObj` to fill in `_threadObj`
However, Between 3-4 steps, a JFR safepoint operation is executing. It traverses the ThreadList and attempts to read the id of each thread. The id is gotten by using `_threadObj` as a base value and adding a offset. Thus, the JVM crash happens when read the illegal address.

**Comment by jia-wei-tang** [comment]
@phohensee @jerboaa Could you pls approve this [JDK-8322511](https://bugs.openjdk.org/browse/JDK-8322511) and review my codes? I showed the details about how JVM visit the null object `_threadObj` before and the change is harmless (only add the null condition check).

**Review by phohensee — APPROVED** [review]

**Comment by jia-wei-tang** [comment]
/approval request Fix JVM crash by adding a null condition check

**Comment by jia-wei-tang** [comment]
The results of related JFR testcases are all successful.
 
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/jdk/jfr                              434   434     0     0   
==============================
TEST SUCCESS

**Comment by GoeLin** [comment]
@jia-wei-tang, can you please add [11u] to the PR title as I did for the JBS issue?  Thanks!

**Comment by jia-wei-tang** [comment]
@GoeLin  I changed the title of the pr and triggered GHA tests. May you approve [JDK-8322511](https://bugs.openjdk.org/browse/JDK-8322511) ? Thanks a lot!

**Pull request closed without merging**
