### PR TITLE
8248876: LoadObject with bad base address created for exec file on linux

### PR DESCRIPTION
**Pull request by yukikimmura**
I would like to backport
8248876: LoadObject with bad base address created for exec file on linux.

The original patch does not apply cleanly to 11u.
In case of JDK17, the patch of 8248876 includes the code to invalidate the fix of 8248878.
But in case of JDK11, the fix of 8248878 has never been applied.
I remove the invalidation code of 8248878 from the original patch.

Testing: 
  build on Linux x86_64
  tier1 on Linux x86_64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8248876](https://bugs.openjdk.java.net/browse/JDK-8248876): LoadObject with bad base address created for exec file on linux

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/1014/head:pull/1014` \
`$ git checkout pull/1014`

Update a local copy of the PR: \
`$ git checkout pull/1014` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/1014/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1014`

View PR using the GUI difftool: \
`$ git pr show -t 1014`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/1014.diff">https://git.openjdk.java.net/jdk11u-dev/pull/1014.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
LGTM, but this PR is not recognized as backport. I suggest to change the title to "Backport <hash of the original commit>" and let the Skara Bot do the work.

**Comment by TheRealMDoerr** [comment]
Thanks! It's recognized as backport, now.
Please avoid editing Copyright messages for backports. They should be as clean as possible. The message from the original change should be used.
Other edits look good.
How did you test this PR?

**Review by TheRealMDoerr — APPROVED** [review]
Backport looks good. Please answer the questions https://bugs.openjdk.java.net/browse/JDK-8248876?focusedCommentId=14487656&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14487656

**Comment by yukikimmura** [comment]
Hi TheRealMDoerr,
I tested the fix by using the following command.
$ /work/jdk11u-dev/build/linux-x86_64-normal-server-release/images/jdk/bin/jhsdb jmap --exe /work/jdk11u-dev/build/linux-x86_64-normal-server-release/images/jdk/bin/java --core core.24581

Results after backporting the fix:
Attaching to core core.24581 from executable /work/jdk11u-dev/build/linux-x86_64-normal-server-release/images/jdk/bin/java, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 11.0.16-internal+0-adhoc.xxxx.jdk11u-dev
0x0000562009198000      12K     /work/jdk11u-dev/build/linux-x86_64-normal-server-release/images/jdk/bin/java

Results before backporting the fix:
null    12K     /work/jdk11u-dev/build/linux-x86_64-normal-server-release/images/jdk/bin/java

I will answer the question in https://bugs.openjdk.java.net/browse/JDK-8248876 later.

**Comment by yukikimmura** [comment]
/integrate
I would appliciate it if someone could sponsor the fix.

**Pull request closed without merging**
