### PR TITLE
8291713: assert(!phase->exceeding_node_budget()) failed: sanity after JDK-8223389

### PR DESCRIPTION
**Pull request by rwestrel**
This fixes an issue with the backport of
https://bugs.openjdk.org/browse/JDK-8223363:

https://github.com/openjdk/jdk11u/commit/5f40afc10909061b5b4e17ec59856611e160e474

where a line that should have been removed wasn't.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291713](https://bugs.openjdk.org/browse/JDK-8291713): assert(!phase->exceeding_node_budget()) failed: sanity after JDK-8223389

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Xin Liu](https://openjdk.org/census#xliu) (@navyxliu - no project role)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1335/head:pull/1335` \
`$ git checkout pull/1335`

Update a local copy of the PR: \
`$ git checkout pull/1335` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1335/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1335`

View PR using the GUI difftool: \
`$ git pr show -t 1335`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1335.diff">https://git.openjdk.org/jdk11u-dev/pull/1335.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Review by navyxliu — APPROVED** [review]
LGTM. I am not a reviewer. 

Double check that the original patch did replacement here. We introduced an side-effect (+=) when we backported it. the fix is correct. 

```
-  uint require_nodes(uint require) {
+  uint require_nodes(uint require, uint minreq = REQUIRE_MIN) {
     precond(require > 0);
-    _nodes_required += MAX2(100u, require); // Keep requests at minimum 100.
+    _nodes_required += MAX2(require, minreq);
     return _nodes_required;
   }
```

**Review by RealCLanger — APPROVED** [review]
Good catch.

**Pull request closed without merging**
