### PR TITLE
8276139: TestJpsHostName.java not reliable, better to expand HostIdentifierCreate.java test

### PR DESCRIPTION
**Pull request by DamonFool**
Hi all,

I'd like to backport this fix to jdk11u to improve the test stability.
This is a noreg test improvement, so no risk.

Only changes in test/jdk/sun/tools/jps/TestJpsHostName.java can't be applied cleanly.
But it doesn't matter since that file would be removed after this backport.
And the affected tests all passed on linux after this patch.

Thanks.
Best regards,
Jie

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276139](https://bugs.openjdk.java.net/browse/JDK-8276139): TestJpsHostName.java not reliable, better to expand HostIdentifierCreate.java test

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/643/head:pull/643` \
`$ git checkout pull/643`

Update a local copy of the PR: \
`$ git checkout pull/643` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/643/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 643`

View PR using the GUI difftool: \
`$ git pr show -t 643`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/643.diff">https://git.openjdk.java.net/jdk11u-dev/pull/643.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by DamonFool** [comment]
> Lgtm.

Thanks @phohensee for your review.
Let's wait for the jdk11u-fix-yes approval in the JBS.
Thanks.

**Comment by DamonFool** [comment]
Fix request had been approved.
So integrate it.
Thanks.

/integrate

**Pull request closed without merging**
