### PR TITLE
8237354: Add option to jcmd to write a gzipped heap dump

### PR DESCRIPTION
**Pull request by buddyliao**
Backport of the heap dump enhancement: Add option to jcmd to write a gzipped heap dump

Patch did not apply cleanly, I had to resolve/modify

1) src/hotspot/share/services/heapDumper.cpp
function "int dump(const char* path, bool overwrite = false)" has some different from the jdk-master, since patch 7cbb67a3f8adc83a5b51c092a66480d7b22a6bea is backport before this one, so this patch can't backport clearly

2) src/hotspot/share/services/heapDumperCompression.cpp
MonitorLockerEx is named MonitorLocker in jdk-master, MonitorLockerEx.wait should have parameters, the constructor of  MonitorLockerEx and MutexUnlockerEx also different from jdk-master

3) src/hotspot/share/services/heapDumperCompression.hpp
FileWriter is different from jdk-master since backport of 7cbb67a3f8adc83a5b51c092a66480d7b22a6bea before this patch.

I have built it on linux x86_64 and run test-tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8237354](https://bugs.openjdk.java.net/browse/JDK-8237354): Add option to jcmd to write a gzipped heap dump

### Reviewers
 * [Ralf Schmelter](https://openjdk.java.net/census#rschmelter) (@schmelter-sap - no project role)
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/209/head:pull/209` \
`$ git checkout pull/209`

Update a local copy of the PR: \
`$ git checkout pull/209` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/209/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 209`

View PR using the GUI difftool: \
`$ git pr show -t 209`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/209.diff">https://git.openjdk.java.net/jdk11u-dev/pull/209.diff</a>

</details>

### CODE REVIEW

**Comment by phohensee** [comment]
Can you elaborate on what you had to change in the modified files?

**Comment by buddyliao** [comment]
> Can you elaborate on what you had to change in the modified files?

Hi Paul, thank you for your kindly review, I had elaborate on the changes at the beginning of this issue.

**Comment by phohensee** [comment]
Thanks you for pointing that out. :) I was reading only the email.

**Review by phohensee — CHANGES_REQUESTED** [review]
If MonitorLockerEx.wait() needs parameters, why does the call to wait() in heapDumperCompression.cpp at line 258 lack one? The two other uses pass Mutex::_no_safepoint_check_flag, which seems the correct thing to do given that all three constructors are passed Mutex::_no_safepoint_check_flag.

**Review by phohensee — CHANGES_REQUESTED** [review]
I applied the patch and ran the serviceability/dcmd/gc tests with "make run-test". HeapDumpAllTest crashed due to the lack of the the line 258 change. Adding that cured that crash, but the new HeapDumpCompressedTest test failed due to lack of a backport of [JDK-8233790](https://bugs.openjdk.java.net/browse/JDK-8233790). 8233790 guarantees that the "Unable to create" string for which the test checks will be in the output file. That backport looks useful to me, so I'd do it as a pre-req to this one.

**Comment by buddyliao** [comment]
> I applied the patch and ran the serviceability/dcmd/gc tests with "make run-test". HeapDumpAllTest crashed due to the lack of the the line 258 change. Adding that cured that crash, but the new HeapDumpCompressedTest test failed due to lack of a backport of [JDK-8233790](https://bugs.openjdk.java.net/browse/JDK-8233790). 8233790 guarantees that the "Unable to create" string for which the test checks will be in the output file. That backport looks useful to me, so I'd do it as a pre-req to this one.

Hi Paul, thank you for pointing out the lack of line 258, I will fix it and update the patch. I know JDK-8233790 is a fix for the HeapDumpCompressedTest, I will backport it after this patch merge.

**Comment by buddyliao** [comment]
> If MonitorLockerEx.wait() needs parameters, why does the call to wait() in heapDumperCompression.cpp at line 258 lack one? The two other uses pass Mutex::_no_safepoint_check_flag, which seems the correct thing to do given that all three constructors are passed Mutex::_no_safepoint_check_flag.

Thank you for pointing out this, I have fixed it.

**Comment by phohensee** [comment]
I strongly recommend backporting JDK-8233790 first. The general update release rule is to backport dependencies first, then the dependent issue. It's easier to review that way. Also, I doubt the maintainers will approve a backport such as this one that breaks a test, even if the test is broken for only a short time. At a minimum, automated test systems will notice the failure and provoke work on the part of their owners.

**Comment by buddyliao** [comment]
> I strongly recommend backporting JDK-8233790 first. The general update release rule is to backport dependencies first, then the dependent issue. It's easier to review that way. Also, I doubt the maintainers will approve a backport such as this one that breaks a test, even if the test is broken for only a short time. At a minimum, automated test systems will notice the failure and provoke work on the part of their owners.



> I strongly recommend backporting JDK-8233790 first. The general update release rule is to backport dependencies first, then the dependent issue. It's easier to review that way. Also, I doubt the maintainers will approve a backport such as this one that breaks a test, even if the test is broken for only a short time. At a minimum, automated test systems will notice the failure and provoke work on the part of their owners.

Sounds reasonable, I will backport JDK-8233790 first. Thank you for your Suggestion.

**Comment by buddyliao** [comment]
> I strongly recommend backporting JDK-8233790 first. The general update release rule is to backport dependencies first, then the dependent issue. It's easier to review that way. Also, I doubt the maintainers will approve a backport such as this one that breaks a test, even if the test is broken for only a short time. At a minimum, automated test systems will notice the failure and provoke work on the part of their owners.

Sounds reasonable, I will backport JDK-8233790 first. Thank you for your Suggestion.

**Comment by buddyliao** [comment]
> I strongly recommend backporting JDK-8233790 first. The general update release rule is to backport dependencies first, then the dependent issue. It's easier to review that way. Also, I doubt the maintainers will approve a backport such as this one that breaks a test, even if the test is broken for only a short time. At a minimum, automated test systems will notice the failure and provoke work on the part of their owners.

Hi Paul, I have backported JDK-8233790  in https://github.com/openjdk/jdk11u-dev/pull/256, would you help me to review this patch first? Thank you.

**Comment by linzang** [comment]
I have helped to add "jdk11u-fix-request" label at https://bugs.openjdk.java.net/browse/JDK-8237354
Thanks!

**Comment by schmelter-sap** [comment]
Note that the ParallelScavengeHeap in JDK11 doesn't support the workers() method, since it doesn't uses a work gang. This means that the compression will not be done in parallel in this GC. This is probably not show stopper, but a regression from the behavior found in current JDKs.

**Review by schmelter-sap — APPROVED** [review]
The change looks good to me.

**Review by RealCLanger — APPROVED** [review]

**Pull request closed without merging**
