### PR TITLE
8301167: Update VerifySignedJar to actually exercise and test verification

### PR DESCRIPTION
**Pull request by amosshi**
- Backport [JDK-8301167](https://bugs.openjdk.org/browse/JDK-8301167)
  - Test succeeded in local dev box (MacOS M1)
- The patch applies clean, but the new code must be changed to Java 11 syntax
  - The commit [a56255f211ee8dd378ce40406491cffe799416bc](https://github.com/openjdk/jdk11u-dev/pull/2185/commits/a56255f211ee8dd378ce40406491cffe799416bc) is changing the code to Java 11 syntax

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8301167](https://bugs.openjdk.org/browse/JDK-8301167) needs maintainer approval

### Issue
 * [JDK-8301167](https://bugs.openjdk.org/browse/JDK-8301167): Update VerifySignedJar to actually exercise and test verification (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2185/head:pull/2185` \
`$ git checkout pull/2185`

Update a local copy of the PR: \
`$ git checkout pull/2185` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2185/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2185`

View PR using the GUI difftool: \
`$ git pr show -t 2185`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2185.diff">https://git.openjdk.org/jdk11u-dev/pull/2185.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2185#issuecomment-1763515742)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by amosshi** [comment]
/approval request "Backporting for parity with 11.0.21-oracle. No risk, test fix. Clean backport. Test passes and SAP nightlies pass.”

**Pull request closed without merging**
