### PR TITLE
Allow building with Clang 13

### PR DESCRIPTION
**Pull request by ReillyBrogan**
This patch backports changes from JDK14 commit ae5615c6142a4dc0d9033462f4880d7b3c127e26. It does not rename the class to markWord as the original patch does, but instead converts markOop to a markWord equivalent in-place. This patch allows the JDK to be built with Clang 13, as it avoids undefined behavior.

See the following for more information:

    https://bugs.openjdk.java.net/browse/JDK-8229258
    https://bugs.gentoo.org/817995
    https://mail.openjdk.java.net/pipermail/hotspot-dev/2019-July/038704.html
    https://mail.openjdk.java.net/pipermail/hotspot-dev/2019-July/038712.html
    https://reviews.llvm.org/D99790#2678384

This is a re-do of @Serebit's PR that erroneously targeted the jdk11u repository ([link](https://github.com/openjdk/jdk11u/pull/23)), the only difference is that some errors in the backport were corrected in the `shenandoahForwarding.inline.hpp` file to fix some compilation errors when compiling with `shenandoahgc` enabled.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1284/head:pull/1284` \
`$ git checkout pull/1284`

Update a local copy of the PR: \
`$ git checkout pull/1284` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1284/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1284`

View PR using the GUI difftool: \
`$ git pr show -t 1284`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1284.diff">https://git.openjdk.org/jdk11u-dev/pull/1284.diff</a>

</details>

### CODE REVIEW

**Comment by VVD** [comment]
Is this patch already merged?

**Comment by RealCLanger** [comment]
Hi,

that's quite a big patch. Can this be made smaller - if the purpose is only to make clang13 work?

Furthermore, as this is no full backport of JDK-8229258, I suggest to change the title into just "Allow building with Clang 13" for the time being. I think, if this is ever going to be reviewed and accepted, we'll need to open a specific JBS bug for this, targeting  JDK 11.

I'm also not sure where support for clang13 is needed in the OpenJDK so far. Usually, linux versions are built with gcc. clang is only used on MacOS and AIX but for these OS versions we're not yet at clang version 13, I believe.

Anyway, if it fixes UB and XCode will go to clang13 soon, a fix for this issue might be needed sooner or later.

Another hint/requirement: Please enable GitHub Actions on your repository so as to have some basic tier1 acceptance testing for the PR.

Cheers
Christoph

**Comment by ReillyBrogan** [comment]
> that's quite a big patch. Can this be made smaller - if the purpose is only to make clang13 work?

Renaming the `markOopDesc` class to `markOop` could be reverted which would reduce the diff down to ~58 changed files. Beyond that I'm not sure which changes could be dropped while still fixing the issue.

> Furthermore, as this is no full backport of JDK-8229258, I suggest to change the title into just "Allow building with Clang 13" for the time being. I think, if this is ever going to be reviewed and accepted, we'll need to open a specific JBS bug for this, targeting JDK 11.

I'll rename it. Not sure if I have the ability to create a JBS account, I did the password reset but didn't receive an email.

> I'm also not sure where support for clang13 is needed in the OpenJDK so far. Usually, linux versions are built with gcc. clang is only used on MacOS and AIX but for these OS versions we're not yet at clang version 13, I believe.

A few Linux distributions have switched to building with Clang because the end result is significantly smaller package sizes. FreeBSD also builds with clang and had to pin to clang12. 

> Another hint/requirement: Please enable GitHub Actions on your repository so as to have some basic tier1 acceptance testing for the PR.
Will do!

**Comment by RealCLanger** [comment]
> > that's quite a big patch. Can this be made smaller - if the purpose is only to make clang13 work?
> 
> Renaming the `markOopDesc` class to `markOop` could be reverted which would reduce the diff down to ~58 changed files. Beyond that I'm not sure which changes could be dropped while still fixing the issue.

I think it would be a good start.

> > Furthermore, as this is no full backport of JDK-8229258, I suggest to change the title into just "Allow building with Clang 13" for the time being. I think, if this is ever going to be reviewed and accepted, we'll need to open a specific JBS bug for this, targeting JDK 11.
> 
> I'll rename it. Not sure if I have the ability to create a JBS account, I did the password reset but didn't receive an email.

If you aren't in the OpenJDK Census, you won't get an account, unless you have made some 3 commits to the OpenJDK. However, I can create a JBS issue for you.

> > Another hint/requirement: Please enable GitHub Actions on your repository so as to have some basic tier1 acceptance testing for the PR.
> > Will do!

Great. And we already see build failures 😉

**Comment by RealCLanger** [comment]
The more I look at this, I think we should strive for a clean & full backport of https://bugs.openjdk.java.net/browse/JDK-8229258 if this is required to enable clang13 compilation.

**Comment by ReillyBrogan** [comment]
> The more I look at this, I think we should strive for a clean & full backport of https://bugs.openjdk.java.net/browse/JDK-8229258 if this is required to enable clang13 compilation.

Yes, I agree. I was going to suggest that myself but I'm temporarily without reliable internet so I haven't been able to work on this for a while.

**Comment by DingliZhang** [comment]
Hi @ReillyBrogan,
Do you have any updates? Thanks a lot.

**Comment by VVD** [comment]
OpenJDK 11 build and work fine with LLVM 18 on FreeBSD 14.1 amd64.

**Comment by ReillyBrogan** [comment]
> Hi @ReillyBrogan, Do you have any updates? Thanks a lot.

We use this patch on Solus with LLVM 18 and it works fine (with https://github.com/getsolus/packages/blob/main/packages/o/openjdk-11/files/0001-ftbfs-llvm-17.patch). Gtest and tier1 jtreg tests pass, and we haven't had any user reports of issues with it.

I don't really have the time or the inclination to work on this currently. It would probably take a openjdk maintainer to really carry this forward, and I imagine they won't do so since forward LLVM compatibility isn't a guarantee.

> OpenJDK 11 build and work fine with LLVM 18 on FreeBSD 14.1 amd64.

Note that FreeBSD uses forks of the JDK projects with additional patches for various LLVM and FreeBSD issues. Their approach to fixing this issue is to disable inlining for the variable, but I couldn't get that to work without test failures.

**Comment by DingliZhang** [comment]
@VVD @RealCLanger 
Thanks for your information! Do you have plans to create a new PR to jdk11u-dev?

**Pull request closed without merging**
