### PR TITLE
8267042: bug in monitor locking/unlocking on ARM32 C1 due to uninitialized BasicObjectLock::_displaced_header

### PR DESCRIPTION
**Pull request by chrishcole**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8267042](https://bugs.openjdk.java.net/browse/JDK-8267042): bug in monitor locking/unlocking on ARM32 C1 due to uninitialized BasicObjectLock::_displaced_header

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/129/head:pull/129` \
`$ git checkout pull/129`

Update a local copy of the PR: \
`$ git checkout pull/129` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/129/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 129`

View PR using the GUI difftool: \
`$ git pr show -t 129`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/129.diff">https://git.openjdk.java.net/jdk11u-dev/pull/129.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
I've requested backport approval in the JBS issue. It can get integrated once OCA is verified and the backport approved.

**Comment by chrishcole** [comment]
@TheRealMDoerr great thanks for the information and help. 

My company Sage Embedded Software LLC has signed the OCA, if there is any additional information required let me know.

I have tested this change by running the JCK with ARM32 build (without this fix a get a couple test cases that hang). I have also verified that included jtreg test case passes for x86, aarch64 and arm32 builds of jdk11. 

I just remembered that in jdk11 there is the non-default --with-cpu-port=arm64 that is also impacted by this bug and would require additional changes to the "#ifdef AARCH64" blocks of the changed lines of code. I tried building --with-cpu-port=arm64 and it is very broken by various commits over the last few years. So I assume this port has been abandoned and not supported for jdk11 any more. So I will not worry about these extra changes. The default "aarch64" and non-ARM ports are NOT impacted by this issue, but the arm32 port is.

Thanks again,
Chris Cole
Sage Embedded Software LLC

**Pull request closed without merging**
