### PR TITLE
8216137: assert(Compile::current()->live_nodes() < Compile::current()->max_node_limit()) failed: Live Node limit exceeded limit

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Backport of [JDK-8216137](https://bugs.openjdk.java.net/browse/JDK-8216137) (including [JDK-8219520](https://bugs.openjdk.java.net/browse/JDK-8219520) as in original commit)
loopTransform.cpp (introduction of `AutoNodeBudget`) and loopnode.hpp required manual integration. Rest applies cleanly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8216137](https://bugs.openjdk.java.net/browse/JDK-8216137): assert(Compile::current()->live_nodes() < Compile::current()->max_node_limit()) failed: Live Node limit exceeded limit

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/868/head:pull/868` \
`$ git checkout pull/868`

Update a local copy of the PR: \
`$ git checkout pull/868` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/868/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 868`

View PR using the GUI difftool: \
`$ git pr show -t 868`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/868.diff">https://git.openjdk.java.net/jdk11u-dev/pull/868.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
Skara reports this as integration blocker: Title mismatch between PR and JBS for issue [JDK-8219520](https://bugs.openjdk.java.net/browse/JDK-8219520). Fix:
/issue remove JDK-8219520

**Review by GoeLin — APPROVED** [review]
LGTM

**Comment by GoeLin** [comment]
Pre-submit failures: dependencies missing.

**Comment by TheRealMDoerr** [comment]
Thanks for the review and the approval!
/integrate

**Pull request closed without merging**
