### PR TITLE
8280684: JfrRecorderService failes with guarantee(num_written > 0) when no space left on device.

### PR DESCRIPTION
**Pull request by jbachorik**
Backport

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8280684](https://bugs.openjdk.java.net/browse/JDK-8280684): JfrRecorderService failes with guarantee(num_written > 0) when no space left on device.

### Reviewers
 * [Vladimir Kempik](https://openjdk.java.net/census#vkempik) (@VladimirKempik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/1044/head:pull/1044` \
`$ git checkout pull/1044`

Update a local copy of the PR: \
`$ git checkout pull/1044` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/1044/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1044`

View PR using the GUI difftool: \
`$ git pr show -t 1044`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/1044.diff">https://git.openjdk.java.net/jdk11u-dev/pull/1044.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
I removed jdk11u-fix-request from JBS issue for the time being. Please restore once the PR has been reviewed. Please also enable GHA for this. Thx.

**Comment by jbachorik** [comment]
Ok, I enabled the GHA for the PR source repo and now all the checks have passed.

Let's wait for some reviews then - the backport itself is pretty straight-forward with only minor merge conflicts in copyright, type cast and nullptr vs. NULL.

**Comment by jbachorik** [comment]
A gentle ping?

**Review by VladimirKempik — APPROVED** [review]
The backport looks good and almost a clean backport of original

**Pull request closed without merging**
