### PR TITLE
8274338: com/sun/jdi/RedefineCrossEvent.java failed "assert(m != __null) failed: NULL mirror"

### PR DESCRIPTION
**Pull request by zhengyu123**
Backport for parity with Oracle 11.0.15.

The original patch applies cleanly, but some of CDS tests fail due to following new assertion in `ClassLoaderData::loaded_classes_do()`

`  // To call this, one must have the MultiArray_lock held, but the _klasses list still has lock free reads.
  assert_locked_or_safepoint(MultiArray_lock);
`
The solution is to take `MultiArray_lock` in `MetaspaceShared::link_and_cleanup_shared_classes()` method

Test:
- [x]  tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274338](https://bugs.openjdk.java.net/browse/JDK-8274338): com/sun/jdi/RedefineCrossEvent.java failed "assert(m != __null) failed: NULL mirror"

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/584/head:pull/584` \
`$ git checkout pull/584`

Update a local copy of the PR: \
`$ git checkout pull/584` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/584/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 584`

View PR using the GUI difftool: \
`$ git pr show -t 584`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/584.diff">https://git.openjdk.java.net/jdk11u-dev/pull/584.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
I'd add the comment from JvmtiGetLoadedClasses::getLoadedClasses() before the added MultiArray_lock in metaspaceShared.cpp, vis

    // To get a consistent list of classes we need MultiArray_lock to ensure
    // array classes aren't created.

Otherwise, lgtm.

**Comment by zhengyu123** [comment]
> I'd add the comment from JvmtiGetLoadedClasses::getLoadedClasses() before the added MultiArray_lock in metaspaceShared.cpp, vis
> 
> ```
> // To get a consistent list of classes we need MultiArray_lock to ensure
> // array classes aren't created.
> ```
> 
> Otherwise, lgtm.

Thanks for the review, @phohensee . Added comment as you suggested

**Review by phohensee — APPROVED** [review]
Thanks, Zhengyu. Lgtm.

**Comment by zhengyu123** [comment]
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [jdk-updates-dev](mailto:jdk-updates-dev@mail.openjdk.java.net):_
> 
> On 9/11/2021 10:50 pm, Lindenmaier, Goetz wrote:
> 
> > Hi Zhengyu,
> > Since this change has been pushed, we see four test crashing in our CI,
> > see below.  Do you have an idea what is wrong with these?
> 
> From JBS:
> 
> "The original patch applies cleanly, but needs to take additional MultiArray_lock on CDS path to get it work correctly. "
> 
> but that additional change is broken as you can't hold the lock on that path due to the linking that can occur which requires a call up to Java which can't be done when holding the mutex. I don't know why Zhengyu thought that was neccessary.
> 
> David -----

Hi David,

Sorry, I did not see your comment until now.

Adding MultiArray_lock on CDS path, as stated in comment, was to workaround the new assertion in ClassLoaderData::loaded_classes_do() in following code:

`void MetaspaceShared::link_and_cleanup_shared_classes(TRAPS) {`
`  // We need to iterate because verification may cause additional classes`
`  // to be loaded.`
` LinkSharedClassesClosure link_closure(THREAD);`
 `do {`
 `  link_closure.reset();`
 `   ClassLoaderDataGraph::loaded_classes_do(&link_closure);`
 `   guarantee(!HAS_PENDING_EXCEPTION, "exception in link_class");`
 ` } while (link_closure.made_progress());`

Should this backport drop the new assertion in `ClassLoaderData::loaded_classes_do()`?

Thanks,

-Zhengyu

**Pull request closed without merging**
