### PR TITLE
8334332: TestIOException.java fails if run by root

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [472b935b](https://github.com/openjdk/jdk/commit/472b935b442f7f925b665c7de91eda77f3dcbe8b) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by SendaoYan on 18 Jun 2024 and was reviewed by Pavel Rappo.

The reason of backport is not clean is that, multiple PRs have been merged into the `jdk17u-dev` of this file, including `JDK-8215516`, `JDK-8164597`, etc., and these PRs cannot be directly backported to `jdk11u-dev`.

This PR also change `test/langtools/TEST.ROOT`, it's partial backport of [JDK-8242652](https://bugs.openjdk.org/browse/JDK-8242652). [JDK-8242652](https://bugs.openjdk.org/browse/JDK-8242652) can't backport to jdk11u-dev, the jdk11u-dev repo dosen't have file `test/langtools/jdk/javadoc/doclet/testSearchScript/TestSearchScript.java`.

Only change test testcase, the risk is quite very low.

The change verified on below env:

- [x] linux non-root user
- [x] linix root user
- [x] windows

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8334332](https://bugs.openjdk.org/browse/JDK-8334332) needs maintainer approval

### Issue
 * [JDK-8334332](https://bugs.openjdk.org/browse/JDK-8334332): TestIOException.java fails if run by root (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2795/head:pull/2795` \
`$ git checkout pull/2795`

Update a local copy of the PR: \
`$ git checkout pull/2795` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2795/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2795`

View PR using the GUI difftool: \
`$ git pr show -t 2795`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2795.diff">https://git.openjdk.org/jdk11u-dev/pull/2795.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2795#issuecomment-2176410977)
</details>

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Clean backport of JDK-8334332, make the testcase more robustness, almost no risk.

**Comment by sendaoYan** [comment]
Thanks for the approved.

**Comment by sendaoYan** [comment]
Hi, can anyone take a look this backport.

**Comment by sendaoYan** [comment]
Hi, can anyone take a look this backport.

**Comment by sendaoYan** [comment]
Hi, can anyone take a look this PR.

**Review by phohensee — APPROVED** [review]

**Comment by sendaoYan** [comment]
Thanks for the review and approval.

/integrate

**Comment by sendaoYan** [comment]
Thanks for the sponsor.

**Pull request closed without merging**
