### PR TITLE
8306133: Open source few AWT Drag & Drop related tests

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 11.0.21-oracle.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8306133](https://bugs.openjdk.org/browse/JDK-8306133): Open source few AWT Drag &amp; Drop related tests (**Bug** - P4)
 * [JDK-8307135](https://bugs.openjdk.org/browse/JDK-8307135): java/awt/dnd/NotReallySerializableTest/NotReallySerializableTest.java failed (**Bug** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2076/head:pull/2076` \
`$ git checkout pull/2076`

Update a local copy of the PR: \
`$ git checkout pull/2076` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2076/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2076`

View PR using the GUI difftool: \
`$ git pr show -t 2076`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2076.diff">https://git.openjdk.org/jdk11u-dev/pull/2076.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2076#issuecomment-1676882967)

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
Relative to the 17u backport, NotReallySerializableTest.java is missing "@key headfull". Otherwise good.

**Comment by luchenlin** [comment]
> Relative to the 17u backport, NotReallySerializableTest.java is missing "@key headfull". Otherwise good.

hi, NotReallySerializableTest.java has "@key headfull" backport from JDK-8307135

**Review by phohensee — APPROVED** [review]
:)

**Pull request closed without merging**
