### PR TITLE
8308884: [17u/11u] Backout JDK-8297951

### PR DESCRIPTION
**Pull request by jerboaa**
Please review this backout patch for JDK-8297951 which got included in 11.0.19 release and causes crashes. The patch is the result of `git revert de8c37acea0d74524f4f735fef8b03e71a64589f`.

Testing:
- [x] Reproducer from [JDK-8307683](https://bugs.openjdk.org/browse/JDK-8307683) crashes the VM before the patch and the crash is gone after.
- [ ] GHA (still running)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8308884](https://bugs.openjdk.org/browse/JDK-8308884): [17u/11u] Backout JDK-8297951

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1915/head:pull/1915` \
`$ git checkout pull/1915`

Update a local copy of the PR: \
`$ git checkout pull/1915` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1915/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1915`

View PR using the GUI difftool: \
`$ git pr show -t 1915`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1915.diff">https://git.openjdk.org/jdk11u-dev/pull/1915.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1915#issuecomment-1568678707)

### CODE REVIEW

**Comment by jerboaa** [comment]
/summary This reverts commit de8c37acea0d74524f4f735fef8b03e71a64589f

**Comment by GoeLin** [comment]
Hi @jerboaa, I approved it, please integrate. Our CI pulls soon what I will tag. It starts at 18:00, but first does jdk, jdk17 etc.

**Comment by jerboaa** [comment]
> Hi @jerboaa, I approved it, please integrate. Our CI pulls soon what I will tag. It starts at 18:00, but first does pull jdk, jdk17 etc.

OK, integrated.

**Pull request closed without merging**
