### PR TITLE
6849922: java/awt/Choice/ChoiceKeyEventReaction/ChoiceKeyEventReaction.html fails

### PR DESCRIPTION
**Pull request by jmtd**
Backport of [JDK-6849922](https://bugs.openjdk.java.net/browse/JDK-6849922) for jdk11u
Does not apply clean, RFR will be required (ProblemList.txt)
Pre-requisite for [JDK-8214469](https://bugs.openjdk.java.net/browse/JDK-8214469)

Test-only changes, awaiting tier1 test results regardless

Note: the test modified by this patch does *not* pass after applying it, at least on macos -- it does once JDK-8214469 is applied too (that comes next)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-6849922](https://bugs.openjdk.java.net/browse/JDK-6849922): java/awt/Choice/ChoiceKeyEventReaction/ChoiceKeyEventReaction.html fails

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/351/head:pull/351` \
`$ git checkout pull/351`

Update a local copy of the PR: \
`$ git checkout pull/351` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/351/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 351`

View PR using the GUI difftool: \
`$ git pr show -t 351`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/351.diff">https://git.openjdk.java.net/jdk11u-dev/pull/351.diff</a>

</details>

### CODE REVIEW

**Comment by jmtd** [comment]
Test ChoiceKeyEventReaction(.java) passes for me on x86_64 (without also backporting 8214469, which is required to pass on macos)

**Comment by RealCLanger** [comment]
Oh, you have beaten me by a few hours. I also started doing this backport (https://github.com/realclanger/jdk11u-dev/tree/RealCLanger-backport-1b012e21). 😆 

Again, please rename this PR to "Backport 1b012e213d31b184236a56121f7f1548d1a6fe05" to make the bots correctly recognize it as a backport.

Furthermore, please enable Github Actions here: https://github.com/jmtd/jdk11u-dev/actions because this will give us more confidence.

And last but not least, I ran the test on Windows and it passes.

**Comment by jmtd** [comment]
> Oh, you have beaten me by a few hours. I also started doing this backport (https://github.com/realclanger/jdk11u-dev/tree/RealCLanger-backport-1b012e21).  😆 

Oh I'm sorry, I hate it when this happens to me! for 8u, we have/had a convention of labelling issues in JBS with `jdk8u-<username>` to signify "I am working on this". Is there any similar convention for 11u?

**Pull request closed without merging**
