### PR TITLE
8251570: JDK-8215624 causes assert(worker_id < _n_workers) failed: Invalid worker_id

### PR DESCRIPTION
**Pull request by buddyliao**
This patch is backport based on https://github.com/openjdk/jdk11u-dev/pull/127

I have built it on linux x86_64 and run test-tier1 successfully

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8251570](https://bugs.openjdk.java.net/browse/JDK-8251570): JDK-8215624 causes assert(worker_id < _n_workers) failed: Invalid worker_id

### Reviewers
 * [Ralf Schmelter](https://openjdk.java.net/census#rschmelter) (@schmelter-sap - no project role)
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/284/head:pull/284` \
`$ git checkout pull/284`

Update a local copy of the PR: \
`$ git checkout pull/284` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/284/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 284`

View PR using the GUI difftool: \
`$ git pr show -t 284`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/284.diff">https://git.openjdk.java.net/jdk11u-dev/pull/284.diff</a>

</details>

### CODE REVIEW

**Review by schmelter-sap — APPROVED** [review]
The changes look good to me. Thanks.

**Review by RealCLanger — APPROVED** [review]

**Comment by RealCLanger** [comment]
@buddyliao, please type /integrate again and I can sponsor this.
PS: For the future: Before integrating a PR, please make sure it has the appropriate jdk11u-fix-yes label in JBS, even though it was already reviewed.

**Comment by buddyliao** [comment]
> @buddyliao, please type /integrate again and I can sponsor this.
> PS: For the future: Before integrating a PR, please make sure it has the appropriate jdk11u-fix-yes label in JBS, even though it was already reviewed.

Thank you , I will remember this in the feature.

**Pull request closed without merging**
