### PR TITLE
8219475: javap man page needs to be updated

### PR DESCRIPTION
**Pull request by shruacha1234**
OpenJDK commit https://github.com/openjdk/jdk/commit/9d7777e58540777c8837c16dcae5a0457bbcce2e

OpenJDK bug https://bugs.openjdk.org/browse/JDK-8219475

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8219475](https://bugs.openjdk.org/browse/JDK-8219475) needs maintainer approval

### Issue
 * [JDK-8219475](https://bugs.openjdk.org/browse/JDK-8219475): javap man page needs to be updated (**Bug** - P3 - Approved)

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2186/head:pull/2186` \
`$ git checkout pull/2186`

Update a local copy of the PR: \
`$ git checkout pull/2186` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2186/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2186`

View PR using the GUI difftool: \
`$ git pr show -t 2186`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2186.diff">https://git.openjdk.org/jdk11u-dev/pull/2186.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2186#issuecomment-1763780474)

### CODE REVIEW

**Comment by shruacha1234** [comment]
Hi @RealCLanger 
Can you please review this PR

**Review by RealCLanger — APPROVED** [review]
Looks good to me.

**Comment by shruacha1234** [comment]
/approval request The src/jdk.jdeps/share/classes/com/sun/tools/javap/resources/javap.properties file has a duplicate key-value pair 
```
main.usage.summary=\
Usage: {0} <options> <classes>\n\
use --help for a list of possible options. 
```
As part of this PR duplicate key-value pair is removed.
It was a clean backport. There was no merge conflicts seen

**Pull request closed without merging**
