### PR TITLE
8283803: Remove jtreg tag manual=yesno for java/awt/print/PrinterJob/PrintGlyphVectorTest.java and fix test

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 11.0.17-oracle.

Clean backport from 17. 17 includes a test infra file needed for the backport.
I had to adapt a string literal in PrintGlyphVectorTest to make it compile with 11.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8283803](https://bugs.openjdk.org/browse/JDK-8283803): Remove jtreg tag manual=yesno for java/awt/print/PrinterJob/PrintGlyphVectorTest.java and fix test
 * [JDK-8284898](https://bugs.openjdk.org/browse/JDK-8284898): Enhance PassFailJFrame

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [b8d7bba9](https://git.openjdk.org/jdk11u-dev/pull/1295/files/b8d7bba914ea99c0f5085f4ecc3c982ed2313172)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1295/head:pull/1295` \
`$ git checkout pull/1295`

Update a local copy of the PR: \
`$ git checkout pull/1295` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1295/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1295`

View PR using the GUI difftool: \
`$ git pr show -t 1295`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1295.diff">https://git.openjdk.org/jdk11u-dev/pull/1295.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — COMMENTED** [review]
I'm confused here.

The original patch contains the file test/jdk/java/awt/regtesthelpers/PassFailJFrame.java which is missing from this patch.

**Comment by GoeLin** [comment]
Sorry, I just forgot to git add the file.  Fixed. t is unchanged from 17.

**Comment by tstuefe** [comment]
> Sorry, I just forgot to git add the file. Fixed. t is unchanged from 17.

No problem. I thought you wanted to test me. :-)

**Review by tstuefe — APPROVED** [review]
LGTM

**Pull request closed without merging**
