### PR TITLE
8285867: Convert applet manual tests SelectionVisible.java to Frame and automate

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8285867](https://bugs.openjdk.org/browse/JDK-8285867)

Clean Backport: git apply succeeded, no manual edit, although the bot did not add the `clean` label somehow

Tests
- Test Succeeded in local Dev Apple M1 Laptop
- PR - All checks have passed
- SAP nightlies passed on `2023-12-23,24`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8285867](https://bugs.openjdk.org/browse/JDK-8285867) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285867](https://bugs.openjdk.org/browse/JDK-8285867): Convert applet manual tests SelectionVisible.java to Frame and automate (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2360/head:pull/2360` \
`$ git checkout pull/2360`

Update a local copy of the PR: \
`$ git checkout pull/2360` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2360/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2360`

View PR using the GUI difftool: \
`$ git pr show -t 2360`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2360.diff">https://git.openjdk.org/jdk11u-dev/pull/2360.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2360#issuecomment-1853207125)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean backort. SAP nightlies passed on 2023-12-14”

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean backport. SAP nightlies passed on 2023-12-19”

**Review by TheRealMDoerr — CHANGES_REQUESTED** [review]
Your PR only makes the html files empty, but doesn't delete them.

**Comment by amosshi** [comment]
> Your PR only makes the html files empty, but doesn't delete them.

Amazing review.
Just deleted them in the 2nd commit.

**Review by TheRealMDoerr — APPROVED** [review]
It's clean, now.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean backport. SAP nightlies passed on 2023-12-23”

**Pull request closed without merging**
