### PR TITLE
8248500: AArch64: Remove the r18 dependency on Windows AArch64

### PR DESCRIPTION
**Pull request by lewurm**
The ABI for AArch64 reserves r18 as a platform register [1]. Linux doesn't make use of it, thus it's available as an additional callee-saved register. This is not the case for Windows and macOS, therefore we have to make HotSpot aware of that.

[1] https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#61machine-registers

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8248500](https://bugs.openjdk.java.net/browse/JDK-8248500): AArch64: Remove the r18 dependency on Windows AArch64 ⚠️ Issue is not open.

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)

### Contributors
 * Monica Beckwith `<mbeckwit@openjdk.org>`
 * Ludovic Henry `<luhenry@openjdk.org>`
 * Reka Kovacs `<rkovacs@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/567/head:pull/567` \
`$ git checkout pull/567`

Update a local copy of the PR: \
`$ git checkout pull/567` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/567/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 567`

View PR using the GUI difftool: \
`$ git pr show -t 567`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/567.diff">https://git.openjdk.java.net/jdk11u-dev/pull/567.diff</a>

</details>

### CODE REVIEW

**Review by theRealAph — APPROVED** [review]
Thank you very much for doing this.

**Comment by lewurm** [comment]
Thanks for the review @theRealAph

**Comment by lewurm** [comment]
@theRealAph would you mind sponsoring it? 🙂  Thank you!

**Comment by theRealAph** [comment]
> @theRealAph would you mind sponsoring it? slightly_smiling_face Thank you!

Go to https://bugs.openjdk.java.net/browse/JDK-8248500 and tag it `jdk11u-fix-request`.

**Comment by lewurm** [comment]
> > @theRealAph would you mind sponsoring it? slightly_smiling_face Thank you!
> 
> Go to https://bugs.openjdk.java.net/browse/JDK-8248500 and tag it `jdk11u-fix-request`.

Ahh, sorry I missed that step. Done now.

**Comment by GoeLin** [comment]
Hi,
you should also add a comment why you downport this in the JBS bug.
There you also should assess the risk of this downport.
Best, Goetz.

**Comment by lewurm** [comment]
Thank you @GoeLin! Sorry for being sloppy with the process on JBS.

**Comment by RealCLanger** [comment]
@lewurm, just a small hint: I see that Github Actions is not enabled on your repository, so we don't see additional checks in the PR. For the future you should consider turning it on here: https://github.com/lewurm/jdk11u-dev/actions 😄

**Comment by RealCLanger** [comment]
I can sponsor this one. I have, however, added it to our nightly test queue since there's no testing evidence. If we don't see problems I'll sponsor it after Friday's nightlies (was too late for tonight).

**Comment by VladimirKempik** [comment]
We also have tested this patch(taken out of jep-388 backport to jdk11u) with zulu11 on macos-aarch64 about a month ago and found no regressions in linux/macos aarch64 builds

**Comment by lewurm** [comment]
Thank you @RealCLanger for additional testing and sponsoring this change.

**Comment by theRealAph** [comment]
> Thank you @RealCLanger for additional testing and sponsoring this change.

Thank you for doing it, and thanks to everyone who helped.

**Pull request closed without merging**
