### PR TITLE
8255264: Support for identifying the full range of IPv4 localhost addresses on Windows

### PR DESCRIPTION
**Pull request by macarte**
Backport of JDK-8255264

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8255264](https://bugs.openjdk.java.net/browse/JDK-8255264): Support for identifying the full range of IPv4 localhost addresses on Windows

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/627/head:pull/627` \
`$ git checkout pull/627`

Update a local copy of the PR: \
`$ git checkout pull/627` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/627/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 627`

View PR using the GUI difftool: \
`$ git pr show -t 627`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/627.diff">https://git.openjdk.java.net/jdk11u-dev/pull/627.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
Same here... after you've rebased #626 correctly, rebase this PR's source branch to the source branch of #626. Then we should only see one commit in this PR and everything will look good.

**Comment by macarte** [comment]
right, have to wait for https://github.com/openjdk/jdk11u-dev/pull/626 to be commited first

**Pull request closed without merging**
