### PR TITLE
8266461: tools/jmod/hashes/HashesTest.java fails: static @Test methods

### PR DESCRIPTION
**Pull request by gdams**
Backport required to bump JDK11u to jtreg 6

`test/jdk/tools/jmod/hashes/HashesTest.java`
- several occurrences of `ht.checkHashes("j2", Set.of("j3"));` (in jdk) not matching up with `ht.checkHashes("j2", "j3");` in jdk11u.
- [`testHashModulesPattern`](https://github.com/openjdk/jdk/commit/e90388bc1e7bba92675fa799d9da77aa4d6e1a05#diff-90d72039e87e2a26eb11bd8e15e499aa96eef5372361fb1a47eec0d5ab168f5aR322) does not exist in jdk11u so I removed it from the patch.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8266461](https://bugs.openjdk.org/browse/JDK-8266461): tools/jmod/hashes/HashesTest.java fails: static @Test methods
 * [JDK-8267180](https://bugs.openjdk.org/browse/JDK-8267180): Typo in copyright header  for HashesTest

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1252/head:pull/1252` \
`$ git checkout pull/1252`

Update a local copy of the PR: \
`$ git checkout pull/1252` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1252/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1252`

View PR using the GUI difftool: \
`$ git pr show -t 1252`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1252.diff">https://git.openjdk.org/jdk11u-dev/pull/1252.diff</a>

</details>

### CODE REVIEW

**Comment by gdams** [comment]
@GoeLin please can you review and then I'll kick off the integration

**Comment by GoeLin** [comment]
I had the patch in our nightly build.  The test is still failing.

/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:130: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("m2", "m1");
                          ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:134: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("m2", "m1");
                          ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:141: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("m2", "m1");
                          ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:142: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("m3", "m1");
                          ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:149: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("org.bar", "org.foo");
                               ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:152: error: method checkHashes in class HashesTest cannot be applied to given types;
        checkHashes("m3", "org.foo", "org.bar", "m1");
        ^
  required: String,Set<String>
  found: String,String,String,String
  reason: actual and formal argument lists differ in length
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:188: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("y1", "y2");
                          ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:189: error: method checkHashes in class HashesTest cannot be applied to given types;
        checkHashes("z1", "z2", "z3", "y2");
        ^
  required: String,Set<String>
  found: String,String,String,String
  reason: actual and formal argument lists differ in length
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:230: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("j2", "j3");
                          ^
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:231: error: method checkHashes in class HashesTest cannot be applied to given types;
        checkHashes("j1", "m1", "m2", "m3", "j3");
        ^
  required: String,Set<String>
  found: String,String,String,String,String
  reason: actual and formal argument lists differ in length
/System/Volumes/Data/priv/jvmtests/output_openjdk11_dev_dbgU_darwinintel64/grmpf/testdata/jtreg/jtreg_test_11/test/jdk/tools/jmod/hashes/HashesTest.java:304: error: incompatible types: String cannot be converted to Set<String>
        checkHashes("m1", "m2");

**Comment by gdams** [comment]
@GoeLin thags interesting to know. Let me take another look at the patch

**Comment by gdams** [comment]
@GoeLin I've pushed up a commit to align the patch better with upstream but I'm still seeing one test failure:

```output
test HashesTest.testReproducibibleHash(): failure
java.lang.AssertionError: Maps do not match for key:m2 actual:jdk.internal.module.ModuleHashes@115b3f30 expected:jdk.internal.module.ModuleHashes@405f34b
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.assertEquals(Assert.java:1458)
	at org.testng.Assert.assertEquals(Assert.java:1412)
	at HashesTest.testReproducibibleHash(HashesTest.java:297)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Any ideas?

**Comment by RealCLanger** [comment]
I'm looking into the HashesTest and see if I can figure out something. BTW, when backporting this change you should either backport https://bugs.openjdk.org/browse/JDK-8266461 right thereafter or maybe even include the typo fix and add JDK-8266461 to this PR via the /issue command.

**Comment by gdams** [comment]
Ignore my comments. Just tested with 11.0.16 and it works just fine:

```
➜  jdk11u-dev git:(hashes) ✗ java -version
openjdk version "11.0.16-beta" 2022-07-19
OpenJDK Runtime Environment Temurin-11.0.16+7-202207191813 (build 11.0.16-beta+7-202207191813)
OpenJDK 64-Bit Server VM Temurin-11.0.16+7-202207191813 (build 11.0.16-beta+7-202207191813, mixed mode)
➜  jdk11u-dev git:(hashes) ✗ jtreg test/jdk/tools/jmod/hashes/HashesTest.java                    
Test results: passed: 1
Report written to /Users/gadams/jdk11u-dev/JTreport/html/report.html
Results written to /Users/gadams/jdk11u-dev/JTwork
```

**Review by RealCLanger — APPROVED** [review]
Thumbs up. Backport looks good and test passed my local testing on both, Linux and Mac.

**Comment by RealCLanger** [comment]
Passed SAP's nightlies.

/sponsor

**Pull request closed without merging**
