### PR TITLE
8321925: sun/security/mscapi/KeytoolChangeAlias.java fails with "Alias <246810> does not exist"

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi, 

Backport of [JDK-8321925](https://bugs.openjdk.org/browse/JDK-8321925). 

The origin PR use `int nextInt(int origin, int bound)` [link](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/random/RandomGenerator.html#nextInt(int,int)) , but the jdk11 do not have this API. So I change `int nextInt(int origin, int bound)` to `nextInt(bound - origin) + origin` [link](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Random.html#nextInt(int)).

Only change the testcase, the change has been verified, the risk is low.

image

Thanks,
-sendao

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8321925](https://bugs.openjdk.org/browse/JDK-8321925) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8321925](https://bugs.openjdk.org/browse/JDK-8321925): sun/security/mscapi/KeytoolChangeAlias.java fails with "Alias &lt;246810&gt; does not exist" (**Bug** - P3 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2631/head:pull/2631` \
`$ git checkout pull/2631`

Update a local copy of the PR: \
`$ git checkout pull/2631` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2631/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2631`

View PR using the GUI difftool: \
`$ git pr show -t 2631`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2631.diff">https://git.openjdk.org/jdk11u-dev/pull/2631.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2631#issuecomment-2024344980)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Clean backport of [JDK-8321925](https://bugs.openjdk.org/browse/JDK-8321925). Only change the testcase, the change has been verified, the risk is low.

**Comment by sendaoYan** [comment]
> @sendaoYan This pull request has been inactive for more than 4 weeks and will be automatically closed if another 4 weeks passes without any activity. To avoid this, simply add a new comment to the pull request. Feel free to ask for assistance if you need help with progressing this pull request towards integration!

Hi, can anyone review this PR. thanks.

Backport of [JDK-8321925](https://bugs.openjdk.org/browse/JDK-8321925). Only change the testcase, the change has been verified, the risk is low.

**Comment by sendaoYan** [comment]
Hi, can anyone review this PR. thanks.

Backport of [JDK-8321925](https://bugs.openjdk.org/browse/JDK-8321925). Only change the testcase, the change has been verified, the risk is low.

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by sendaoYan** [comment]
> LGTM.

Thanks for the review.

**Comment by sendaoYan** [comment]
> /sponsor

Thanks.

**Pull request closed without merging**
