### PR TITLE
8280155: [PPC64, s390] frame size checks are not yet correct

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Backport of JDK-8280155. Applies cleanly except Copyright update.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280155](https://bugs.openjdk.java.net/browse/JDK-8280155): [PPC64, s390] frame size checks are not yet correct

### Reviewers
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - Committer) ⚠️ Review applies to 56431a96f00f27fd7f8e810af6c7c4d2cc0b909a

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/797/head:pull/797` \
`$ git checkout pull/797`

Update a local copy of the PR: \
`$ git checkout pull/797` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/797/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 797`

View PR using the GUI difftool: \
`$ git pr show -t 797`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/797.diff">https://git.openjdk.java.net/jdk11u-dev/pull/797.diff</a>

</details>

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
The changes look good to me. 
Please note that I'm not a idk-updates reviewer.

**Comment by TheRealMDoerr** [comment]
Still clean except Copyright.
/integrate

**Pull request closed without merging**
