### PR TITLE
8302161: Upgrade jQuery UI to version 1.13.2

### PR DESCRIPTION
**Pull request by Nagata-Haruhito**
I want to backport JDK-8302161 for jdk11u.
This is clean backport.
Also, this backport contains JDK-8293180.

All jdk/javadoc tests are passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8302161](https://bugs.openjdk.org/browse/JDK-8302161): Upgrade jQuery UI to version 1.13.2 (**Task** - P4)
 * [JDK-8293180](https://bugs.openjdk.org/browse/JDK-8293180): JQuery UI license file not updated (**Bug** - P3)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2064/head:pull/2064` \
`$ git checkout pull/2064`

Update a local copy of the PR: \
`$ git checkout pull/2064` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2064/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2064`

View PR using the GUI difftool: \
`$ git pr show -t 2064`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2064.diff">https://git.openjdk.org/jdk11u-dev/pull/2064.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2064#issuecomment-1665032850)

### CODE REVIEW

**Comment by Nagata-Haruhito** [comment]
Would someone review this fix?

**Review by phohensee — APPROVED** [review]
Backport from 17u appears clean.

**Comment by GoeLin** [comment]
Hi [Nagata-Haruhito](https://github.com/Nagata-Haruhito)
For next time: If you backport starting out with the change in 17 and using the hash of the push there in the commit message, such backports often are clean.  This saves work for the reviewer and increases trust in the change.
Best, Goetz.

**Comment by Nagata-Haruhito** [comment]
Thanks for your advice.

**Pull request closed without merging**
