### PR TITLE
8320597: RSA signature verification fails on signed data that does not encode params correctly

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Almost clean backport from [JDK17 PR](https://github.com/openjdk/jdk17u-dev/pull/2052)
The only difference is a string concatenation in the test

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320597](https://bugs.openjdk.org/browse/JDK-8320597) needs maintainer approval

### Issue
 * [JDK-8320597](https://bugs.openjdk.org/browse/JDK-8320597): RSA signature verification fails on signed data that does not encode params correctly (**Bug** - P3 - Approved)

### Reviewers
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2384/head:pull/2384` \
`$ git checkout pull/2384`

Update a local copy of the PR: \
`$ git checkout pull/2384` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2384/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2384`

View PR using the GUI difftool: \
`$ git pr show -t 2384`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2384.diff">https://git.openjdk.org/jdk11u-dev/pull/2384.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2384#issuecomment-1854957662)

### CODE REVIEW

**Comment by jerboaa** [comment]
@alexeybakhtin Please update the patch. It currently shows changes from #2383 as well.

**Comment by martinuy** [comment]
Thanks @alexeybakhtin for proposing this backport. The commit specific to 8317547 looks good to me. I'll approve after the rebase.

The Skara bot does not like it but in my view a rebase is cleaner than a merge:

```
git switch JDK-8320597
git fetch upstream master
git rebase upstream/master
git push --force-with-lease
```

**Comment by alexeybakhtin** [comment]
> @alexeybakhtin Please update the patch. It currently shows changes from #2383 as well.

Thank you. I've fixed the conflicts

**Comment by alexeybakhtin** [comment]
Reverted copyright date in RSAPadding.java Looks like a merge issue

**Review by martinuy — APPROVED** [review]
Looks good to me. Thanks.-

**Pull request closed without merging**
