### PR TITLE
5029431: (bf) Add absolute bulk put and get methods

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-5029431](https://bugs.openjdk.org/browse/JDK-5029431)
- This PR contains two commits
- commit 1: is a clean result of git apply
- commit 2: is a manual merge of `Basic.java`, the only change is adding`5029431` to `@bug` section 
  - Content of `test/jdk/java/nio/Buffer/Basic.java.rej` as bellow
  - It shows the only differences in the `.rej` file bellow is adding `5029431`

```diff
@@ -24,9 +24,9 @@
 /* @test
  * @summary Unit test for buffers
  * @bug 4413135 4414911 4416536 4416562 4418782 4471053 4472779 4490253 4523725
- *      4526177 4463011 4660660 4661219 4663521 4782970 4804304 4938424 6231529
- *      6221101 6234263 6535542 6591971 6593946 6795561 7190219 7199551 8065556
- *      8149469
+ *      4526177 4463011 4660660 4661219 4663521 4782970 4804304 4938424 5029431
+ *      6231529 6221101 6234263 6535542 6591971 6593946 6795561 7190219 7199551
+ *      8065556 8149469
  * @modules java.base/java.nio:open
  *          java.base/jdk.internal.misc
  * @author Mark Reinhold
``` 

Testing
- Local: Test passed on `MaOS 14.4.1`
  - `test/jdk/java/nio/Buffer/`: Test results: passed: 11
- Pipeline: All checks have passed
- Testing Machine: SAP nightlies passed on 2024-04-27
  - Automated jtreg test: jtreg_jdk_tier1
  - java/nio/Buffer/AllocateDirectInit.java: SUCCESSFUL GitHub 📊⏲ - [147 msec]
  - java/nio/Buffer/Basic.java: SUCCESSFUL GitHub 📊⏲ - [5,440 msec]
  - java/nio/Buffer/ByteBufferViews.java: SUCCESSFUL GitHub 📊⏲ - [5,916 msec]
  - java/nio/Buffer/CharAt.java: SUCCESSFUL GitHub 📊⏲ - [145 msec]
  - java/nio/Buffer/Chars.java: SUCCESSFUL GitHub 📊⏲ - [3,025 msec]
  - java/nio/Buffer/Chew.java: SUCCESSFUL GitHub 📊⏲ - [1,582 msec]
  - java/nio/Buffer/CopyDirectMemory.java: SUCCESSFUL GitHub 📊⏲ - [2,040 msec]
  - java/nio/Buffer/DirectBufferAllocTest.java: SUCCESSFUL GitHub 📊⏲ - [9,170 msec]
  - java/nio/Buffer/EqualsCompareTest.java: SUCCESSFUL GitHub 📊⏲ - [18,275 msec]
  - java/nio/Buffer/LimitDirectMemory.java: SUCCESSFUL GitHub 📊⏲ - [16,471 msec]
  - java/nio/Buffer/LimitDirectMemoryNegativeTest.java: SUCCESSFUL GitHub 📊⏲ - [1,437 msec]
  - java/nio/Buffer/Order.java: SUCCESSFUL GitHub 📊⏲ - [506 msec]
  - java/nio/Buffer/StringCharBufferSliceTest.java: SUCCESSFUL GitHub 📊⏲ - [232 msec]

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] [JDK-5029431](https://bugs.openjdk.org/browse/JDK-5029431) needs maintainer approval
- [x] Commit message must refer to an issue
- [ ] Change requires a CSR request matching fixVersion 11.0.24 to be approved (needs to be created)

### Issue
 * [JDK-5029431](https://bugs.openjdk.org/browse/JDK-5029431): (bf) Add absolute bulk put and get methods (**Enhancement** - P3 - Rejected)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2685/head:pull/2685` \
`$ git checkout pull/2685`

Update a local copy of the PR: \
`$ git checkout pull/2685` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2685/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2685`

View PR using the GUI difftool: \
`$ git pr show -t 2685`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2685.diff">https://git.openjdk.org/jdk11u-dev/pull/2685.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2685#issuecomment-2079939412)

### CODE REVIEW

**Comment by AlanBateman** [comment]
Adding standard APIs to Java 11 would require a Maintenance Release of JSR 384. Did you mean to backport a change that adds new APIs?

**Comment by amosshi** [comment]
Hi @AlanBateman, Cc. @GoeLin, here is the full story: 

- when we are trying to back port [JDK-8326643](https://bugs.openjdk.org/browse/JDK-8326643) to `jdk11u-dev`, compile errors are occurred:

```
----------System.err:(130/10006)----------
github.com/dev-8326643-11/test/jdk/javax/net/ssl/TLSv13/EngineOutOfSeqCCS.java:56: error: SSLEngineTemplate() has private access in SSLEngineTemplate
        super();
        ^
github.com/dev-8326643-11/test/jdk/javax/net/ssl/TLSv13/EngineOutOfSeqCCS.java:68: error: cannot find symbol
                sslParams.setNamedGroups(new String[] {"secp384r1"});
                         ^
  symbol:   method setNamedGroups(String[])
  location: variable sslParams of type SSLParameters
...
...
39 errors
result: Failed. Compilation failed: Compilation failed
```

- It turns out we need to back port [JDK-5029431](https://bugs.openjdk.org/browse/JDK-5029431) and [JDK-5071718](https://bugs.openjdk.org/browse/JDK-5071718) to fix this compile error for `JDK-8326643`

While current `JDK-5029431` PR adding standard API.

**Comment by jerboaa** [comment]
@amosshi The test needs to get reworked without using the new API introduced in JDK 13. Backporting [JDK-5029431](https://bugs.openjdk.org/browse/JDK-5029431) is not suitable for JDK 11. Let alone for fixing a compilation error in a test of an unrelated bug.

**Comment by amosshi** [comment]
Close this PR, because we all agreed now the API should not be changed. Cancel the backport of [JDK-5029431](https://bugs.openjdk.org/browse/JDK-5029431)

**Pull request closed without merging**
