### PR TITLE
8065704: Set LC_ALL=C for all relevant commands in the build system

### PR DESCRIPTION
**Pull request by VladimirKempik**
Please review this backport to jdk11u-dev.
This is needed to fix JDK-8278762 which was introduced by backport of JDK-8267246.
It will set LC_ALL=C for all cases now and make result to be 6.25 (instead of 6,25) always, not depending on user's locale setting.
The backport wasn't clean, 3 pieces of compare.sh patch weren't needed and small context code difference in other two chunks.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8065704](https://bugs.openjdk.java.net/browse/JDK-8065704): Set LC_ALL=C for all relevant commands in the build system

### Reviewers
 * [Jie Fu](https://openjdk.java.net/census#jiefu) (@DamonFool - no project role)
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/717/head:pull/717` \
`$ git checkout pull/717`

Update a local copy of the PR: \
`$ git checkout pull/717` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/717/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 717`

View PR using the GUI difftool: \
`$ git pr show -t 717`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/717.diff">https://git.openjdk.java.net/jdk11u-dev/pull/717.diff</a>

</details>

### CODE REVIEW

**Review by DamonFool — APPROVED** [review]
LGTM

Thanks for fixing this.

**Comment by VladimirKempik** [comment]
Can I have one more review (from reviewer) on this please ?

**Review by phohensee — APPROVED** [review]
Lgtm.

**Pull request closed without merging**
