### PR TITLE
8314263: Signed jars triggering Logger finder recursion and StackOverflowError

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 11.0.22-oracle.

test/jdk/java/lang/System/LoggerFinder/RecursiveLoading/PlatformRecursiveLoadingTest.java
test/jdk/java/lang/System/LoggerFinder/RecursiveLoading/RecursiveLoadingTest.java
"SimpleLogRecord" is modified due to "Record" is not supported in jdk11

test/jdk/java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java
test/jdk/java/lang/System/LoggerFinder/SignedLoggerFinderTest/SimpleLoggerFinder.java
"long sleep = new Random().nextLong(1000L) + 1L;" is modified due to not supported in jdk11

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8314263](https://bugs.openjdk.org/browse/JDK-8314263) needs maintainer approval
- [x] [JDK-8316087](https://bugs.openjdk.org/browse/JDK-8316087) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315696](https://bugs.openjdk.org/browse/JDK-8315696) needs maintainer approval

### Issues
 * [JDK-8314263](https://bugs.openjdk.org/browse/JDK-8314263): Signed jars triggering Logger finder recursion and StackOverflowError (**Bug** - P2 - Approved)
 * [JDK-8315696](https://bugs.openjdk.org/browse/JDK-8315696): SignedLoggerFinderTest.java test failed (**Bug** - P3 - Approved)
 * [JDK-8316087](https://bugs.openjdk.org/browse/JDK-8316087): Test SignedLoggerFinderTest.java is still failing (**Bug** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2223/head:pull/2223` \
`$ git checkout pull/2223`

Update a local copy of the PR: \
`$ git checkout pull/2223` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2223/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2223`

View PR using the GUI difftool: \
`$ git pr show -t 2223`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2223.diff">https://git.openjdk.org/jdk11u-dev/pull/2223.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2223#issuecomment-1782405229)

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
Changes look good.

**Comment by GoeLin** [comment]
approve yes all

**Pull request closed without merging**
