### PR TITLE
8221351: Crash in KlassFactory::check_shared_class_file_load_hook

### PR DESCRIPTION
**Pull request by caojoshua**
This fixes a crash in JDK 11.

Merge conflicts are mostly trivial. We can keep hunks from both HEAD and the backport. There is one merge conflict in licensing.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8221351](https://bugs.openjdk.org/browse/JDK-8221351): Crash in KlassFactory::check_shared_class_file_load_hook

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [666c4eca](https://git.openjdk.org/jdk11u-dev/pull/1604/files/666c4eca67978bc1f42dea197ff3e07c0d0f0c67)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1604/head:pull/1604` \
`$ git checkout pull/1604`

Update a local copy of the PR: \
`$ git checkout pull/1604` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1604/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1604`

View PR using the GUI difftool: \
`$ git pr show -t 1604`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1604.diff">https://git.openjdk.org/jdk11u-dev/pull/1604.diff</a>

</details>

### CODE REVIEW

**Comment by caojoshua** [comment]
I entered in the wrong commit ID the first time. I just edited the PR title, but not sure if the bots will fix things.

**Comment by caojoshua** [comment]
looks like the bot is smart! the PR info looks correct now

**Comment by RealCLanger** [comment]
Looks good but you should resolve the copyright in test/hotspot/jtreg/runtime/appcds/customLoader/HelloCustom.java to 2019.

**Comment by GoeLin** [comment]
Hi, 
your change is not ready to be flagged -fix-request. 
Please follow https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

**Review by RealCLanger — APPROVED** [review]

**Comment by phohensee** [comment]
The [JDK-8221621](https://bugs.openjdk.org/browse/JDK-8221621) backport https://github.com/openjdk/jdk11u-dev/pull/1603 is prerequisite for this one and is clean and trivial, so I've tagged it.

This PR has been reviewed by @RealCLanger. We can wait for [JDK-8221621](https://bugs.openjdk.org/browse/JDK-8221621)  approval before tagging [JDK-8221351](https://bugs.openjdk.org/browse/JDK-8221351).

**Comment by GoeLin** [comment]
Hi,
I will not approve prerequisites if their only purpose is being preparation for another change as long as I did not decide to approve the other change.  So I need the fix request for this here along with a good reason to backport it.
Thanks.

**Comment by phohensee** [comment]
We believe the [JDK-8221621](https://bugs.openjdk.org/browse/JDK-8221621) backport to be useful in it's own right since it fixes a build error. I've updated that fix request comment to reflect that.

**Comment by phohensee** [comment]
This backport fixes a crash we've seen in production.

**Comment by caojoshua** [comment]
Can pass the included test locally. Tier1 test suite is passing, except for some langtool/javadoc errors, which I believe are unrelated. We have confirmed that this patch fixes the crash we have seen in production.

**Comment by GoeLin** [comment]
This is a big change for backporting to an old release as 11. Tier1 tests are the bare minimum, they run in the Pre-submit tests anyways.  I hope that you confiming the patch is working means you have run some substatntial tests with it in your production or pre-production landscapes. 
I ran the test through our testing, which means all tier1-4 and JCK tests on 7 platforms plus a row of benchmarks and SAP applications.
Approving.

**Comment by caojoshua** [comment]
Hi @GoeLin . We ran the test through tier1-2 and JCK on many platforms. For production services, we have only tested on the service that has been seeing this issue.

We plan to release this patch in our January JDK release. We will do significantly more testing a week before the release. If it feels safer, I can wait to merge this patch after our users use the new JDK release for 2 weeks and we don't see issues.

**Comment by GoeLin** [comment]
Yes, that's good if you deliver it in January. That leaves enough time for follow up fixes.  So go ahead and push it.

**Pull request closed without merging**
