### PR TITLE
8284536: [11, AIX] Build fails on AIX due to gensrc issues

### PR DESCRIPTION
**Pull request by backwaterred**
#993 

This PR restores build-ability to AIX. This description will be updated, and a JBS issue will be linked shortly.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8284536](https://bugs.openjdk.java.net/browse/JDK-8284536): [11, AIX] Build fails on AIX due to gensrc issues

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/1000/head:pull/1000` \
`$ git checkout pull/1000`

Update a local copy of the PR: \
`$ git checkout pull/1000` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/1000/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1000`

View PR using the GUI difftool: \
`$ git pr show -t 1000`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/1000.diff">https://git.openjdk.java.net/jdk11u-dev/pull/1000.diff</a>

</details>

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
It should be understood why this is needed in 11u, but not in later JDK releases (e.g. 17u  make/modules/java.base/gensrc/GensrcMisc.gmk). Also, my 11.0.16 build works without it.

**Comment by takiguc** [comment]
Hello @backwaterred .
Is this the last patch for XL C++ 16.1 support ?

**Comment by backwaterred** [comment]
@takiguc I may end up closing this PR. I initially thought it was required to build jdk11 with the new compiler, but that seems to be related to some peculiarity of my build & test system.

I suggest #999, but that too may require modifications to work well with the older compiler. Sorry for the long-winded answer. I had to put this on hold for a bit while I address another issue. I should be back to it next week.

**Comment by backwaterred** [comment]
This change is no longer required

**Pull request closed without merging**
