### PR TITLE
8180573: Refactor sun/security/tools shell tests to plain java tests

### PR DESCRIPTION
**Pull request by RealCLanger**
Backport of JDK-8180573: Refactor sun/security/tools shell tests to plain java tests

Applies mostly clean, deletion of a few files had to be done manually. Then I had to resolve the testlibrary in two places and add a a few tweaks to a few tests that came later with some CPU fixes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8180573](https://bugs.openjdk.java.net/browse/JDK-8180573): Refactor sun/security/tools shell tests to plain java tests

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to af3177ee9fa00f68a502f93dbbedcde69328adb9

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/415/head:pull/415` \
`$ git checkout pull/415`

Update a local copy of the PR: \
`$ git checkout pull/415` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/415/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 415`

View PR using the GUI difftool: \
`$ git pr show -t 415`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/415.diff">https://git.openjdk.java.net/jdk11u-dev/pull/415.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by RealCLanger** [comment]
@GoeLin @TheRealMDoerr This one is passing SAP regression tests now...

**Review by TheRealMDoerr — APPROVED** [review]
Thumbs up!

**Pull request closed without merging**
