### PR TITLE
8272700: [macos] Build failure with Xcode 13.0 after JDK-8264848

### PR DESCRIPTION
**Pull request by DamonFool**
Backport of 8272700: [macos] Build failure with Xcode 13.0 after JDK-8264848

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8272700](https://bugs.openjdk.java.net/browse/JDK-8272700): [macos] Build failure with Xcode 13.0 after JDK-8264848

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/282/head:pull/282` \
`$ git checkout pull/282`

Update a local copy of the PR: \
`$ git checkout pull/282` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/282/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 282`

View PR using the GUI difftool: \
`$ git pr show -t 282`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/282.diff">https://git.openjdk.java.net/jdk11u-dev/pull/282.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
@DamonFool, can you please run GHA on this commit (e.g. enable it on your fork and rebase this PR to current master branch)? Thanks

**Comment by DamonFool** [comment]
> @DamonFool, can you please run GHA on this commit (e.g. enable it on your fork and rebase this PR to current master branch)? Thanks

Testing is now in progress.
Thanks.

**Comment by DamonFool** [comment]
Backport has been approved.
/integrate

**Comment by DamonFool** [comment]
> /sponsor

Thanks @RealCLanger for your sponsor.

**Pull request closed without merging**
