### PR TITLE
8303466: C2: failed: malformed control flow. Limit type made precise with MaxL/MinL

### PR DESCRIPTION
**Pull request by martinuy**
Hi,

I would like to propose a backport of 8303466 [1] to jdk11u. jdk11u can benefit from this fix and having more accurate limit type information.

The jdk17u patch does not apply cleanly because of the following:

 * src/hotspot/share/opto/addnode.hpp
   * 11u does not have 8223347. Manually backported the MaxLNode/MinLNode class.

 * src/hotspot/share/opto/macro.cpp
   * The 11u backport of 8275330 does not add n->Opcode() == Op_Opaque4 to the assertion. Manually applied the change.

 * src/hotspot/share/opto/convertnode.cpp
   * 11u does not have 8256730 so the context is different. Manually applied the change.

 * src/hotspot/share/opto/loopTransform.cpp
   * 11u does not have 8301074 (replace of NULL with nullptr) so the change does not apply cleanly. Manually applied the change.
   * 11u does not have 8273115, so the context is different.
   * The 11u backport of 8262017 has "set_subtree_ctrl(inner_result_long);" instead of "set_subtree_ctrl(inner_result_long, false);" so the context is different.

In addition, the following changes were made:

 * C++11 lambda functions is_clamp and is_sub_con replaced with static equivalents.

 * nullptr replaced with NULL

No regressions observed in hotspot:tier1.

Thanks,
Martin.-

--
[1] - https://bugs.openjdk.org/browse/JDK-8303466

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8303466](https://bugs.openjdk.org/browse/JDK-8303466) needs maintainer approval

### Issue
 * [JDK-8303466](https://bugs.openjdk.org/browse/JDK-8303466): C2: failed: malformed control flow. Limit type made precise with MaxL/MinL (**Bug** - P3 - Approved)

### Reviewers
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2814/head:pull/2814` \
`$ git checkout pull/2814`

Update a local copy of the PR: \
`$ git checkout pull/2814` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2814/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2814`

View PR using the GUI difftool: \
`$ git pr show -t 2814`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2814.diff">https://git.openjdk.org/jdk11u-dev/pull/2814.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2814#issuecomment-2189259099)

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by martinuy** [comment]
The GHA windows-aarch64 failure at build time seems unrelated to this backport. It's a failure in wget that we also observed in Fedora 40 for some URLs.

**Comment by martinuy** [comment]
/approval request jdk11u is affected by this bug and would benefit from its fix. The patch does not apply cleanly but has been reviewed.

**Pull request closed without merging**
