### PR TITLE
8299254: Support dealing with standard assert macro

### PR DESCRIPTION
**Pull request by elifaslan1**
Not a clean backport of  [c61bd4e1d5e58a0129c7](https://git.openjdk.org/jdk/commit/3e2314d08218dc8a4f4fc61bd4e1d5e58a0129c7) .
Context and whitespace conflicts only, plus shenandoah gc tests don't exist in 11u.
Resolved JBS issue is [JDK-8299254](https://bugs.openjdk.org/browse/JDK-8299254)

GHA tested.
Tier1/tier2 and jck tests passed on windows, linux

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8299254](https://bugs.openjdk.org/browse/JDK-8299254) needs maintainer approval

### Issue
 * [JDK-8299254](https://bugs.openjdk.org/browse/JDK-8299254): Support dealing with standard assert macro (**Enhancement** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2239/head:pull/2239` \
`$ git checkout pull/2239`

Update a local copy of the PR: \
`$ git checkout pull/2239` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2239/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2239`

View PR using the GUI difftool: \
`$ git pr show -t 2239`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2239.diff">https://git.openjdk.org/jdk11u-dev/pull/2239.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2239#issuecomment-1785525262)

### CODE REVIEW

**Comment by GoeLin** [comment]
@elifaslan1
Please only label if the review is done. Also be more elaborate with the fix request comment.

**Review by phohensee — APPROVED** [review]
Please include the reasons for unclean backports. In this case, context and whitespace conflicts only, plus shenandoah gc tests don't exist in 11u.

**Comment by phohensee** [comment]
Please also do the 17u backport.

**Comment by elifaslan1** [comment]
https://github.com/openjdk/jdk17u-dev/pull/1940

**Comment by elifaslan1** [comment]
/approval request Second request to get fix request label added to the JBS issue

**Comment by elifaslan1** [comment]
/approval request Not a clean backport. Changes are context and whitespace conflicts, additionally shenandoah gc tests don't exist in 11u. GHA tested plus Tier1/tier2 and jck tests passed

**Comment by tstuefe** [comment]
Curious, why is this downported?

**Pull request closed without merging**
