### PR TITLE
8207214: Broken links in JDK API serialized-form page

### PR DESCRIPTION
**Pull request by shruacha1234**
OpenJDK commit https://github.com/openjdk/jdk/commit/955ce37d602d9456f5b665d0ccd90d51a6fe4637

OpenJDK issue https://bugs.openjdk.org/browse/JDK-8207214

---------
### Progress
- [x] [JDK-8207214](https://bugs.openjdk.org/browse/JDK-8207214) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8207214](https://bugs.openjdk.org/browse/JDK-8207214): Broken links in JDK API serialized-form page (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2187/head:pull/2187` \
`$ git checkout pull/2187`

Update a local copy of the PR: \
`$ git checkout pull/2187` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2187/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2187`

View PR using the GUI difftool: \
`$ git pr show -t 2187`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2187.diff">https://git.openjdk.org/jdk11u-dev/pull/2187.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2187#issuecomment-1763795116)

### CODE REVIEW

**Comment by shruacha1234** [comment]
Hi @RealCLanger
Can you please review this PR

**Comment by RealCLanger** [comment]
> [shruacha1234](/shruacha1234)

Applies clean, no review necessary. I'll run the PR through our internal testing, though. Did you run test TestSerializedFormWithSee.java and verify that it doesn't fail?

You'll then need to apply for maintainer approval.

**Comment by shruacha1234** [comment]
> Applies clean, no review necessary. I'll run the PR through our internal testing, though. Did you run test TestSerializedFormWithSee.java and verify that it doesn't fail?

Hi @RealCLanger 
I ran the TestSerializedFormWithSee.java test against this fix and it is passing

```
../JTreg/jtreg_6+1/bin/jtreg -jdk:/home/shruthi1/jdk11u-dev/build/linux-x86_64-normal-server-release/jdk ./test/langtools/jdk/javadoc/doclet/testSerializedFormWithSee/TestSerializedFormWithSee.java
Directory "JTwork" not found: creating
Directory "JTreport" not found: creating
Test results: passed: 1
Report written to /home/shruthi1/jdk11u-dev/JTreport/html/report.html
Results written to /home/shruthi1/jdk11u-dev/JTwork

**Comment by shruacha1234** [comment]
@RealCLanger Shall I apply for maintainer approval?

**Comment by RealCLanger** [comment]
> @RealCLanger Shall I apply for maintainer approval?

Yes, please.

**Comment by shruacha1234** [comment]
/approval request The src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/resources/doclets.properties file has a duplicate key-value pair

`doclet.Class=Class`

As part of this PR, the duplicate key-value pair is removed.
It was a clean backport. There were no merge conflicts seen. Validated with TestSerializedFormWithSee.java test case.

**Pull request closed without merging**
