### PR TITLE
8248001: javadoc generates invalid HTML pages whose ftp:// links are broken

### PR DESCRIPTION
**Pull request by ktakakuri**
I would like to backport
8248001: javadoc generates invalid HTML pages whose ftp:// links are broken.
There are minor differences regarding DocRoot, but otherwise this is a clean backport.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8248001](https://bugs.openjdk.org/browse/JDK-8248001): javadoc generates invalid HTML pages whose ftp:// links are broken (**Bug** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2002/head:pull/2002` \
`$ git checkout pull/2002`

Update a local copy of the PR: \
`$ git checkout pull/2002` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2002/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2002`

View PR using the GUI difftool: \
`$ git pr show -t 2002`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2002.diff">https://git.openjdk.org/jdk11u-dev/pull/2002.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2002#issuecomment-1612470636)

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
Testing?

**Comment by ktakakuri** [comment]
I built and tested test/langtools on Windows x86_64, and confirmed that all tests passed.

**Comment by GoeLin** [comment]
@ ktakakuri , please enable the pre-submit tests.
Merging head will trigger them to run.

**Comment by ktakakuri** [comment]
linux-cross-compile failed.
```
E: Version '10.3.0-1ubuntu1~20.04cross1' for 'gcc-10-s390x-linux-gnu' was not found
E: Version '10.3.0-1ubuntu1~20.04cross1' for 'g++-10-s390x-linux-gnu' was not found
```
But all other tests passed.
Is it OK?

**Comment by phohensee** [comment]
It's ok, looks like a GHA infra failure.

**Pull request closed without merging**
