### PR TITLE
8220202: Simplify/standardize method naming for HtmlTree

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8220202](https://bugs.openjdk.org/browse/JDK-8220202)
- This PR contains 2 commits
- Commit 1: is the git apply from the original commit
- Commit 2: is trying to aplly the rejected changes. Although it contains many files, well it only contains 3 types of changes:
  - Change type A. Change method name from `addContent` to `add`
  - Change type B. Change method name from `addAttr` to `put`
  - Change type C. Add missing `import` to fix compile error

Testing
- Local: Test passed
  - `TestHtmlDocument.java`: Test results: passed: 1
- Pipeline: **All checks have passed**
- Testing Machine: SAP nightlies passed on `2024-04-22`
  - Automated jtreg test: jtreg_langtools
  - `jdk/javadoc/doclet/testHtmlDocument/TestHtmlDocument.java`: SUCCESSFUL GitHub 📊⏲ - [761 msec]

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8220202](https://bugs.openjdk.org/browse/JDK-8220202) needs maintainer approval

### Issue
 * [JDK-8220202](https://bugs.openjdk.org/browse/JDK-8220202): Simplify/standardize method naming for HtmlTree (**Enhancement** - P3 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2674/head:pull/2674` \
`$ git checkout pull/2674`

Update a local copy of the PR: \
`$ git checkout pull/2674` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2674/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2674`

View PR using the GUI difftool: \
`$ git pr show -t 2674`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2674.diff">https://git.openjdk.org/jdk11u-dev/pull/2674.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2674#issuecomment-2067874893)

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
Looks good.
I admit I did not check each and every changed line. Diffing the original patch and this backport patch resulted in close to 5,000 lines.

**Comment by amosshi** [comment]
/approval request "Backporting as 8253700 dependency. Un-Clean backport. SAP nightlies passed on 2024-04-22”

**Pull request closed without merging**
