### PR TITLE
8218431: Improved platform checking in makefiles

### PR DESCRIPTION
**Pull request by GoeLin**
This is a quite big change, but it's all  mechanic edits.
It replaces the tests for platforms. The old tests
still work, so there is no problem in omitting some 
of the adaptions.
The new functionality added in Utels.gmk applied clean.

I resolved the following hunks:make/Images.gmk
make/RunTests.gmk
Simple resolve

make/TestImage.gmk
Skipped, edited code not in 11.

make/common/NativeCompilation.gmk
Two hunks did not apply.
Skipped first one, code not in 11.
Second was trivial.

make/copy/Copy-java.base.gmk
First trivial.
Second skipped. Two conditions checked magically :)
Third skipped.

make/hotspot/gensrc/GensrcAdlc.gmk
Trivial.

make/hotspot/ide/CreateVSProject.gmk
Skipped, code not in 11.

make/hotspot/lib/CompileDtraceLibraries.gmk
Trivial

make/hotspot/lib/CompileJvm.gmk
Trivial.

make/launcher/LauncherCommon.gmk
Omitted. Code not in 11.

make/lib/Awt2dLibraries.gmk
Parts applied, parts of the patched code not in 11.
Second and third hung to resolve were trivial.

make/lib/CoreLibraries.gmk
Trival.

make/lib/Lib-java.base.gmk
Code not in 11.

make/lib/Lib-jdk.hotspot.agent.gmk
Trivial

make/test/JtregNativeJdk.gmk
Trivial

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8218431](https://bugs.openjdk.org/browse/JDK-8218431): Improved platform checking in makefiles

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1702/head:pull/1702` \
`$ git checkout pull/1702`

Update a local copy of the PR: \
`$ git checkout pull/1702` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1702/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1702`

View PR using the GUI difftool: \
`$ git pr show -t 1702`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1702.diff">https://git.openjdk.org/jdk11u-dev/pull/1702.diff</a>

</details>

### CODE REVIEW

**Comment by MBaesken** [comment]
Could you please check make/common/NativeCompilation.gmk , around line 986 ? Seems this one was moved and missed in the patch

```
        # Generate debuginfo files.
        ifeq ($(OPENJDK_TARGET_OS), windows)
```

**Comment by GoeLin** [comment]
Thanks for catching this! I hadn't saved this ... the editor was still open.  Fixed.
I also merged the main branch, so now the jtreg test errors should be gone.

**Comment by MBaesken** [comment]
Looks  like  make/launcher/LauncherCommon.gmk, ~ line 120 misses the macosx handling.

**Comment by GoeLin** [comment]
I left out the changes in LauncherCommon intentionally. I thought the code in the patch differs too much to the code in 11.  There are more occurrences of the old test coding in this file, anyways.

**Review by MBaesken — APPROVED** [review]
Thanks for backporting, approved!

**Comment by GoeLin** [comment]
Thanks for reviewing this tedious change!!

**Review by MBaesken — APPROVED** [review]

**Pull request closed without merging**
