### PR TITLE
8209611: use C++ compiler for hotspot tests

### PR DESCRIPTION
**Pull request by GoeLin**
I want to downport this for parity with jdk11.0.x-oracle.

I had to resolve /make/common/TestFilesCompilation.gmk
One chunk is pointless, as it was changed again by "8210920: Native C++ tests are not using CXXFLAGS"
which, in head, came after this change, but was already downported to 11u.
I resolved the other chunk that did not apply to the current syntax in head.

I had to conserve some changes we backported from the .cpp files
to the .c files and move them over to the new .cpp files:

test/hotspot/jtreg/vmTestbase/nsk/jvmti/GetClassMethods/getclmthd007/getclmthd007.c
test/hotspot/jtreg/vmTestbase/nsk/jvmti/scenarios/extension/EX03/ex03t001/ex03t001.c
test/hotspot/jtreg/vmTestbase/nsk/jvmti/unit/extmech/extmech.c

In this file, we disable some warnings in 11 with "8232084: HotSpot build failed with GCC 9.2.1"
I can not check whether the warnings are a problem in cpp, too, so
I moved the change to the new file:
test/hotspot/jtreg/vmTestbase/nsk/share/jvmti/jvmti_tools.c

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8209611](https://bugs.openjdk.java.net/browse/JDK-8209611): use C++ compiler for hotspot tests

### Reviewers
 * [Matthias Baesken](https://openjdk.java.net/census#mbaesken) (@MBaesken - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/634/head:pull/634` \
`$ git checkout pull/634`

Update a local copy of the PR: \
`$ git checkout pull/634` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/634/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 634`

View PR using the GUI difftool: \
`$ git pr show -t 634`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/634.diff">https://git.openjdk.java.net/jdk11u-dev/pull/634.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
I need to backport '8226943: compile error in libfollowref003.cpp with XCode 10.2 on macosx" to fix the build error in the CI.

**Review by MBaesken — APPROVED** [review]

**Comment by tstuefe** [comment]
Wow. The original bug must be one of the most taciturn JBS issues I have ever seen, especially considering the patch size. How is one supposed to seriously review this?

**Comment by GoeLin** [comment]
To verify what I did, I dumped the original and my change, and diffed the changes.
I did it twice, once so that moved files are recognized, and once without. This can be achieved by setting git config merge.renamelimit .
Luckily the change is from 12, so not that far away from 11...
Thanks for reviewing, Matthias!

**Comment by tstuefe** [comment]
Sorry, my comment was aimed more at the original JBS issue (I like to understand what I review). Meanwhile, I found Igors original review thread in build-dev from 2018, which offers more explanations than the JBS issue:

https://mail.openjdk.java.net/pipermail/build-dev/2018-August/022880.html

It seems that converting everything to C++ files was a workaround for shortcomings in the build system for tests, where .c files include other .c files, so all of them have to be either C or C++.

"Currently our build system supports only 1-1 relation b/w tests lib/exec and source file; most of native libraries in vmTestbase have more than one source file. to work that around, we introduced a .c file for each library and theses .c files include all other required .c files."

I wondered about the implications since C->C++ conversion has pitfalls (http://david.tribble.com/text/cdiffs.htm), and the patch size makes earnest reviews challenging.

After applying your patch, I noticed that there are 78 files left in test/hotspot/jtreg that remain C. None of these were removed for JDK12, so looks like they were not touched by the original patch either. I did not find an explanation for that, but I assume that's ok.

Note that one disadvantage of moving wholesale to C++ is longer build times. But I guess that ship is sailed. Since if oracle did backport this we should follow suit.

To review, I tried to clone the original jdk12u sources, but both mercurial repo and github readonly mirror are that slow that I gave up after an hour. I diffed the two diffs by hand and did not find anything overly suspicious. I also looked at your patch in general, the places you pointed out, and it seems fine. Due to the patch size this was a cursory look only. I guess if tests start failing, we will see follow up issues.

**Review by tstuefe — APPROVED** [review]

**Pull request closed without merging**
