### PR TITLE
8230305: Cgroups v2: Container awareness

### PR DESCRIPTION
**Pull request by zhengyu123**
I would like backport cgroups v2  support to openjdk11u.

The original patch does not apply cleanly, conflicts are resolved manually.

Test:
  - [x] jtreg containers/docker test on Ubuntu 20.04.4 LTS

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8230305](https://bugs.openjdk.java.net/browse/JDK-8230305): Cgroups v2: Container awareness
 * [JDK-8229202](https://bugs.openjdk.java.net/browse/JDK-8229202): Docker reporting causes secondary crashes in error handling
 * [JDK-8216366](https://bugs.openjdk.java.net/browse/JDK-8216366): Add rationale to PER_CPU_SHARES define

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to 4749f095d980b030d16782a49f8f6e5ae576506f

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/840/head:pull/840` \
`$ git checkout pull/840`

Update a local copy of the PR: \
`$ git checkout pull/840` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/840/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 840`

View PR using the GUI difftool: \
`$ git pr show -t 840`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/840.diff">https://git.openjdk.java.net/jdk11u-dev/pull/840.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
This seems fine. A few minor comments.

Aside: We need to devise a plan how we want to deal with integrating this set of patches. For example I'm seeing test failures of the hotspot container tests on a cgroups v2 system due to https://bugs.openjdk.java.net/browse/JDK-8253714.

**Comment by zhengyu123** [comment]
@jerboaa  Thanks for the review.

**Comment by jmtd** [comment]
For me, `PlainRead.java` is failing on a pure cgroups v2 system (passes on v1):

```
;$JT_HOME/bin/jtreg -jdk:build/linux-x86_64-normal-server-release/jdk test/hotspot/jtreg/containers/cgroup/PlainRead.java
Test results: failed: 1
```

(I noticed this in a downstream backport and traced it back up here)

I've put my JTreport here: https://jmtd.net/tmp/jdk11u_8230305_PlainRead_jtreport/JTreport/html/index.html

**Comment by jerboaa** [comment]
> For me, `PlainRead.java` is failing on a pure cgroups v2 system (passes on v1):
> 
> ```
> ;$JT_HOME/bin/jtreg -jdk:build/linux-x86_64-normal-server-release/jdk test/hotspot/jtreg/containers/cgroup/PlainRead.java
> Test results: failed: 1
> ```
> 
> (I noticed this in a downstream backport and traced it back up here)
> 
> I've put my JTreport here: https://jmtd.net/tmp/jdk11u_8230305_PlainRead_jtreport/JTreport/html/index.html
> 
> Edit: @jerboaa [points out](https://github.com/openjdk/jdk11u-dev/pull/881#issuecomment-1065226806) that this is probably JDK-8278951, although backporting that does not fix the test for me locally. I'll keep exploring.
> 
> Edit 2: fails for me on jdk17u-dev master, passes on jdk master.

Note that the `PlainRead.java` test depends on proper [setup of the `cpu` controller](https://www.scrivano.org/2019/02/26/resources-management-with-rootless-containers/) on your cgroups v2 system (unlike cgroups v1). It passes for me on my configured cgroups v2 system:
```
# /home/sgehwolf/jdk11u-dev/../jdk11u-jdk/bin/java -cp /home/sgehwolf/jdk11u-dev/JTwork/classes/containers/cgroup/PlainRead.d:/home/sgehwolf/jdk11u-dev/test/hotspot/jtreg/containers/cgroup:/home/sgehwolf/jdk11u-dev/JTwork/classes/testlibrary:/home/sgehwolf/jdk11u-dev/test/hotspot/jtreg/testlibrary:/home/sgehwolf/jdk11u-dev/JTwork/classes/test/lib:/home/sgehwolf/jdk11u-dev/test/lib:/home/sgehwolf/jtreg-5/lib/javatest.jar:/home/sgehwolf/jtreg-5/lib/jtreg.jar -Xlog:os+container=trace -version
[0.001s][trace][os,container] OSContainer::init: Initializing Container Support
[0.001s][debug][os,container] Detected cgroups v2 unified hierarchy
[0.001s][trace][os,container] Path to /memory.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/memory.max
[0.001s][trace][os,container] Raw value for memory limit is: max
[0.001s][trace][os,container] Memory Limit is: Unlimited
[0.002s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/cpu.max
[0.002s][trace][os,container] Raw value for CPU quota is: max
[0.002s][trace][os,container] CPU Quota is: -1
[0.002s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/cpu.max
[0.002s][trace][os,container] CPU Period is: 100000
[0.002s][trace][os,container] Path to /cpu.weight is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/cpu.weight
[0.002s][trace][os,container] Raw value for CPU shares is: 100
[0.002s][debug][os,container] CPU Shares is: -1
[0.002s][trace][os,container] OSContainer::active_processor_count: 4
[0.002s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 4
[0.002s][debug][os,container] container memory limit unlimited: -1, using host value
[0.002s][debug][os,container] container memory limit unlimited: -1, using host value
[0.003s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 4
[0.072s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/cpu.max
[0.072s][trace][os,container] Raw value for CPU quota is: max
[0.072s][trace][os,container] CPU Quota is: -1
[0.072s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/cpu.max
[0.072s][trace][os,container] CPU Period is: 100000
[0.072s][trace][os,container] Path to /cpu.weight is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/cpu.weight
[0.072s][trace][os,container] Raw value for CPU shares is: 100
[0.072s][debug][os,container] CPU Shares is: -1
[0.072s][trace][os,container] OSContainer::active_processor_count: 4
[0.095s][trace][os,container] Path to /memory.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/memory.max
[0.095s][trace][os,container] Raw value for memory limit is: max
[0.095s][trace][os,container] Memory Limit is: Unlimited
[0.095s][debug][os,container] container memory limit unlimited: -1, using host value
[0.095s][debug][os,container] container memory limit unlimited: -1, using host value
[0.096s][debug][os,container] container memory limit unlimited: -1, using host value
[0.096s][debug][os,container] container memory limit unlimited: -1, using host value
[0.097s][debug][os,container] container memory limit unlimited: -1, using host value
[0.097s][debug][os,container] container memory limit unlimited: -1, using host value
[0.098s][debug][os,container] container memory limit unlimited: -1, using host value
[0.098s][debug][os,container] container memory limit unlimited: -1, using host value
[0.100s][debug][os,container] container memory limit unlimited: -1, using host value
[0.100s][debug][os,container] container memory limit unlimited: -1, using host value
[0.101s][debug][os,container] container memory limit unlimited: -1, using host value
[0.103s][debug][os,container] container memory limit unlimited: -1, using host value
[0.104s][debug][os,container] container memory limit unlimited: -1, using host value
[0.104s][debug][os,container] container memory limit unlimited: -1, using host value
[0.104s][debug][os,container] container memory limit unlimited: -1, using host value
[0.105s][debug][os,container] container memory limit unlimited: -1, using host value
[0.105s][debug][os,container] container memory limit unlimited: -1, using host value
[0.106s][debug][os,container] container memory limit unlimited: -1, using host value
[0.107s][debug][os,container] container memory limit unlimited: -1, using host value
[0.108s][debug][os,container] container memory limit unlimited: -1, using host value
[0.108s][debug][os,container] container memory limit unlimited: -1, using host value
[0.108s][debug][os,container] container memory limit unlimited: -1, using host value
[0.109s][debug][os,container] container memory limit unlimited: -1, using host value
[0.114s][debug][os,container] container memory limit unlimited: -1, using host value
[0.115s][debug][os,container] container memory limit unlimited: -1, using host value
[0.118s][trace][os,container] Path to /memory.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/memory.max
[0.118s][trace][os,container] Raw value for memory limit is: max
[0.118s][trace][os,container] Memory Limit is: Unlimited
[0.118s][debug][os,container] container memory limit unlimited: -1, using host value
[0.120s][debug][os,container] container memory limit unlimited: -1, using host value
[0.121s][debug][os,container] container memory limit unlimited: -1, using host value
[0.121s][debug][os,container] container memory limit unlimited: -1, using host value
[0.122s][debug][os,container] container memory limit unlimited: -1, using host value
[0.123s][debug][os,container] container memory limit unlimited: -1, using host value
[0.123s][debug][os,container] container memory limit unlimited: -1, using host value
[0.124s][debug][os,container] container memory limit unlimited: -1, using host value
[0.125s][debug][os,container] container memory limit unlimited: -1, using host value
[0.131s][debug][os,container] container memory limit unlimited: -1, using host value
[0.132s][debug][os,container] container memory limit unlimited: -1, using host value
[0.135s][debug][os,container] container memory limit unlimited: -1, using host value
[0.137s][debug][os,container] container memory limit unlimited: -1, using host value
[0.137s][debug][os,container] container memory limit unlimited: -1, using host value
[0.138s][trace][os,container] Path to /memory.max is /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/memory.max
[0.138s][trace][os,container] Raw value for memory limit is: max
[0.138s][trace][os,container] Memory Limit is: Unlimited
[0.138s][debug][os,container] container memory limit unlimited: -1, using host value
[0.138s][debug][os,container] container memory limit unlimited: -1, using host value
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (fastdebug build 11.0.15-internal+0-adhoc.sgehwolf.jdk11u-dev)
OpenJDK 64-Bit Server VM (fastdebug build 11.0.15-internal+0-adhoc.sgehwolf.jdk11u-dev, mixed mode)
[0.142s][debug][os,container] container memory limit unlimited: -1, using host value
[0.142s][debug][os,container] container memory limit unlimited: -1, using host value
```

This shouldn't block this backport.

**Pull request closed without merging**
