### PR TITLE
8310923: Refactor Currency tests to use JUnit

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 11.0.24-oracle.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8310923](https://bugs.openjdk.org/browse/JDK-8310923) needs maintainer approval

### Integration blocker
&nbsp;⚠️ Too few reviewers with at least role reviewer found (have 0, need at least 1) (failed with updated jcheck configuration in pull request)

### Issue
 * [JDK-8310923](https://bugs.openjdk.org/browse/JDK-8310923): Refactor Currency tests to use JUnit (**Sub-task** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2503/head:pull/2503` \
`$ git checkout pull/2503`

Update a local copy of the PR: \
`$ git checkout pull/2503` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2503/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2503`

View PR using the GUI difftool: \
`$ git pr show -t 2503`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2503.diff">https://git.openjdk.org/jdk11u-dev/pull/2503.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2503#issuecomment-1920849682)

### CODE REVIEW

**Comment by GoeLin** [comment]
The github actions tests fail, because the junit code used in this change depends on a recent junit.  GHA of 11 use old jtreg 6.1.. With 7.3.1, the tests would work.

**Comment by gnu-andrew** [comment]
> The github actions tests fail, because the junit code used in this change depends on a recent junit. GHA of 11 use old jtreg 6.1.. With 7.3.1, which contains a more recent junit, the tests would work.

Do we plan to transition 11u to jtreg 7? Doing so has quite a long tail of dependencies: https://bugs.openjdk.org/browse/JDK-8289798

I think this is being backported for [8321480: ISO 4217 Amendment 176 Update](https://github.com/openjdk/jdk17u-dev/commit/223018a3aabc319992d9790fa1d6c88b02fcca9f) because it contains some follow-on unrelated test changes from this patch.  You could do 8321480 without this patch - I think we'll have to in 8u as jtreg 7 needs JDK 11 - but I don't want to do that if we are going to bring this change in, as it will make this change unclean and risk missing the post-8310923 changes in 8321480.

**Comment by GoeLin** [comment]
Hi @gnu-andrew,
Yes, we backport this because [8321480: ISO 4217 Amendment 176 Update](https://github.com/openjdk/jdk17u-dev/commit/223018a3aabc319992d9790fa1d6c88b02fcca9f) depends on it. But it is also easy to resolve 8321480 without this change, which is what Oracle did.
I have been looking at raising the jtreg version. As a first step, I wanted to explore backporting the required test fixes you mention above. Actually, there are some more prerequisites. But I don't think we will achieve this by Feb 27th. So maybe we should proceed with the ISO 4217 Amendment.

**Comment by gnu-andrew** [comment]
> Hi @gnu-andrew, Yes, we backport this because [8321480: ISO 4217 Amendment 176 Update](https://github.com/openjdk/jdk17u-dev/commit/223018a3aabc319992d9790fa1d6c88b02fcca9f) depends on it. But it is also easy to resolve 8321480 without this change, which is what Oracle did. I have been looking at raising the jtreg version. As a first step, I wanted to explore backporting the required test fixes you mention above. Actually, there are some more prerequisites. But I don't think we will achieve this by Feb 27th. So maybe we should proceed with the ISO 4217 Amendment.

Yes, I'm starting to think it would be better not to try and rush the jtreg bump and instead do that in the July cycle. I have a backport of the ISO amendment without the test change almost ready and can submit a PR later today. Let me know if I can be of any help with the jtreg bump.

**Comment by GoeLin** [comment]
Hi @gnu-andrew, 
Yes, I think we should bring JDK-8321480 to 11 now, and not wait for this change.
I think we should not omit the test changes, but resolve them. 
This change just makes them a clean backpot.
Could you please have a look at that, @luchenlin?
Thanks!

**Comment by gnu-andrew** [comment]
I've opened a backport for JDK-8321480 on #2532
It would be good if this PR could pick up the skipped change to `twoLetterCodesTest` from that backport straight away so it doesn't get missed when this finally does get integrated. It seems to not be directly related to 8321480 anyway (method is introduced by this refactoring and original tests pass after 8321480 only)

**Pull request closed without merging**
