### PR TITLE
8214245: Case insensitive matching doesn't work correctly for some character classes

### PR DESCRIPTION
**Pull request by Korov**
fix [JDK-8305733](https://bugs.openjdk.org/browse/JDK-8305733)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8214245](https://bugs.openjdk.org/browse/JDK-8214245) needs maintainer approval
- [ ] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))
- [ ] Change requires CSR request [JDK-8328951](https://bugs.openjdk.org/browse/JDK-8328951) to be approved

### Issues
 * [JDK-8214245](https://bugs.openjdk.org/browse/JDK-8214245): Case insensitive matching doesn't work correctly for some character classes (**Bug** - P4)
 * [JDK-8328951](https://bugs.openjdk.org/browse/JDK-8328951): Case insensitive matching doesn't work correctly for some character classes (**CSR**)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2062/head:pull/2062` \
`$ git checkout pull/2062`

Update a local copy of the PR: \
`$ git checkout pull/2062` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2062/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2062`

View PR using the GUI difftool: \
`$ git pr show -t 2062`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2062.diff">https://git.openjdk.org/jdk11u-dev/pull/2062.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2062#issuecomment-1656866090)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
This repository requires approval before integration. See https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix step 6.

**Comment by phohensee** [comment]
@Korov, what testing have you done, and what do you estimate the risk is?

**Comment by Korov** [comment]
> @Korov, what testing have you done, and what do you estimate the risk is?

Here we test whether the matching of Posix character, Unicode character, Unicode categories, aliases, properties, and java methods is correct under the condition of ignoring case.

Currently considered no risk.

**Comment by phohensee** [comment]
@Korov, please post a fix request comment for the JBS issue outlining risk and testing.

**Comment by RealCLanger** [comment]
I don't get this. What is the difference of this change to a full backport of [JDK-8214245](https://bugs.openjdk.org/browse/JDK-8214245)? If there's no difference, this should be a backport of JDK-8214245. And then we'd also need to file a CSR.

**Comment by Korov** [comment]
@RealCLanger There's no difference, But I have no permission to login JBS, and I cannot create a CSR from `https://bugreport.java.com/bugreport/`, Can anyone give me some help on how to create a CSR?

**Comment by Korov** [comment]
After learning abour CSR, does it mean that this change may cause changes in the behavior of some programs, causing compatibility issues?

**Comment by RealCLanger** [comment]
@Korov - yes, a CSR is done when there is a change in behavior to the user. But the fact that a CSR is needed does not necessarily mean that a change is not suitable for an Update release. So in this case, we'd probably have to create a CSR for JDK11u as a copy from the original CSR. I can do that for you.

And furthermore, please make this PR a backport of [JDK-8214245](https://bugs.openjdk.org/browse/JDK-8214245). You can do so by changing the title to "Backport 1d4a4fed437184b2f9fef605de40aab82846c717". When should then close the JBS issue [JDK-8305733](https://bugs.openjdk.org/browse/JDK-8305733) as a duplicate.

**Comment by Korov** [comment]
@RealCLanger Thank you very much for your help, I have changed the title.

**Comment by RealCLanger** [comment]
> @RealCLanger Thank you very much for your help, I have changed the title.

Looks like the bots don't recognize the short hash. You need to rename it "Backport `1d4a4fed437184b2f9fef605de40aab82846c717`" (which is what I wanted to say but GitHub made the short hash out of it)

**Comment by GoeLin** [comment]
/reviewers 2

Asking for a second review because intergrate was already triggered, but the CSR is still missing.

**Comment by RealCLanger** [comment]
@Korov Sorry for being inactive on this one for so long. Are you still willing to follow up on this backport? In that case I would create the CSR now. Please let me know.

**Comment by Korov** [comment]
@RealCLanger Yes

**Comment by Korov** [comment]
Hello @RealCLanger , I'm very interested in continuing to work on this backport, Please help me create a CSR and tell me the relevant links. Thank you very much for your help.

**Comment by RealCLanger** [comment]
> Hello @RealCLanger , I'm very interested in continuing to work on this backport, Please help me create a CSR and tell me the relevant links. Thank you very much for your help.

OK, I now created a CSR for 11-pool: [JDK-8328951](https://bugs.openjdk.org/browse/JDK-8328951). The CSR will need a review from some OpenJDK reviewer, e.g. @phohensee or @GoeLin, would you mind taking a look?

After CSR review, we have to wait whether it'll be approved before we can continue with this backport.

**Comment by Korov** [comment]
> > Hello @RealCLanger , I'm very interested in continuing to work on this backport, Please help me create a CSR and tell me the relevant links. Thank you very much for your help.
> 
> OK, I now created a CSR for 11-pool: [JDK-8328951](https://bugs.openjdk.org/browse/JDK-8328951). The CSR will need a review from some OpenJDK reviewer, e.g. @phohensee or @GoeLin, would you mind taking a look?
> 
> After CSR review, we have to wait whether it'll be approved before we can continue with this backport.

Thats great, thanks for your help. I will continue to pay attention to the progress of CSR.

**Comment by RealCLanger** [comment]
@Korov The CSR request got rejected, please see the [comment](https://bugs.openjdk.org/browse/JDK-8328951?focusedId=14664774&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14664774). I agree that this change bears a compatibility risk that is maybe too high for a backport.

What's the reason that you need this in JDK11? E.g. would it be possible for you to move on to JDK17?

**Comment by Korov** [comment]
> @Korov The CSR request got rejected, please see the [comment](https://bugs.openjdk.org/browse/JDK-8328951?focusedId=14664774&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14664774). I agree that this change bears a compatibility risk that is maybe too high for a backport.
> 
> What's the reason that you need this in JDK11? E.g. would it be possible for you to move on to JDK17?

This has been fixed in JDK17, so I think this PR can be closed.

**Pull request closed without merging**
