### PR TITLE
8180571: Refactor sun/security/pkcs11 shell tests to plain java tests and fix failures

### PR DESCRIPTION
**Pull request by jmtd**
Please consider this backport of [JDK-8180571](https://bugs.openjdk.java.net/browse/JDK-8180571) to 11u.

It's not a clean backport. cherry-pick conflicts manually resolved:

 * all file deletions didn't succeed due to hunk differences
 * all: copyright year differences 
 * `ReadConfInUTF16Env.java`: upstream hunks differ due to removed SPARC support
 * `PKCS11Test.java`: import list differences (nio imports not present in 11u's copy, resolved by including them as this change needs them)

The test `Login.java` needed further alterations for 11u:

 * two uses of JDK12+ `instanceof` pattern matching needed unsugaring
 * Removed @run argument `-Djava.security.manager=allow`. This is invalid for JDK11 (and corresponds to the JDK11 behaviour when specified for 12+)

All included tests now pass for me. Awaiting GitHub's tier1 test results.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8180571](https://bugs.openjdk.java.net/browse/JDK-8180571): Refactor sun/security/pkcs11 shell tests to plain java tests and fix failures

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.java.net/census#goetz) (@GoeLin - **Reviewer**)

### Contributors
 * Jonathan Dowland `<jdowland@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/396/head:pull/396` \
`$ git checkout pull/396`

Update a local copy of the PR: \
`$ git checkout pull/396` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/396/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 396`

View PR using the GUI difftool: \
`$ git pr show -t 396`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/396.diff">https://git.openjdk.java.net/jdk11u-dev/pull/396.diff</a>

</details>

### CODE REVIEW

**Review by GoeLin — APPROVED** [review]
LGTM
I also saw Christoph put this into our nightly testing ... seems good.

**Comment by RealCLanger** [comment]
> LGTM
> I also saw Christoph put this into our nightly testing ... seems good.

Hm, I didn't do this, don't know what you saw here 😉 But after all, maybe it's a good idea to do so as GHA would probably not cover all modified tests...?

**Comment by jmtd** [comment]
/contributor add Jonathan Dowland <jdowland@openjdk.org>
/contributor remove Fernando Guallini <fguallini@openjdk.org>

Looking at my chain of three dependent PRs, I realised this one (at the bottom of the stack) had Fernando as author (due to the way I cherry picked the commit: Fernando is the original patch author upstream). The above commands are an attempt to make this PR consistent with others, where the backporter is listed as author. Alternatively I could rewrite the commit and force-push, but I would then invalidate the PR's Review and need to rebase the two dependent PRs. Sorry for the noise: I'm slowly getting there with the Skara/GH workflow!

**Comment by RealCLanger** [comment]
> /contributor add Jonathan Dowland [jdowland@openjdk.org](mailto:jdowland@openjdk.org)
> /contributor remove Fernando Guallini [fguallini@openjdk.org](mailto:fguallini@openjdk.org)
> 
> Looking at my chain of three dependent PRs, I realised this one (at the bottom of the stack) had Fernando as author (due to the way I cherry picked the commit: Fernando is the original patch author upstream). The above commands are an attempt to make this PR consistent with others, where the backporter is listed as author. Alternatively I could rewrite the commit and force-push, but I would then invalidate the PR's Review and need to rebase the two dependent PRs. Sorry for the noise: I'm slowly getting there with the Skara/GH workflow!

@jmtd, that's not necessary. With the git workflow, you'll be the author of the backport when the change is integrated, no matter what you have in your commit. Also, with the new workflow a backport would not set the original author as author of the backport and that's also how it should be (unless you worked together with Fernando on the backport and owe him some credits). So I suggest you also remove yourself as additional contributor...

**Comment by TheRealMDoerr** [comment]
It was me who put it into our nightly testing. Results are fine.

**Comment by RealCLanger** [comment]
@jmtd, any chance to integrate this? (With or without co-author ;-))

**Pull request closed without merging**
