### PR TITLE
8268364: jmethod clearing should be done during unloading

### PR DESCRIPTION
**Pull request by krk**
Backport of [8268364](https://bugs.openjdk.org/browse/JDK-8268364), single hunk conflict resolved by accepting "empty" from the backport commit vs. `clear_jmethod_ids` invocation in the dtor. Backport commit moves the `clear_jmethod_ids` invocation to `unload` method instead.

It fixes crashes when accessing jmethodIDs of a class being unloaded.

Here is the reproducer that crashes JVM in ~1 second without the patch, but works fine with it: [gist](https://gist.github.com/krk/a0800bac5bc5a01709be85637285a965).

This fix also resolves the issue reported at https://github.com/async-profiler/async-profiler/issues/974 for Java 11.

To run the repro:

```
javac Main.java
gcc -shared -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" -fPIC repro.cpp -orepro.so

java -agentpath:"$(pwd)/repro.so" -Xmx100m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+ExplicitGCInvokesConcurrent Main
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8268364](https://bugs.openjdk.org/browse/JDK-8268364) needs maintainer approval

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8268364: jmethod clearing should be done during unloading`

### Issue
 * [JDK-8268364](https://bugs.openjdk.org/browse/JDK-8268364): jmethod clearing should be done during unloading (**Bug** - P4 - Approved)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2935/head:pull/2935` \
`$ git checkout pull/2935`

Update a local copy of the PR: \
`$ git checkout pull/2935` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2935/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2935`

View PR using the GUI difftool: \
`$ git pr show -t 2935`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2935.diff">https://git.openjdk.org/jdk11u-dev/pull/2935.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2935#issuecomment-2358769964)
</details>

### CODE REVIEW

**Comment by krk** [comment]
* MacOS builds are failing for unrelated reason: ` error: 'sprintf' is deprecated`.
* `linux-x86 / test - Test (tier1)` failing while uploading test artifacts:
```
Error: Failed to CreateArtifact: Failed to make request after 5 attempts: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact
```

**Comment by krk** [comment]
cc @coleenp @fisk

**Review by coleenp — APPROVED** [review]
This looks like a good backport.

**Comment by krk** [comment]
/approval request The fix is required to allow JVM TI tools, especially profilers, run safely with class unloading enabled. Low risk: a small localized change that only affects liveness of jmethodIDs.

**Comment by krk** [comment]
/approval request All checks passing. The fix is required to allow JVM TI tools, especially profilers, to run safely with class unloading enabled. Low risk: a small localized change that only affects liveness of jmethodIDs.

**Comment by shipilev** [comment]
@GoeLin, @jerboaa -- do you see any blockers for approving this?

**Comment by jerboaa** [comment]
@shipilev JDK 11u is done and only very select fixes will be allowed in going forward. For this one, I'll let @theRealAph handle approval. On the surface it seems OK, but it's another change to a done release which only seems to affect corner cases (profilers when classes get unloaded).

FWIW, SAP stopped work on JDK 11u (11.0.25 was the last one) so you can not expect answers from them for 11u.

**Comment by jerboaa** [comment]
@krk @shipilev Andrew Haley has approved this PR. Do you plan to integrate it?

**Comment by gnu-andrew** [comment]
> @krk @shipilev Andrew Haley has approved this PR. Do you plan to integrate it?

This really should have waited until the rampdown changes were in place. I've manually moved this one to 11.0.27.

**Comment by gnu-andrew** [comment]
> Sorry for the confusion, thanks for moving it.

Thanks. I'm a little late in doing the transition myself with being away at the beginning of the week, but the right version should be used automatically once https://bugs.openjdk.org/browse/JDK-8345509 is integrated. I just thought you should be aware that this will be in the April release. The cut-off for January was Friday.

**Pull request closed without merging**
