### PR TITLE
8242468: VS2019 build missing vcruntime140_1.dll

### PR DESCRIPTION
**Pull request by gdams**
Fixes an issue observed at Adoptium when bumping the compiler to VS 2019 (https://github.com/adoptium/temurin-build/issues/3052)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8242468](https://bugs.openjdk.org/browse/JDK-8242468): VS2019 build missing vcruntime140_1.dll

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [dec71c5a](https://git.openjdk.org/jdk11u-dev/pull/1247/files/dec71c5a264194feb5ecb309b3196182d09ead61)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1247/head:pull/1247` \
`$ git checkout pull/1247`

Update a local copy of the PR: \
`$ git checkout pull/1247` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1247/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1247`

View PR using the GUI difftool: \
`$ git pr show -t 1247`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1247.diff">https://git.openjdk.org/jdk11u-dev/pull/1247.diff</a>

</details>

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
LGTM

**Comment by RealCLanger** [comment]
Hm, as you are backporting 8239708 in #1277, I think you should do this backport afterwards. It'll then probably apply cleanly. As of now it looks as if you'd have forgotten this change in basics.m4 in #1277

**Comment by gdams** [comment]
> Hm, as you are backporting 8239708 in https://github.com/openjdk/jdk11u-dev/pull/1277, I think you should do this backport afterwards. It'll then probably apply cleanly. As of now it looks as if you'd have forgotten this change in basics.m4 in https://github.com/openjdk/jdk11u-dev/pull/1277

I've switched the base now so this should be good

**Pull request closed without merging**
