### PR TITLE
8244508: JFR: FlightRecorderOptions reset date format

### PR DESCRIPTION
**Pull request by pushkarnk**
Hello all,

This backport request is related to JDK-8244508 [1]. When using JFR (`-XX:StartFlightRecording`), the configured default Locale is not honored, with FormatData or TimezoneNames(for example), because the relevant ResourceBundles do not get loaded when an attempt is made to locate and load them during VM startup (i.e when  `-XX:StartFlightRecording` triggers JFR initialiazation). Though [1] quotes a mailing-list post [2] mentioning this issue was not seen with jdk11 then, the testcase in [1] does fail with 11.0.20 (as well as 11.0.22/master branch) as of today:

```
$ java --show-version -Duser.country=DE -Duser.language=de -XX:FlightRecorderOptions=stackdepth=128 Main
openjdk 11.0.22-internal 2024-01-16
OpenJDK Runtime Environment (build 11.0.22-internal+0-adhoc.pushkarnk.jdk11u-dev)
OpenJDK 64-Bit Server VM (build 11.0.22-internal+0-adhoc.pushkarnk.jdk11u-dev, mixed mode)
expected: 01.01.2020, 00:00:00
actual:   2020 Jan 1 00:00:00 
```
Testing: Linux x86-64 build, tier1 tests with `release` and `fastdebug` builds.

[1] https://bugs.openjdk.org/browse/JDK-8244508
[2] https://mail.openjdk.org/pipermail/hotspot-jfr-dev/2020-March/001313.html

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8244508](https://bugs.openjdk.org/browse/JDK-8244508) needs maintainer approval

### Issue
 * [JDK-8244508](https://bugs.openjdk.org/browse/JDK-8244508): JFR: FlightRecorderOptions reset date format (**Bug** - P3 - Approved)

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2121/head:pull/2121` \
`$ git checkout pull/2121`

Update a local copy of the PR: \
`$ git checkout pull/2121` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2121/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2121`

View PR using the GUI difftool: \
`$ git pr show -t 2121`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2121.diff">https://git.openjdk.org/jdk11u-dev/pull/2121.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2121#issuecomment-1710321578)

### CODE REVIEW

**Comment by pushkarnk** [comment]
Hello Maintainers, 

Apologies for the ping. I was hoping to get some feedback on this backport request. Thanks!

**Comment by pushkarnk** [comment]
Hello Maintainers,

Apologies for the ping. I was hoping to get some feedback on this backport request. Please do let me know if there are questions. cc @RealCLanger @GoeLin

**Comment by pushkarnk** [comment]
> @pushkarnk This pull request has been inactive for more than 4 weeks and will be automatically closed if another 4 weeks passes without any activity. To avoid this, simply add a new comment to the pull request. Feel free to ask for assistance if you need help with progressing this pull request towards integration!

I'd appreciate feedback on this backport request. Thank you.

**Comment by RealCLanger** [comment]
Hi @pushkarnk,

I think this backport is appropriate. Can you please run Github Actions verification? (E.g. enable actions here: https://github.com/pushkarnk/jdk11u-dev/actions and then merge the PR with master).

Furthermore, I'm wondering why the backport is not marked as clean. What did you have to resolve?

Cheers
Christoph

**Comment by pushkarnk** [comment]
Hi @RealCLanger,

I've run the checks. 

The original commit removes an [unused import in DCmdConfigure.java](https://github.com/openjdk/jdk/commit/f3519016c7766934d0aa3014b1a0593d91a0556c#diff-4f41b8efbc78c3085cd8d0810e41349fc9c27095daaff54be2127dd27b88939bL35) which does not exist in jdk11. That's the only conflict I had to resolve.

Thanks!
 - Pushkar

**Comment by RealCLanger** [comment]
OK, looks good. I'll run the backport through our tests and will approve when no regressions spotted.

**Comment by pushkarnk** [comment]
> OK, looks good. I'll run the backport through our tests and will approve when no regressions spotted.


Hi @RealCLanger, any news on this?

**Review by RealCLanger — APPROVED** [review]
Oh, sorry and thanks for the ping. I completely forgot about this. Tests are looking good.

**Comment by RealCLanger** [comment]
> /approval request

@pushkarnk, you are supposed to also add some comment as part of the approval request to provide the maintainers some information. That includes some reasoning why you want this backport plus a risk assessment and information about the testing you did. So, please update or re-issue the /approval command with some text. Thx.

**Comment by pushkarnk** [comment]
> > /approval request
> 
> @pushkarnk, you are supposed to also add some comment as part of the approval request to provide the maintainers some information. That includes some reasoning why you want this backport plus a risk assessment and information about the testing you did. So, please update or re-issue the /approval command with some text. Thx.

Thanks Chris. I guess this backport request has been approved now. I'll keep this in mind for all future work.

**Comment by pushkarnk** [comment]
I requested for this backport because an Ubuntu user reported this bug of JFR not honoring a configured default Locale. Locally, I ran the tier1 tests on Linux x86-64 with `release` and `fastdebug` builds.

**Comment by RealCLanger** [comment]
Weird that it didn't take your initial /integrate. So be it.

/sponsor

**Pull request closed without merging**
