### PR TITLE
8262409: sun/security/ssl/SSLSocketImpl/SSLSocketImplThrowsWrongExceptions. SSL test failures caused by java failed with "Server reported the wrong exception"

### PR DESCRIPTION
**Pull request by RealCLanger**
This test error can be observed in jdk11u as well since JDK-8259662 was backported with 11.0.12.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8262409](https://bugs.openjdk.java.net/browse/JDK-8262409): sun/security/ssl/SSLSocketImpl/SSLSocketImplThrowsWrongExceptions. SSL test failures caused by java failed with "Server reported the wrong exception"

### Reviewers
 * [Thomas Stuefe](https://openjdk.java.net/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/79/head:pull/79` \
`$ git checkout pull/79`

Update a local copy of the PR: \
`$ git checkout pull/79` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/79/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 79`

View PR using the GUI difftool: \
`$ git pr show -t 79`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/79.diff">https://git.openjdk.java.net/jdk11u-dev/pull/79.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
The backport applies clean, except for the change to the problem list.

**Review by tstuefe — APPROVED** [review]
Looks good. Though I would have felt better if the original fix was restricted to catching the right exception instead of also changing test synchronization.

**Pull request closed without merging**
