### PR TITLE
8274338: com/sun/jdi/RedefineCrossEvent.java failed "assert(m != __null) failed: NULL mirror"

### PR DESCRIPTION
**Pull request by zhengyu123**
This patch redoes JDK-8274338 backport to openjdk 11u.

Early backport failed and was backout. The failure was due to `CLD::loaded_classes_do()`, now requires to hold `MultiArray_lock`, therefore, the closure  `LinkSharedClassesClosure` can not trigger `JavaCall` while holding a lock.

[Revised]
Drop new assertion in `CLD::loaded_classes_do()`, only add `MultiArray_lock` to `InstanceKlass::restore_unshareable_info()`, which is the only thing matter in this patch.

Test:
- [x] hotspot_appcds 
- [x] tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8274338](https://bugs.openjdk.java.net/browse/JDK-8274338): com/sun/jdi/RedefineCrossEvent.java failed "assert(m != __null) failed: NULL mirror"

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/632/head:pull/632` \
`$ git checkout pull/632`

Update a local copy of the PR: \
`$ git checkout pull/632` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/632/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 632`

View PR using the GUI difftool: \
`$ git pr show -t 632`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/632.diff">https://git.openjdk.java.net/jdk11u-dev/pull/632.diff</a>

</details>

### CODE REVIEW

**Comment by zhengyu123** [comment]
@phohensee

Could you review this redo patch?

Thanks,

-Zhengyu

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
I ran the change through our nightly tests an do not see any failures.

**Pull request closed without merging**
