### PR TITLE
8285835: SIGSEGV in PhaseIdealLoop::build_loop_late_post_work

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 11.0.19-oracle.

I resolved one chunk in escape.cpp because 
non_escaped_worklist has been renamed in 17 to
non_escaped_allocs_worklist by "8263989: Cleanup in EA"
Might end up being clean.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285835](https://bugs.openjdk.org/browse/JDK-8285835): SIGSEGV in PhaseIdealLoop::build_loop_late_post_work

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [d762a41e](https://git.openjdk.org/jdk11u-dev/pull/1649/files/d762a41e60306f4f68d645f6f0067e5dc795502d)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1649/head:pull/1649` \
`$ git checkout pull/1649`

Update a local copy of the PR: \
`$ git checkout pull/1649` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1649/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1649`

View PR using the GUI difftool: \
`$ git pr show -t 1649`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1649.diff">https://git.openjdk.org/jdk11u-dev/pull/1649.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Thanks catching this. Forgotten again.

**Comment by GoeLin** [comment]
Pre-submit tests: all the x86/64 builds access the same unavailable resouce:
Unable to connect to azure.archive.ubuntu.com

**Review by phohensee — APPROVED** [review]
Lgtm now.

**Pull request closed without merging**
