### PR TITLE
8255548: Missing coverage for javax.xml.crypto.dom.DOMCryptoContext

### PR DESCRIPTION
**Pull request by amosshi**
- Backport for [JDK-8255548](https://bugs.openjdk.org/browse/JDK-8255548)
- Test succeeded in local dev box

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8255548](https://bugs.openjdk.org/browse/JDK-8255548) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8255548](https://bugs.openjdk.org/browse/JDK-8255548): Missing coverage for javax.xml.crypto.dom.DOMCryptoContext (**Bug** - P4 - Approved)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2177/head:pull/2177` \
`$ git checkout pull/2177`

Update a local copy of the PR: \
`$ git checkout pull/2177` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2177/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2177`

View PR using the GUI difftool: \
`$ git pr show -t 2177`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2177.diff">https://git.openjdk.org/jdk11u-dev/pull/2177.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2177#issuecomment-1760520985)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request "Backporting for parity with jdk11.0.21-oracle. No risk, test fix. Clean backport. Test passes and SAP nightlies pass.”

**Review by GoeLin — APPROVED** [review]
LGTM

**Comment by GoeLin** [comment]
Hi @amosshi, this is not a clean backport :)
This is the case if no review was needed.

**Pull request closed without merging**
