### PR TITLE
8220093: Change to GCC 8.2 for building on Linux at Oracle

### PR DESCRIPTION
**Pull request by RealCLanger**
This is a backport of [JDK-8220093](https://bugs.openjdk.org/browse/JDK-8220093). The motivation for doing it is that configure output will then show same output as in higher releases for the used linker. E.g.

`configure: Using gcc linker version 2.36.1 [GNU ld (GNU Binutils) 2.36.1]`

vs

`configure: Using gcc linker version 8.5.0 [collect2 version 8.5.0]`

One can then deduct the version of binutils used.

I had to make a few modifications. In toolchain.m4, [JDK-8257679](https://bugs.openjdk.org/browse/JDK-8257679) was already present so I had to make the hunk fit. The other adaptations are in jib-profiles.js which is not relevant to OpenJDK because it's used internally at Oracle only and some improvements to the devkit build scripts.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8220093](https://bugs.openjdk.org/browse/JDK-8220093): Change to GCC 8.2 for building on Linux at Oracle

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [5c375ac1](https://git.openjdk.org/jdk11u-dev/pull/1792/files/5c375ac123e5dc4409c11fa287e2cc3ec5a18d7c)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1792/head:pull/1792` \
`$ git checkout pull/1792`

Update a local copy of the PR: \
`$ git checkout pull/1792` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1792/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1792`

View PR using the GUI difftool: \
`$ git pr show -t 1792`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1792.diff">https://git.openjdk.org/jdk11u-dev/pull/1792.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
There is a hunk missing (Tools.gmk 370ff) ?

**Comment by RealCLanger** [comment]
> There is a hunk missing (Tools.gmk 370ff) ?

True. I should have explained my reasoning here: I didn't dare to change the devkit build logic from `--enable-gold` to `--enable-gold=default` as we had seen issues with compatibility by that change which makes the build use the gold linker then.

**Comment by VladimirKempik** [comment]
> looks good to me, but maybe someone from Oracle should comment on the make/conf/jib-profiles.js change

It's wrong way.

jib-profiles.js is used internally in oracle.

Oracle has their own branch of 11u, and not building from **open**jdk11u
Therefore jib-profiles.js change should be dropped from the backport as it has no reason to go into **open**jdk11u

**Comment by RealCLanger** [comment]
> > looks good to me, but maybe someone from Oracle should comment on the make/conf/jib-profiles.js change
> 
> It's wrong way.
> 
> jib-profiles.js is used internally in oracle.
> 
> Oracle has their own branch of 11u, and not building from **open**jdk11u Therefore jib-profiles.js change should be dropped from the backport as it has no reason to go into **open**jdk11u

I'd say it doesn't matter. As I stated above, it is not relevant in OpenJDK. I can however drop the changes to the file.

**Comment by GoeLin** [comment]
Why are the tests failing?

**Comment by RealCLanger** [comment]
> Why are the tests failing?

Probably nothing to do with my change - I've retriggered.

**Comment by RealCLanger** [comment]
> > Why are the tests failing?
> 
> Probably nothing to do with my change - I've retriggered.

OK, still failing tests but this time others. That's all GHA wag.

**Pull request closed without merging**
