### PR TITLE
8267256: Extend minimal retry for loopback connections on Windows to PlainSocketImpl

### PR DESCRIPTION
**Pull request by macarte**
Backport of JDK-8267256

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8267256](https://bugs.openjdk.java.net/browse/JDK-8267256): Extend minimal retry for loopback connections on Windows to PlainSocketImpl

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/628/head:pull/628` \
`$ git checkout pull/628`

Update a local copy of the PR: \
`$ git checkout pull/628` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/628/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 628`

View PR using the GUI difftool: \
`$ git pr show -t 628`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/628.diff">https://git.openjdk.java.net/jdk11u-dev/pull/628.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
and finally this one needs rebasing as well.

**Comment by macarte** [comment]
right, have to wait for https://github.com/openjdk/jdk11u-dev/pull/627 to be commited first

**Pull request closed without merging**
