### PR TITLE
8207248: Reduce incidence of compiler.warn.source.no.bootclasspath in javac tests

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 11.0.19-oracle.

Change itself applied clean, but
WeirdTwr.java needs fix from 8206439: Remove javac -source/-target 6 from langtools regression tests
Else it fails after delting the .out file.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8207248](https://bugs.openjdk.org/browse/JDK-8207248): Reduce incidence of compiler.warn.source.no.bootclasspath in javac tests

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [1435e7cf](https://git.openjdk.org/jdk11u-dev/pull/1721/files/1435e7cf0405a74a585d19d15fc993bd4436b50c)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1721/head:pull/1721` \
`$ git checkout pull/1721`

Update a local copy of the PR: \
`$ git checkout pull/1721` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1721/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1721`

View PR using the GUI difftool: \
`$ git pr show -t 1721`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1721.diff">https://git.openjdk.org/jdk11u-dev/pull/1721.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Pre-submit failure: infra problem, unrelated.
Downloading https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar to /d/a/jdk11u-dev/jdk11u-dev/jtreg/src/make/../build/deps/junit/junit-4.13.2.jar
Error: sh][ERROR] wget exited with exit code 4

**Comment by RealCLanger** [comment]
I'm not sure about the approach regarding WeirdTwr. Maybe you should leave this test alone, meaning not to remove WeirdTwr.out as well. I think the -source/-target 6 is still supported in JDK 11 so you should keep the test.

**Comment by GoeLin** [comment]
What about doing it similar to SuppressDeprecation.java?  See new change.

**Comment by RealCLanger** [comment]
> What about doing it similar to SuppressDeprecation.java? See new change.

Nice. :)

**Review by RealCLanger — APPROVED** [review]

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by GoeLin** [comment]
Pre-submit failure: windows infra issue.
This is a testbug that does not depend on win so I think we can go without these tests.

**Pull request closed without merging**
