### PR TITLE
8272352: Java launcher can not parse Chinese character when system locale is set to UTF-8

### PR DESCRIPTION
**Pull request by calderast**
Backport of JDK-8272352: Java launcher can not parse Chinese character when system locale is set to UTF-8.

Does not apply cleanly to 11u due to a minor change for UTF-8 support otherwise included in JDK-8264208: Console charset API, which has not been backported to 11u. (I added `case 65001:` for UTF-8 on line 83).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8272352](https://bugs.openjdk.org/browse/JDK-8272352): Java launcher can not parse Chinese character when system locale is set to UTF-8

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [2a874e22](https://git.openjdk.org/jdk11u-dev/pull/1234/files/2a874e22e72e60cabdcc7c487d8cea2803deaada)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1234/head:pull/1234` \
`$ git checkout pull/1234`

Update a local copy of the PR: \
`$ git checkout pull/1234` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1234/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1234`

View PR using the GUI difftool: \
`$ git pr show -t 1234`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1234.diff">https://git.openjdk.org/jdk11u-dev/pull/1234.diff</a>

</details>

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
LGTM

**Comment by calderast** [comment]
@RealCLanger one last PR for you to sponsor 😃

**Pull request closed without merging**
