### PR TITLE
8226943: compile error in libfollowref003.cpp  with XCode 10.2 on macosx

### PR DESCRIPTION
**Pull request by GoeLin**
A build fix needed after 8209611

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8226943](https://bugs.openjdk.java.net/browse/JDK-8226943): compile error in libfollowref003.cpp  with XCode 10.2 on macosx

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/636/head:pull/636` \
`$ git checkout pull/636`

Update a local copy of the PR: \
`$ git checkout pull/636` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/636/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 636`

View PR using the GUI difftool: \
`$ git pr show -t 636`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/636.diff">https://git.openjdk.java.net/jdk11u-dev/pull/636.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
There are 2523 files in the PR, but only one in the original commit http://hg.openjdk.java.net/jdk/jdk13/rev/5c8eb7381088.

**Review by phohensee — COMMENTED** [review]
Now I see. This PR includes https://github.com/openjdk/jdk11u-dev/pull/634. I'd split the patches and integrate them one after the other.

**Comment by GoeLin** [comment]
Hi Paul, 
This is a dependent pull request. I need this fix on top of #634.  After 634 was pushed, this PR will automatically get rebased and only the second change/commit will remain.
But I need this ready to push right away so that I do not leave a broken repo when I integrate 634.

**Comment by RealCLanger** [comment]
> Hi Paul, This is a dependent pull request. I need this fix on top of #634. After 634 was pushed, this PR will automatically get rebased and only the second change/commit will remain. But I need this ready to push right away so that I do not leave a broken repo when I integrate 634.

Hi Goetz, why don't you make it a real dependend Pull Request? Just change the target of this PR from master to branch pr/634. Then it'll look much nicer :)

**Comment by GoeLin** [comment]
> why don't you make it a real dependend Pull Request?
I thought that was what I did ... making a real dependend PR 😊
But I'll have a look, maybe also solves the mac build issue then !!

**Comment by GoeLin** [comment]
Opened #637 comparing to pr/634.

**Pull request closed without merging**
