### PR TITLE
8329348: jdk11u build for Windows AArch64 fails

### PR DESCRIPTION
**Pull request by swesonga**
The root cause of the build error 'No rule to make target .../windows/conf/tzmappings' when building jdk11u for Windows AArch64 is that the GENSRC_TARGETS have not been built. This happens because the buildjdk is x86 but the target jdk is aarch64. Reusing artifacts is not correct in this scenario. The fix is to ensure that the required targets are built unconditionally for Windows AArch64.

Note that the existing checks for CREATING_BUILDJDK were also found to be incorrect in https://bugs.openjdk.org/browse/JDK-8217739

Builds on macOS, Linux, and Windows across both x64/AArch64 succeeded with this fix.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8329348](https://bugs.openjdk.org/browse/JDK-8329348) needs maintainer approval

### Issue
 * [JDK-8329348](https://bugs.openjdk.org/browse/JDK-8329348): jdk11u build for Windows AArch64 fails (**Bug** - P1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2668/head:pull/2668` \
`$ git checkout pull/2668`

Update a local copy of the PR: \
`$ git checkout pull/2668` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2668/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2668`

View PR using the GUI difftool: \
`$ git pr show -t 2668`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2668.diff">https://git.openjdk.org/jdk11u-dev/pull/2668.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2668#issuecomment-2059994711)

### CODE REVIEW

**Comment by swesonga** [comment]
Hi @MBaesken, I am searching for a reviewer for this PR and I noticed that you reviewed one of the recent changes to this file. Would you be able to review this change or to suggest other possible reviewers?

**Comment by MBaesken** [comment]
lines  114-116 please check the indentation I think this has to be adjusted by one space.
I am wondering how it works/worked for other **cross builds** then windows cross, the problem you describe sounds like it should be seen for cross builds on other platforms too?

**Comment by MBaesken** [comment]
I do not see Windows aarch in the list of  supported builds for jdk11 https://wiki.openjdk.org/display/Build/Supported+Build+Platforms
so is this really worth the effort for such an old release ?

**Comment by swesonga** [comment]
> I do not see Windows aarch in the list of supported builds for jdk11 https://wiki.openjdk.org/display/Build/Supported+Build+Platforms so is this really worth the effort for such an old release ?

Windows AArch64 is a supported platform for jdk11u. Microsoft backported this support in https://github.com/openjdk/jdk11u-dev/pull/301
We are looking into updating the supported build platforms page to reflect this.

**Comment by swesonga** [comment]
> lines 114-116 please check the indentation I think this has to be adjusted by one space. I am wondering how it works/worked for other **cross builds** then windows cross, the problem you describe sounds like it should be seen for cross builds on other platforms too?

Let me investigate cross builds on other platforms to verify the build behavior.

**Pull request closed without merging**
