### PR TITLE
8320005: Allow loading of shared objects with .a extension on AIX

### PR DESCRIPTION
**Pull request by suchismith1993**
Hi all,

This pull request contains a backport of commit [e85355ad](https://github.com/openjdk/jdk/commit/e85355ada4ac1061c49ee9f1247d37a437c7b5ab) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Suchismith Roy on 27 Feb 2024 and was reviewed by Amit Kumar, Thomas Stuefe, Joachim Kern and Martin Doerr.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320005](https://bugs.openjdk.org/browse/JDK-8320005) needs maintainer approval

### Issue
 * [JDK-8320005](https://bugs.openjdk.org/browse/JDK-8320005): Allow loading of shared objects with .a extension on AIX (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2622/head:pull/2622` \
`$ git checkout pull/2622`

Update a local copy of the PR: \
`$ git checkout pull/2622` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2622/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2622`

View PR using the GUI difftool: \
`$ git pr show -t 2622`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2622.diff">https://git.openjdk.org/jdk11u-dev/pull/2622.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2622#issuecomment-2018606603)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @suchismith1993, I removed your label, please first backport to 17.

**Comment by suchismith1993** [comment]
@GoeLin  the backport for jdk17-udev is already there for review. For multiple line changes i think it went in for a review.
https://github.com/openjdk/jdk17u-dev/pull/2332/

**Comment by suchismith1993** [comment]
/approval request This back port is required to handle dynamic libraries of AIX.

**Comment by suchismith1993** [comment]
@GoeLin  The backport for jdk17 is complete.

**Pull request closed without merging**
