### PR TITLE
8251558: J2DBench should support shaped and translucent windows

### PR DESCRIPTION
**Pull request by gnu-andrew**
I discovered this change when looking at potential conflicts for JDK-8275872. Shaped and translucent windows have been supported since OpenJDK 6, so having support for these in 11u's J2DBench seems appropriate and a good way of testing these features.

I've dropped the `Makefile`, `README` & `build.xml` changes which bump the source & target to 1.7 as the 11u javac compiler can still compile for 1.6. Other than that, the patch applies as is, bar some copyright conflicts, thanks to JDK-8211693 : "Convert C-style array declarations in client demos and jdk.accessibility" and JDK-8223237: "Replace use of string.equals("") with isEmpty() in java.desktop". The absence of the latter also means we don't need to revert it in `OutputImageTests.java` & `InputImageTests.java`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8251558](https://bugs.openjdk.java.net/browse/JDK-8251558): J2DBench should support shaped and translucent windows

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/613/head:pull/613` \
`$ git checkout pull/613`

Update a local copy of the PR: \
`$ git checkout pull/613` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/613/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 613`

View PR using the GUI difftool: \
`$ git pr show -t 613`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/613.diff">https://git.openjdk.java.net/jdk11u-dev/pull/613.diff</a>

</details>

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
Looks good. 

(We could have left the bump to 1.7 as is, but this is also fine)

**Comment by gnu-andrew** [comment]
> Looks good.
> 
> (We could have left the bump to 1.7 as is, but this is also fine)

Thanks. I would like to follow up with a patch to trunk to allow the path to javac and the source/target options to be configured more easily. It's implied that the code should continue working on 1.4, but actually testing that means hacking the Makefile at present.

**Comment by gnu-andrew** [comment]
Now has jdk11u-fix-yes.

**Pull request closed without merging**
