### PR TITLE
8284206: AIX build failure by JDK-8261169 requires a short-term solution

### PR DESCRIPTION
**Pull request by takiguc**
AIX build was failed by [JDK-8261169](https://bugs.openjdk.java.net/browse/JDK-8261169) against jdk11u-dev.
To fix this issue, C++ compiler should migrate from XL C++ 13.1.3 to XL C++ 16.1.
Also we need to switch from xlC-based to clang-based compiler.

I want to request some backports (which are not related Harfbuzz) against AIX platform.
For short-term solution, I'd like to keep Harfbuzz 2.3.1 just for AIX platform only.

* Copy Harfbuzz 2.3.1 to src/java.desktop/aix/native/libharfbuzz
* Modify make/lib/Awt2dLibraries.gmk

By there changes, we can use xlC-based XL C++ 13.1.3 and 16.1.

So please backout this change before migrating to clang-based 16.1.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8284206](https://bugs.openjdk.java.net/browse/JDK-8284206): AIX build failure by JDK-8261169 requires a short-term solution

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/991/head:pull/991` \
`$ git checkout pull/991`

Update a local copy of the PR: \
`$ git checkout pull/991` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/991/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 991`

View PR using the GUI difftool: \
`$ git pr show -t 991`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/991.diff">https://git.openjdk.java.net/jdk11u-dev/pull/991.diff</a>

</details>

### CODE REVIEW

**Comment by backwaterred** [comment]
Thanks @takiguc! From a quick look, this seems to be to be a good short term solution. I'm curious, were you unable to build jdk11u-dev on AIX with xlc 16.1 before this change?

Depending on how the maintainers feel, it may be a good idea to push this change through to the release of OpenJDK 11.0.16, then deploy #993 once it has been thoroughly reviewed and tested. Maybe @theRealAph has thoughts on this idea?

**Comment by sxa** [comment]
As a representative of Adoptium I'm good with holding back the harfbuzz upgrade on AIX for now. The concern I have is that moving up to xlc16 will introduce a change within the JDK11 stream that requires a different xlc runtime package to be installed on the end users' machines, therefore it could break people which would be a relatively unusual/undesirable thing to do within the JDK11 stream. FYI We already use xlc16 for JDK17+

**Comment by TheRealMDoerr** [comment]
I don't know if changing runtime requirements is really problematic. Updating the JVM sometimes implies updating/installing libraries. The xlclang compatible runtime is not really new.

It may also be an option to support both for 11.0.16 depending on the installed compiler on the build machine:

- Old harfbuzz with old xlc
- New harfbuzz with xlclang

But I'll leave you guys free to decide.

**Comment by sxa** [comment]
> Updating the JVM sometimes implies updating/installing libraries

IMHO that's a very unusual situation - I'm not sure I can recall when that's happened within a major version stream in the time I've been working with openjdk.

**Comment by backwaterred** [comment]
> It may also be an option to support both for 11.0.16 depending on the installed compiler on the build machine:
> 
>     * Old harfbuzz with old xlc
> 
>     * New harfbuzz with xlclang

I'm not opposed to modifying this PR to warn that the 'Old harfbuzz with old xlc' path is depreciated (to be removed in a future release), and keeping both options available for 11.0.16. Would this work for Adoptium @sxa?

**Comment by TheRealMDoerr** [comment]
> > Updating the JVM sometimes implies updating/installing libraries
> 
> IMHO that's a very unusual situation - I'm not sure I can recall when that's happened within a major version stream in the time I've been working with openjdk.

We had updated the requirements for linux after 11.0.2 (see https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms).
Maybe most people didn't notice because it just worked on their systems. That may be different on AIX.
However, sticking with an unmaintained old lib is not a better solution in the long run IMHO. (Maybe acceptable for 11.0.16.)

**Comment by sxa** [comment]
> > > Updating the JVM sometimes implies updating/installing libraries

> > IMHO that's a very unusual situation - I'm not sure I can recall when that's happened within a major version stream in the time I've been working with openjdk.
> We had updated the requirements for linux after 11.0.2 (see https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms).

Wasn't that just compiler changes which have a relevance for anyone building but shouldn't have affected users? In general we still target and run on RHEL6/Cent6 levels of software and libraries so there should have been no visible impact to users of that change.

**Comment by sxa** [comment]
I think that would be a good intermediate solution if 

> > It may also be an option to support both for 11.0.16 depending on the installed compiler on the build machine:
> > * Old harfbuzz with old xlc
> > * New harfbuzz with xlclang
> I'm not opposed to modifying this PR to warn that the 'Old harfbuzz with old xlc' path is depreciated (to be removed in a future release), and keeping both options available for 11.0.16. Would this work for Adoptium @sxa?

If that's relatively easy to do it seems like it would be a good option for now.

**Comment by TheRealMDoerr** [comment]
AIX build with xlc 16 seems to be fine after Tyler's other backports: https://ci.adoptopenjdk.net/job/AIX-jdk11-dev-build/69
I guess this PR will not be needed anymore?
Otherwise, note that the window for regular 11.0.16 changes will close on June 1st.

**Comment by takiguc** [comment]
Hello @TheRealMDoerr .
Sorry I'm late.
I'm still testing 11.0.16 AIX build.
One jtreg testcase was failed which was reported by [JDK-8287362](https://bugs.openjdk.java.net/browse/JDK-8287362) .
[PR#8904](https://github.com/openjdk/jdk/pull/8904) was submitted.

**Comment by takiguc** [comment]
Sorry, I'm late.
No short-term solution is required for JDK 11.0.16 for AIX.

**Comment by RealCLanger** [comment]
@takiguc, could you then please also close the JBS bug (e.g. as duplicate of the actual fix)?

**Comment by takiguc** [comment]
Thanks @RealCLanger .
[JDK-8284206](https://bugs.openjdk.org/browse/JDK-8284206) was closed.

**Pull request closed without merging**
