### PR TITLE
8247818: GCC 10 warning stringop-overflow with symbol code

### PR DESCRIPTION
**Pull request by jmtd**
11u-dev is tricky to build with GCC 11 and newer. GCC 11 is the default version in current Debian stable (and likely derivatives e.g. Ubuntu, but I have not checked) as well as RHEL 9 (and derivatives, likewise unchecked), so I think it's worthwhile to improve that.

This particular patch addresses one of the obstacles (a warning from GCC 10 onwards). It doesn't apply clean, but cherry-pick conflicts were trivial to resolve. It was backported from 16 to 15 and 13 and seems worthwhile for 11u.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8247818](https://bugs.openjdk.org/browse/JDK-8247818) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8247818](https://bugs.openjdk.org/browse/JDK-8247818): GCC 10 warning stringop-overflow with symbol code (**Bug** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2451/head:pull/2451` \
`$ git checkout pull/2451`

Update a local copy of the PR: \
`$ git checkout pull/2451` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2451/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2451`

View PR using the GUI difftool: \
`$ git pr show -t 2451`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2451.diff">https://git.openjdk.org/jdk11u-dev/pull/2451.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2451#issuecomment-1884840855)

### CODE REVIEW

**Comment by jmtd** [comment]
/approval request improves experience building 11u with gcc 10 and newer, patch has been in 13,15,16+ for a while. TIA

(those two command are rather similar)

**Comment by GoeLin** [comment]
Hi @jmtd,
what about follow up JDK_8249087? I think we need that, too.

**Comment by jmtd** [comment]
>  what about follow up JDK_8249087? I think we need that, too.

I think you are right: perhaps 8247818 in isolation merely promotes the bug from compile-time to run time!

I've got a PR for that I'm about to raise. For 8247818, I don't hit the compiler error unless I first apply GitHub PR #2470 (8324307), to resolve earlier errors. They are otherwise unrelated. Would this be an appropriate place to use dependent PRs?

**Comment by jmtd** [comment]
/approval request related backports 8247818 and 8249087 for modern GCC support in 11u ready for another look. Thanks!

**Review by tstuefe — APPROVED** [review]
Looks fine.

What I find weird is that the memcpy version does not produce warnings. Since we are doing exactly the same (Symbol is var-sized in the typical C way, by defining a trailing one-byte-array, and gcc does not get it).

**Pull request closed without merging**
