### PR TITLE
8210047: some pages contain content outside of landmark region

### PR DESCRIPTION
**Pull request by psoujany**
Backport of 8210047: some pages contain content outside of landmark region 

OpenJDK Bug : https://bugs.openjdk.org/browse/JDK-8210047

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8210047](https://bugs.openjdk.org/browse/JDK-8210047): some pages contain content outside of landmark region

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1320/head:pull/1320` \
`$ git checkout pull/1320`

Update a local copy of the PR: \
`$ git checkout pull/1320` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1320/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1320`

View PR using the GUI difftool: \
`$ git pr show -t 1320`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1320.diff">https://git.openjdk.org/jdk11u-dev/pull/1320.diff</a>

</details>

### CODE REVIEW

**Comment by psoujany** [comment]
@RealCLanger Could you please review this backport. Thank you.

**Comment by RealCLanger** [comment]
@psoujany, do you have any hints on what you had to modify for this backport?

**Comment by psoujany** [comment]
@RealCLanger After applying the backport, I've modified the below testcase i.e, TestHtmlVersion.java
https://github.com/openjdk/jdk11u-dev/pull/1320/files#diff-758d666ce824475aacf00bdbd1af556809a342f6fa24eb177e5a4540f11801a5

**Comment by psoujany** [comment]
@RealCLanger Could you please review the PR, thank you.

**Comment by RealCLanger** [comment]
OK, at a glance the PR looks good to me. I'll run it through our testing and let you know the results tomorrow.

**Review by RealCLanger — APPROVED** [review]
Sorry for the late reply. Testing looks good. Please flag for approval.

**Comment by psoujany** [comment]
@RealCLanger Here's the JBS issue for which review is requested, yet to get the approval.
https://bugs.openjdk.org/browse/JDK-8210047

**Comment by RealCLanger** [comment]
> @RealCLanger Here's the JBS issue for which review is requested, yet to get the approval. https://bugs.openjdk.org/browse/JDK-8210047

OK, I take you don't have JBS access? I can add the fix request on your behalf. Can you provide me with some text on why you want to have this backported, risk assessment, testcoverage etc. ?

**Comment by psoujany** [comment]
Yes, I don't have JBS access. JDK11 javadoc generates docs with violations which got fixed in later release i.e 12. Hence requesting this backport which resolves one of those violations. Risk would be moderate as this affects javadoc generation. No regressions shown in Tier1 and javadoc tests from jdk11u-dev.

**Comment by RealCLanger** [comment]
> JDK11 javadoc generates docs with violations which got fixed in later release i.e 12. Hence requesting this backport which resolves one of those violations. Risk would be moderate as this affects javadoc generation. No regressions shown in Tier1 and javadoc tests from jdk11u-dev.

OK, I added the JBS item on your behalf. Please monitor it for approval.

**Comment by GoeLin** [comment]
Hi @psoujany, you can integrate now.

**Pull request closed without merging**
