### PR TITLE
8278456: Define jtreg jdk_desktop test group time-based sub-tasks for use by headful testing.

### PR DESCRIPTION
**Pull request by amosshi**
- Backport for [JDK-8278456](https://bugs.openjdk.org/browse/JDK-8278456)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8278456](https://bugs.openjdk.org/browse/JDK-8278456) needs maintainer approval

### Issue
 * [JDK-8278456](https://bugs.openjdk.org/browse/JDK-8278456): Define jtreg jdk_desktop test group time-based sub-tasks for use by headful testing. (**Bug** - P4 - Approved)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2164/head:pull/2164` \
`$ git checkout pull/2164`

Update a local copy of the PR: \
`$ git checkout pull/2164` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2164/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2164`

View PR using the GUI difftool: \
`$ git pr show -t 2164`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2164.diff">https://git.openjdk.org/jdk11u-dev/pull/2164.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2164#issuecomment-1745771001)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request "Backporting for parity with jdk11.0.21-oracle. No risk, test fix. Clean backport. Test passes and SAP nightlies pass.”

**Comment by GoeLin** [comment]
The edit was needed because 8236044: Create jdk_accessibility test group  is not in 11.

**Review by GoeLin — APPROVED** [review]
LGTM

**Pull request closed without merging**
