### PR TITLE
8234510: Remove file seeking requirement for writing a heap dump

### PR DESCRIPTION
**Pull request by buddyliao**
Backport of the heap dump enhancement: Remove file seeking requirement for writing a heap dump

Patch did not apply cleanly, I had to resolve/modify
    src/hotspot/share/services/heapDumper.cpp

I have built it on linux x86_64 and run test-tier1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8234510](https://bugs.openjdk.java.net/browse/JDK-8234510): Remove file seeking requirement for writing a heap dump

### Reviewers
 * [Ralf Schmelter](https://openjdk.java.net/census#rschmelter) (@schmelter-sap - no project role) ⚠️ Review applies to 4b146be9cba527c9eb4f7181aee8b0cff7dfe38d
 * [Christoph Langer](https://openjdk.java.net/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to 6098c619c155968885f61024443e645e5832f4ac

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/134/head:pull/134` \
`$ git checkout pull/134`

Update a local copy of the PR: \
`$ git checkout pull/134` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/134/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 134`

View PR using the GUI difftool: \
`$ git pr show -t 134`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/134.diff">https://git.openjdk.java.net/jdk11u-dev/pull/134.diff</a>

</details>

### CODE REVIEW

**Review by schmelter-sap — APPROVED** [review]
The change looks good to me. I've run the tier1 and tier2 tests without the problems.

**Comment by RealCLanger** [comment]
@buddyliao, thanks for rebasing. I'll run this through our nightlies and if all goes well I'll approve it then.

**Review by RealCLanger — APPROVED** [review]
No regressions spotted in the nightlies. Good to go from my end.

**Comment by RealCLanger** [comment]
> /integrate

@buddyliao, you need to Request maintainer approval via jdk11u-fix-request label and Fix request comment in the JBS item [JDK-8234510](https://bugs.openjdk.java.net/browse/JDK-8234510), that part of the protocol hasn't changed with the migration to GitHub.

**Comment by linzang** [comment]
Dear @RealCLanger,
Thanks for reminder, as @buddyliao doesn't has the access to JBS, I have helped to add the `jdk11u-fix-request` label in JDK-8234510.

BRs,
Lin

**Comment by RealCLanger** [comment]
> Dear @RealCLanger,
> Thanks for reminder, as @buddyliao doesn't have the access to JBS, I have helped to add the `jdk11u-fix-request` label in JDK-8234510.
> 
> BRs,
> Lin

Thank you. I approved it and will sponsor this one.

**Pull request closed without merging**
