### PR TITLE
8308593: Add KEEPALIVE Extended Socket Options Support for Windows

### PR DESCRIPTION
**Pull request by tkyc**
This is an unclean backport of [JDK-8308593](https://bugs.openjdk.org/browse/JDK-8308593), which provides support for the keepalive extended socket options on Windows.

The following changes are the differences from the original patch in order to get this backport working for 11u:

make/lib/Lib-jdk.net.gmk -- Updated this script to support building extnet for Windows.

src/jdk.net/share/classes/jdk/net/ExtendedSocketOptions.java -- Added a case to support returning an instance of WindowsSocketOptions in PlatformSocketOptions.

src/java.base/windows/classes/java/net/PlainSocketImpl.java -- The Windows PlainSocketImpl class will need to have similar setOption/getOption methods as the Unix PlainSocketImpl class to support setting these extended socket options for Windows.

Backport passed against Tier 1 tests and was manually verified to be working on Windows.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8308593](https://bugs.openjdk.org/browse/JDK-8308593) needs maintainer approval

### Issue
 * [JDK-8308593](https://bugs.openjdk.org/browse/JDK-8308593): Add KEEPALIVE Extended Socket Options Support for Windows (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2278/head:pull/2278` \
`$ git checkout pull/2278`

Update a local copy of the PR: \
`$ git checkout pull/2278` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2278/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2278`

View PR using the GUI difftool: \
`$ git pr show -t 2278`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2278.diff">https://git.openjdk.org/jdk11u-dev/pull/2278.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2278#issuecomment-1806372709)

### CODE REVIEW

**Comment by tkyc** [comment]
/approval request Requesting backport approval to 11u to have keepalive parity with the other OS platforms. Risk is low as the new code path in the backported code applies to Windows only and requires the new socket options to be set to take effect. Backport was ran against Tier 1 tests and was also manually tested. There's also existing tests in 11u that cover this scenario and so no new tests were added.

**Comment by GoeLin** [comment]
Hi @tkyc,
please only label for approval if you have a review, i.e. the change is ready to be integrated.
Did you make sure all relevant tests did run? Tier1 is only a basic sanity check.

**Comment by tkyc** [comment]
@GoeLin apologies, my mistake. Aside from tier 1, I ran the keepalive tests from PR JDK-8194298 that initially added support for Linux (which passed). At the moment also I'm running the `jdk_net` test group as well just as another precaution. Let me know if there's any further testing I can do.

**Comment by tkyc** [comment]
An update, my `jdk_net` test group run also passed.

**Comment by tkyc** [comment]
Hello, let me know if there's anything else I can do to move this forward.

**Comment by tkyc** [comment]
Hello, just bumping the thread. Let me know if there's anything I can do to progress this towards integration. I'll check back in the new year as right now I'm on vacation.

**Comment by tkyc** [comment]
Let me know how I can progress this towards integration. Thanks.

**Comment by tkyc** [comment]
Let me know how I can progress this towards integration. Thanks.

**Comment by tkyc** [comment]
Commenting for activity. Let me know how I can progress this towards integration. Thanks.

**Pull request closed without merging**
