### PR TITLE
8267695: Bump update version for OpenJDK: jdk-11.0.13

### PR DESCRIPTION
**Pull request by GoeLin**
Change to bump the version to 11.0.13 and to update .jcheck/conf.

That is needed so that JBS annotates the right version when closing changes.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267695](https://bugs.openjdk.java.net/browse/JDK-8267695): Bump update version for OpenJDK: jdk-11.0.13 ⚠️ Issue is not open.

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/7/head:pull/7` \
`$ git checkout pull/7`

Update a local copy of the PR: \
`$ git checkout pull/7` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/7/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7`

View PR using the GUI difftool: \
`$ git pr show -t 7`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/7.diff">https://git.openjdk.java.net/jdk11u-dev/pull/7.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by jerboaa** [comment]
@edvbld @rwestberg Any idea why I show up as "Committer" in the "Reviewers" section of this issue added by the bots? Shouldn't that be "Reviewer"? See:
https://openjdk.java.net/census#sgehwolf

**Comment by kevinrushforth** [comment]
@jerboaa This is because the current version of `.jcheck/conf` is incorrectly pointing to the `jdk10` project, in which you are a Committer, and not the `jdk-updates` project. Once this PR is integrated you should no longer see this problem.

**Comment by jerboaa** [comment]
@kevinrushforth Thanks! That clears things up. Much appreciated!

**Review by erikj79 — APPROVED** [review]

**Comment by jerboaa** [comment]
@GoeLin Since this has been pushed with https://github.com/openjdk/jdk11u-dev/commit/2d768280fb67252343ee161be63b627a8bc7746b please close this PR.

**Pull request closed without merging**
