### PR TITLE
8281811: assert(_base == Tuple) failed: Not a Tuple after JDK-8280799

### PR DESCRIPTION
**Pull request by rwestrel**
This change doesn't apply cleanly. It requires a GC API method that's not available in 11. There's already adhoc code for shenandoah in PhaseIdealLoop::build_and_optimize() to replace the missing API call. The backported patch uses the same logic. Tested with tier1 and the patch's test case (fails without the fix, passes with it).

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8281811](https://bugs.openjdk.java.net/browse/JDK-8281811): assert(_base == Tuple) failed: Not a Tuple after JDK-8280799

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**) ⚠️ Review applies to 00ea7ad222b817bfbc0be491b74d2e1104b6baef

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/1049/head:pull/1049` \
`$ git checkout pull/1049`

Update a local copy of the PR: \
`$ git checkout pull/1049` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/1049/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1049`

View PR using the GUI difftool: \
`$ git pr show -t 1049`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/1049.diff">https://git.openjdk.java.net/jdk11u-dev/pull/1049.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
https://github.com/openjdk/jdk/commit/8849b1c7b7d85f3e4fe1706a5dcebcdb5f397583 may be a bit hard to backport, so, I'm ok with your Shenandoah specific replacement.

**Comment by rwestrel** [comment]
> [openjdk/jdk@8849b1c](https://github.com/openjdk/jdk/commit/8849b1c7b7d85f3e4fe1706a5dcebcdb5f397583) may be a bit hard to backport, so, I'm ok with your Shenandoah specific replacement.

Thanks for the review!

**Comment by VladimirKempik** [comment]
it's good this goes in pair with JDK-8280799. as JDK-8280799 alone can cause a crash on release buidls too.

**Comment by GoeLin** [comment]
What is wrong with the tests?

**Comment by rwestrel** [comment]
> What is wrong with the tests?

It's fixed by #1042 
I intend to push this one and #1042 #1035 together so #1035 doesn't introduce regressions.

**Pull request closed without merging**
