### PR TITLE
8265980: Fix systemDictionary and loaderConstraints printing

### PR DESCRIPTION
**Pull request by yukikimmura**
I would like to backport
JDK-8265980 Fix systemDictionary and loaderConstraints printing
Because the systemDictionary infomation is important for develoers or users to maintain JVM.
I would appriciate if someone could review it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8265980](https://bugs.openjdk.org/browse/JDK-8265980): Fix systemDictionary and loaderConstraints printing (**Enhancement** - P4)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1938/head:pull/1938` \
`$ git checkout pull/1938`

Update a local copy of the PR: \
`$ git checkout pull/1938` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1938/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1938`

View PR using the GUI difftool: \
`$ git pr show -t 1938`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1938.diff">https://git.openjdk.org/jdk11u-dev/pull/1938.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1938#issuecomment-1583856961)

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
The changes to loaderConstraints.hpp, dictionary.cpp, and systemDictionary.cpp/hpp are missing, and the PR changes DumpSymbolAndStringTable.java while the original commit dos not.

**Comment by yukikimmura** [comment]
Hello Paul,
Thank you for the review.

The original patch does not apply cleanly to 11u.

dictionary.cpp:
Removing an new line character in DictionaryEntry::print_count() is unnecessary because print_count() is not called from Dictionary::print_on() in JDK11,
hence adding an new line character after print_count() in DictionaryEntry::add_protection_domain() is unnecessary.
If the specification of DictionaryEntry::print_count() should be the same for respecting the original commit, I will fix it.

systemDictionary.cpp/hpp:
These are the fix related to JDK-8259839, but which are not backported to JDK11.
Therefore, I didn't apply this fix.

loaderConstraints.hpp, DumpSymbolAndStringTable.java:
I applied the original commit.

Thanks,
Kimura Yukihiro

**Review by phohensee — CHANGES_REQUESTED** [review]
Thanks for the explanation of your changes. Looks good now, except please add the original commit's changes to print_count() and add_protection_domain in dictionary.cpp, in order to make future backports easier.

**Comment by yukikimmura** [comment]
Hello Paul,
Thank you for your advice.

I added the original commit's changes to print_count() and add_protection_domain,
and I verified that the -Xlog:protectiondomain=trace logs are correct.

Thanks,
Kimura Yukihiro

**Review by phohensee — APPROVED** [review]
Looks good now. Thanks for making the changes!

**Comment by GoeLin** [comment]
Can you please add the empty line in loaderConstraints.cpp:194? 
(Not to the output, but to the code.)  It is the first line of add_entry().

**Review by phohensee — APPROVED** [review]

**Pull request closed without merging**
