### PR TITLE
8265524 Upgrading JSZip from v3.2.2 to v3.6.0

### PR DESCRIPTION
**Pull request by GoeLin**
I want to "backport" 8265524 to jdk11u.
Unfortunately, the original issue has no patch attached, it's only Oracle internal.
So normal backporting does not work.

Luckily, the bug nicely describes where to get the sources, so I crafted the change myself.
So please review. Ev. compare to https://github.com/Stuk/jszip/releases v.3.6.0.
I also adapted the license as happened in "JDK-8236700 Upgrading JSZip from v3.1.5 to v3.2.2".
That is the MIT license from th jszip github repo.

I'm not completely clear whether this should be considered a Backport, or a new Enhancement.
Also, I guess, the bots will not grok this is a backport, I will have to update the JBS issue accordingly.
I might even have a problem submitting this because I used the bugID of the original issue.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265524](https://bugs.openjdk.java.net/browse/JDK-8265524): Upgrading JSZip from v3.2.2  to v3.6.0 ⚠️ Issue is not open.

### Reviewers
 * [Martin Doerr](https://openjdk.java.net/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/439/head:pull/439` \
`$ git checkout pull/439`

Update a local copy of the PR: \
`$ git checkout pull/439` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/439/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 439`

View PR using the GUI difftool: \
`$ git pr show -t 439`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/439.diff">https://git.openjdk.java.net/jdk11u-dev/pull/439.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
> I'm not completely clear whether this should be considered a Backport, or a new Enhancement.
> Also, I guess, the bots will not grok this is a backport, I will have to update the JBS issue accordingly.
> I might even have a problem submitting this because I used the bugID of the original issue.

This will work as expected. The Skara bots will happily create or update a backport record if you use the main bug ID.

**Comment by GoeLin** [comment]
Thanks, Kevin!  (How did you pick this out from my many PRs?)

**Comment by RealCLanger** [comment]
> > I'm not completely clear whether this should be considered a Backport, or a new Enhancement.
> > Also, I guess, the bots will not grok this is a backport, I will have to update the JBS issue accordingly.
> > I might even have a problem submitting this because I used the bugID of the original issue.
> 
> This will work as expected. The Skara bots will happily create or update a backport record if you use the main bug ID.

The PR title should be Backport 'JDK-8265524', correct?

**Comment by kevinrushforth** [comment]
> The PR title should be Backport 'JDK-8265524', correct?

No, the PR title is correct as-is.

A backport-style PR needs a 40-char commit hash (which this one doesn't have). So this is just an "ordinary-style" PR.

Regardless of what type of PR it is, once the fix is integrated, Skara will do the same thing as for any commit that is pushed: look up the bug ID, check the fix version of the repo that the fix went into, find a matching record (main bug or backport) or create one if there is no matching record alread.

**Review by TheRealMDoerr — APPROVED** [review]
The change is basically https://github.com/Stuk/jszip/commit/7d4caa8c81b594409ca28dff9eeae510532aa1c8#diff-28c21f37443769bcb7d91e2fc9c31b12facd68b9401dd61b305d131eab93ddc8.
LGTM.

**Pull request closed without merging**
