### PR TITLE
8280041: Retry loop issues in java.io.ClassCache

### PR DESCRIPTION
**Pull request by rkennke**
This backports the fix for JDK-8280041, which fixes a number of small issues with the preceding change for JDK-8277072.
The original change has baked for several weeks in jdk19. One of the tests needed a small adjustment because the API Reference.refersTo() does not exist in JDK 11.

Testing:
 - [x] tier1
 - [x] tier2
 - [x] tier3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280041](https://bugs.openjdk.java.net/browse/JDK-8280041): Retry loop issues in java.io.ClassCache

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - **Reviewer**) ⚠️ Review applies to fdd0c9af41e81fd1ce1bc8a3db6cec074e0f3ac8
 * [Peter Levart](https://openjdk.java.net/census#plevart) (@plevart - **Reviewer**) ⚠️ Review applies to fdd0c9af41e81fd1ce1bc8a3db6cec074e0f3ac8

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/887/head:pull/887` \
`$ git checkout pull/887`

Update a local copy of the PR: \
`$ git checkout pull/887` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/887/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 887`

View PR using the GUI difftool: \
`$ git pr show -t 887`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/887.diff">https://git.openjdk.java.net/jdk11u-dev/pull/887.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
@rkennek I remove the fix-request tag. There seems to be no progress on this and I keep checking the three
changes for progress over and over. Please add the tag again once the follow-ups are ready to go, especially reviewed.

**Comment by rkennke** [comment]
@plevart @shipilev @RogerRiggs if you find some time, could you please review this backport? Thank you!

**Review by shipilev — APPROVED** [review]
> One of the tests needed a small adjustment because the API Reference.refersTo() does not exist in JDK 11.

I don't see where.

Looks good otherwise.

**Comment by rkennke** [comment]
> > One of the tests needed a small adjustment because the API Reference.refersTo() does not exist in JDK 11.
> 
> I don't see where.

Actually, I think that comment applies to PR #869. Dependent PRs seems to have made a little mess in GH review tab.

> Looks good otherwise.

Thank you!

**Comment by GoeLin** [comment]
Pre-submit failures: gcc issued, unrelated.

**Comment by plevart** [comment]
Hi, sorry for late reply. The changes look good. There are usual caveats about the use of `Reference.get() != null` vs. `!Reference.refersTo(null)` in that the former might contribute to keeping the referent alive, but in the last test this seems not to be the case so it is good as is.

**Review by plevart — APPROVED** [review]

**Pull request closed without merging**
