### PR TITLE
8313643: Update HarfBuzz to 8.2.2

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8313643](https://bugs.openjdk.org/browse/JDK-8313643)

Unclean Backport:
- `src/java.desktop/share/native/libharfbuzz/hb-subset.cc`
  - Manually merged the code of bellow; 
  - This file change could be considered as `Clean`

```diff
@@ -43,21 +43,19 @@
 #include "OT/Color/sbix/sbix.hh"
 #include "hb-ot-os2-table.hh"
 #include "hb-ot-post-table.hh"
-
-#if !defined(AIX) || defined(AIX_XLC_GE_17)
 #include "hb-ot-post-table-v2subset.hh"
-#endif
-
 #include "hb-ot-cff1-table.hh"
 #include "hb-ot-cff2-table.hh"
 #include "hb-ot-vorg-table.hh"
 #include "hb-ot-name-table.hh"
 #include "hb-ot-layout-gsub-table.hh"
 #include "hb-ot-layout-gpos-table.hh"
+#include "hb-ot-var-avar-table.hh"
 #include "hb-ot-var-cvar-table.hh"
 #include "hb-ot-var-fvar-table.hh"
 #include "hb-ot-var-gvar-table.hh"
 #include "hb-ot-var-hvar-table.hh"
+#include "hb-ot-var-mvar-table.hh"
 #include "hb-ot-math-table.hh"
 #include "hb-ot-stat-table.hh"
 #include "hb-repacker.hh"
```

- `make/modules/java.desktop/lib/Awt2dLibraries.gmk`
  - Manually merged the code of bellow to the file `make/lib/Awt2dLibraries.gmk`.
  - This file change could be considered as `Clean`

```diff
@@ -495,6 +495,11 @@
    # hb-ft.cc is not presently needed, and requires freetype 2.4.2 or later.
    LIBFONTMANAGER_EXCLUDE_FILES += libharfbuzz/hb-ft.cc
 
+   # list of disabled warnings and the compilers for which it was specifically added.
+   # array-bounds         -> GCC 12 on Alpine Linux
+   # parentheses          -> GCC 6
+   # range-loop-analysis  -> clang on Xcode12
+
    HARFBUZZ_DISABLED_WARNINGS_gcc := missing-field-initializers strict-aliasing \
        unused-result array-bounds parentheses
    # noexcept-type required for GCC 7 builds. Not required for GCC 8+.
```

Tests
- PR: All checks have passed
- SAP nightlies passed on `2023-12-21,22,23,24`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8313643](https://bugs.openjdk.org/browse/JDK-8313643) needs maintainer approval

### Issue
 * [JDK-8313643](https://bugs.openjdk.org/browse/JDK-8313643): Update HarfBuzz to 8.2.2 (**Bug** - P3 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2398/head:pull/2398` \
`$ git checkout pull/2398`

Update a local copy of the PR: \
`$ git checkout pull/2398` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2398/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2398`

View PR using the GUI difftool: \
`$ git pr show -t 2398`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2398.diff">https://git.openjdk.org/jdk11u-dev/pull/2398.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2398#issuecomment-1857486889)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @amosshi, if you base this on the 17u backport it will be clean. Just adapt the title of the PR...

**Comment by amosshi** [comment]
> Hi @amosshi, if you base this on the 17u backport it will be clean. Just adapt the title of the PR...

Change to the 17 commit id: [0bc91f60d28567f888eee948dbb156c1405bbeeb](https://git.openjdk.org/jdk17u-dev/commit/0bc91f60d28567f888eee948dbb156c1405bbeeb)

**Review by MBaesken — APPROVED** [review]

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.23-oracle. UnClean backport. SAP nightlies passed on 2023-12-24”

**Pull request closed without merging**
