### PR TITLE
8274606: Fix jaxp/javax/xml/jaxp/unittest/transform/SurrogateTest.java test

### PR DESCRIPTION
**Pull request by Nagata-Haruhito**
Here is backport of JDK-8274606 for jdk11u.
This is a test fix and applied clean.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8274606](https://bugs.openjdk.org/browse/JDK-8274606): Fix jaxp/javax/xml/jaxp/unittest/transform/SurrogateTest.java test (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1934/head:pull/1934` \
`$ git checkout pull/1934`

Update a local copy of the PR: \
`$ git checkout pull/1934` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1934/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1934`

View PR using the GUI difftool: \
`$ git pr show -t 1934`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1934.diff">https://git.openjdk.org/jdk11u-dev/pull/1934.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1934#issuecomment-1578318484)

### CODE REVIEW

**Comment by Nagata-Haruhito** [comment]
Would someone please review this PR?

**Comment by phohensee** [comment]
/clean

Clean backport from 17u.

**Comment by GoeLin** [comment]
Did you run the test?

**Comment by Nagata-Haruhito** [comment]
Sorry, I missed operation to paste fix source. 
I run the fixed test and got passed.

**Pull request closed without merging**
