### PR TITLE
8289764: gc/lock tests failed with "OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects"

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8289764](https://bugs.openjdk.org/browse/JDK-8289764)

- The following files are manually merged, can be consider as `clean` because the business logic is unchanged and inline with the original commit
  - test/hotspot/jtreg/vmTestbase/gc/lock/jni/jnilock001/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/gc/lock/jniref/jniglobalreflock01/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/gc/lock/jniref/jnilocalreflock01/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/gc/lock/jniref/jnireflock01/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/gc/lock/jniref/jniweakglobalreflock01/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/gc/lock/jvmti/alloc/jvmtialloclock01/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/gc/lock/malloc/malloclock01/TestDescription.java
  - test/hotspot/jtreg/vmTestbase/nsk/share/gc/gp/GarbageUtils.java - The `Copyright year` is manually merged
- We have made the following change to make the code work on Java 11
  - Change `jdk.test.whitebox.WhiteBox` to `sun.hotspot.WhiteBox`
  - Change `jdk.test.lib.helpers.ClassFileInstaller` to `ClassFileInstaller`

Testing
- Local: passed
  - jtreg test against `test/hotspot/jtreg/vmTestbase/gc/lock/`
  - result: `Test results: passed: 7`
- Pipeline: All checks have passed
- Testing Machine: SAP nightlies passed on `2024-01-25,26`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8289764](https://bugs.openjdk.org/browse/JDK-8289764) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8289764](https://bugs.openjdk.org/browse/JDK-8289764): gc/lock tests failed with "OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects" (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2469/head:pull/2469` \
`$ git checkout pull/2469`

Update a local copy of the PR: \
`$ git checkout pull/2469` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2469/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2469`

View PR using the GUI difftool: \
`$ git pr show -t 2469`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2469.diff">https://git.openjdk.org/jdk11u-dev/pull/2469.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2469#issuecomment-1903746847)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM. Thanks for the description!

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.23-oracle. No risk, test fix. Clean backport. SAP nightlies passed on 2024-01-25,26”

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.23-oracle. No risk, test fix. Un-Clean backport. SAP nightlies passed on 2024-01-25,26”

**Pull request closed without merging**
