### PR TITLE
8207200: Committed > max memory usage when getting MemoryUsage

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 11.0.22-oracle.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8207200](https://bugs.openjdk.org/browse/JDK-8207200) needs maintainer approval
- [ ] [JDK-8209061](https://bugs.openjdk.org/browse/JDK-8209061) needs maintainer approval
- [ ] [JDK-8209062](https://bugs.openjdk.org/browse/JDK-8209062) needs maintainer approval

### Issues
 * [JDK-8207200](https://bugs.openjdk.org/browse/JDK-8207200): Committed &gt; max memory usage when getting MemoryUsage (**Bug** - P3)
 * [JDK-8209061](https://bugs.openjdk.org/browse/JDK-8209061): Move G1 serviceability functionality to G1MonitoringSupport (**Enhancement** - P4)
 * [JDK-8209062](https://bugs.openjdk.org/browse/JDK-8209062): Clean up G1MonitoringSupport (**Enhancement** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2281/head:pull/2281` \
`$ git checkout pull/2281`

Update a local copy of the PR: \
`$ git checkout pull/2281` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2281/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2281`

View PR using the GUI difftool: \
`$ git pr show -t 2281`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2281.diff">https://git.openjdk.org/jdk11u-dev/pull/2281.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2281#issuecomment-1818291310)

### CODE REVIEW

**Comment by jerboaa** [comment]
This seems a fairly risky backport for a somewhat minor issue that it tries to solve. Are you sure this one is appropriate for  OpenJDK 11u in its current lifecyce? Also, I agree with @RealCLanger on [his comment ](https://bugs.openjdk.org/browse/JDK-8207200?focusedId=14390322&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14390322) on the bug and what he said, hasn't changed IMO.

**Comment by GoeLin** [comment]
Hi @jerboaa 
There are a few points to this. 
First, I don't think the issue is that minor. As I understand it, the MemoryUsage reported is always bogus since the values can be updated concurrently. It only became apparent when committed exceeded max.
Further, two things have changed since 2020:
Oracle obviously considers the risk acceptable.
OpenJDK falls back behind Oracle JDK and reports wrong values. 

Finally, others asked for this, too: Man Cao in https://bugs.openjdk.org/browse/JDK-8209061

If you agree, I would ask Andrew to backport the four changes involved individually and ask Richard, our GC expert, to review them.
What do you think?
(JDK-8208498, JDK-8209061, JDK-8209062, JDK-8207200)

**Pull request closed without merging**
