### PR TITLE
8235385: Crash on aarch64 JDK due to long offset

### PR DESCRIPTION
**Pull request by apavlyutkin**
This is just a copying of tests added to jdk-8 by 8235385

Verification: hotspot_compiler on arm64/18.04.6

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8235385](https://bugs.openjdk.org/browse/JDK-8235385): Crash on aarch64 JDK due to long offset
 * [JDK-8287508](https://bugs.openjdk.org/browse/JDK-8287508): The tests added to jdk-8 by 8235385 are to be ported to jdk-11

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1122/head:pull/1122` \
`$ git checkout pull/1122`

Update a local copy of the PR: \
`$ git checkout pull/1122` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1122/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1122`

View PR using the GUI difftool: \
`$ git pr show -t 1122`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1122.diff">https://git.openjdk.org/jdk11u-dev/pull/1122.diff</a>

</details>

### CODE REVIEW

**Comment by apavlyutkin** [comment]
> Hi, the state of https://bugs.openjdk.java.net/browse/JDK-8287508 looks weird. It was marked as resolved by the jdk8u-dev commit. We can theoretically reopen it for this push. But I have another question: Why don't you bring these tests to OpenJDK head in first place and backport it down from there?

The fix makes sense only for 8 & 11, that have only lite version of 8235385 patch. The full patch along with tests were applied to 15, so there is not reason bring the test to the upstream

**Comment by gnu-andrew** [comment]
I believe you need to change the title of this to "Backport 820ab134927cb76c61cf9c144637d18e0e2a4f2c"

That should make SKARA pick it up as a "backport" of the 8u commit (even though technically it's going in the wrong direction)

I hadn't realised this was in 15u. How did it get lost for 11u?

**Comment by apavlyutkin** [comment]
> I believe you need to change the title of this to "Backport 820ab134927cb76c61cf9c144637d18e0e2a4f2c"
> 
> That should make SKARA pick it up as a "backport" of the 8u commit (even though technically it's going in the wrong direction)
> 
> I hadn't realised this was in 15u. How did it get lost for 11u?

The original patch

https://github.com/openjdk/jdk15u-dev/commit/21c02a5b18a8f8b0ab66f32fbb9fe7cff415376d

was really huge and too risky to be backported to 11u, and it was decided to backport a lite version of it. Thus technically that wasn't a backport and I forgot to publish the tests.

**Comment by apavlyutkin** [comment]
We've just got a response from customer that patching of only STR instructions is not enough and LDR ones are to be patched too. Thus I'm closing this one and going to update 8287508

**Pull request closed without merging**
