### PR TITLE
8179503: Java should support GET OCSP calls

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi, here is backport of [JDK-8179503](https://bugs.openjdk.org/browse/JDK-8179503) that adds support of GET OCSP calls for parity with Oracle: in spite of the fact that JBS issue is not labelled with any Oracle release, this one is mandatory for [JDK-8274471](https://bugs.openjdk.org/browse/JDK-8274471) released to 11.0.18-oracle

Original patch applied with the only change

**`src/java.base/share/classes/sun/security/provider/certpath/OCSP.java`**
- resolved baseline conflict related to revokation checking

Verification (amd64/20.04): newly added `test/jdk/java/security/cert/CertPathValidator/OCSP/GetAndPostTests.java`
Regression  (amd64/20.04): `jdk_security`

@TheRealMDoerr I raised this one instead of already reviewed https://github.com/openjdk/jdk11u-dev/pull/847. Please check it out

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [ ] [JDK-8179503](https://bugs.openjdk.org/browse/JDK-8179503) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8179503](https://bugs.openjdk.org/browse/JDK-8179503): Java should support GET OCSP calls (**Enhancement** - P3)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1917/head:pull/1917` \
`$ git checkout pull/1917`

Update a local copy of the PR: \
`$ git checkout pull/1917` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1917/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1917`

View PR using the GUI difftool: \
`$ git pr show -t 1917`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1917.diff">https://git.openjdk.org/jdk11u-dev/pull/1917.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1917#issuecomment-1569819284)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Still good.

**Comment by apavlyutkin** [comment]
Please don't close this, bot.

**Comment by apavlyutkin** [comment]
There is no a blocker anymore

**Comment by GoeLin** [comment]
Please also request the follow up change in PR 1920. I will approve both.

**Comment by apavlyutkin** [comment]
> Please also request the follow up change in PR 1920. I will approve both.

This is a chain of 4 dependent PR's: 1917 (this one), 1918 (not yet reviewed), 1920 (reviewed), and 1921 (clean), and 1920 makes sense only on top of 1918.

**Comment by GoeLin** [comment]
Hi, I think it would be good to merge head into these, maybe into the topmost change of the chain of dependent fixes.
This would cause the tests to run again.

**Comment by alexey-pavlyutkin** [comment]
Hi, Goetz, let's make it AFTER all the changes get reviewed. Once I rebased the original chain (this one is just a copy) through a year of master and Github went crazy, it correctly displayed the delta as a patch, but at the same time review pane also showed all the commits to master for this year making review just impossible, and exactly that is the reason why I created this copy of the original chain. Thank you

**Comment by GoeLin** [comment]
Hi, ok, I am waiting for PR 1918 being reviewed. 
I ran 1917, 1918 and 1920 through our testing. I had to grep the patches and do some simple resolves. Unfortunately, 1918 does not compile:
java.base/share/classes/sun/security/x509/X509CertImpl.java:1087: error: unreported exception IOException; must be caught or declared to be thrown
        return algId == null ? null : algId.getEncodedParams();
Actually there was a row of other patches in the nightbuild, but after removing these three it worked.

**Comment by apavlyutkin** [comment]
I do not observe the problem
```
Creating jdk image
Stopping sjavac server
Finished building target 'images' in configuration 'linux-x86_64-normal-server-release'
alex@alex-vbox:~/jdk11u-dev$ git status
On branch 8274471_
Your branch is up to date with 'origin/8274471_'.

nothing to commit, working tree clean
alex@alex-vbox:~/jdk11u-dev$ git log
commit 6192658292ae314236fcd63591438f8b5ed17db0 (HEAD -> 8274471_, origin/8274471_)
Author: Alexey Pavlyutkin <apavlyutkin@azul.com>
Date:   Wed May 31 13:46:34 2023 +0300

    Backport f63c4a832a1aea451f47aaf86d5361e970c6a28f

commit 2355e23d467afc603867d87c8820149d20727c46 (origin/8179503_, 8179503_)
Author: Alexey Pavlyutkin <apavlyutkin@azul.com>
Date:   Wed May 31 12:04:56 2023 +0300

    Backport f5ee356540d7aa4a7663c0d5d74f5fdb0726b426

commit b2faa3567e3b934689845025333c41bcbfe18b1e (origin/master, origin/HEAD, master)

Author: Goetz Lindenmaier <goetz@openjdk.org>
Date:   Tue May 30 16:40:22 2023 +0000

    8309108: Bump update version for OpenJDK: jdk-11.0.21

    Reviewed-by: mdoerr
```
It looks like for some reason your nigthbuild didn't incorporate all the changes

https://github.com/openjdk/jdk11u-dev/pull/1918/files#diff-bfcfa1bb8e1022116232bea13c3b15a51955d853a5a06c2b8fd5b264a07e8d6dL294

**Pull request closed without merging**
