### PR TITLE
8248414: AArch64: Remove uses of long and unsigned long ints

### PR DESCRIPTION
**Pull request by VladimirKempik**
This is a backport of 8248414 to jdk11u-dev

The backport didn't apply clean, partially due to backport of JDK-8247766

It's needed for mac-aarch and win-aarch64 ports

It will be followed by 8250824 and 8251930.

Sections of aarch64.ad file between line 10260-12560 were regenerated from aarch64_ad.m4

Original commit - https://github.com/openjdk/jdk/commit/c7d84850bfdbd112a495fab453a79832e3810f47

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8248414](https://bugs.openjdk.java.net/browse/JDK-8248414): AArch64: Remove uses of long and unsigned long ints

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u-dev pull/215/head:pull/215` \
`$ git checkout pull/215`

Update a local copy of the PR: \
`$ git checkout pull/215` \
`$ git pull https://git.openjdk.java.net/jdk11u-dev pull/215/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 215`

View PR using the GUI difftool: \
`$ git pr show -t 215`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u-dev/pull/215.diff">https://git.openjdk.java.net/jdk11u-dev/pull/215.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by VladimirKempik** [comment]
Hello @phohensee , as this backport is also part of winaarch64 backport, I'm going to withdraw this to not make MS folks to do the job twice, could your repeat your approval there as well, the patches are almost identical https://github.com/openjdk/jdk11u-dev/pull/222

**Comment by phohensee** [comment]
Yes, this patch is almost identical to a small part of [#222](https://github.com/openjdk/jdk11u-dev/pull/222), but the latter is huge. I'll take a shot at reviewing it though.

**Comment by phohensee** [comment]
On second thought, see my comment on [#222](https://github.com/openjdk/jdk11u-dev/pull/222). I'd prefer to push this backport separately.

**Review by phohensee — COMMENTED** [review]
Did a little more spelunking and found that some of the changes in this patch (e.g., aarch64.ad) are in [JDK-8248403](https://bugs.openjdk.java.net/browse/JDK-8248403). I did a quick backport of that issue, see [#246](https://github.com/openjdk/jdk11u-dev/pull/246).

**Comment by theRealAph** [comment]
> On second thought, see my comment on [#222](https://github.com/openjdk/jdk11u-dev/pull/222). I'd prefer to push this backport separately.

Yes, definitely. The two integer type cleanup patches were because of Windows/Mac, but they are logically independent of the ports. It really wouldn't help to merge them.
In general, it is a good idea to commit pure cleanups (which these were, in the sense that they had no behavioral effect) separately from functional changes.

**Comment by theRealAph** [comment]
> In general, it is a good idea to commit pure cleanups (which these were, in the sense that they had no behavioral effect) separately from functional changes.

Substantial cleanups,I mean. I have no objection to tidying up bits and pieces as we go along,and John Rose has said that we should.

**Comment by phohensee** [comment]
Hi, Vladimir. Note that the current patch has a conflict in immediate_aarch64.cpp due to the backport of JDK-8248403.

**Comment by phohensee** [comment]
Note that your current patch has a conflict due to the backport of JDK-8248403. Please update the PR.

**Comment by VladimirKempik** [comment]
Thanks for heads up! fixed merge conflict

**Review by phohensee — APPROVED** [review]

**Pull request closed without merging**
