### PR TITLE
8317374: Add Let's Encrypt ISRG Root X2

### PR DESCRIPTION
**Pull request by jerboaa**
Unclean backport, but got resolved trivially. Pattern matching for switch isn't present in 11u. Test change in `VerifyCACerts.java` has slightly different context. Fixed those issues manually. Please review!

Testing:
- [x] GHA
- [x]  `test/jdk/sun/security/lib/cacerts` and `test/jdk/security/infra/java/security/cert/CertPathValidator` tests. All pass (including the new one `CAInterop.java#letsencryptisrgx2`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317374](https://bugs.openjdk.org/browse/JDK-8317374) needs maintainer approval

### Issue
 * [JDK-8317374](https://bugs.openjdk.org/browse/JDK-8317374): Add Let's Encrypt ISRG Root X2 (**Enhancement** - P2 - Approved)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2280/head:pull/2280` \
`$ git checkout pull/2280`

Update a local copy of the PR: \
`$ git checkout pull/2280` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2280/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2280`

View PR using the GUI difftool: \
`$ git pr show -t 2280`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2280.diff">https://git.openjdk.org/jdk11u-dev/pull/2280.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2280#issuecomment-1812312330)

### CODE REVIEW

**Comment by jerboaa** [comment]
Anyone willing to review this, please? Thanks!

**Review by GoeLin — APPROVED** [review]
LGTM

Hint: if you base this on the 17u commit, only the CAInterop change remains. 
The other two changes, adapting the path and the hash, are identical.
You can use "Backport <17u hash>.
It's a bummer we always have to resolve the switch syntax.

**Comment by jerboaa** [comment]
> Hint: if you base this on the 17u commit, only the CAInterop change remains.
> The other two changes, adapting the path and the hash, are identical.

I believe I did that. The context for 11u was still different enough for it to not apply cleanly.

> You can use "Backport <17u hash>.

In the PR?

> It's a bummer we always have to resolve the switch syntax.

Yeah.

**Comment by GoeLin** [comment]
> In the PR?
As title of the PR, or as title of the change you push for your PR.
You can also use the /backport command in any commit, but this won't help here as it's not clean.

**Pull request closed without merging**
