### PR TITLE
8274471: Add support for RSASSA-PSS in OCSP Response

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi!

Here is backport of [JDK-8274471](https://bugs.openjdk.org/browse/JDK-8274471) adding support of RSASSA-PSS signature to OCSP Response. Original patch applied with the following changes

**`src/java.base/share/classes/sun/security/provider/certpath/OCSP.java`**
- import of `java.security.cert.TrustAnchor` and `sun.security.validator.Validator` packages didn't removed cuz they are still in use;
- added import of `java.nio.charset.StandardCharsets.UTF_8` promoting `UTF_8` constant;
- the changes to revocation checking were skipped

**`src/java.base/share/classes/sun/security/util/SignatureUtil.java`**
- added import `sun.security.x509.AlgorithmId` package;
- the following required methods ported
```
    public static Signature fromKey(String sigAlg, PrivateKey key, String provider);
    public static Signature fromKey(String sigAlg, PrivateKey key, Provider provider);
    private static Signature autoInitInternal(String alg, PrivateKey key, Signature s);
    public static AlgorithmId fromSignature(Signature sigEngine, PrivateKey key);
```
- `EdEC` related code dropped
- `SignatureUtil.autoInitInternal()` method updated to use `AlgorithmId.getDefaultAlgorithmParameterSpec()` instead of almost identical `SignatureUtil.getDefaultParamSpec()`

**`src/java.base/share/classes/sun/security/x509/AlgorithmId.java`**
- `public byte[] getEncodedParams()` does not throw anymore

**`test/jdk/java/security/testlibrary/CertificateBuilder.java`**
**`test/jdk/java/security/testlibrary/SimpleOCSPServer.java`**
- added import of `sun.security.util.SignatureUtil` package

Verification/regression (amd64/LTS 20.04): `jdk_security` including updated tests

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8274471](https://bugs.openjdk.org/browse/JDK-8274471): Add support for RSASSA-PSS in OCSP Response

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1891/head:pull/1891` \
`$ git checkout pull/1891`

Update a local copy of the PR: \
`$ git checkout pull/1891` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1891/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1891`

View PR using the GUI difftool: \
`$ git pr show -t 1891`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1891.diff">https://git.openjdk.org/jdk11u-dev/pull/1891.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1891#issuecomment-1559889523)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
I'm not an expert in this area, but the backport looks good, including the addition of a big chunk of code in SignatureUtil.java from [JDK-8242068](https://bugs.openjdk.org/browse/JDK-8242068), which latter is huge and would anyway require a spec change.

**Comment by apavlyutkin** [comment]
Actually I'm not sure about EdDSA related delta, it's does not seem necessary for RSASSA-PSS support, and moreover original patch does not have the changes

https://github.com/openjdk/jdk/commit/f63c4a832a1aea451f47aaf86d5361e970c6a28f#diff-0393704a5343769f4ef9fa23b6fe9107d0ff96c17c078c30a05ef3be6c7d2304

but for some reason Git transfers them on `cherry-pick`. I could eliminate unnecesssary code, but I'm not sure if it's better to make more changes

**Comment by phohensee** [comment]
If it works without the EdDSA code, then don't include the latter.

**Review by phohensee — APPROVED** [review]

**Comment by apavlyutkin** [comment]
https://github.com/openjdk/jdk11u-dev/pull/1918 raised to replace this one

**Pull request closed without merging**
