### PR TITLE
8242151: Improve OID mapping and reuse among JDK security providers for aliases registration

### PR DESCRIPTION
**Pull request by GoeLin**
This change required some work to get it backported. 
I touched the following files to resolve or get the code/test working:

src/java.base/share/classes/com/sun/crypto/provider/SunJCE.java

These entries are not in 11:
        List<String> macSHA512_224Aliases = createAliasesWithOid(macOidBase + "12");
        List<String> macSHA512_256Aliases = createAliasesWithOid(macOidBase + "13");

        String nistHashAlgsOidBase = "2.16.840.1.101.3.4.2.";
        List<String> macSHA3_224Aliases =
            createAliasesWithOid(nistHashAlgsOidBase + "13");
        List<String> macSHA3_256Aliases =
            createAliasesWithOid(nistHashAlgsOidBase + "14");
        List<String> macSHA3_384Aliases =
            createAliasesWithOid(nistHashAlgsOidBase + "15");
        List<String> macSHA3_512Aliases =
            createAliasesWithOid(nistHashAlgsOidBase + "16");

Thus I could not remove them.
Also, the Hmac keys differ. Some are not in 11.

src/java.base/share/classes/java/security/cert/CertificateRevokedException.java
Copyright.

src/java.base/share/classes/sun/security/pkcs/PKCS7.java
src/java.base/share/classes/sun/security/pkcs/PKCS9Attribute.java
Already applied in "8268801: Improve PKCS attribute handling"

src/java.base/share/classes/sun/security/pkcs12/PKCS12KeyStore.java
Resolve imports due to context.

src/java.base/share/classes/sun/security/provider/KeyProtector.java
Copyright

src/java.base/share/classes/sun/security/ssl/SunJSSE.java
Resolved due to context.

src/java.base/share/classes/sun/security/ssl/X509KeyManagerImpl.java
Copyright.

src/java.base/share/classes/sun/security/tools/keytool/Main.java
Basically applied by hand.

src/java.base/share/classes/sun/security/util/ConstraintsParameters.java
This file was turned into an interface by "8249906: Enhance opening JARs" which
moved the implementation to CertPathConstraintsParameters.java and DisabledAlgorithmConstraints.
8249906 was applied later than this change, but is already in 11.

The method getNamedCurveFromKey(Key key) was moved to DisabledAlgorithmConstraints, I
applied the hunk there similar as in 17.

src/java.base/share/classes/sun/security/util/CurveDB.java
I had to resolve because "8226307: Curve names should be case-insensitive" is not in 11.

src/java.base/share/classes/sun/security/util/KnownOIDs.java,
Already in 11, a small difference in line 428 which seem fine to me.

src/java.base/share/classes/sun/security/util/ObjectIdentifier.java
Most parts already backported by "8268801: Improve PKCS attribute handling"

src/java.base/share/classes/sun/security/util/SecurityProviderConstants.java
Trivial resolve due to context.

src/java.base/share/classes/sun/security/x509/AVA.java
Copyright

src/java.base/share/classes/sun/security/x509/AlgorithmId.java
I had to resolve bigger parts of this.
In addition, I removed the three cases added in "8266929: Unable to use algorithms from 3p providers"
These entries are in KnownOid.java and should still properly be handled.

src/java.base/share/classes/sun/security/x509/OIDName.java
Copyright

src/java.security.jgss/share/classes/sun/security/jgss/GSSNameImpl.java
src/java.security.jgss/share/classes/sun/security/jgss/wrapper/GSSNameElement.java
src/java.security.jgss/share/classes/sun/security/jgss/wrapper/NativeGSSContext.java
Copyright

src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
Resolved, there was ChaCha20 in the context.

For ChaCha20, I implemented the change myself:
removing the s() call and changeing the outer
call from d() to dA().
KnownID.java contains these mappings.

src/jdk.crypto.ec/share/classes/sun/security/ec/SunEC.java
One hunk is not needed because "8166597: Crypto support for the EdDSA Signature Algorithm" is not in 11.
Another I had to resolve.

src/jdk.crypto.ec/share/classes/sun/security/ec/XECParameters.java
Simple resolve due to context.

src/jdk.crypto.ec/share/classes/sun/security/ec/ed/EdDSAParameters.java
Skipped. File comes with "8166597: Crypto support for the EdDSA Signature Algorithm" which is not in 11.

test/jdk/sun/security/pkcs/pkcs9/UnknownAttribute.java
Already backported ? 

test/jdk/sun/security/pkcs12/ParamsPreferences.java
This test already received two further backports obviously subsuming the
changes of this one.

test/jdk/sun/security/pkcs12/ParamsTest.java
Test was renamed to KeytoolOpensslInteropTest.java in "8266182: Automate manual steps listed in the test jdk/sun/security/pkcs12/ParamsTest.java"
That test is already reworked. Only applied some minor fixes.

test/jdk/sun/security/tools/jarsigner/TimestampCheck.java
Test does not use the pattern to change any more.

test/jdk/sun/security/tools/keytool/KeyToolTest.java
Trivial resolves

To make tests compile, I had to adpat calls to
new ObjectIdentifier() in DerUtils.java, TsaSigner.java
to make it compile.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8242151](https://bugs.openjdk.org/browse/JDK-8242151): Improve OID mapping and reuse among JDK security providers for aliases registration (**Enhancement** - P3)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**) ⚠️ Review applies to [3de9041e](https://git.openjdk.org/jdk11u-dev/pull/1908/files/3de9041e9e41aabcd1c061f1a65fd5d40bd334f6)
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/1908/head:pull/1908` \
`$ git checkout pull/1908`

Update a local copy of the PR: \
`$ git checkout pull/1908` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/1908/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1908`

View PR using the GUI difftool: \
`$ git pr show -t 1908`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1908.diff">https://git.openjdk.org/jdk11u-dev/pull/1908.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/1908#issuecomment-1566956082)

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]
Thanks for backporting!

There are a few places where the old oid syntax is still in place in 11, e.g. src/java.base/share/classes/sun/security/pkcs/PKCS7.java
KP_TIMESTAMPING_OID, EXTENDED_KEY_USAGE_OID
(just an example)
Those could be addressed in a follow up change.

**Comment by martinuy** [comment]
Hi Goetz,

Thanks for proposing this backport.

A few minor comments:

  * In sun/security/util/ConstraintsParameters.java:
    * If there weren't any changes to the file, we should probably keep the current copyright date in the header.

  * In sun/security/util/CurveDB.java:
    * I have the impression that we don't need to call "trim" anymore because the curve name and aliases come from KnownOIDs and do not have any spaces at the beginning or end. This was necessary before because we were splitting strings such as "secp192r1 [NIST P-192, X9.62 prime192v1]" to get the name and aliases separately. You can check how this same information now comes from "secp192r1("1.2.840.10045.3.1.1", "secp192r1", "NIST P-192", "X9.62 prime192v1")" in KnownOIDs.

  * In sun/security/util/ObjectIdentifier.java:
    * Is it possible to remove "public ObjectIdentifier(int[] values)" and "public static ObjectIdentifier newInternal(int[] values)" now? This could be part of 8239264 backport perhaps. This will make help to check that there are no current uses and enforce that it's not used in the future.

  * In sun/security/x509/AlgorithmId.java:
    * There are a couple of OIDs which were not part of jdk11u: ed25519_oid and ed448_oid.
 
  * In sun/security/x509/OIDName.java:
    * Should we bump the copyright date?

  * In sun/security/jgss/GSSNameImpl.java:
    * Should we bump the copyright date?

  * In sun/security/jgss/wrapper/GSSNameElement.java:
    * Should we bump the copyright date?

  * In sun/security/jgss/wrapper/NativeGSSContext.java:
    * Should we bump the copyright date?

  * In sun/security/ec/SunEC.java:
    * I think that we can remove the import of java.util.regex.Pattern because it's unused.

  * In sun/security/pkcs12/ParamsPreferences.java:
    * I'd add that 8242151 is related to this test.
 
  * In sun/security/tools/keytool/KeyToolTest.java:
    * Copyright date bump?
    * Shouldn't we indicate that it's related to 8242151?

  * Shouldn't we indicate that KeytoolOpensslInteropTest.java is related to 8242151?

Other than that, looks good to me.

Regards,
Martin.-

**Comment by martinuy** [comment]
> > In sun/security/util/ConstraintsParameters.java:
> > If there weren't any changes to the file, we should probably keep the current copyright date in the header.
> 
> We usually always backport the Copyrights and resolve to the later year if necessary. This file should have been edited by this change, but the edit was made in 8249906 which forgot to adapt the Copyright. So I would like adapt this now here.

Ah, good.

> > In sun/security/util/ObjectIdentifier.java:
> > Is it possible to remove "public ObjectIdentifier(int[] values)" and "public static ObjectIdentifier newInternal(int[] values)" now? This could be part of 8239264 backport perhaps. This will make help to check that there are no current uses and enforce that it's not used in the future.
> 
> I removed it before. Build and tests pass without it. But Matthias asked me to add it again to not break compatibility.
>

Hmm, I tend to agree with your initial decision but ok. This is an internal API (based on the package). It's good to know that no one internally is currently using it. My only concern is that someone in the future does, if we keep it available. Anyways, let's move on.

**Pull request closed without merging**
