### PR TITLE
8330063: Upgrade jQuery to 3.7.1

### PR DESCRIPTION
**Pull request by MBaesken**
Backport from 17, manual; javadoc-search.js is not in 11

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8330063](https://bugs.openjdk.org/browse/JDK-8330063) needs maintainer approval

### Issue
 * [JDK-8330063](https://bugs.openjdk.org/browse/JDK-8330063): Upgrade jQuery to 3.7.1 (**Bug** - P3 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2847/head:pull/2847` \
`$ git checkout pull/2847`

Update a local copy of the PR: \
`$ git checkout pull/2847` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2847/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2847`

View PR using the GUI difftool: \
`$ git pr show -t 2847`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2847.diff">https://git.openjdk.org/jdk11u-dev/pull/2847.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2847#issuecomment-2221373713)

### CODE REVIEW

**Review by RealLucy — APPROVED** [review]
Looks good.
Please double-check the GHA results.

**Comment by MBaesken** [comment]
Pre-submit tests - linux-x64 / test - Test (tier1)  - upload failed, infra issue

**Comment by MBaesken** [comment]
macOS builds broken (GHA needs adustment); Windows error - upload issue .

**Pull request closed without merging**
