### PR TITLE
8296715: CLDR v42 update for tzdata 2022f

### PR DESCRIPTION
**Pull request by MBaesken**
Backport of 8296715; es_419.xml has different path, otherwise close to 13u backport

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296715](https://bugs.openjdk.org/browse/JDK-8296715): CLDR v42 update for tzdata 2022f

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)
 * [Yuri Nesterenko](https://openjdk.org/census#yan) (@yan-too - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1560/head:pull/1560` \
`$ git checkout pull/1560`

Update a local copy of the PR: \
`$ git checkout pull/1560` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1560/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1560`

View PR using the GUI difftool: \
`$ git pr show -t 1560`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1560.diff">https://git.openjdk.org/jdk11u-dev/pull/1560.diff</a>

</details>

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
Ok, `src/jdk.localedata/share/classes/sun/util/cldr/resources/common/main/es_MX.xml` doesn't contain the part which got modified upstream. LGTM.

**Review by yan-too — APPROVED** [review]
Fine with me!

**Comment by MBaesken** [comment]
Hi Martin and Yuri, thanks for the reviews !

**Pull request closed without merging**
