### PR TITLE
8335801: [11u] Backport of 8210988 to 11u removes gcc warnings

### PR DESCRIPTION
**Pull request by gnu-andrew**
The backport of 8210988 contained a number of issues, the most serious of which is it completely removed warnings from `gcc` builds by changing `WARNING_CFLAGS_JDK` and `WARNING_CFLAGS_JVM`, but not defining `WARNINGS_ENABLE_ALL`, `WARNINGS_ENABLE_ADDITIONAL_JVM` and `DISABLED_WARNINGS`.

The other more minor issues are the silent inclusion of `-Wreorder` to clang builds (should be a backport of [JDK-8208672](https://bugs.openjdk.org/browse/JDK-8208672)) and `-xc99=%none` (reverting [JDK-8215296](https://bugs.openjdk.org/browse/JDK-8215296)), because new lines were used as is without comparing differences in what was being replaced.

All three of these changes show up clearly when comparing the 11u & 12u changesets, and are corrected by this patch.

I can also confirm this has the desired effect with warnings as my local build on GCC 13 now fails again, whereas it was passing before (we need some backports there to make that work)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8335801](https://bugs.openjdk.org/browse/JDK-8335801) needs maintainer approval

### Issue
 * [JDK-8335801](https://bugs.openjdk.org/browse/JDK-8335801): [11u] Backport of 8210988 to 11u removes gcc warnings (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2838/head:pull/2838` \
`$ git checkout pull/2838`

Update a local copy of the PR: \
`$ git checkout pull/2838` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2838/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2838`

View PR using the GUI difftool: \
`$ git pr show -t 2838`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2838.diff">https://git.openjdk.org/jdk11u-dev/pull/2838.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2838#issuecomment-2211792450)
</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by gnu-andrew** [comment]
Thanks Paul!

/approval request Resolves a regression introduced in 11.0.24 by a bad backport of 8210988 which removed all gcc warning flags, along with a number of other minor issues. Patch has been reviewed by Paul Hohensee.

**Comment by jerboaa** [comment]
It would be good to first wait on #2937 and merge that in so as to have fixed MacOX X GHA checks.

**Comment by gnu-andrew** [comment]
> It would be good to first wait on #2937 and merge that in so as to have fixed MacOX X GHA checks.

Ok, but you do realise this is fixing a regression, not something new? This should really have been fixed in 11.0.25. We are currently building without any of the usual warnings turned on.

**Comment by gnu-andrew** [comment]
Merged with latest jdk11u-dev and tests passed. Merging.
/integrate

**Pull request closed without merging**
