### PR TITLE
8289948: Improve test coverage for XPath functions: Node Set Functions

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8289948](https://bugs.openjdk.org/browse/JDK-8289948)
- Clean Backport

Tests
- PR - All checks have passed
- SAP nightlies passed on `2023-12-21,22`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8289948](https://bugs.openjdk.org/browse/JDK-8289948) needs maintainer approval

### Issue
 * [JDK-8289948](https://bugs.openjdk.org/browse/JDK-8289948): Improve test coverage for XPath functions: Node Set Functions (**Sub-task** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev.git pull/2361/head:pull/2361` \
`$ git checkout pull/2361`

Update a local copy of the PR: \
`$ git checkout pull/2361` \
`$ git pull https://git.openjdk.org/jdk11u-dev.git pull/2361/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2361`

View PR using the GUI difftool: \
`$ git pr show -t 2361`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/2361.diff">https://git.openjdk.org/jdk11u-dev/pull/2361.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u-dev/pull/2361#issuecomment-1853222818)

### CODE REVIEW

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean backport. SAP nightlies passed on 2023-12-19”

**Review by TheRealMDoerr — APPROVED** [review]
It's not clean. You had to replace the text block `String DTD`. Looks correct.

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Clean backport. SAP nightlies passed on 2023-12-21”

**Comment by amosshi** [comment]
/approval request “Backporting for parity with jdk 11.0.22-oracle. No risk, test fix. Unclean backport. SAP nightlies passed on 2023-12-21”

**Pull request closed without merging**
